(define (problem p4_hosts_trial_10)
(:domain caldera-split)
(:objects
    id_ccschtask - observedschtask
    id_caschtask - observedschtask
    id_cbschtask - observedschtask
    id_cdschtask - observedschtask
    id_cdomainuser - observeddomainuser
    id_kdomainuser - observeddomainuser
    id_odomainuser - observeddomainuser
    id_sdomainuser - observeddomainuser
    id_gdomainuser - observeddomainuser
    id_bstimedelta - observedtimedelta
    id_bltimedelta - observedtimedelta
    id_betimedelta - observedtimedelta
    id_xtimedelta - observedtimedelta
    id_cefile - observedfile
    id_chfile - observedfile
    id_cffile - observedfile
    id_cgfile - observedfile
    id_cjshare - observedshare
    id_cishare - observedshare
    id_clshare - observedshare
    id_ckshare - observedshare
    id_cprat - observedrat
    id_byrat - observedrat
    id_corat - observedrat
    id_cnrat - observedrat
    id_cmrat - observedrat
    id_ddomaincredential - observeddomaincredential
    id_pdomaincredential - observeddomaincredential
    id_tdomaincredential - observeddomaincredential
    id_ldomaincredential - observeddomaincredential
    id_hdomaincredential - observeddomaincredential
    num__46 - num
    num__31 - num
    num__45 - num
    num__39 - num
    num__32 - num
    num__24 - num
    num__25 - num
    num__38 - num
    str__bj - string
    str__bp - string
    str__bc - string
    str__patricia - string
    str__bq - string
    str__ba - string
    str__john - string
    str__r - string
    str__bz - string
    str__alpha - string
    str__q - string
    str__james - string
    str__n - string
    str__j - string
    str__e - string
    str__bv - string
    str__m - string
    str__bo - string
    str__bh - string
    str__bx - string
    str__f - string
    str__bb - string
    str__b - string
    str__mary - string
    str__bw - string
    str__u - string
    str__bi - string
    str__v - string
    str__i - string
    str__robert - string
    id_adomain - observeddomain
    id_bkhost - observedhost
    id_brhost - observedhost
    id_whost - observedhost
    id_bdhost - observedhost
)
(:init
    (knows id_bdhost)
    (knows id_byrat)
    (knows_property id_bdhost pfqdn)
    (knows_property id_byrat pexecutable)
    (knows_property id_byrat phost)
    (MEM_CACHED_DOMAIN_CREDS id_bdhost id_ldomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_bdhost id_pdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_bdhost id_tdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_bkhost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_bkhost id_pdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_bkhost id_tdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_brhost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_brhost id_hdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_brhost id_ldomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_whost id_hdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_whost id_pdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_whost id_tdomaincredential)
    (MEM_DOMAIN_USER_ADMINS id_bdhost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_bdhost id_gdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_bdhost id_kdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_bdhost id_odomainuser)
    (MEM_DOMAIN_USER_ADMINS id_bdhost id_sdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_bkhost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_bkhost id_gdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_bkhost id_kdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_bkhost id_odomainuser)
    (MEM_DOMAIN_USER_ADMINS id_bkhost id_sdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_brhost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_brhost id_gdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_brhost id_kdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_brhost id_odomainuser)
    (MEM_DOMAIN_USER_ADMINS id_brhost id_sdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_whost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_whost id_gdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_whost id_kdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_whost id_odomainuser)
    (MEM_DOMAIN_USER_ADMINS id_whost id_sdomainuser)
    (mem_hosts id_adomain id_bdhost)
    (mem_hosts id_adomain id_bkhost)
    (mem_hosts id_adomain id_brhost)
    (mem_hosts id_adomain id_whost)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (PROP_DC id_bdhost no)
    (PROP_DC id_bkhost yes)
    (PROP_DC id_brhost no)
    (PROP_DC id_whost no)
    (PROP_DNS_DOMAIN id_adomain str__b)
    (PROP_DNS_DOMAIN_NAME id_bdhost str__bh)
    (PROP_DNS_DOMAIN_NAME id_bkhost str__bo)
    (PROP_DNS_DOMAIN_NAME id_brhost str__bv)
    (PROP_DNS_DOMAIN_NAME id_whost str__ba)
    (PROP_DOMAIN id_bdhost id_adomain)
    (PROP_DOMAIN id_bkhost id_adomain)
    (PROP_DOMAIN id_brhost id_adomain)
    (PROP_DOMAIN id_cdomainuser id_adomain)
    (PROP_DOMAIN id_ddomaincredential id_adomain)
    (PROP_DOMAIN id_gdomainuser id_adomain)
    (PROP_DOMAIN id_hdomaincredential id_adomain)
    (PROP_DOMAIN id_kdomainuser id_adomain)
    (PROP_DOMAIN id_ldomaincredential id_adomain)
    (PROP_DOMAIN id_odomainuser id_adomain)
    (PROP_DOMAIN id_pdomaincredential id_adomain)
    (PROP_DOMAIN id_sdomainuser id_adomain)
    (PROP_DOMAIN id_tdomaincredential id_adomain)
    (PROP_DOMAIN id_whost id_adomain)
    (prop_elevated id_byrat yes)
    (prop_executable id_byrat str__bz)
    (PROP_FQDN id_bdhost str__bj)
    (PROP_FQDN id_bkhost str__bq)
    (PROP_FQDN id_brhost str__bx)
    (PROP_FQDN id_whost str__bc)
    (prop_host id_betimedelta id_bdhost)
    (prop_host id_bltimedelta id_bkhost)
    (prop_host id_bstimedelta id_brhost)
    (prop_host id_byrat id_bdhost)
    (prop_host id_xtimedelta id_whost)
    (PROP_HOSTNAME id_bdhost str__bi)
    (PROP_HOSTNAME id_bkhost str__bp)
    (PROP_HOSTNAME id_brhost str__bw)
    (PROP_HOSTNAME id_whost str__bb)
    (PROP_IS_GROUP id_cdomainuser no)
    (PROP_IS_GROUP id_gdomainuser no)
    (PROP_IS_GROUP id_kdomainuser no)
    (PROP_IS_GROUP id_odomainuser no)
    (PROP_IS_GROUP id_sdomainuser no)
    (PROP_MICROSECONDS id_betimedelta num__32)
    (PROP_MICROSECONDS id_bltimedelta num__39)
    (PROP_MICROSECONDS id_bstimedelta num__46)
    (PROP_MICROSECONDS id_xtimedelta num__25)
    (PROP_PASSWORD id_ddomaincredential str__e)
    (PROP_PASSWORD id_hdomaincredential str__i)
    (PROP_PASSWORD id_ldomaincredential str__m)
    (PROP_PASSWORD id_pdomaincredential str__q)
    (PROP_PASSWORD id_tdomaincredential str__u)
    (PROP_SECONDS id_betimedelta num__31)
    (PROP_SECONDS id_bltimedelta num__38)
    (PROP_SECONDS id_bstimedelta num__45)
    (PROP_SECONDS id_xtimedelta num__24)
    (PROP_SID id_cdomainuser str__f)
    (PROP_SID id_gdomainuser str__j)
    (PROP_SID id_kdomainuser str__n)
    (PROP_SID id_odomainuser str__r)
    (PROP_SID id_sdomainuser str__v)
    (PROP_TIMEDELTA id_bdhost id_betimedelta)
    (PROP_TIMEDELTA id_bkhost id_bltimedelta)
    (PROP_TIMEDELTA id_brhost id_bstimedelta)
    (PROP_TIMEDELTA id_whost id_xtimedelta)
    (PROP_USER id_ddomaincredential id_cdomainuser)
    (PROP_USER id_hdomaincredential id_gdomainuser)
    (PROP_USER id_ldomaincredential id_kdomainuser)
    (PROP_USER id_pdomaincredential id_odomainuser)
    (PROP_USER id_tdomaincredential id_sdomainuser)
    (PROP_USERNAME id_cdomainuser str__james)
    (PROP_USERNAME id_gdomainuser str__mary)
    (PROP_USERNAME id_kdomainuser str__john)
    (PROP_USERNAME id_odomainuser str__patricia)
    (PROP_USERNAME id_sdomainuser str__robert)
    (PROP_WINDOWS_DOMAIN id_adomain str__alpha)
    (procnone)
    (= (total-cost) 0)
)
(:goal
(and
    (procnone)
    (prop_host id_cnrat id_brhost)
    (prop_host id_cprat id_bkhost)
    (prop_host id_cmrat id_whost)
)
)
(:metric minimize (total-cost))
)