(define (problem p6_hosts_trial_1)
(:domain caldera-split)
(:objects
    id_ddomaincredential - observeddomaincredential
    id_cdfile - observedfile
    id_byfile - observedfile
    id_bzfile - observedfile
    id_cbfile - observedfile
    id_ccfile - observedfile
    id_cafile - observedfile
    id_bihost - observedhost
    id_nhost - observedhost
    id_ghost - observedhost
    id_uhost - observedhost
    id_bphost - observedhost
    id_bbhost - observedhost
    id_cdomainuser - observeddomainuser
    num__36 - num
    num__37 - num
    num__15 - num
    num__16 - num
    num__29 - num
    num__30 - num
    num__23 - num
    num__44 - num
    num__43 - num
    num__22 - num
    num__9 - num
    num__8 - num
    id_chschtask - observedschtask
    id_ceschtask - observedschtask
    id_cfschtask - observedschtask
    id_cjschtask - observedschtask
    id_cischtask - observedschtask
    id_cgschtask - observedschtask
    id_adomain - observeddomain
    id_bqtimedelta - observedtimedelta
    id_otimedelta - observedtimedelta
    id_htimedelta - observedtimedelta
    id_bctimedelta - observedtimedelta
    id_bjtimedelta - observedtimedelta
    id_vtimedelta - observedtimedelta
    str__bf - string
    str__bg - string
    str__bh - string
    str__t - string
    str__bm - string
    str__bn - string
    str__bo - string
    str__z - string
    str__s - string
    str__l - string
    str__e - string
    str__b - string
    str__bt - string
    str__ba - string
    str__k - string
    str__m - string
    str__bv - string
    str__y - string
    str__bx - string
    str__bu - string
    str__alpha - string
    str__r - string
    str__f - string
    str__james - string
    id_cmshare - observedshare
    id_ckshare - observedshare
    id_cpshare - observedshare
    id_cnshare - observedshare
    id_coshare - observedshare
    id_clshare - observedshare
    id_cvrat - observedrat
    id_csrat - observedrat
    id_crrat - observedrat
    id_ctrat - observedrat
    id_curat - observedrat
    id_cqrat - observedrat
    id_bwrat - observedrat
)
(:init
    (knows id_bwrat)
    (knows id_ghost)
    (knows_property id_bwrat pexecutable)
    (knows_property id_bwrat phost)
    (knows_property id_ghost pfqdn)
    (MEM_CACHED_DOMAIN_CREDS id_bbhost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_bihost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_bphost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_ghost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_nhost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_uhost id_ddomaincredential)
    (MEM_DOMAIN_USER_ADMINS id_bbhost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_bihost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_bphost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_ghost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_nhost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_uhost id_cdomainuser)
    (mem_hosts id_adomain id_bbhost)
    (mem_hosts id_adomain id_bihost)
    (mem_hosts id_adomain id_bphost)
    (mem_hosts id_adomain id_ghost)
    (mem_hosts id_adomain id_nhost)
    (mem_hosts id_adomain id_uhost)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (PROP_DC id_bbhost no)
    (PROP_DC id_bihost no)
    (PROP_DC id_bphost yes)
    (PROP_DC id_ghost no)
    (PROP_DC id_nhost yes)
    (PROP_DC id_uhost no)
    (PROP_DNS_DOMAIN id_adomain str__b)
    (PROP_DNS_DOMAIN_NAME id_bbhost str__bh)
    (PROP_DNS_DOMAIN_NAME id_bihost str__bo)
    (PROP_DNS_DOMAIN_NAME id_bphost str__bv)
    (PROP_DNS_DOMAIN_NAME id_ghost str__m)
    (PROP_DNS_DOMAIN_NAME id_nhost str__t)
    (PROP_DNS_DOMAIN_NAME id_uhost str__ba)
    (PROP_DOMAIN id_bbhost id_adomain)
    (PROP_DOMAIN id_bihost id_adomain)
    (PROP_DOMAIN id_bphost id_adomain)
    (PROP_DOMAIN id_cdomainuser id_adomain)
    (PROP_DOMAIN id_ddomaincredential id_adomain)
    (PROP_DOMAIN id_ghost id_adomain)
    (PROP_DOMAIN id_nhost id_adomain)
    (PROP_DOMAIN id_uhost id_adomain)
    (prop_elevated id_bwrat yes)
    (prop_executable id_bwrat str__bx)
    (PROP_FQDN id_bbhost str__bf)
    (PROP_FQDN id_bihost str__bm)
    (PROP_FQDN id_bphost str__bt)
    (PROP_FQDN id_ghost str__k)
    (PROP_FQDN id_nhost str__r)
    (PROP_FQDN id_uhost str__y)
    (prop_host id_bctimedelta id_bbhost)
    (prop_host id_bjtimedelta id_bihost)
    (prop_host id_bqtimedelta id_bphost)
    (prop_host id_bwrat id_ghost)
    (prop_host id_htimedelta id_ghost)
    (prop_host id_otimedelta id_nhost)
    (prop_host id_vtimedelta id_uhost)
    (PROP_HOSTNAME id_bbhost str__bg)
    (PROP_HOSTNAME id_bihost str__bn)
    (PROP_HOSTNAME id_bphost str__bu)
    (PROP_HOSTNAME id_ghost str__l)
    (PROP_HOSTNAME id_nhost str__s)
    (PROP_HOSTNAME id_uhost str__z)
    (PROP_IS_GROUP id_cdomainuser no)
    (PROP_MICROSECONDS id_bctimedelta num__29)
    (PROP_MICROSECONDS id_bjtimedelta num__36)
    (PROP_MICROSECONDS id_bqtimedelta num__43)
    (PROP_MICROSECONDS id_htimedelta num__8)
    (PROP_MICROSECONDS id_otimedelta num__15)
    (PROP_MICROSECONDS id_vtimedelta num__22)
    (PROP_PASSWORD id_ddomaincredential str__e)
    (PROP_SECONDS id_bctimedelta num__30)
    (PROP_SECONDS id_bjtimedelta num__37)
    (PROP_SECONDS id_bqtimedelta num__44)
    (PROP_SECONDS id_htimedelta num__9)
    (PROP_SECONDS id_otimedelta num__16)
    (PROP_SECONDS id_vtimedelta num__23)
    (PROP_SID id_cdomainuser str__f)
    (PROP_TIMEDELTA id_bbhost id_bctimedelta)
    (PROP_TIMEDELTA id_bihost id_bjtimedelta)
    (PROP_TIMEDELTA id_bphost id_bqtimedelta)
    (PROP_TIMEDELTA id_ghost id_htimedelta)
    (PROP_TIMEDELTA id_nhost id_otimedelta)
    (PROP_TIMEDELTA id_uhost id_vtimedelta)
    (PROP_USER id_ddomaincredential id_cdomainuser)
    (PROP_USERNAME id_cdomainuser str__james)
    (PROP_WINDOWS_DOMAIN id_adomain str__alpha)
    (procnone)
    (= (total-cost) 0)
)
(:goal
(and
    (procnone)
    (prop_host id_ctrat id_bphost)
    (prop_host id_crrat id_uhost)
    (prop_host id_csrat id_bbhost)
    (prop_host id_cvrat id_bihost)
    (prop_host id_cqrat id_nhost)
)
)
(:metric minimize (total-cost))
)