(define (problem add-paren-4-20062018203620)
(:domain flashfill)
(:objects
)
(:init
    (hiindex str i4)
    (loindex str i0)
    (size str i4)
    (size res i0)
    (input-assignment str-var str row-0)
    (next i0 i1)
    (next i1 i2)
    (next i2 i3)
    (next i3 i4)
    (next i4 i5)
    (assignment str i0 lpar)
    (assignment str i1 t)
    (assignment str i2 o)
    (assignment str i3 a)
    (test-0)
    (NEXT-STACK-ROW row-0 row-1)
    (stack-main row-0)
    (stack-line-0 row-0)
    (top-stack row-0)
    (empty-0)
    (empty-1)
    (empty-2)
    (empty-3)
    (empty-4)
    (empty-5)
    (empty-6)
)
(:goal
(and
    (done-programming)
)
)
(:metric minimize (total-cost))
)