(define (problem initials-5-5-20062018204811)
(:domain flashfill)
(:objects
)
(:init
    (hiindex str i5)
    (loindex str i0)
    (hiindex str2 i5)
    (loindex str2 i0)
    (size str i5)
    (size str2 i5)
    (size res i0)
    (input-assignment str-var str row-0)
    (input-assignment str2-var str2 row-0)
    (next i0 i1)
    (next i1 i2)
    (next i2 i3)
    (next i3 i4)
    (next i4 i5)
    (next i5 i6)
    (next i6 i7)
    (next i7 i8)
    (next i8 i9)
    (next i9 i10)
    (next i10 i11)
    (assignment str i0 r)
    (assignment str i1 p)
    (assignment str i2 l)
    (assignment str i3 j)
    (assignment str i4 j)
    (assignment str2 i0 y)
    (assignment str2 i1 n)
    (assignment str2 i2 p)
    (assignment str2 i3 b)
    (assignment str2 i4 o)
    (test-0)
    (NEXT-STACK-ROW row-0 row-1)
    (stack-main row-0)
    (stack-line-0 row-0)
    (top-stack row-0)
    (empty-0)
    (empty-1)
    (empty-2)
    (empty-3)
    (empty-4)
    (empty-5)
)
(:goal
(and
    (done-programming)
)
)
(:metric minimize (total-cost))
)