
(define (problem os-softpreferences-wbop_20_20-14)
        (:domain openstacks-softpreferences)
        (:objects n0 - count n1 - count n2 - count n3 - count n4 - count n5 -
         count n6 - count n7 - count n8 - count n9 - count n10 - count n11 -
         count n12 - count n13 - count n14 - count n15 - count n16 - count n17
         - count n18 - count n19 - count n20 - count o1 - order o2 - order o3 -
         order o4 - order o5 - order o6 - order o7 - order o8 - order o9 -
         order o10 - order o11 - order o12 - order o13 - order o14 - order o15
         - order o16 - order o17 - order o18 - order o19 - order o20 - order p1
         - product p2 - product p3 - product p4 - product p5 - product p6 -
         product p7 - product p8 - product p9 - product p10 - product p11 -
         product p12 - product p13 - product p14 - product p15 - product p16 -
         product p17 - product p18 - product p19 - product p20 - product)
        (:init (next-count n0 n1) (next-count n1 n2) (next-count n2 n3)
         (next-count n3 n4) (next-count n4 n5) (next-count n5 n6)
         (next-count n6 n7) (next-count n7 n8) (next-count n8 n9)
         (next-count n9 n10) (next-count n10 n11) (next-count n11 n12)
         (next-count n12 n13) (next-count n13 n14) (next-count n14 n15)
         (next-count n15 n16) (next-count n16 n17) (next-count n17 n18)
         (next-count n18 n19) (next-count n19 n20) (stacks-in-use n0)
         (waiting o1) (includes o1 p16) (includes o1 p19) (includes o1 p20)
         (waiting o2) (includes o2 p4) (includes o2 p5) (includes o2 p8)
         (waiting o3) (includes o3 p6) (includes o3 p9) (includes o3 p15)
         (waiting o4) (includes o4 p8) (includes o4 p11) (includes o4 p13)
         (waiting o5) (includes o5 p5) (includes o5 p7) (includes o5 p17)
         (waiting o6) (includes o6 p2) (includes o6 p10) (includes o6 p12)
         (waiting o7) (includes o7 p2) (includes o7 p8) (includes o7 p16)
         (waiting o8) (includes o8 p9) (includes o8 p11) (includes o8 p18)
         (waiting o9) (includes o9 p1) (includes o9 p3) (includes o9 p7)
         (waiting o10) (includes o10 p2) (includes o10 p9) (includes o10 p20)
         (waiting o11) (includes o11 p6) (includes o11 p11) (includes o11 p18)
         (waiting o12) (includes o12 p4) (includes o12 p10) (includes o12 p14)
         (waiting o13) (includes o13 p6) (includes o13 p17) (includes o13 p18)
         (waiting o14) (includes o14 p10) (includes o14 p12) (includes o14 p19)
         (waiting o15) (includes o15 p1) (includes o15 p3) (includes o15 p4)
         (waiting o16) (includes o16 p7) (includes o16 p13) (includes o16 p15)
         (waiting o17) (includes o17 p3) (includes o17 p14) (includes o17 p17)
         (waiting o18) (includes o18 p1) (includes o18 p15) (includes o18 p19)
         (waiting o19) (includes o19 p5) (includes o19 p14) (includes o19 p16)
         (waiting o20) (includes o20 p12) (includes o20 p13)
         (includes o20 p20))
        (:goal
         (and (shipped o1)
              (shipped o2)
              (shipped o3)
              (shipped o4)
              (shipped o5)
              (shipped o6)
              (shipped o7)
              (shipped o8)
              (shipped o9)
              (shipped o10)
              (shipped o11)
              (shipped o12)
              (shipped o13)
              (shipped o14)
              (shipped o15)
              (shipped o16)
              (shipped o17)
              (shipped o18)
              (shipped o19)
              (shipped o20)
              (preference d-o1-n1 (delivered o1 p16))
              (preference d-o1-n2 (and (delivered o1 p19) (delivered o1 p16)))
              (preference d-o1-n3
               (and (delivered o1 p20) (delivered o1 p19) (delivered o1 p16)))
              (preference d-o2-n1 (delivered o2 p4))
              (preference d-o2-n2 (and (delivered o2 p5) (delivered o2 p4)))
              (preference d-o2-n3
               (and (delivered o2 p8) (delivered o2 p5) (delivered o2 p4)))
              (preference d-o3-n1 (delivered o3 p6))
              (preference d-o3-n2 (and (delivered o3 p9) (delivered o3 p6)))
              (preference d-o3-n3
               (and (delivered o3 p15) (delivered o3 p9) (delivered o3 p6)))
              (preference d-o4-n1 (delivered o4 p8))
              (preference d-o4-n2 (and (delivered o4 p11) (delivered o4 p8)))
              (preference d-o4-n3
               (and (delivered o4 p13) (delivered o4 p11) (delivered o4 p8)))
              (preference d-o5-n1 (delivered o5 p5))
              (preference d-o5-n2 (and (delivered o5 p7) (delivered o5 p5)))
              (preference d-o5-n3
               (and (delivered o5 p17) (delivered o5 p7) (delivered o5 p5)))
              (preference d-o6-n1 (delivered o6 p2))
              (preference d-o6-n2 (and (delivered o6 p10) (delivered o6 p2)))
              (preference d-o6-n3
               (and (delivered o6 p12) (delivered o6 p10) (delivered o6 p2)))
              (preference d-o7-n1 (delivered o7 p2))
              (preference d-o7-n2 (and (delivered o7 p8) (delivered o7 p2)))
              (preference d-o7-n3
               (and (delivered o7 p16) (delivered o7 p8) (delivered o7 p2)))
              (preference d-o8-n1 (delivered o8 p9))
              (preference d-o8-n2 (and (delivered o8 p11) (delivered o8 p9)))
              (preference d-o8-n3
               (and (delivered o8 p18) (delivered o8 p11) (delivered o8 p9)))
              (preference d-o9-n1 (delivered o9 p1))
              (preference d-o9-n2 (and (delivered o9 p3) (delivered o9 p1)))
              (preference d-o9-n3
               (and (delivered o9 p7) (delivered o9 p3) (delivered o9 p1)))
              (preference d-o10-n1 (delivered o10 p2))
              (preference d-o10-n2 (and (delivered o10 p9) (delivered o10 p2)))
              (preference d-o10-n3
               (and (delivered o10 p20) (delivered o10 p9) (delivered o10 p2)))
              (preference d-o11-n1 (delivered o11 p6))
              (preference d-o11-n2
               (and (delivered o11 p11) (delivered o11 p6)))
              (preference d-o11-n3
               (and (delivered o11 p18)
                    (delivered o11 p11)
                    (delivered o11 p6)))
              (preference d-o12-n1 (delivered o12 p4))
              (preference d-o12-n2
               (and (delivered o12 p10) (delivered o12 p4)))
              (preference d-o12-n3
               (and (delivered o12 p14)
                    (delivered o12 p10)
                    (delivered o12 p4)))
              (preference d-o13-n1 (delivered o13 p6))
              (preference d-o13-n2
               (and (delivered o13 p17) (delivered o13 p6)))
              (preference d-o13-n3
               (and (delivered o13 p18)
                    (delivered o13 p17)
                    (delivered o13 p6)))
              (preference d-o14-n1 (delivered o14 p10))
              (preference d-o14-n2
               (and (delivered o14 p12) (delivered o14 p10)))
              (preference d-o14-n3
               (and (delivered o14 p19)
                    (delivered o14 p12)
                    (delivered o14 p10)))
              (preference d-o15-n1 (delivered o15 p1))
              (preference d-o15-n2 (and (delivered o15 p3) (delivered o15 p1)))
              (preference d-o15-n3
               (and (delivered o15 p4) (delivered o15 p3) (delivered o15 p1)))
              (preference d-o16-n1 (delivered o16 p7))
              (preference d-o16-n2
               (and (delivered o16 p13) (delivered o16 p7)))
              (preference d-o16-n3
               (and (delivered o16 p15)
                    (delivered o16 p13)
                    (delivered o16 p7)))
              (preference d-o17-n1 (delivered o17 p3))
              (preference d-o17-n2
               (and (delivered o17 p14) (delivered o17 p3)))
              (preference d-o17-n3
               (and (delivered o17 p17)
                    (delivered o17 p14)
                    (delivered o17 p3)))
              (preference d-o18-n1 (delivered o18 p1))
              (preference d-o18-n2
               (and (delivered o18 p15) (delivered o18 p1)))
              (preference d-o18-n3
               (and (delivered o18 p19)
                    (delivered o18 p15)
                    (delivered o18 p1)))
              (preference d-o19-n1 (delivered o19 p5))
              (preference d-o19-n2
               (and (delivered o19 p14) (delivered o19 p5)))
              (preference d-o19-n3
               (and (delivered o19 p16)
                    (delivered o19 p14)
                    (delivered o19 p5)))
              (preference d-o20-n1 (delivered o20 p12))
              (preference d-o20-n2
               (and (delivered o20 p13) (delivered o20 p12)))
              (preference d-o20-n3
               (and (delivered o20 p20)
                    (delivered o20 p13)
                    (delivered o20 p12)))))
        (:constraints
         (and (preference max1 (always (not (stacks-in-use n1))))
              (preference max2 (always (not (stacks-in-use n2))))
              (preference max3 (always (not (stacks-in-use n3))))
              (preference max4 (always (not (stacks-in-use n4))))
              (preference max5 (always (not (stacks-in-use n5))))
              (preference max6 (always (not (stacks-in-use n6))))
              (preference max7 (always (not (stacks-in-use n7))))
              (preference max8 (always (not (stacks-in-use n8))))
              (preference max9 (always (not (stacks-in-use n9))))
              (preference max10 (always (not (stacks-in-use n10))))
              (preference max11 (always (not (stacks-in-use n11))))
              (preference max12 (always (not (stacks-in-use n12))))
              (preference max13 (always (not (stacks-in-use n13))))
              (preference max14 (always (not (stacks-in-use n14))))
              (preference max15 (always (not (stacks-in-use n15))))
              (preference max16 (always (not (stacks-in-use n16))))
              (preference max17 (always (not (stacks-in-use n17))))
              (preference max18 (always (not (stacks-in-use n18))))
              (preference max19 (always (not (stacks-in-use n19))))
              (preference max20 (always (not (stacks-in-use n20))))))
        (:metric minimize
         (+ (* (is-violated d-o1-n3) 4)
            (* (is-violated d-o1-n2) 2)
            (is-violated d-o1-n1)
            (* (is-violated d-o2-n3) 4)
            (* (is-violated d-o2-n2) 2)
            (is-violated d-o2-n1)
            (* (is-violated d-o3-n3) 4)
            (* (is-violated d-o3-n2) 2)
            (is-violated d-o3-n1)
            (* (is-violated d-o4-n3) 4)
            (* (is-violated d-o4-n2) 2)
            (is-violated d-o4-n1)
            (* (is-violated d-o5-n3) 4)
            (* (is-violated d-o5-n2) 2)
            (is-violated d-o5-n1)
            (* (is-violated d-o6-n3) 4)
            (* (is-violated d-o6-n2) 2)
            (is-violated d-o6-n1)
            (* (is-violated d-o7-n3) 4)
            (* (is-violated d-o7-n2) 2)
            (is-violated d-o7-n1)
            (* (is-violated d-o8-n3) 4)
            (* (is-violated d-o8-n2) 2)
            (is-violated d-o8-n1)
            (* (is-violated d-o9-n3) 4)
            (* (is-violated d-o9-n2) 2)
            (is-violated d-o9-n1)
            (* (is-violated d-o10-n3) 4)
            (* (is-violated d-o10-n2) 2)
            (is-violated d-o10-n1)
            (* (is-violated d-o11-n3) 4)
            (* (is-violated d-o11-n2) 2)
            (is-violated d-o11-n1)
            (* (is-violated d-o12-n3) 4)
            (* (is-violated d-o12-n2) 2)
            (is-violated d-o12-n1)
            (* (is-violated d-o13-n3) 4)
            (* (is-violated d-o13-n2) 2)
            (is-violated d-o13-n1)
            (* (is-violated d-o14-n3) 4)
            (* (is-violated d-o14-n2) 2)
            (is-violated d-o14-n1)
            (* (is-violated d-o15-n3) 4)
            (* (is-violated d-o15-n2) 2)
            (is-violated d-o15-n1)
            (* (is-violated d-o16-n3) 4)
            (* (is-violated d-o16-n2) 2)
            (is-violated d-o16-n1)
            (* (is-violated d-o17-n3) 4)
            (* (is-violated d-o17-n2) 2)
            (is-violated d-o17-n1)
            (* (is-violated d-o18-n3) 4)
            (* (is-violated d-o18-n2) 2)
            (is-violated d-o18-n1)
            (* (is-violated d-o19-n3) 4)
            (* (is-violated d-o19-n2) 2)
            (is-violated d-o19-n1)
            (* (is-violated d-o20-n3) 4)
            (* (is-violated d-o20-n2) 2)
            (is-violated d-o20-n1)
            (* (is-violated max1) 15.5)
            (* (is-violated max2) 15.5)
            (* (is-violated max3) 15.5)
            (* (is-violated max4) 15.5)
            (* (is-violated max5) 15.5)
            (* (is-violated max6) 15.5)
            (* (is-violated max7) 15.5)
            (* (is-violated max8) 15.5)
            (* (is-violated max9) 15.5)
            (* (is-violated max10) 15.5)
            (* (is-violated max11) 15.5)
            (* (is-violated max12) 15.5)
            (* (is-violated max13) 15.5)
            (* (is-violated max14) 15.5)
            (* (is-violated max15) 15.5)
            (* (is-violated max16) 15.5)
            (* (is-violated max17) 15.5)
            (* (is-violated max18) 15.5)
            (* (is-violated max19) 15.5)
            (* (is-violated max20) 15.5))))
