
(define (problem os-softpreferences-wbop_30_30-20)
        (:domain openstacks-softpreferences)
        (:objects n0 - count n1 - count n2 - count n3 - count n4 - count n5 -
         count n6 - count n7 - count n8 - count n9 - count n10 - count n11 -
         count n12 - count n13 - count n14 - count n15 - count n16 - count n17
         - count n18 - count n19 - count n20 - count n21 - count n22 - count
         n23 - count n24 - count n25 - count n26 - count n27 - count n28 -
         count n29 - count n30 - count o1 - order o2 - order o3 - order o4 -
         order o5 - order o6 - order o7 - order o8 - order o9 - order o10 -
         order o11 - order o12 - order o13 - order o14 - order o15 - order o16
         - order o17 - order o18 - order o19 - order o20 - order o21 - order
         o22 - order o23 - order o24 - order o25 - order o26 - order o27 -
         order o28 - order o29 - order o30 - order p1 - product p2 - product p3
         - product p4 - product p5 - product p6 - product p7 - product p8 -
         product p9 - product p10 - product p11 - product p12 - product p13 -
         product p14 - product p15 - product p16 - product p17 - product p18 -
         product p19 - product p20 - product p21 - product p22 - product p23 -
         product p24 - product p25 - product p26 - product p27 - product p28 -
         product p29 - product p30 - product)
        (:init (next-count n0 n1) (next-count n1 n2) (next-count n2 n3)
         (next-count n3 n4) (next-count n4 n5) (next-count n5 n6)
         (next-count n6 n7) (next-count n7 n8) (next-count n8 n9)
         (next-count n9 n10) (next-count n10 n11) (next-count n11 n12)
         (next-count n12 n13) (next-count n13 n14) (next-count n14 n15)
         (next-count n15 n16) (next-count n16 n17) (next-count n17 n18)
         (next-count n18 n19) (next-count n19 n20) (next-count n20 n21)
         (next-count n21 n22) (next-count n22 n23) (next-count n23 n24)
         (next-count n24 n25) (next-count n25 n26) (next-count n26 n27)
         (next-count n27 n28) (next-count n28 n29) (next-count n29 n30)
         (stacks-in-use n0) (waiting o1) (includes o1 p18) (includes o1 p19)
         (includes o1 p21) (waiting o2) (includes o2 p7) (includes o2 p19)
         (includes o2 p24) (waiting o3) (includes o3 p3) (includes o3 p10)
         (includes o3 p18) (waiting o4) (includes o4 p6) (includes o4 p11)
         (includes o4 p21) (waiting o5) (includes o5 p13) (includes o5 p17)
         (includes o5 p25) (waiting o6) (includes o6 p3) (includes o6 p10)
         (includes o6 p22) (waiting o7) (includes o7 p11) (includes o7 p27)
         (includes o7 p28) (waiting o8) (includes o8 p6) (includes o8 p11)
         (includes o8 p17) (waiting o9) (includes o9 p16) (includes o9 p22)
         (includes o9 p26) (waiting o10) (includes o10 p5) (includes o10 p19)
         (includes o10 p27) (waiting o11) (includes o11 p1) (includes o11 p14)
         (includes o11 p29) (waiting o12) (includes o12 p4) (includes o12 p13)
         (includes o12 p17) (waiting o13) (includes o13 p9) (includes o13 p22)
         (includes o13 p25) (waiting o14) (includes o14 p7) (includes o14 p9)
         (includes o14 p23) (waiting o15) (includes o15 p8) (includes o15 p15)
         (includes o15 p28) (waiting o16) (includes o16 p1) (includes o16 p2)
         (includes o16 p29) (waiting o17) (includes o17 p9) (includes o17 p26)
         (includes o17 p28) (waiting o18) (includes o18 p3) (includes o18 p6)
         (includes o18 p15) (waiting o19) (includes o19 p12) (includes o19 p14)
         (includes o19 p20) (waiting o20) (includes o20 p7) (includes o20 p24)
         (includes o20 p30) (waiting o21) (includes o21 p2) (includes o21 p13)
         (includes o21 p20) (waiting o22) (includes o22 p5) (includes o22 p10)
         (includes o22 p23) (waiting o23) (includes o23 p5) (includes o23 p23)
         (includes o23 p24) (waiting o24) (includes o24 p12) (includes o24 p14)
         (includes o24 p21) (waiting o25) (includes o25 p1) (includes o25 p2)
         (includes o25 p27) (waiting o26) (includes o26 p16) (includes o26 p26)
         (includes o26 p30) (waiting o27) (includes o27 p4) (includes o27 p16)
         (includes o27 p30) (waiting o28) (includes o28 p8) (includes o28 p12)
         (includes o28 p20) (waiting o29) (includes o29 p8) (includes o29 p18)
         (includes o29 p29) (waiting o30) (includes o30 p4) (includes o30 p15)
         (includes o30 p25))
        (:goal
         (and (shipped o1)
              (shipped o2)
              (shipped o3)
              (shipped o4)
              (shipped o5)
              (shipped o6)
              (shipped o7)
              (shipped o8)
              (shipped o9)
              (shipped o10)
              (shipped o11)
              (shipped o12)
              (shipped o13)
              (shipped o14)
              (shipped o15)
              (shipped o16)
              (shipped o17)
              (shipped o18)
              (shipped o19)
              (shipped o20)
              (shipped o21)
              (shipped o22)
              (shipped o23)
              (shipped o24)
              (shipped o25)
              (shipped o26)
              (shipped o27)
              (shipped o28)
              (shipped o29)
              (shipped o30)
              (preference d-o1-n1 (delivered o1 p18))
              (preference d-o1-n2 (and (delivered o1 p19) (delivered o1 p18)))
              (preference d-o1-n3
               (and (delivered o1 p21) (delivered o1 p19) (delivered o1 p18)))
              (preference d-o2-n1 (delivered o2 p7))
              (preference d-o2-n2 (and (delivered o2 p19) (delivered o2 p7)))
              (preference d-o2-n3
               (and (delivered o2 p24) (delivered o2 p19) (delivered o2 p7)))
              (preference d-o3-n1 (delivered o3 p3))
              (preference d-o3-n2 (and (delivered o3 p10) (delivered o3 p3)))
              (preference d-o3-n3
               (and (delivered o3 p18) (delivered o3 p10) (delivered o3 p3)))
              (preference d-o4-n1 (delivered o4 p6))
              (preference d-o4-n2 (and (delivered o4 p11) (delivered o4 p6)))
              (preference d-o4-n3
               (and (delivered o4 p21) (delivered o4 p11) (delivered o4 p6)))
              (preference d-o5-n1 (delivered o5 p13))
              (preference d-o5-n2 (and (delivered o5 p17) (delivered o5 p13)))
              (preference d-o5-n3
               (and (delivered o5 p25) (delivered o5 p17) (delivered o5 p13)))
              (preference d-o6-n1 (delivered o6 p3))
              (preference d-o6-n2 (and (delivered o6 p10) (delivered o6 p3)))
              (preference d-o6-n3
               (and (delivered o6 p22) (delivered o6 p10) (delivered o6 p3)))
              (preference d-o7-n1 (delivered o7 p11))
              (preference d-o7-n2 (and (delivered o7 p27) (delivered o7 p11)))
              (preference d-o7-n3
               (and (delivered o7 p28) (delivered o7 p27) (delivered o7 p11)))
              (preference d-o8-n1 (delivered o8 p6))
              (preference d-o8-n2 (and (delivered o8 p11) (delivered o8 p6)))
              (preference d-o8-n3
               (and (delivered o8 p17) (delivered o8 p11) (delivered o8 p6)))
              (preference d-o9-n1 (delivered o9 p16))
              (preference d-o9-n2 (and (delivered o9 p22) (delivered o9 p16)))
              (preference d-o9-n3
               (and (delivered o9 p26) (delivered o9 p22) (delivered o9 p16)))
              (preference d-o10-n1 (delivered o10 p5))
              (preference d-o10-n2
               (and (delivered o10 p19) (delivered o10 p5)))
              (preference d-o10-n3
               (and (delivered o10 p27)
                    (delivered o10 p19)
                    (delivered o10 p5)))
              (preference d-o11-n1 (delivered o11 p1))
              (preference d-o11-n2
               (and (delivered o11 p14) (delivered o11 p1)))
              (preference d-o11-n3
               (and (delivered o11 p29)
                    (delivered o11 p14)
                    (delivered o11 p1)))
              (preference d-o12-n1 (delivered o12 p4))
              (preference d-o12-n2
               (and (delivered o12 p13) (delivered o12 p4)))
              (preference d-o12-n3
               (and (delivered o12 p17)
                    (delivered o12 p13)
                    (delivered o12 p4)))
              (preference d-o13-n1 (delivered o13 p9))
              (preference d-o13-n2
               (and (delivered o13 p22) (delivered o13 p9)))
              (preference d-o13-n3
               (and (delivered o13 p25)
                    (delivered o13 p22)
                    (delivered o13 p9)))
              (preference d-o14-n1 (delivered o14 p7))
              (preference d-o14-n2 (and (delivered o14 p9) (delivered o14 p7)))
              (preference d-o14-n3
               (and (delivered o14 p23) (delivered o14 p9) (delivered o14 p7)))
              (preference d-o15-n1 (delivered o15 p8))
              (preference d-o15-n2
               (and (delivered o15 p15) (delivered o15 p8)))
              (preference d-o15-n3
               (and (delivered o15 p28)
                    (delivered o15 p15)
                    (delivered o15 p8)))
              (preference d-o16-n1 (delivered o16 p1))
              (preference d-o16-n2 (and (delivered o16 p2) (delivered o16 p1)))
              (preference d-o16-n3
               (and (delivered o16 p29) (delivered o16 p2) (delivered o16 p1)))
              (preference d-o17-n1 (delivered o17 p9))
              (preference d-o17-n2
               (and (delivered o17 p26) (delivered o17 p9)))
              (preference d-o17-n3
               (and (delivered o17 p28)
                    (delivered o17 p26)
                    (delivered o17 p9)))
              (preference d-o18-n1 (delivered o18 p3))
              (preference d-o18-n2 (and (delivered o18 p6) (delivered o18 p3)))
              (preference d-o18-n3
               (and (delivered o18 p15) (delivered o18 p6) (delivered o18 p3)))
              (preference d-o19-n1 (delivered o19 p12))
              (preference d-o19-n2
               (and (delivered o19 p14) (delivered o19 p12)))
              (preference d-o19-n3
               (and (delivered o19 p20)
                    (delivered o19 p14)
                    (delivered o19 p12)))
              (preference d-o20-n1 (delivered o20 p7))
              (preference d-o20-n2
               (and (delivered o20 p24) (delivered o20 p7)))
              (preference d-o20-n3
               (and (delivered o20 p30)
                    (delivered o20 p24)
                    (delivered o20 p7)))
              (preference d-o21-n1 (delivered o21 p2))
              (preference d-o21-n2
               (and (delivered o21 p13) (delivered o21 p2)))
              (preference d-o21-n3
               (and (delivered o21 p20)
                    (delivered o21 p13)
                    (delivered o21 p2)))
              (preference d-o22-n1 (delivered o22 p5))
              (preference d-o22-n2
               (and (delivered o22 p10) (delivered o22 p5)))
              (preference d-o22-n3
               (and (delivered o22 p23)
                    (delivered o22 p10)
                    (delivered o22 p5)))
              (preference d-o23-n1 (delivered o23 p5))
              (preference d-o23-n2
               (and (delivered o23 p23) (delivered o23 p5)))
              (preference d-o23-n3
               (and (delivered o23 p24)
                    (delivered o23 p23)
                    (delivered o23 p5)))
              (preference d-o24-n1 (delivered o24 p12))
              (preference d-o24-n2
               (and (delivered o24 p14) (delivered o24 p12)))
              (preference d-o24-n3
               (and (delivered o24 p21)
                    (delivered o24 p14)
                    (delivered o24 p12)))
              (preference d-o25-n1 (delivered o25 p1))
              (preference d-o25-n2 (and (delivered o25 p2) (delivered o25 p1)))
              (preference d-o25-n3
               (and (delivered o25 p27) (delivered o25 p2) (delivered o25 p1)))
              (preference d-o26-n1 (delivered o26 p16))
              (preference d-o26-n2
               (and (delivered o26 p26) (delivered o26 p16)))
              (preference d-o26-n3
               (and (delivered o26 p30)
                    (delivered o26 p26)
                    (delivered o26 p16)))
              (preference d-o27-n1 (delivered o27 p4))
              (preference d-o27-n2
               (and (delivered o27 p16) (delivered o27 p4)))
              (preference d-o27-n3
               (and (delivered o27 p30)
                    (delivered o27 p16)
                    (delivered o27 p4)))
              (preference d-o28-n1 (delivered o28 p8))
              (preference d-o28-n2
               (and (delivered o28 p12) (delivered o28 p8)))
              (preference d-o28-n3
               (and (delivered o28 p20)
                    (delivered o28 p12)
                    (delivered o28 p8)))
              (preference d-o29-n1 (delivered o29 p8))
              (preference d-o29-n2
               (and (delivered o29 p18) (delivered o29 p8)))
              (preference d-o29-n3
               (and (delivered o29 p29)
                    (delivered o29 p18)
                    (delivered o29 p8)))
              (preference d-o30-n1 (delivered o30 p4))
              (preference d-o30-n2
               (and (delivered o30 p15) (delivered o30 p4)))
              (preference d-o30-n3
               (and (delivered o30 p25)
                    (delivered o30 p15)
                    (delivered o30 p4)))))
        (:constraints
         (and (preference max1 (always (not (stacks-in-use n1))))
              (preference max2 (always (not (stacks-in-use n2))))
              (preference max3 (always (not (stacks-in-use n3))))
              (preference max4 (always (not (stacks-in-use n4))))
              (preference max5 (always (not (stacks-in-use n5))))
              (preference max6 (always (not (stacks-in-use n6))))
              (preference max7 (always (not (stacks-in-use n7))))
              (preference max8 (always (not (stacks-in-use n8))))
              (preference max9 (always (not (stacks-in-use n9))))
              (preference max10 (always (not (stacks-in-use n10))))
              (preference max11 (always (not (stacks-in-use n11))))
              (preference max12 (always (not (stacks-in-use n12))))
              (preference max13 (always (not (stacks-in-use n13))))
              (preference max14 (always (not (stacks-in-use n14))))
              (preference max15 (always (not (stacks-in-use n15))))
              (preference max16 (always (not (stacks-in-use n16))))
              (preference max17 (always (not (stacks-in-use n17))))
              (preference max18 (always (not (stacks-in-use n18))))
              (preference max19 (always (not (stacks-in-use n19))))
              (preference max20 (always (not (stacks-in-use n20))))
              (preference max21 (always (not (stacks-in-use n21))))
              (preference max22 (always (not (stacks-in-use n22))))
              (preference max23 (always (not (stacks-in-use n23))))
              (preference max24 (always (not (stacks-in-use n24))))
              (preference max25 (always (not (stacks-in-use n25))))
              (preference max26 (always (not (stacks-in-use n26))))
              (preference max27 (always (not (stacks-in-use n27))))
              (preference max28 (always (not (stacks-in-use n28))))
              (preference max29 (always (not (stacks-in-use n29))))
              (preference max30 (always (not (stacks-in-use n30))))))
        (:metric minimize
         (+ (* (is-violated d-o1-n3) 4)
            (* (is-violated d-o1-n2) 2)
            (is-violated d-o1-n1)
            (* (is-violated d-o2-n3) 4)
            (* (is-violated d-o2-n2) 2)
            (is-violated d-o2-n1)
            (* (is-violated d-o3-n3) 4)
            (* (is-violated d-o3-n2) 2)
            (is-violated d-o3-n1)
            (* (is-violated d-o4-n3) 4)
            (* (is-violated d-o4-n2) 2)
            (is-violated d-o4-n1)
            (* (is-violated d-o5-n3) 4)
            (* (is-violated d-o5-n2) 2)
            (is-violated d-o5-n1)
            (* (is-violated d-o6-n3) 4)
            (* (is-violated d-o6-n2) 2)
            (is-violated d-o6-n1)
            (* (is-violated d-o7-n3) 4)
            (* (is-violated d-o7-n2) 2)
            (is-violated d-o7-n1)
            (* (is-violated d-o8-n3) 4)
            (* (is-violated d-o8-n2) 2)
            (is-violated d-o8-n1)
            (* (is-violated d-o9-n3) 4)
            (* (is-violated d-o9-n2) 2)
            (is-violated d-o9-n1)
            (* (is-violated d-o10-n3) 4)
            (* (is-violated d-o10-n2) 2)
            (is-violated d-o10-n1)
            (* (is-violated d-o11-n3) 4)
            (* (is-violated d-o11-n2) 2)
            (is-violated d-o11-n1)
            (* (is-violated d-o12-n3) 4)
            (* (is-violated d-o12-n2) 2)
            (is-violated d-o12-n1)
            (* (is-violated d-o13-n3) 4)
            (* (is-violated d-o13-n2) 2)
            (is-violated d-o13-n1)
            (* (is-violated d-o14-n3) 4)
            (* (is-violated d-o14-n2) 2)
            (is-violated d-o14-n1)
            (* (is-violated d-o15-n3) 4)
            (* (is-violated d-o15-n2) 2)
            (is-violated d-o15-n1)
            (* (is-violated d-o16-n3) 4)
            (* (is-violated d-o16-n2) 2)
            (is-violated d-o16-n1)
            (* (is-violated d-o17-n3) 4)
            (* (is-violated d-o17-n2) 2)
            (is-violated d-o17-n1)
            (* (is-violated d-o18-n3) 4)
            (* (is-violated d-o18-n2) 2)
            (is-violated d-o18-n1)
            (* (is-violated d-o19-n3) 4)
            (* (is-violated d-o19-n2) 2)
            (is-violated d-o19-n1)
            (* (is-violated d-o20-n3) 4)
            (* (is-violated d-o20-n2) 2)
            (is-violated d-o20-n1)
            (* (is-violated d-o21-n3) 4)
            (* (is-violated d-o21-n2) 2)
            (is-violated d-o21-n1)
            (* (is-violated d-o22-n3) 4)
            (* (is-violated d-o22-n2) 2)
            (is-violated d-o22-n1)
            (* (is-violated d-o23-n3) 4)
            (* (is-violated d-o23-n2) 2)
            (is-violated d-o23-n1)
            (* (is-violated d-o24-n3) 4)
            (* (is-violated d-o24-n2) 2)
            (is-violated d-o24-n1)
            (* (is-violated d-o25-n3) 4)
            (* (is-violated d-o25-n2) 2)
            (is-violated d-o25-n1)
            (* (is-violated d-o26-n3) 4)
            (* (is-violated d-o26-n2) 2)
            (is-violated d-o26-n1)
            (* (is-violated d-o27-n3) 4)
            (* (is-violated d-o27-n2) 2)
            (is-violated d-o27-n1)
            (* (is-violated d-o28-n3) 4)
            (* (is-violated d-o28-n2) 2)
            (is-violated d-o28-n1)
            (* (is-violated d-o29-n3) 4)
            (* (is-violated d-o29-n2) 2)
            (is-violated d-o29-n1)
            (* (is-violated d-o30-n3) 4)
            (* (is-violated d-o30-n2) 2)
            (is-violated d-o30-n1)
            (* (is-violated max1) 17.5)
            (* (is-violated max2) 17.5)
            (* (is-violated max3) 17.5)
            (* (is-violated max4) 17.5)
            (* (is-violated max5) 17.5)
            (* (is-violated max6) 17.5)
            (* (is-violated max7) 17.5)
            (* (is-violated max8) 17.5)
            (* (is-violated max9) 17.5)
            (* (is-violated max10) 17.5)
            (* (is-violated max11) 17.5)
            (* (is-violated max12) 17.5)
            (* (is-violated max13) 17.5)
            (* (is-violated max14) 17.5)
            (* (is-violated max15) 17.5)
            (* (is-violated max16) 17.5)
            (* (is-violated max17) 17.5)
            (* (is-violated max18) 17.5)
            (* (is-violated max19) 17.5)
            (* (is-violated max20) 17.5)
            (* (is-violated max21) 17.5)
            (* (is-violated max22) 17.5)
            (* (is-violated max23) 17.5)
            (* (is-violated max24) 17.5)
            (* (is-violated max25) 17.5)
            (* (is-violated max26) 17.5)
            (* (is-violated max27) 17.5)
            (* (is-violated max28) 17.5)
            (* (is-violated max29) 17.5)
            (* (is-violated max30) 17.5))))
