; Time: 0.03 seconds
(define (problem GROUNDED-TRUCK-9)
(:domain GROUNDED-TRUCKS)
(:init
(FOO)
(time-now_t0)
(at_package8_l1)
(at_package7_l1)
(at_package6_l3)
(at_package5_l3)
(at_package4_l3)
(at_package3_l3)
(at_package2_l3)
(at_package1_l3)
(free_a3_truck1)
(free_a2_truck1)
(free_a1_truck1)
(at_truck1_l3)
)
(:goal
(and
(delivered_package8_l2_t12)
(delivered_package7_l3_t12)
(delivered_package6_l1_t8)
(at-destination_package5_l1)
(delivered_package4_l1_t8)
(delivered_package3_l2_t4)
(delivered_package2_l2_t4)
(delivered_package1_l2_t4)
)
)
)