; Time: 0.02 seconds
(define (problem GROUNDED-TRUCK-5)
(:domain GROUNDED-TRUCKS)
(:init
(FOO)
(time-now_t0)
(at_package7_l2)
(at_package6_l3)
(at_package5_l3)
(at_package4_l2)
(at_package3_l2)
(at_package2_l1)
(at_package1_l1)
(free_a2_truck1)
(free_a1_truck1)
(at_truck1_l2)
)
(:goal
(and
(at-destination_package7_l1)
(at-destination_package6_l2)
(delivered_package5_l2_t9)
(at-destination_package4_l3)
(delivered_package3_l1_t6)
(at-destination_package2_l2)
(at-destination_package1_l3)
)
)
)