; Time: 0.01 seconds
(define (problem GROUNDED-TRUCK-3)
(:domain GROUNDED-TRUCKS)
(:init
(FOO)
(time-now_t0)
(at_package5_l2)
(at_package4_l1)
(at_package3_l1)
(at_package2_l1)
(at_package1_l1)
(free_a2_truck1)
(free_a1_truck1)
(at_truck1_l2)
)
(:goal
(and
(at-destination_package5_l3)
(at-destination_package4_l3)
(at-destination_package3_l3)
(delivered_package2_l2_t3)
(at-destination_package1_l2)
)
)
)