(define (problem strips-mprime-x-16)
   (:domain mystery-prime-strips)
   (:objects chicken pepper guava marzipan bacon arugula flounder
             wonderbread baguette rice chocolate rest stimulation excitement
             satiety learning achievement triumph prostatitis boils
             loneliness depression angina jealousy abrasion sciatica grief
             manitoba alsace bosnia kentucky pennsylvania goias mercury
             neptune vulcan earth)
   (:init (food chicken)
          (food pepper)
          (food guava)
          (food marzipan)
          (food bacon)
          (food arugula)
          (food flounder)
          (food wonderbread)
          (food baguette)
          (food rice)
          (food chocolate)
          (pleasure rest)
          (pleasure stimulation)
          (pleasure excitement)
          (pleasure satiety)
          (pleasure learning)
          (pleasure achievement)
          (pleasure triumph)
          (pain prostatitis)
          (pain boils)
          (pain loneliness)
          (pain depression)
          (pain angina)
          (pain jealousy)
          (pain abrasion)
          (pain sciatica)
          (pain grief)
          (province manitoba)
          (province alsace)
          (province bosnia)
          (province kentucky)
          (province pennsylvania)
          (province goias)
          (planet mercury)
          (planet neptune)
          (planet vulcan)
          (planet earth)
          (eats wonderbread flounder)
          (locale flounder alsace)
          (harmony stimulation earth)
          (harmony learning vulcan)
          (locale baguette manitoba)
          (eats chicken bacon)
          (attacks pennsylvania goias)
          (harmony satiety neptune)
          (craves excitement arugula)
          (craves angina wonderbread)
          (locale bacon pennsylvania)
          (craves rest chicken)
          (craves triumph chocolate)
          (eats arugula baguette)
          (eats chocolate flounder)
          (eats pepper chocolate)
          (craves depression bacon)
          (locale chicken manitoba)
          (orbits mercury neptune)
          (eats arugula wonderbread)
          (locale rice alsace)
          (locale chocolate goias)
          (attacks alsace bosnia)
          (craves learning baguette)
          (eats guava baguette)
          (orbits neptune vulcan)
          (attacks manitoba alsace)
          (orbits vulcan earth)
          (attacks kentucky pennsylvania)
          (eats baguette arugula)
          (craves stimulation pepper)
          (craves sciatica baguette)
          (craves boils pepper)
          (locale guava pennsylvania)
          (locale marzipan manitoba)
          (craves grief baguette)
          (eats pepper guava)
          (eats wonderbread arugula)
          (eats bacon chicken)
          (eats rice bacon)
          (craves prostatitis chicken)
          (eats chicken marzipan)
          (eats chocolate marzipan)
          (craves jealousy wonderbread)
          (eats marzipan chicken)
          (craves loneliness bacon)
          (eats rice baguette)
          (eats flounder chocolate)
          (harmony achievement vulcan)
          (craves satiety wonderbread)
          (craves abrasion baguette)
          (harmony rest neptune)
          (eats guava pepper)
          (harmony excitement earth)
          (eats baguette guava)
          (eats chocolate pepper)
          (eats flounder wonderbread)
          (locale arugula kentucky)
          (craves achievement rice)
          (eats marzipan chocolate)
          (eats bacon rice)
          (attacks bosnia kentucky)
          (eats baguette rice)
          (harmony triumph vulcan)
          (locale wonderbread bosnia)
          (locale pepper kentucky))
   (:goal (and (craves abrasion rice)
               (craves sciatica rice))))