(define (problem strips-mprime-x-8)
   (:domain mystery-prime-strips)
   (:objects rice okra hotdog tofu muffin tuna pork cantelope turkey
             baguette arugula wonderbread pepper flounder lobster scallop
             tomato pistachio achievement love triumph stimulation
             learning lubricity rest aesthetics excitement sciatica
             hangover anxiety abrasion anger bavaria goias pennsylvania
             bosnia surrey earth uranus vulcan jupiter)
   (:init (food rice)
          (food okra)
          (food hotdog)
          (food tofu)
          (food muffin)
          (food tuna)
          (food pork)
          (food cantelope)
          (food turkey)
          (food baguette)
          (food arugula)
          (food wonderbread)
          (food pepper)
          (food flounder)
          (food lobster)
          (food scallop)
          (food tomato)
          (food pistachio)
          (pleasure achievement)
          (pleasure love)
          (pleasure triumph)
          (pleasure stimulation)
          (pleasure learning)
          (pleasure lubricity)
          (pleasure rest)
          (pleasure aesthetics)
          (pleasure excitement)
          (pain sciatica)
          (pain hangover)
          (pain anxiety)
          (pain abrasion)
          (pain anger)
          (province bavaria)
          (province goias)
          (province pennsylvania)
          (province bosnia)
          (province surrey)
          (planet earth)
          (planet uranus)
          (planet vulcan)
          (planet jupiter)
          (harmony learning vulcan)
          (attacks bavaria goias)
          (eats turkey baguette)
          (eats muffin tuna)
          (eats flounder wonderbread)
          (harmony stimulation uranus)
          (eats wonderbread scallop)
          (craves excitement tomato)
          (eats tuna muffin)
          (eats pistachio arugula)
          (harmony achievement vulcan)
          (harmony rest jupiter)
          (locale pork bosnia)
          (craves hangover muffin)
          (eats rice tofu)
          (locale flounder goias)
          (eats cantelope arugula)
          (attacks goias pennsylvania)
          (eats pork lobster)
          (craves lubricity arugula)
          (orbits uranus vulcan)
          (eats okra hotdog)
          (locale tuna surrey)
          (craves sciatica okra)
          (craves anxiety muffin)
          (eats flounder lobster)
          (locale scallop pennsylvania)
          (eats tuna rice)
          (locale turkey goias)
          (craves love okra)
          (eats okra wonderbread)
          (locale tofu goias)
          (eats arugula pistachio)
          (eats rice tuna)
          (orbits vulcan jupiter)
          (craves abrasion baguette)
          (eats baguette turkey)
          (eats tomato scallop)
          (eats tuna okra)
          (attacks bosnia surrey)
          (locale tomato bosnia)
          (eats scallop tomato)
          (locale pepper goias)
          (eats hotdog okra)
          (craves triumph hotdog)
          (eats hotdog tofu)
          (locale cantelope pennsylvania)
          (eats muffin rice)
          (craves learning cantelope)
          (craves anger baguette)
          (eats muffin tofu)
          (craves rest wonderbread)
          (locale hotdog bavaria)
          (eats wonderbread flounder)
          (eats wonderbread okra)
          (eats tofu rice)
          (harmony love jupiter)
          (craves achievement rice)
          (eats baguette tomato)
          (harmony aesthetics vulcan)
          (locale rice bavaria)
          (eats tomato baguette)
          (eats tofu muffin)
          (eats tofu hotdog)
          (locale wonderbread goias)
          (eats arugula cantelope)
          (locale pistachio pennsylvania)
          (eats rice muffin)
          (eats scallop wonderbread)
          (eats pistachio pepper)
          (eats lobster pork)
          (eats lobster flounder)
          (eats pepper turkey)
          (locale lobster goias)
          (attacks pennsylvania bosnia)
          (orbits earth uranus)
          (eats pork cantelope)
          (locale baguette bosnia)
          (harmony excitement jupiter)
          (locale okra bosnia)
          (harmony triumph vulcan)
          (eats okra tuna)
          (eats cantelope pork)
          (eats turkey pepper)
          (harmony lubricity uranus)
          (locale muffin bavaria)
          (craves aesthetics scallop)
          (craves stimulation muffin)
          (eats pepper pistachio)
          (locale arugula bavaria))
   (:goal (and (craves anxiety wonderbread))))