(define (problem settlers)
(:domain civ)
(:objects
	location0 - place
	location1 - place
	location2 - place
	location3 - place
	location4 - place
	location5 - place
	location6 - place
	location7 - place
	location8 - place
	location9 - place
	location10 - place
	location11 - place
	vehicle0 - vehicle
	vehicle1 - vehicle
	vehicle2 - vehicle
	vehicle3 - vehicle
	vehicle4 - vehicle
	vehicle5 - vehicle
	vehicle6 - vehicle
	vehicle7 - vehicle
	vehicle8 - vehicle
	vehicle9 - vehicle
)
(:init
	(= (resource-use) 0)
	(= (labour) 0)
	(= (pollution) 0)
	(woodland location0)
	(by-coast location0)
	(= (housing location0) 0)
	(= (available wood location0) 0)
	(= (available timber location0) 0)
	(= (available ore location0) 0)
	(= (available stone location0) 0)
	(= (available iron location0) 0)
	(= (available coal location0) 0)
	(woodland location1)
	(by-coast location1)
	(= (housing location1) 0)
	(= (available wood location1) 0)
	(= (available timber location1) 0)
	(= (available ore location1) 0)
	(= (available stone location1) 0)
	(= (available iron location1) 0)
	(= (available coal location1) 0)
	(woodland location2)
	(by-coast location2)
	(= (housing location2) 0)
	(= (available wood location2) 0)
	(= (available timber location2) 0)
	(= (available ore location2) 0)
	(= (available stone location2) 0)
	(= (available iron location2) 0)
	(= (available coal location2) 0)
	(mountain location3)
	(by-coast location3)
	(= (housing location3) 0)
	(= (available wood location3) 0)
	(= (available timber location3) 0)
	(= (available ore location3) 0)
	(= (available stone location3) 0)
	(= (available iron location3) 0)
	(= (available coal location3) 0)
	(= (housing location4) 0)
	(= (available wood location4) 0)
	(= (available timber location4) 0)
	(= (available ore location4) 0)
	(= (available stone location4) 0)
	(= (available iron location4) 0)
	(= (available coal location4) 0)
	(woodland location5)
	(by-coast location5)
	(metalliferous location5)
	(= (housing location5) 0)
	(= (available wood location5) 0)
	(= (available timber location5) 0)
	(= (available ore location5) 0)
	(= (available stone location5) 0)
	(= (available iron location5) 0)
	(= (available coal location5) 0)
	(mountain location6)
	(woodland location6)
	(by-coast location6)
	(= (housing location6) 0)
	(= (available wood location6) 0)
	(= (available timber location6) 0)
	(= (available ore location6) 0)
	(= (available stone location6) 0)
	(= (available iron location6) 0)
	(= (available coal location6) 0)
	(mountain location7)
	(metalliferous location7)
	(= (housing location7) 0)
	(= (available wood location7) 0)
	(= (available timber location7) 0)
	(= (available ore location7) 0)
	(= (available stone location7) 0)
	(= (available iron location7) 0)
	(= (available coal location7) 0)
	(woodland location8)
	(= (housing location8) 0)
	(= (available wood location8) 0)
	(= (available timber location8) 0)
	(= (available ore location8) 0)
	(= (available stone location8) 0)
	(= (available iron location8) 0)
	(= (available coal location8) 0)
	(mountain location9)
	(= (housing location9) 0)
	(= (available wood location9) 0)
	(= (available timber location9) 0)
	(= (available ore location9) 0)
	(= (available stone location9) 0)
	(= (available iron location9) 0)
	(= (available coal location9) 0)
	(mountain location10)
	(woodland location10)
	(= (housing location10) 0)
	(= (available wood location10) 0)
	(= (available timber location10) 0)
	(= (available ore location10) 0)
	(= (available stone location10) 0)
	(= (available iron location10) 0)
	(= (available coal location10) 0)
	(woodland location11)
	(= (housing location11) 0)
	(= (available wood location11) 0)
	(= (available timber location11) 0)
	(= (available ore location11) 0)
	(= (available stone location11) 0)
	(= (available iron location11) 0)
	(= (available coal location11) 0)
	(connected-by-land location0 location2)
	(connected-by-land location2 location0)
	(connected-by-land location1 location0)
	(connected-by-land location0 location1)
	(connected-by-land location1 location2)
	(connected-by-land location2 location1)
	(connected-by-land location1 location6)
	(connected-by-land location6 location1)
	(connected-by-land location1 location10)
	(connected-by-land location10 location1)
	(connected-by-land location2 location3)
	(connected-by-land location3 location2)
	(connected-by-land location2 location4)
	(connected-by-land location4 location2)
	(connected-by-land location2 location5)
	(connected-by-land location5 location2)
	(connected-by-land location2 location10)
	(connected-by-land location10 location2)
	(connected-by-land location3 location10)
	(connected-by-land location10 location3)
	(connected-by-land location4 location6)
	(connected-by-land location6 location4)
	(connected-by-land location4 location7)
	(connected-by-land location7 location4)
	(connected-by-land location4 location8)
	(connected-by-land location8 location4)
	(connected-by-land location5 location6)
	(connected-by-land location6 location5)
	(connected-by-land location5 location8)
	(connected-by-land location8 location5)
	(connected-by-land location5 location9)
	(connected-by-land location9 location5)
	(connected-by-land location6 location0)
	(connected-by-land location0 location6)
	(connected-by-land location7 location0)
	(connected-by-land location0 location7)
	(connected-by-land location7 location1)
	(connected-by-land location1 location7)
	(connected-by-land location7 location3)
	(connected-by-land location3 location7)
	(connected-by-land location7 location5)
	(connected-by-land location5 location7)
	(connected-by-land location7 location8)
	(connected-by-land location8 location7)
	(connected-by-land location7 location11)
	(connected-by-land location11 location7)
	(connected-by-land location8 location3)
	(connected-by-land location3 location8)
	(connected-by-land location9 location0)
	(connected-by-land location0 location9)
	(connected-by-land location9 location1)
	(connected-by-land location1 location9)
	(connected-by-land location9 location3)
	(connected-by-land location3 location9)
	(connected-by-land location9 location7)
	(connected-by-land location7 location9)
	(connected-by-land location9 location11)
	(connected-by-land location11 location9)
	(connected-by-land location10 location4)
	(connected-by-land location4 location10)
	(connected-by-land location10 location5)
	(connected-by-land location5 location10)
	(connected-by-land location10 location6)
	(connected-by-land location6 location10)
	(connected-by-land location10 location11)
	(connected-by-land location11 location10)
	(connected-by-land location11 location1)
	(connected-by-land location1 location11)
	(connected-by-land location11 location2)
	(connected-by-land location2 location11)
	(connected-by-land location11 location6)
	(connected-by-land location6 location11)
	(connected-by-land location11 location8)
	(connected-by-land location8 location11)
	(connected-by-sea location0 location3)
	(connected-by-sea location3 location0)
	(connected-by-sea location2 location6)
	(connected-by-sea location6 location2)
	(potential vehicle0)
	(potential vehicle1)
	(potential vehicle2)
	(potential vehicle3)
	(potential vehicle4)
	(potential vehicle5)
	(potential vehicle6)
	(potential vehicle7)
	(potential vehicle8)
	(potential vehicle9)
)
(:goal (and
	(connected-by-rail location1 location0)
	(connected-by-rail location0 location2)
	(connected-by-rail location2 location10)
	(>= (housing location0) 1)
	(has-coal-stack location0)
	(>= (housing location6) 1)
	(connected-by-rail location1 location10)
	(connected-by-rail location10 location11)
	(connected-by-rail location11 location2)
	(connected-by-rail location2 location4)
	(has-coal-stack location2)
	(>= (housing location9) 1)
	(has-ironworks location4)
	(>= (housing location4) 2)
	(has-coal-stack location5)
	(has-sawmill location5)
	(connected-by-rail location11 location6)
	(connected-by-rail location6 location0)
	(has-ironworks location7)
	(>= (housing location10) 2)
	)
)

(:metric minimize (+ (+ (* 1 (pollution)) (* 0 (resource-use))) (* 2 (labour))))
)
