(define (problem p10_hosts_trial_9)
(:domain caldera-split)
(:objects
    id_fmrat - observedrat
    id_fnrat - observedrat
    id_fjrat - observedrat
    id_firat - observedrat
    id_fqrat - observedrat
    id_frrat - observedrat
    id_forat - observedrat
    id_fgrat - observedrat
    id_fkrat - observedrat
    id_flrat - observedrat
    id_fprat - observedrat
    str__r - string
    str__dw - string
    str__dv - string
    str__du - string
    str__q - string
    str__db - string
    str__da - string
    str__ey - string
    str__james - string
    str__robert - string
    str__michael - string
    str__bp - string
    str__ec - string
    str__cs - string
    str__cn - string
    str__ex - string
    str__dn - string
    str__bd - string
    str__susan - string
    str__bw - string
    str__ej - string
    str__fe - string
    str__m - string
    str__e - string
    str__i - string
    str__dp - string
    str__ff - string
    str__cm - string
    str__ew - string
    str__ca - string
    str__eq - string
    str__ce - string
    str__john - string
    str__cf - string
    str__y - string
    str__maria - string
    str__cz - string
    str__dg - string
    str__elizabeth - string
    str__ed - string
    str__cb - string
    str__barbara - string
    str__alpha - string
    str__do - string
    str__b - string
    str__bt - string
    str__jennifer - string
    str__bh - string
    str__cu - string
    str__bs - string
    str__charles - string
    str__u - string
    str__di - string
    str__william - string
    str__ct - string
    str__n - string
    str__linda - string
    str__ek - string
    str__fh - string
    str__ep - string
    str__f - string
    str__z - string
    str__richard - string
    str__dh - string
    str__bx - string
    str__bc - string
    str__cj - string
    str__bg - string
    str__david - string
    str__ei - string
    str__j - string
    str__bl - string
    str__patricia - string
    str__er - string
    str__eb - string
    str__v - string
    str__bo - string
    str__ci - string
    str__fd - string
    str__bk - string
    str__mary - string
    num__69 - num
    num__76 - num
    num__125 - num
    num__104 - num
    num__83 - num
    num__132 - num
    num__97 - num
    num__117 - num
    num__75 - num
    num__82 - num
    num__68 - num
    num__89 - num
    num__131 - num
    num__103 - num
    num__96 - num
    num__111 - num
    num__118 - num
    num__110 - num
    num__90 - num
    num__124 - num
    id_gifile - observedfile
    id_ghfile - observedfile
    id_gjfile - observedfile
    id_gkfile - observedfile
    id_gcfile - observedfile
    id_gdfile - observedfile
    id_ggfile - observedfile
    id_glfile - observedfile
    id_gefile - observedfile
    id_gffile - observedfile
    id_cptimedelta - observedtimedelta
    id_eftimedelta - observedtimedelta
    id_dytimedelta - observedtimedelta
    id_ddtimedelta - observedtimedelta
    id_ettimedelta - observedtimedelta
    id_dktimedelta - observedtimedelta
    id_drtimedelta - observedtimedelta
    id_fatimedelta - observedtimedelta
    id_emtimedelta - observedtimedelta
    id_cwtimedelta - observedtimedelta
    id_ddomaincredential - observeddomaincredential
    id_bjdomaincredential - observeddomaincredential
    id_xdomaincredential - observeddomaincredential
    id_ldomaincredential - observeddomaincredential
    id_bzdomaincredential - observeddomaincredential
    id_bndomaincredential - observeddomaincredential
    id_cddomaincredential - observeddomaincredential
    id_bfdomaincredential - observeddomaincredential
    id_cldomaincredential - observeddomaincredential
    id_brdomaincredential - observeddomaincredential
    id_hdomaincredential - observeddomaincredential
    id_bbdomaincredential - observeddomaincredential
    id_bvdomaincredential - observeddomaincredential
    id_pdomaincredential - observeddomaincredential
    id_tdomaincredential - observeddomaincredential
    id_chdomaincredential - observeddomaincredential
    id_dxhost - observedhost
    id_eshost - observedhost
    id_ezhost - observedhost
    id_cvhost - observedhost
    id_dqhost - observedhost
    id_dchost - observedhost
    id_elhost - observedhost
    id_cohost - observedhost
    id_eehost - observedhost
    id_djhost - observedhost
    id_gdomainuser - observeddomainuser
    id_cdomainuser - observeddomainuser
    id_odomainuser - observeddomainuser
    id_kdomainuser - observeddomainuser
    id_ccdomainuser - observeddomainuser
    id_bmdomainuser - observeddomainuser
    id_wdomainuser - observeddomainuser
    id_budomainuser - observeddomainuser
    id_cgdomainuser - observeddomainuser
    id_bedomainuser - observeddomainuser
    id_badomainuser - observeddomainuser
    id_sdomainuser - observeddomainuser
    id_bqdomainuser - observeddomainuser
    id_ckdomainuser - observeddomainuser
    id_bydomainuser - observeddomainuser
    id_bidomainuser - observeddomainuser
    id_fwshare - observedshare
    id_fxshare - observedshare
    id_ftshare - observedshare
    id_gbshare - observedshare
    id_fvshare - observedshare
    id_fzshare - observedshare
    id_gashare - observedshare
    id_fsshare - observedshare
    id_fushare - observedshare
    id_fyshare - observedshare
    id_adomain - observeddomain
    id_gtschtask - observedschtask
    id_gmschtask - observedschtask
    id_gqschtask - observedschtask
    id_guschtask - observedschtask
    id_gvschtask - observedschtask
    id_grschtask - observedschtask
    id_goschtask - observedschtask
    id_gsschtask - observedschtask
    id_gpschtask - observedschtask
    id_gnschtask - observedschtask
)
(:init
    (knows id_eehost)
    (knows id_fgrat)
    (knows_property id_eehost pfqdn)
    (knows_property id_fgrat pexecutable)
    (knows_property id_fgrat phost)
    (MEM_CACHED_DOMAIN_CREDS id_cohost id_cddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_cohost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_cohost id_pdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_cvhost id_bjdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_cvhost id_brdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_cvhost id_chdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dchost id_brdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dchost id_cddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dchost id_ldomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_djhost id_brdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_djhost id_cddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_djhost id_pdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dqhost id_bvdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dqhost id_cldomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dqhost id_hdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dxhost id_bzdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dxhost id_cldomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dxhost id_tdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_eehost id_cddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_eehost id_chdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_eehost id_hdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_elhost id_bfdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_elhost id_brdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_elhost id_bzdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_eshost id_hdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_eshost id_ldomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_eshost id_xdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_ezhost id_bbdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_ezhost id_bzdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_ezhost id_tdomaincredential)
    (MEM_DOMAIN_USER_ADMINS id_cohost id_badomainuser)
    (MEM_DOMAIN_USER_ADMINS id_cvhost id_bydomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dchost id_ccdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_djhost id_odomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dqhost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dxhost id_bqdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_eehost id_bidomainuser)
    (MEM_DOMAIN_USER_ADMINS id_elhost id_sdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_eshost id_bidomainuser)
    (MEM_DOMAIN_USER_ADMINS id_ezhost id_bqdomainuser)
    (mem_hosts id_adomain id_cohost)
    (mem_hosts id_adomain id_cvhost)
    (mem_hosts id_adomain id_dchost)
    (mem_hosts id_adomain id_djhost)
    (mem_hosts id_adomain id_dqhost)
    (mem_hosts id_adomain id_dxhost)
    (mem_hosts id_adomain id_eehost)
    (mem_hosts id_adomain id_elhost)
    (mem_hosts id_adomain id_eshost)
    (mem_hosts id_adomain id_ezhost)
    (prop_cred id_badomainuser id_bbdomaincredential)
    (prop_cred id_bedomainuser id_bfdomaincredential)
    (prop_cred id_bidomainuser id_bjdomaincredential)
    (prop_cred id_bmdomainuser id_bndomaincredential)
    (prop_cred id_bqdomainuser id_brdomaincredential)
    (prop_cred id_budomainuser id_bvdomaincredential)
    (prop_cred id_bydomainuser id_bzdomaincredential)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_ccdomainuser id_cddomaincredential)
    (prop_cred id_cgdomainuser id_chdomaincredential)
    (prop_cred id_ckdomainuser id_cldomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (prop_cred id_wdomainuser id_xdomaincredential)
    (PROP_DC id_cohost no)
    (PROP_DC id_cvhost no)
    (PROP_DC id_dchost no)
    (PROP_DC id_djhost yes)
    (PROP_DC id_dqhost no)
    (PROP_DC id_dxhost no)
    (PROP_DC id_eehost no)
    (PROP_DC id_elhost no)
    (PROP_DC id_eshost no)
    (PROP_DC id_ezhost yes)
    (PROP_DNS_DOMAIN id_adomain str__b)
    (PROP_DNS_DOMAIN_NAME id_cohost str__cs)
    (PROP_DNS_DOMAIN_NAME id_cvhost str__cz)
    (PROP_DNS_DOMAIN_NAME id_dchost str__dg)
    (PROP_DNS_DOMAIN_NAME id_djhost str__dn)
    (PROP_DNS_DOMAIN_NAME id_dqhost str__du)
    (PROP_DNS_DOMAIN_NAME id_dxhost str__eb)
    (PROP_DNS_DOMAIN_NAME id_eehost str__ei)
    (PROP_DNS_DOMAIN_NAME id_elhost str__ep)
    (PROP_DNS_DOMAIN_NAME id_eshost str__ew)
    (PROP_DNS_DOMAIN_NAME id_ezhost str__fd)
    (PROP_DOMAIN id_badomainuser id_adomain)
    (PROP_DOMAIN id_bbdomaincredential id_adomain)
    (PROP_DOMAIN id_bedomainuser id_adomain)
    (PROP_DOMAIN id_bfdomaincredential id_adomain)
    (PROP_DOMAIN id_bidomainuser id_adomain)
    (PROP_DOMAIN id_bjdomaincredential id_adomain)
    (PROP_DOMAIN id_bmdomainuser id_adomain)
    (PROP_DOMAIN id_bndomaincredential id_adomain)
    (PROP_DOMAIN id_bqdomainuser id_adomain)
    (PROP_DOMAIN id_brdomaincredential id_adomain)
    (PROP_DOMAIN id_budomainuser id_adomain)
    (PROP_DOMAIN id_bvdomaincredential id_adomain)
    (PROP_DOMAIN id_bydomainuser id_adomain)
    (PROP_DOMAIN id_bzdomaincredential id_adomain)
    (PROP_DOMAIN id_cdomainuser id_adomain)
    (PROP_DOMAIN id_ccdomainuser id_adomain)
    (PROP_DOMAIN id_cddomaincredential id_adomain)
    (PROP_DOMAIN id_cgdomainuser id_adomain)
    (PROP_DOMAIN id_chdomaincredential id_adomain)
    (PROP_DOMAIN id_ckdomainuser id_adomain)
    (PROP_DOMAIN id_cldomaincredential id_adomain)
    (PROP_DOMAIN id_cohost id_adomain)
    (PROP_DOMAIN id_cvhost id_adomain)
    (PROP_DOMAIN id_ddomaincredential id_adomain)
    (PROP_DOMAIN id_dchost id_adomain)
    (PROP_DOMAIN id_djhost id_adomain)
    (PROP_DOMAIN id_dqhost id_adomain)
    (PROP_DOMAIN id_dxhost id_adomain)
    (PROP_DOMAIN id_eehost id_adomain)
    (PROP_DOMAIN id_elhost id_adomain)
    (PROP_DOMAIN id_eshost id_adomain)
    (PROP_DOMAIN id_ezhost id_adomain)
    (PROP_DOMAIN id_gdomainuser id_adomain)
    (PROP_DOMAIN id_hdomaincredential id_adomain)
    (PROP_DOMAIN id_kdomainuser id_adomain)
    (PROP_DOMAIN id_ldomaincredential id_adomain)
    (PROP_DOMAIN id_odomainuser id_adomain)
    (PROP_DOMAIN id_pdomaincredential id_adomain)
    (PROP_DOMAIN id_sdomainuser id_adomain)
    (PROP_DOMAIN id_tdomaincredential id_adomain)
    (PROP_DOMAIN id_wdomainuser id_adomain)
    (PROP_DOMAIN id_xdomaincredential id_adomain)
    (prop_elevated id_fgrat yes)
    (prop_executable id_fgrat str__fh)
    (PROP_FQDN id_cohost str__cu)
    (PROP_FQDN id_cvhost str__db)
    (PROP_FQDN id_dchost str__di)
    (PROP_FQDN id_djhost str__dp)
    (PROP_FQDN id_dqhost str__dw)
    (PROP_FQDN id_dxhost str__ed)
    (PROP_FQDN id_eehost str__ek)
    (PROP_FQDN id_elhost str__er)
    (PROP_FQDN id_eshost str__ey)
    (PROP_FQDN id_ezhost str__ff)
    (prop_host id_cptimedelta id_cohost)
    (prop_host id_cwtimedelta id_cvhost)
    (prop_host id_ddtimedelta id_dchost)
    (prop_host id_dktimedelta id_djhost)
    (prop_host id_drtimedelta id_dqhost)
    (prop_host id_dytimedelta id_dxhost)
    (prop_host id_eftimedelta id_eehost)
    (prop_host id_emtimedelta id_elhost)
    (prop_host id_ettimedelta id_eshost)
    (prop_host id_fatimedelta id_ezhost)
    (prop_host id_fgrat id_eehost)
    (PROP_HOSTNAME id_cohost str__ct)
    (PROP_HOSTNAME id_cvhost str__da)
    (PROP_HOSTNAME id_dchost str__dh)
    (PROP_HOSTNAME id_djhost str__do)
    (PROP_HOSTNAME id_dqhost str__dv)
    (PROP_HOSTNAME id_dxhost str__ec)
    (PROP_HOSTNAME id_eehost str__ej)
    (PROP_HOSTNAME id_elhost str__eq)
    (PROP_HOSTNAME id_eshost str__ex)
    (PROP_HOSTNAME id_ezhost str__fe)
    (PROP_IS_GROUP id_badomainuser no)
    (PROP_IS_GROUP id_bedomainuser no)
    (PROP_IS_GROUP id_bidomainuser no)
    (PROP_IS_GROUP id_bmdomainuser no)
    (PROP_IS_GROUP id_bqdomainuser no)
    (PROP_IS_GROUP id_budomainuser no)
    (PROP_IS_GROUP id_bydomainuser no)
    (PROP_IS_GROUP id_cdomainuser no)
    (PROP_IS_GROUP id_ccdomainuser no)
    (PROP_IS_GROUP id_cgdomainuser no)
    (PROP_IS_GROUP id_ckdomainuser no)
    (PROP_IS_GROUP id_gdomainuser no)
    (PROP_IS_GROUP id_kdomainuser no)
    (PROP_IS_GROUP id_odomainuser no)
    (PROP_IS_GROUP id_sdomainuser no)
    (PROP_IS_GROUP id_wdomainuser no)
    (PROP_MICROSECONDS id_cptimedelta num__68)
    (PROP_MICROSECONDS id_cwtimedelta num__75)
    (PROP_MICROSECONDS id_ddtimedelta num__82)
    (PROP_MICROSECONDS id_dktimedelta num__89)
    (PROP_MICROSECONDS id_drtimedelta num__96)
    (PROP_MICROSECONDS id_dytimedelta num__103)
    (PROP_MICROSECONDS id_eftimedelta num__110)
    (PROP_MICROSECONDS id_emtimedelta num__117)
    (PROP_MICROSECONDS id_ettimedelta num__124)
    (PROP_MICROSECONDS id_fatimedelta num__131)
    (PROP_PASSWORD id_bbdomaincredential str__bc)
    (PROP_PASSWORD id_bfdomaincredential str__bg)
    (PROP_PASSWORD id_bjdomaincredential str__bk)
    (PROP_PASSWORD id_bndomaincredential str__bo)
    (PROP_PASSWORD id_brdomaincredential str__bs)
    (PROP_PASSWORD id_bvdomaincredential str__bw)
    (PROP_PASSWORD id_bzdomaincredential str__ca)
    (PROP_PASSWORD id_cddomaincredential str__ce)
    (PROP_PASSWORD id_chdomaincredential str__ci)
    (PROP_PASSWORD id_cldomaincredential str__cm)
    (PROP_PASSWORD id_ddomaincredential str__e)
    (PROP_PASSWORD id_hdomaincredential str__i)
    (PROP_PASSWORD id_ldomaincredential str__m)
    (PROP_PASSWORD id_pdomaincredential str__q)
    (PROP_PASSWORD id_tdomaincredential str__u)
    (PROP_PASSWORD id_xdomaincredential str__y)
    (PROP_SECONDS id_cptimedelta num__69)
    (PROP_SECONDS id_cwtimedelta num__76)
    (PROP_SECONDS id_ddtimedelta num__83)
    (PROP_SECONDS id_dktimedelta num__90)
    (PROP_SECONDS id_drtimedelta num__97)
    (PROP_SECONDS id_dytimedelta num__104)
    (PROP_SECONDS id_eftimedelta num__111)
    (PROP_SECONDS id_emtimedelta num__118)
    (PROP_SECONDS id_ettimedelta num__125)
    (PROP_SECONDS id_fatimedelta num__132)
    (PROP_SID id_badomainuser str__bd)
    (PROP_SID id_bedomainuser str__bh)
    (PROP_SID id_bidomainuser str__bl)
    (PROP_SID id_bmdomainuser str__bp)
    (PROP_SID id_bqdomainuser str__bt)
    (PROP_SID id_budomainuser str__bx)
    (PROP_SID id_bydomainuser str__cb)
    (PROP_SID id_cdomainuser str__f)
    (PROP_SID id_ccdomainuser str__cf)
    (PROP_SID id_cgdomainuser str__cj)
    (PROP_SID id_ckdomainuser str__cn)
    (PROP_SID id_gdomainuser str__j)
    (PROP_SID id_kdomainuser str__n)
    (PROP_SID id_odomainuser str__r)
    (PROP_SID id_sdomainuser str__v)
    (PROP_SID id_wdomainuser str__z)
    (PROP_TIMEDELTA id_cohost id_cptimedelta)
    (PROP_TIMEDELTA id_cvhost id_cwtimedelta)
    (PROP_TIMEDELTA id_dchost id_ddtimedelta)
    (PROP_TIMEDELTA id_djhost id_dktimedelta)
    (PROP_TIMEDELTA id_dqhost id_drtimedelta)
    (PROP_TIMEDELTA id_dxhost id_dytimedelta)
    (PROP_TIMEDELTA id_eehost id_eftimedelta)
    (PROP_TIMEDELTA id_elhost id_emtimedelta)
    (PROP_TIMEDELTA id_eshost id_ettimedelta)
    (PROP_TIMEDELTA id_ezhost id_fatimedelta)
    (PROP_USER id_bbdomaincredential id_badomainuser)
    (PROP_USER id_bfdomaincredential id_bedomainuser)
    (PROP_USER id_bjdomaincredential id_bidomainuser)
    (PROP_USER id_bndomaincredential id_bmdomainuser)
    (PROP_USER id_brdomaincredential id_bqdomainuser)
    (PROP_USER id_bvdomaincredential id_budomainuser)
    (PROP_USER id_bzdomaincredential id_bydomainuser)
    (PROP_USER id_cddomaincredential id_ccdomainuser)
    (PROP_USER id_chdomaincredential id_cgdomainuser)
    (PROP_USER id_cldomaincredential id_ckdomainuser)
    (PROP_USER id_ddomaincredential id_cdomainuser)
    (PROP_USER id_hdomaincredential id_gdomainuser)
    (PROP_USER id_ldomaincredential id_kdomainuser)
    (PROP_USER id_pdomaincredential id_odomainuser)
    (PROP_USER id_tdomaincredential id_sdomainuser)
    (PROP_USER id_xdomaincredential id_wdomainuser)
    (PROP_USERNAME id_badomainuser str__michael)
    (PROP_USERNAME id_bedomainuser str__barbara)
    (PROP_USERNAME id_bidomainuser str__william)
    (PROP_USERNAME id_bmdomainuser str__elizabeth)
    (PROP_USERNAME id_bqdomainuser str__david)
    (PROP_USERNAME id_budomainuser str__jennifer)
    (PROP_USERNAME id_bydomainuser str__richard)
    (PROP_USERNAME id_cdomainuser str__james)
    (PROP_USERNAME id_ccdomainuser str__maria)
    (PROP_USERNAME id_cgdomainuser str__charles)
    (PROP_USERNAME id_ckdomainuser str__susan)
    (PROP_USERNAME id_gdomainuser str__mary)
    (PROP_USERNAME id_kdomainuser str__john)
    (PROP_USERNAME id_odomainuser str__patricia)
    (PROP_USERNAME id_sdomainuser str__robert)
    (PROP_USERNAME id_wdomainuser str__linda)
    (PROP_WINDOWS_DOMAIN id_adomain str__alpha)
    (procnone)
    (= (total-cost) 0)
)
(:goal
(and
    (procnone)
    (prop_host id_fkrat id_cohost)
    (prop_host id_forat id_elhost)
    (prop_host id_frrat id_dchost)
    (prop_host id_fqrat id_dqhost)
    (prop_host id_firat id_cvhost)
    (prop_host id_fjrat id_ezhost)
    (prop_host id_fnrat id_eshost)
    (prop_host id_fmrat id_dxhost)
    (prop_host id_fprat id_djhost)
)
)
(:metric minimize (total-cost))
)