(define (problem p10_hosts_trial_15)
(:domain caldera-split)
(:objects
    id_hdrat - observedrat
    id_hfrat - observedrat
    id_hcrat - observedrat
    id_hjrat - observedrat
    id_hhrat - observedrat
    id_herat - observedrat
    id_hirat - observedrat
    id_fwrat - observedrat
    id_hlrat - observedrat
    id_hkrat - observedrat
    id_hgrat - observedrat
    num__147 - num
    num__99 - num
    num__133 - num
    num__140 - num
    num__127 - num
    num__113 - num
    num__148 - num
    num__134 - num
    num__141 - num
    num__92 - num
    num__106 - num
    num__119 - num
    num__126 - num
    num__85 - num
    num__105 - num
    num__112 - num
    num__120 - num
    num__84 - num
    num__91 - num
    num__98 - num
    id_adomain - observeddomain
    id_fphost - observedhost
    id_dehost - observedhost
    id_enhost - observedhost
    id_eghost - observedhost
    id_fbhost - observedhost
    id_dlhost - observedhost
    id_euhost - observedhost
    id_dshost - observedhost
    id_fihost - observedhost
    id_dzhost - observedhost
    id_xdomaincredential - observeddomaincredential
    id_bbdomaincredential - observeddomaincredential
    id_cxdomaincredential - observeddomaincredential
    id_bvdomaincredential - observeddomaincredential
    id_ctdomaincredential - observeddomaincredential
    id_bndomaincredential - observeddomaincredential
    id_tdomaincredential - observeddomaincredential
    id_ldomaincredential - observeddomaincredential
    id_brdomaincredential - observeddomaincredential
    id_pdomaincredential - observeddomaincredential
    id_chdomaincredential - observeddomaincredential
    id_cpdomaincredential - observeddomaincredential
    id_bfdomaincredential - observeddomaincredential
    id_ddomaincredential - observeddomaincredential
    id_bjdomaincredential - observeddomaincredential
    id_cldomaincredential - observeddomaincredential
    id_hdomaincredential - observeddomaincredential
    id_bzdomaincredential - observeddomaincredential
    id_dbdomaincredential - observeddomaincredential
    id_cddomaincredential - observeddomaincredential
    id_gbfile - observedfile
    id_fyfile - observedfile
    id_gdfile - observedfile
    id_gefile - observedfile
    id_gffile - observedfile
    id_gcfile - observedfile
    id_fzfile - observedfile
    id_ggfile - observedfile
    id_ghfile - observedfile
    id_gafile - observedfile
    str__susan - string
    str__er - string
    str__mary - string
    str__dx - string
    str__fg - string
    str__bd - string
    str__q - string
    str__thomas - string
    str__cy - string
    str__bo - string
    str__elizabeth - string
    str__william - string
    str__ef - string
    str__cb - string
    str__bl - string
    str__charles - string
    str__cq - string
    str__z - string
    str__bs - string
    str__n - string
    str__dc - string
    str__v - string
    str__dj - string
    str__ez - string
    str__robert - string
    str__cr - string
    str__linda - string
    str__ey - string
    str__es - string
    str__james - string
    str__fm - string
    str__cj - string
    str__cu - string
    str__dr - string
    str__et - string
    str__dq - string
    str__r - string
    str__bt - string
    str__ff - string
    str__margaret - string
    str__cf - string
    str__bk - string
    str__f - string
    str__dw - string
    str__ci - string
    str__john - string
    str__richard - string
    str__bh - string
    str__di - string
    str__em - string
    str__m - string
    str__bp - string
    str__ft - string
    str__maria - string
    str__cm - string
    str__ca - string
    str__cz - string
    str__david - string
    str__barbara - string
    str__fx - string
    str__joseph - string
    str__i - string
    str__cv - string
    str__bw - string
    str__el - string
    str__ee - string
    str__fo - string
    str__e - string
    str__j - string
    str__bx - string
    str__ed - string
    str__ek - string
    str__dorothy - string
    str__bg - string
    str__ce - string
    str__fh - string
    str__patricia - string
    str__alpha - string
    str__dk - string
    str__y - string
    str__bc - string
    str__cn - string
    str__fv - string
    str__fu - string
    str__jennifer - string
    str__dy - string
    str__fa - string
    str__fn - string
    str__dp - string
    str__u - string
    str__b - string
    str__michael - string
    str__dd - string
    id_gishare - observedshare
    id_glshare - observedshare
    id_gjshare - observedshare
    id_gkshare - observedshare
    id_gqshare - observedshare
    id_gmshare - observedshare
    id_gpshare - observedshare
    id_grshare - observedshare
    id_gnshare - observedshare
    id_goshare - observedshare
    id_guschtask - observedschtask
    id_gwschtask - observedschtask
    id_gvschtask - observedschtask
    id_hbschtask - observedschtask
    id_haschtask - observedschtask
    id_gsschtask - observedschtask
    id_gtschtask - observedschtask
    id_gxschtask - observedschtask
    id_gzschtask - observedschtask
    id_gyschtask - observedschtask
    id_dftimedelta - observedtimedelta
    id_dmtimedelta - observedtimedelta
    id_fjtimedelta - observedtimedelta
    id_evtimedelta - observedtimedelta
    id_fctimedelta - observedtimedelta
    id_eatimedelta - observedtimedelta
    id_ehtimedelta - observedtimedelta
    id_fqtimedelta - observedtimedelta
    id_eotimedelta - observedtimedelta
    id_dttimedelta - observedtimedelta
    id_kdomainuser - observeddomainuser
    id_sdomainuser - observeddomainuser
    id_odomainuser - observeddomainuser
    id_wdomainuser - observeddomainuser
    id_gdomainuser - observeddomainuser
    id_badomainuser - observeddomainuser
    id_bmdomainuser - observeddomainuser
    id_budomainuser - observeddomainuser
    id_ckdomainuser - observeddomainuser
    id_cwdomainuser - observeddomainuser
    id_ccdomainuser - observeddomainuser
    id_bedomainuser - observeddomainuser
    id_cgdomainuser - observeddomainuser
    id_codomainuser - observeddomainuser
    id_bqdomainuser - observeddomainuser
    id_cdomainuser - observeddomainuser
    id_bydomainuser - observeddomainuser
    id_bidomainuser - observeddomainuser
    id_dadomainuser - observeddomainuser
    id_csdomainuser - observeddomainuser
)
(:init
    (knows id_eghost)
    (knows id_fwrat)
    (knows_property id_eghost pfqdn)
    (knows_property id_fwrat pexecutable)
    (knows_property id_fwrat phost)
    (MEM_CACHED_DOMAIN_CREDS id_dehost id_cpdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dehost id_ldomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dlhost id_brdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dlhost id_cldomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dshost id_bbdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dshost id_brdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dzhost id_bfdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dzhost id_cddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_eghost id_bbdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_eghost id_pdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_enhost id_dbdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_enhost id_pdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_euhost id_brdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_euhost id_cxdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_fbhost id_chdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_fbhost id_tdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_fihost id_cxdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_fihost id_ldomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_fphost id_ldomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_fphost id_tdomaincredential)
    (MEM_DOMAIN_USER_ADMINS id_dehost id_gdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dehost id_sdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dlhost id_bedomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dlhost id_odomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dshost id_bqdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dshost id_gdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dzhost id_cwdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dzhost id_odomainuser)
    (MEM_DOMAIN_USER_ADMINS id_eghost id_csdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_eghost id_cwdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_enhost id_badomainuser)
    (MEM_DOMAIN_USER_ADMINS id_enhost id_csdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_euhost id_bydomainuser)
    (MEM_DOMAIN_USER_ADMINS id_euhost id_ckdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_fbhost id_bqdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_fbhost id_gdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_fihost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_fihost id_odomainuser)
    (MEM_DOMAIN_USER_ADMINS id_fphost id_bedomainuser)
    (MEM_DOMAIN_USER_ADMINS id_fphost id_csdomainuser)
    (mem_hosts id_adomain id_dehost)
    (mem_hosts id_adomain id_dlhost)
    (mem_hosts id_adomain id_dshost)
    (mem_hosts id_adomain id_dzhost)
    (mem_hosts id_adomain id_eghost)
    (mem_hosts id_adomain id_enhost)
    (mem_hosts id_adomain id_euhost)
    (mem_hosts id_adomain id_fbhost)
    (mem_hosts id_adomain id_fihost)
    (mem_hosts id_adomain id_fphost)
    (prop_cred id_badomainuser id_bbdomaincredential)
    (prop_cred id_bedomainuser id_bfdomaincredential)
    (prop_cred id_bidomainuser id_bjdomaincredential)
    (prop_cred id_bmdomainuser id_bndomaincredential)
    (prop_cred id_bqdomainuser id_brdomaincredential)
    (prop_cred id_budomainuser id_bvdomaincredential)
    (prop_cred id_bydomainuser id_bzdomaincredential)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_ccdomainuser id_cddomaincredential)
    (prop_cred id_cgdomainuser id_chdomaincredential)
    (prop_cred id_ckdomainuser id_cldomaincredential)
    (prop_cred id_codomainuser id_cpdomaincredential)
    (prop_cred id_csdomainuser id_ctdomaincredential)
    (prop_cred id_cwdomainuser id_cxdomaincredential)
    (prop_cred id_dadomainuser id_dbdomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (prop_cred id_wdomainuser id_xdomaincredential)
    (PROP_DC id_dehost no)
    (PROP_DC id_dlhost no)
    (PROP_DC id_dshost no)
    (PROP_DC id_dzhost no)
    (PROP_DC id_eghost yes)
    (PROP_DC id_enhost no)
    (PROP_DC id_euhost yes)
    (PROP_DC id_fbhost no)
    (PROP_DC id_fihost yes)
    (PROP_DC id_fphost no)
    (PROP_DNS_DOMAIN id_adomain str__b)
    (PROP_DNS_DOMAIN_NAME id_dehost str__dk)
    (PROP_DNS_DOMAIN_NAME id_dlhost str__dr)
    (PROP_DNS_DOMAIN_NAME id_dshost str__dy)
    (PROP_DNS_DOMAIN_NAME id_dzhost str__ef)
    (PROP_DNS_DOMAIN_NAME id_eghost str__em)
    (PROP_DNS_DOMAIN_NAME id_enhost str__et)
    (PROP_DNS_DOMAIN_NAME id_euhost str__fa)
    (PROP_DNS_DOMAIN_NAME id_fbhost str__fh)
    (PROP_DNS_DOMAIN_NAME id_fihost str__fo)
    (PROP_DNS_DOMAIN_NAME id_fphost str__fv)
    (PROP_DOMAIN id_badomainuser id_adomain)
    (PROP_DOMAIN id_bbdomaincredential id_adomain)
    (PROP_DOMAIN id_bedomainuser id_adomain)
    (PROP_DOMAIN id_bfdomaincredential id_adomain)
    (PROP_DOMAIN id_bidomainuser id_adomain)
    (PROP_DOMAIN id_bjdomaincredential id_adomain)
    (PROP_DOMAIN id_bmdomainuser id_adomain)
    (PROP_DOMAIN id_bndomaincredential id_adomain)
    (PROP_DOMAIN id_bqdomainuser id_adomain)
    (PROP_DOMAIN id_brdomaincredential id_adomain)
    (PROP_DOMAIN id_budomainuser id_adomain)
    (PROP_DOMAIN id_bvdomaincredential id_adomain)
    (PROP_DOMAIN id_bydomainuser id_adomain)
    (PROP_DOMAIN id_bzdomaincredential id_adomain)
    (PROP_DOMAIN id_cdomainuser id_adomain)
    (PROP_DOMAIN id_ccdomainuser id_adomain)
    (PROP_DOMAIN id_cddomaincredential id_adomain)
    (PROP_DOMAIN id_cgdomainuser id_adomain)
    (PROP_DOMAIN id_chdomaincredential id_adomain)
    (PROP_DOMAIN id_ckdomainuser id_adomain)
    (PROP_DOMAIN id_cldomaincredential id_adomain)
    (PROP_DOMAIN id_codomainuser id_adomain)
    (PROP_DOMAIN id_cpdomaincredential id_adomain)
    (PROP_DOMAIN id_csdomainuser id_adomain)
    (PROP_DOMAIN id_ctdomaincredential id_adomain)
    (PROP_DOMAIN id_cwdomainuser id_adomain)
    (PROP_DOMAIN id_cxdomaincredential id_adomain)
    (PROP_DOMAIN id_ddomaincredential id_adomain)
    (PROP_DOMAIN id_dadomainuser id_adomain)
    (PROP_DOMAIN id_dbdomaincredential id_adomain)
    (PROP_DOMAIN id_dehost id_adomain)
    (PROP_DOMAIN id_dlhost id_adomain)
    (PROP_DOMAIN id_dshost id_adomain)
    (PROP_DOMAIN id_dzhost id_adomain)
    (PROP_DOMAIN id_eghost id_adomain)
    (PROP_DOMAIN id_enhost id_adomain)
    (PROP_DOMAIN id_euhost id_adomain)
    (PROP_DOMAIN id_fbhost id_adomain)
    (PROP_DOMAIN id_fihost id_adomain)
    (PROP_DOMAIN id_fphost id_adomain)
    (PROP_DOMAIN id_gdomainuser id_adomain)
    (PROP_DOMAIN id_hdomaincredential id_adomain)
    (PROP_DOMAIN id_kdomainuser id_adomain)
    (PROP_DOMAIN id_ldomaincredential id_adomain)
    (PROP_DOMAIN id_odomainuser id_adomain)
    (PROP_DOMAIN id_pdomaincredential id_adomain)
    (PROP_DOMAIN id_sdomainuser id_adomain)
    (PROP_DOMAIN id_tdomaincredential id_adomain)
    (PROP_DOMAIN id_wdomainuser id_adomain)
    (PROP_DOMAIN id_xdomaincredential id_adomain)
    (prop_elevated id_fwrat yes)
    (prop_executable id_fwrat str__fx)
    (PROP_FQDN id_dehost str__di)
    (PROP_FQDN id_dlhost str__dp)
    (PROP_FQDN id_dshost str__dw)
    (PROP_FQDN id_dzhost str__ed)
    (PROP_FQDN id_eghost str__ek)
    (PROP_FQDN id_enhost str__er)
    (PROP_FQDN id_euhost str__ey)
    (PROP_FQDN id_fbhost str__ff)
    (PROP_FQDN id_fihost str__fm)
    (PROP_FQDN id_fphost str__ft)
    (prop_host id_dftimedelta id_dehost)
    (prop_host id_dmtimedelta id_dlhost)
    (prop_host id_dttimedelta id_dshost)
    (prop_host id_eatimedelta id_dzhost)
    (prop_host id_ehtimedelta id_eghost)
    (prop_host id_eotimedelta id_enhost)
    (prop_host id_evtimedelta id_euhost)
    (prop_host id_fctimedelta id_fbhost)
    (prop_host id_fjtimedelta id_fihost)
    (prop_host id_fqtimedelta id_fphost)
    (prop_host id_fwrat id_eghost)
    (PROP_HOSTNAME id_dehost str__dj)
    (PROP_HOSTNAME id_dlhost str__dq)
    (PROP_HOSTNAME id_dshost str__dx)
    (PROP_HOSTNAME id_dzhost str__ee)
    (PROP_HOSTNAME id_eghost str__el)
    (PROP_HOSTNAME id_enhost str__es)
    (PROP_HOSTNAME id_euhost str__ez)
    (PROP_HOSTNAME id_fbhost str__fg)
    (PROP_HOSTNAME id_fihost str__fn)
    (PROP_HOSTNAME id_fphost str__fu)
    (PROP_IS_GROUP id_badomainuser no)
    (PROP_IS_GROUP id_bedomainuser no)
    (PROP_IS_GROUP id_bidomainuser no)
    (PROP_IS_GROUP id_bmdomainuser no)
    (PROP_IS_GROUP id_bqdomainuser no)
    (PROP_IS_GROUP id_budomainuser no)
    (PROP_IS_GROUP id_bydomainuser no)
    (PROP_IS_GROUP id_cdomainuser no)
    (PROP_IS_GROUP id_ccdomainuser no)
    (PROP_IS_GROUP id_cgdomainuser no)
    (PROP_IS_GROUP id_ckdomainuser no)
    (PROP_IS_GROUP id_codomainuser no)
    (PROP_IS_GROUP id_csdomainuser no)
    (PROP_IS_GROUP id_cwdomainuser no)
    (PROP_IS_GROUP id_dadomainuser no)
    (PROP_IS_GROUP id_gdomainuser no)
    (PROP_IS_GROUP id_kdomainuser no)
    (PROP_IS_GROUP id_odomainuser no)
    (PROP_IS_GROUP id_sdomainuser no)
    (PROP_IS_GROUP id_wdomainuser no)
    (PROP_MICROSECONDS id_dftimedelta num__84)
    (PROP_MICROSECONDS id_dmtimedelta num__91)
    (PROP_MICROSECONDS id_dttimedelta num__98)
    (PROP_MICROSECONDS id_eatimedelta num__105)
    (PROP_MICROSECONDS id_ehtimedelta num__112)
    (PROP_MICROSECONDS id_eotimedelta num__119)
    (PROP_MICROSECONDS id_evtimedelta num__126)
    (PROP_MICROSECONDS id_fctimedelta num__133)
    (PROP_MICROSECONDS id_fjtimedelta num__140)
    (PROP_MICROSECONDS id_fqtimedelta num__147)
    (PROP_PASSWORD id_bbdomaincredential str__bc)
    (PROP_PASSWORD id_bfdomaincredential str__bg)
    (PROP_PASSWORD id_bjdomaincredential str__bk)
    (PROP_PASSWORD id_bndomaincredential str__bo)
    (PROP_PASSWORD id_brdomaincredential str__bs)
    (PROP_PASSWORD id_bvdomaincredential str__bw)
    (PROP_PASSWORD id_bzdomaincredential str__ca)
    (PROP_PASSWORD id_cddomaincredential str__ce)
    (PROP_PASSWORD id_chdomaincredential str__ci)
    (PROP_PASSWORD id_cldomaincredential str__cm)
    (PROP_PASSWORD id_cpdomaincredential str__cq)
    (PROP_PASSWORD id_ctdomaincredential str__cu)
    (PROP_PASSWORD id_cxdomaincredential str__cy)
    (PROP_PASSWORD id_ddomaincredential str__e)
    (PROP_PASSWORD id_dbdomaincredential str__dc)
    (PROP_PASSWORD id_hdomaincredential str__i)
    (PROP_PASSWORD id_ldomaincredential str__m)
    (PROP_PASSWORD id_pdomaincredential str__q)
    (PROP_PASSWORD id_tdomaincredential str__u)
    (PROP_PASSWORD id_xdomaincredential str__y)
    (PROP_SECONDS id_dftimedelta num__85)
    (PROP_SECONDS id_dmtimedelta num__92)
    (PROP_SECONDS id_dttimedelta num__99)
    (PROP_SECONDS id_eatimedelta num__106)
    (PROP_SECONDS id_ehtimedelta num__113)
    (PROP_SECONDS id_eotimedelta num__120)
    (PROP_SECONDS id_evtimedelta num__127)
    (PROP_SECONDS id_fctimedelta num__134)
    (PROP_SECONDS id_fjtimedelta num__141)
    (PROP_SECONDS id_fqtimedelta num__148)
    (PROP_SID id_badomainuser str__bd)
    (PROP_SID id_bedomainuser str__bh)
    (PROP_SID id_bidomainuser str__bl)
    (PROP_SID id_bmdomainuser str__bp)
    (PROP_SID id_bqdomainuser str__bt)
    (PROP_SID id_budomainuser str__bx)
    (PROP_SID id_bydomainuser str__cb)
    (PROP_SID id_cdomainuser str__f)
    (PROP_SID id_ccdomainuser str__cf)
    (PROP_SID id_cgdomainuser str__cj)
    (PROP_SID id_ckdomainuser str__cn)
    (PROP_SID id_codomainuser str__cr)
    (PROP_SID id_csdomainuser str__cv)
    (PROP_SID id_cwdomainuser str__cz)
    (PROP_SID id_dadomainuser str__dd)
    (PROP_SID id_gdomainuser str__j)
    (PROP_SID id_kdomainuser str__n)
    (PROP_SID id_odomainuser str__r)
    (PROP_SID id_sdomainuser str__v)
    (PROP_SID id_wdomainuser str__z)
    (PROP_TIMEDELTA id_dehost id_dftimedelta)
    (PROP_TIMEDELTA id_dlhost id_dmtimedelta)
    (PROP_TIMEDELTA id_dshost id_dttimedelta)
    (PROP_TIMEDELTA id_dzhost id_eatimedelta)
    (PROP_TIMEDELTA id_eghost id_ehtimedelta)
    (PROP_TIMEDELTA id_enhost id_eotimedelta)
    (PROP_TIMEDELTA id_euhost id_evtimedelta)
    (PROP_TIMEDELTA id_fbhost id_fctimedelta)
    (PROP_TIMEDELTA id_fihost id_fjtimedelta)
    (PROP_TIMEDELTA id_fphost id_fqtimedelta)
    (PROP_USER id_bbdomaincredential id_badomainuser)
    (PROP_USER id_bfdomaincredential id_bedomainuser)
    (PROP_USER id_bjdomaincredential id_bidomainuser)
    (PROP_USER id_bndomaincredential id_bmdomainuser)
    (PROP_USER id_brdomaincredential id_bqdomainuser)
    (PROP_USER id_bvdomaincredential id_budomainuser)
    (PROP_USER id_bzdomaincredential id_bydomainuser)
    (PROP_USER id_cddomaincredential id_ccdomainuser)
    (PROP_USER id_chdomaincredential id_cgdomainuser)
    (PROP_USER id_cldomaincredential id_ckdomainuser)
    (PROP_USER id_cpdomaincredential id_codomainuser)
    (PROP_USER id_ctdomaincredential id_csdomainuser)
    (PROP_USER id_cxdomaincredential id_cwdomainuser)
    (PROP_USER id_ddomaincredential id_cdomainuser)
    (PROP_USER id_dbdomaincredential id_dadomainuser)
    (PROP_USER id_hdomaincredential id_gdomainuser)
    (PROP_USER id_ldomaincredential id_kdomainuser)
    (PROP_USER id_pdomaincredential id_odomainuser)
    (PROP_USER id_tdomaincredential id_sdomainuser)
    (PROP_USER id_xdomaincredential id_wdomainuser)
    (PROP_USERNAME id_badomainuser str__michael)
    (PROP_USERNAME id_bedomainuser str__barbara)
    (PROP_USERNAME id_bidomainuser str__william)
    (PROP_USERNAME id_bmdomainuser str__elizabeth)
    (PROP_USERNAME id_bqdomainuser str__david)
    (PROP_USERNAME id_budomainuser str__jennifer)
    (PROP_USERNAME id_bydomainuser str__richard)
    (PROP_USERNAME id_cdomainuser str__james)
    (PROP_USERNAME id_ccdomainuser str__maria)
    (PROP_USERNAME id_cgdomainuser str__charles)
    (PROP_USERNAME id_ckdomainuser str__susan)
    (PROP_USERNAME id_codomainuser str__joseph)
    (PROP_USERNAME id_csdomainuser str__margaret)
    (PROP_USERNAME id_cwdomainuser str__thomas)
    (PROP_USERNAME id_dadomainuser str__dorothy)
    (PROP_USERNAME id_gdomainuser str__mary)
    (PROP_USERNAME id_kdomainuser str__john)
    (PROP_USERNAME id_odomainuser str__patricia)
    (PROP_USERNAME id_sdomainuser str__robert)
    (PROP_USERNAME id_wdomainuser str__linda)
    (PROP_WINDOWS_DOMAIN id_adomain str__alpha)
    (procnone)
    (= (total-cost) 0)
)
(:goal
(and
    (procnone)
    (prop_host id_hlrat id_fihost)
    (prop_host id_hirat id_dshost)
    (prop_host id_herat id_euhost)
    (prop_host id_hhrat id_dlhost)
    (prop_host id_hjrat id_fbhost)
    (prop_host id_hcrat id_enhost)
    (prop_host id_hfrat id_dehost)
    (prop_host id_hdrat id_fphost)
    (prop_host id_hgrat id_dzhost)
)
)
(:metric minimize (total-cost))
)