(define (problem p12_hosts_trial_14)
(:domain caldera-split)
(:objects
    id_cwdomainuser - observeddomainuser
    id_dmdomainuser - observeddomainuser
    id_sdomainuser - observeddomainuser
    id_budomainuser - observeddomainuser
    id_ckdomainuser - observeddomainuser
    id_codomainuser - observeddomainuser
    id_cdomainuser - observeddomainuser
    id_bmdomainuser - observeddomainuser
    id_odomainuser - observeddomainuser
    id_bydomainuser - observeddomainuser
    id_bidomainuser - observeddomainuser
    id_kdomainuser - observeddomainuser
    id_dqdomainuser - observeddomainuser
    id_bedomainuser - observeddomainuser
    id_gdomainuser - observeddomainuser
    id_dadomainuser - observeddomainuser
    id_wdomainuser - observeddomainuser
    id_csdomainuser - observeddomainuser
    id_cgdomainuser - observeddomainuser
    id_bqdomainuser - observeddomainuser
    id_ccdomainuser - observeddomainuser
    id_badomainuser - observeddomainuser
    id_dedomainuser - observeddomainuser
    id_didomainuser - observeddomainuser
    num__115 - num
    num__101 - num
    num__114 - num
    num__121 - num
    num__136 - num
    num__128 - num
    num__129 - num
    num__156 - num
    num__107 - num
    num__163 - num
    num__108 - num
    num__157 - num
    num__122 - num
    num__150 - num
    num__164 - num
    num__135 - num
    num__171 - num
    num__142 - num
    num__143 - num
    num__170 - num
    num__100 - num
    num__178 - num
    num__149 - num
    num__177 - num
    id_frhost - observedhost
    id_fyhost - observedhost
    id_gfhost - observedhost
    id_ephost - observedhost
    id_fdhost - observedhost
    id_gmhost - observedhost
    id_duhost - observedhost
    id_ebhost - observedhost
    id_gthost - observedhost
    id_eihost - observedhost
    id_ewhost - observedhost
    id_fkhost - observedhost
    id_gntimedelta - observedtimedelta
    id_eqtimedelta - observedtimedelta
    id_ggtimedelta - observedtimedelta
    id_ectimedelta - observedtimedelta
    id_ejtimedelta - observedtimedelta
    id_fstimedelta - observedtimedelta
    id_gutimedelta - observedtimedelta
    id_dvtimedelta - observedtimedelta
    id_fztimedelta - observedtimedelta
    id_fltimedelta - observedtimedelta
    id_extimedelta - observedtimedelta
    id_fetimedelta - observedtimedelta
    id_ihshare - observedshare
    id_idshare - observedshare
    id_iishare - observedshare
    id_ieshare - observedshare
    id_ilshare - observedshare
    id_iashare - observedshare
    id_igshare - observedshare
    id_ijshare - observedshare
    id_ifshare - observedshare
    id_ikshare - observedshare
    id_ibshare - observedshare
    id_icshare - observedshare
    id_hhfile - observedfile
    id_hmfile - observedfile
    id_hkfile - observedfile
    id_hlfile - observedfile
    id_hefile - observedfile
    id_hnfile - observedfile
    id_hcfile - observedfile
    id_hdfile - observedfile
    id_hifile - observedfile
    id_hgfile - observedfile
    id_hffile - observedfile
    id_hjfile - observedfile
    str__james - string
    str__robert - string
    str__gd - string
    str__n - string
    str__lisa - string
    str__v - string
    str__cq - string
    str__em - string
    str__ea - string
    str__john - string
    str__gy - string
    str__charles - string
    str__bc - string
    str__r - string
    str__eu - string
    str__gc - string
    str__bo - string
    str__michael - string
    str__cu - string
    str__eo - string
    str__bt - string
    str__linda - string
    str__ev - string
    str__dh - string
    str__fj - string
    str__bk - string
    str__ds - string
    str__dp - string
    str__cz - string
    str__fb - string
    str__bl - string
    str__u - string
    str__gz - string
    str__cj - string
    str__cn - string
    str__david - string
    str__gs - string
    str__j - string
    str__bp - string
    str__dy - string
    str__fx - string
    str__barbara - string
    str__maria - string
    str__dorothy - string
    str__ca - string
    str__richard - string
    str__bh - string
    str__gl - string
    str__dz - string
    str__hb - string
    str__cr - string
    str__cy - string
    str__gk - string
    str__daniel - string
    str__margaret - string
    str__z - string
    str__ef - string
    str__gx - string
    str__e - string
    str__patricia - string
    str__gr - string
    str__dl - string
    str__fq - string
    str__bx - string
    str__thomas - string
    str__ci - string
    str__elizabeth - string
    str__mary - string
    str__fp - string
    str__joseph - string
    str__fo - string
    str__cm - string
    str__eg - string
    str__alpha - string
    str__fa - string
    str__b - string
    str__q - string
    str__nancy - string
    str__eh - string
    str__et - string
    str__fh - string
    str__y - string
    str__dt - string
    str__susan - string
    str__do - string
    str__fw - string
    str__f - string
    str__gj - string
    str__m - string
    str__gq - string
    str__fc - string
    str__en - string
    str__bd - string
    str__cf - string
    str__fv - string
    str__dc - string
    str__ce - string
    str__cv - string
    str__bs - string
    str__william - string
    str__jennifer - string
    str__bw - string
    str__bg - string
    str__fi - string
    str__ge - string
    str__cb - string
    str__dd - string
    str__dg - string
    str__christopher - string
    str__dk - string
    str__i - string
    id_adomain - observeddomain
    id_hsschtask - observedschtask
    id_hwschtask - observedschtask
    id_htschtask - observedschtask
    id_hqschtask - observedschtask
    id_hvschtask - observedschtask
    id_huschtask - observedschtask
    id_hrschtask - observedschtask
    id_hzschtask - observedschtask
    id_hoschtask - observedschtask
    id_hxschtask - observedschtask
    id_hpschtask - observedschtask
    id_hyschtask - observedschtask
    id_brdomaincredential - observeddomaincredential
    id_drdomaincredential - observeddomaincredential
    id_ctdomaincredential - observeddomaincredential
    id_djdomaincredential - observeddomaincredential
    id_bjdomaincredential - observeddomaincredential
    id_hdomaincredential - observeddomaincredential
    id_bndomaincredential - observeddomaincredential
    id_cxdomaincredential - observeddomaincredential
    id_xdomaincredential - observeddomaincredential
    id_cddomaincredential - observeddomaincredential
    id_dndomaincredential - observeddomaincredential
    id_dfdomaincredential - observeddomaincredential
    id_bzdomaincredential - observeddomaincredential
    id_dbdomaincredential - observeddomaincredential
    id_chdomaincredential - observeddomaincredential
    id_cldomaincredential - observeddomaincredential
    id_bfdomaincredential - observeddomaincredential
    id_ldomaincredential - observeddomaincredential
    id_cpdomaincredential - observeddomaincredential
    id_pdomaincredential - observeddomaincredential
    id_ddomaincredential - observeddomaincredential
    id_bvdomaincredential - observeddomaincredential
    id_tdomaincredential - observeddomaincredential
    id_bbdomaincredential - observeddomaincredential
    id_imrat - observedrat
    id_irrat - observedrat
    id_ivrat - observedrat
    id_itrat - observedrat
    id_iurat - observedrat
    id_iprat - observedrat
    id_ixrat - observedrat
    id_inrat - observedrat
    id_iorat - observedrat
    id_israt - observedrat
    id_iwrat - observedrat
    id_harat - observedrat
    id_iqrat - observedrat
)
(:init
    (knows id_fkhost)
    (knows id_harat)
    (knows_property id_fkhost pfqdn)
    (knows_property id_harat pexecutable)
    (knows_property id_harat phost)
    (MEM_CACHED_DOMAIN_CREDS id_duhost id_brdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_duhost id_tdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_ebhost id_bbdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_ebhost id_bndomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_eihost id_cxdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_eihost id_hdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_ephost id_cpdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_ephost id_ldomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_ewhost id_bjdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_ewhost id_tdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_fdhost id_ctdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_fdhost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_fkhost id_bvdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_fkhost id_bzdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_frhost id_bvdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_frhost id_cddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_fyhost id_ctdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_fyhost id_ldomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_gfhost id_cpdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_gfhost id_dbdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_gmhost id_dbdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_gmhost id_xdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_gthost id_dbdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_gthost id_djdomaincredential)
    (MEM_DOMAIN_USER_ADMINS id_duhost id_cwdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_duhost id_didomainuser)
    (MEM_DOMAIN_USER_ADMINS id_ebhost id_bedomainuser)
    (MEM_DOMAIN_USER_ADMINS id_ebhost id_budomainuser)
    (MEM_DOMAIN_USER_ADMINS id_eihost id_dadomainuser)
    (MEM_DOMAIN_USER_ADMINS id_eihost id_didomainuser)
    (MEM_DOMAIN_USER_ADMINS id_ephost id_csdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_ephost id_odomainuser)
    (MEM_DOMAIN_USER_ADMINS id_ewhost id_bqdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_ewhost id_csdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_fdhost id_ckdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_fdhost id_gdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_fkhost id_bmdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_fkhost id_sdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_frhost id_bedomainuser)
    (MEM_DOMAIN_USER_ADMINS id_frhost id_dadomainuser)
    (MEM_DOMAIN_USER_ADMINS id_fyhost id_bidomainuser)
    (MEM_DOMAIN_USER_ADMINS id_fyhost id_cwdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_gfhost id_codomainuser)
    (MEM_DOMAIN_USER_ADMINS id_gfhost id_csdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_gmhost id_badomainuser)
    (MEM_DOMAIN_USER_ADMINS id_gmhost id_sdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_gthost id_csdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_gthost id_kdomainuser)
    (mem_hosts id_adomain id_duhost)
    (mem_hosts id_adomain id_ebhost)
    (mem_hosts id_adomain id_eihost)
    (mem_hosts id_adomain id_ephost)
    (mem_hosts id_adomain id_ewhost)
    (mem_hosts id_adomain id_fdhost)
    (mem_hosts id_adomain id_fkhost)
    (mem_hosts id_adomain id_frhost)
    (mem_hosts id_adomain id_fyhost)
    (mem_hosts id_adomain id_gfhost)
    (mem_hosts id_adomain id_gmhost)
    (mem_hosts id_adomain id_gthost)
    (prop_cred id_badomainuser id_bbdomaincredential)
    (prop_cred id_bedomainuser id_bfdomaincredential)
    (prop_cred id_bidomainuser id_bjdomaincredential)
    (prop_cred id_bmdomainuser id_bndomaincredential)
    (prop_cred id_bqdomainuser id_brdomaincredential)
    (prop_cred id_budomainuser id_bvdomaincredential)
    (prop_cred id_bydomainuser id_bzdomaincredential)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_ccdomainuser id_cddomaincredential)
    (prop_cred id_cgdomainuser id_chdomaincredential)
    (prop_cred id_ckdomainuser id_cldomaincredential)
    (prop_cred id_codomainuser id_cpdomaincredential)
    (prop_cred id_csdomainuser id_ctdomaincredential)
    (prop_cred id_cwdomainuser id_cxdomaincredential)
    (prop_cred id_dadomainuser id_dbdomaincredential)
    (prop_cred id_dedomainuser id_dfdomaincredential)
    (prop_cred id_didomainuser id_djdomaincredential)
    (prop_cred id_dmdomainuser id_dndomaincredential)
    (prop_cred id_dqdomainuser id_drdomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (prop_cred id_wdomainuser id_xdomaincredential)
    (PROP_DC id_duhost no)
    (PROP_DC id_ebhost no)
    (PROP_DC id_eihost no)
    (PROP_DC id_ephost no)
    (PROP_DC id_ewhost no)
    (PROP_DC id_fdhost no)
    (PROP_DC id_fkhost no)
    (PROP_DC id_frhost no)
    (PROP_DC id_fyhost no)
    (PROP_DC id_gfhost no)
    (PROP_DC id_gmhost no)
    (PROP_DC id_gthost no)
    (PROP_DNS_DOMAIN id_adomain str__b)
    (PROP_DNS_DOMAIN_NAME id_duhost str__dz)
    (PROP_DNS_DOMAIN_NAME id_ebhost str__eg)
    (PROP_DNS_DOMAIN_NAME id_eihost str__en)
    (PROP_DNS_DOMAIN_NAME id_ephost str__eu)
    (PROP_DNS_DOMAIN_NAME id_ewhost str__fb)
    (PROP_DNS_DOMAIN_NAME id_fdhost str__fi)
    (PROP_DNS_DOMAIN_NAME id_fkhost str__fp)
    (PROP_DNS_DOMAIN_NAME id_frhost str__fw)
    (PROP_DNS_DOMAIN_NAME id_fyhost str__gd)
    (PROP_DNS_DOMAIN_NAME id_gfhost str__gk)
    (PROP_DNS_DOMAIN_NAME id_gmhost str__gr)
    (PROP_DNS_DOMAIN_NAME id_gthost str__gy)
    (PROP_DOMAIN id_badomainuser id_adomain)
    (PROP_DOMAIN id_bbdomaincredential id_adomain)
    (PROP_DOMAIN id_bedomainuser id_adomain)
    (PROP_DOMAIN id_bfdomaincredential id_adomain)
    (PROP_DOMAIN id_bidomainuser id_adomain)
    (PROP_DOMAIN id_bjdomaincredential id_adomain)
    (PROP_DOMAIN id_bmdomainuser id_adomain)
    (PROP_DOMAIN id_bndomaincredential id_adomain)
    (PROP_DOMAIN id_bqdomainuser id_adomain)
    (PROP_DOMAIN id_brdomaincredential id_adomain)
    (PROP_DOMAIN id_budomainuser id_adomain)
    (PROP_DOMAIN id_bvdomaincredential id_adomain)
    (PROP_DOMAIN id_bydomainuser id_adomain)
    (PROP_DOMAIN id_bzdomaincredential id_adomain)
    (PROP_DOMAIN id_cdomainuser id_adomain)
    (PROP_DOMAIN id_ccdomainuser id_adomain)
    (PROP_DOMAIN id_cddomaincredential id_adomain)
    (PROP_DOMAIN id_cgdomainuser id_adomain)
    (PROP_DOMAIN id_chdomaincredential id_adomain)
    (PROP_DOMAIN id_ckdomainuser id_adomain)
    (PROP_DOMAIN id_cldomaincredential id_adomain)
    (PROP_DOMAIN id_codomainuser id_adomain)
    (PROP_DOMAIN id_cpdomaincredential id_adomain)
    (PROP_DOMAIN id_csdomainuser id_adomain)
    (PROP_DOMAIN id_ctdomaincredential id_adomain)
    (PROP_DOMAIN id_cwdomainuser id_adomain)
    (PROP_DOMAIN id_cxdomaincredential id_adomain)
    (PROP_DOMAIN id_ddomaincredential id_adomain)
    (PROP_DOMAIN id_dadomainuser id_adomain)
    (PROP_DOMAIN id_dbdomaincredential id_adomain)
    (PROP_DOMAIN id_dedomainuser id_adomain)
    (PROP_DOMAIN id_dfdomaincredential id_adomain)
    (PROP_DOMAIN id_didomainuser id_adomain)
    (PROP_DOMAIN id_djdomaincredential id_adomain)
    (PROP_DOMAIN id_dmdomainuser id_adomain)
    (PROP_DOMAIN id_dndomaincredential id_adomain)
    (PROP_DOMAIN id_dqdomainuser id_adomain)
    (PROP_DOMAIN id_drdomaincredential id_adomain)
    (PROP_DOMAIN id_duhost id_adomain)
    (PROP_DOMAIN id_ebhost id_adomain)
    (PROP_DOMAIN id_eihost id_adomain)
    (PROP_DOMAIN id_ephost id_adomain)
    (PROP_DOMAIN id_ewhost id_adomain)
    (PROP_DOMAIN id_fdhost id_adomain)
    (PROP_DOMAIN id_fkhost id_adomain)
    (PROP_DOMAIN id_frhost id_adomain)
    (PROP_DOMAIN id_fyhost id_adomain)
    (PROP_DOMAIN id_gdomainuser id_adomain)
    (PROP_DOMAIN id_gfhost id_adomain)
    (PROP_DOMAIN id_gmhost id_adomain)
    (PROP_DOMAIN id_gthost id_adomain)
    (PROP_DOMAIN id_hdomaincredential id_adomain)
    (PROP_DOMAIN id_kdomainuser id_adomain)
    (PROP_DOMAIN id_ldomaincredential id_adomain)
    (PROP_DOMAIN id_odomainuser id_adomain)
    (PROP_DOMAIN id_pdomaincredential id_adomain)
    (PROP_DOMAIN id_sdomainuser id_adomain)
    (PROP_DOMAIN id_tdomaincredential id_adomain)
    (PROP_DOMAIN id_wdomainuser id_adomain)
    (PROP_DOMAIN id_xdomaincredential id_adomain)
    (prop_elevated id_harat yes)
    (prop_executable id_harat str__hb)
    (PROP_FQDN id_duhost str__ea)
    (PROP_FQDN id_ebhost str__eh)
    (PROP_FQDN id_eihost str__eo)
    (PROP_FQDN id_ephost str__ev)
    (PROP_FQDN id_ewhost str__fc)
    (PROP_FQDN id_fdhost str__fj)
    (PROP_FQDN id_fkhost str__fq)
    (PROP_FQDN id_frhost str__fx)
    (PROP_FQDN id_fyhost str__ge)
    (PROP_FQDN id_gfhost str__gl)
    (PROP_FQDN id_gmhost str__gs)
    (PROP_FQDN id_gthost str__gz)
    (prop_host id_dvtimedelta id_duhost)
    (prop_host id_ectimedelta id_ebhost)
    (prop_host id_ejtimedelta id_eihost)
    (prop_host id_eqtimedelta id_ephost)
    (prop_host id_extimedelta id_ewhost)
    (prop_host id_fetimedelta id_fdhost)
    (prop_host id_fltimedelta id_fkhost)
    (prop_host id_fstimedelta id_frhost)
    (prop_host id_fztimedelta id_fyhost)
    (prop_host id_ggtimedelta id_gfhost)
    (prop_host id_gntimedelta id_gmhost)
    (prop_host id_gutimedelta id_gthost)
    (prop_host id_harat id_fkhost)
    (PROP_HOSTNAME id_duhost str__dy)
    (PROP_HOSTNAME id_ebhost str__ef)
    (PROP_HOSTNAME id_eihost str__em)
    (PROP_HOSTNAME id_ephost str__et)
    (PROP_HOSTNAME id_ewhost str__fa)
    (PROP_HOSTNAME id_fdhost str__fh)
    (PROP_HOSTNAME id_fkhost str__fo)
    (PROP_HOSTNAME id_frhost str__fv)
    (PROP_HOSTNAME id_fyhost str__gc)
    (PROP_HOSTNAME id_gfhost str__gj)
    (PROP_HOSTNAME id_gmhost str__gq)
    (PROP_HOSTNAME id_gthost str__gx)
    (PROP_IS_GROUP id_badomainuser no)
    (PROP_IS_GROUP id_bedomainuser no)
    (PROP_IS_GROUP id_bidomainuser no)
    (PROP_IS_GROUP id_bmdomainuser no)
    (PROP_IS_GROUP id_bqdomainuser no)
    (PROP_IS_GROUP id_budomainuser no)
    (PROP_IS_GROUP id_bydomainuser no)
    (PROP_IS_GROUP id_cdomainuser no)
    (PROP_IS_GROUP id_ccdomainuser no)
    (PROP_IS_GROUP id_cgdomainuser no)
    (PROP_IS_GROUP id_ckdomainuser no)
    (PROP_IS_GROUP id_codomainuser no)
    (PROP_IS_GROUP id_csdomainuser no)
    (PROP_IS_GROUP id_cwdomainuser no)
    (PROP_IS_GROUP id_dadomainuser no)
    (PROP_IS_GROUP id_dedomainuser no)
    (PROP_IS_GROUP id_didomainuser no)
    (PROP_IS_GROUP id_dmdomainuser no)
    (PROP_IS_GROUP id_dqdomainuser no)
    (PROP_IS_GROUP id_gdomainuser no)
    (PROP_IS_GROUP id_kdomainuser no)
    (PROP_IS_GROUP id_odomainuser no)
    (PROP_IS_GROUP id_sdomainuser no)
    (PROP_IS_GROUP id_wdomainuser no)
    (PROP_MICROSECONDS id_dvtimedelta num__100)
    (PROP_MICROSECONDS id_ectimedelta num__107)
    (PROP_MICROSECONDS id_ejtimedelta num__114)
    (PROP_MICROSECONDS id_eqtimedelta num__121)
    (PROP_MICROSECONDS id_extimedelta num__128)
    (PROP_MICROSECONDS id_fetimedelta num__135)
    (PROP_MICROSECONDS id_fltimedelta num__142)
    (PROP_MICROSECONDS id_fstimedelta num__149)
    (PROP_MICROSECONDS id_fztimedelta num__156)
    (PROP_MICROSECONDS id_ggtimedelta num__163)
    (PROP_MICROSECONDS id_gntimedelta num__170)
    (PROP_MICROSECONDS id_gutimedelta num__177)
    (PROP_PASSWORD id_bbdomaincredential str__bc)
    (PROP_PASSWORD id_bfdomaincredential str__bg)
    (PROP_PASSWORD id_bjdomaincredential str__bk)
    (PROP_PASSWORD id_bndomaincredential str__bo)
    (PROP_PASSWORD id_brdomaincredential str__bs)
    (PROP_PASSWORD id_bvdomaincredential str__bw)
    (PROP_PASSWORD id_bzdomaincredential str__ca)
    (PROP_PASSWORD id_cddomaincredential str__ce)
    (PROP_PASSWORD id_chdomaincredential str__ci)
    (PROP_PASSWORD id_cldomaincredential str__cm)
    (PROP_PASSWORD id_cpdomaincredential str__cq)
    (PROP_PASSWORD id_ctdomaincredential str__cu)
    (PROP_PASSWORD id_cxdomaincredential str__cy)
    (PROP_PASSWORD id_ddomaincredential str__e)
    (PROP_PASSWORD id_dbdomaincredential str__dc)
    (PROP_PASSWORD id_dfdomaincredential str__dg)
    (PROP_PASSWORD id_djdomaincredential str__dk)
    (PROP_PASSWORD id_dndomaincredential str__do)
    (PROP_PASSWORD id_drdomaincredential str__ds)
    (PROP_PASSWORD id_hdomaincredential str__i)
    (PROP_PASSWORD id_ldomaincredential str__m)
    (PROP_PASSWORD id_pdomaincredential str__q)
    (PROP_PASSWORD id_tdomaincredential str__u)
    (PROP_PASSWORD id_xdomaincredential str__y)
    (PROP_SECONDS id_dvtimedelta num__101)
    (PROP_SECONDS id_ectimedelta num__108)
    (PROP_SECONDS id_ejtimedelta num__115)
    (PROP_SECONDS id_eqtimedelta num__122)
    (PROP_SECONDS id_extimedelta num__129)
    (PROP_SECONDS id_fetimedelta num__136)
    (PROP_SECONDS id_fltimedelta num__143)
    (PROP_SECONDS id_fstimedelta num__150)
    (PROP_SECONDS id_fztimedelta num__157)
    (PROP_SECONDS id_ggtimedelta num__164)
    (PROP_SECONDS id_gntimedelta num__171)
    (PROP_SECONDS id_gutimedelta num__178)
    (PROP_SID id_badomainuser str__bd)
    (PROP_SID id_bedomainuser str__bh)
    (PROP_SID id_bidomainuser str__bl)
    (PROP_SID id_bmdomainuser str__bp)
    (PROP_SID id_bqdomainuser str__bt)
    (PROP_SID id_budomainuser str__bx)
    (PROP_SID id_bydomainuser str__cb)
    (PROP_SID id_cdomainuser str__f)
    (PROP_SID id_ccdomainuser str__cf)
    (PROP_SID id_cgdomainuser str__cj)
    (PROP_SID id_ckdomainuser str__cn)
    (PROP_SID id_codomainuser str__cr)
    (PROP_SID id_csdomainuser str__cv)
    (PROP_SID id_cwdomainuser str__cz)
    (PROP_SID id_dadomainuser str__dd)
    (PROP_SID id_dedomainuser str__dh)
    (PROP_SID id_didomainuser str__dl)
    (PROP_SID id_dmdomainuser str__dp)
    (PROP_SID id_dqdomainuser str__dt)
    (PROP_SID id_gdomainuser str__j)
    (PROP_SID id_kdomainuser str__n)
    (PROP_SID id_odomainuser str__r)
    (PROP_SID id_sdomainuser str__v)
    (PROP_SID id_wdomainuser str__z)
    (PROP_TIMEDELTA id_duhost id_dvtimedelta)
    (PROP_TIMEDELTA id_ebhost id_ectimedelta)
    (PROP_TIMEDELTA id_eihost id_ejtimedelta)
    (PROP_TIMEDELTA id_ephost id_eqtimedelta)
    (PROP_TIMEDELTA id_ewhost id_extimedelta)
    (PROP_TIMEDELTA id_fdhost id_fetimedelta)
    (PROP_TIMEDELTA id_fkhost id_fltimedelta)
    (PROP_TIMEDELTA id_frhost id_fstimedelta)
    (PROP_TIMEDELTA id_fyhost id_fztimedelta)
    (PROP_TIMEDELTA id_gfhost id_ggtimedelta)
    (PROP_TIMEDELTA id_gmhost id_gntimedelta)
    (PROP_TIMEDELTA id_gthost id_gutimedelta)
    (PROP_USER id_bbdomaincredential id_badomainuser)
    (PROP_USER id_bfdomaincredential id_bedomainuser)
    (PROP_USER id_bjdomaincredential id_bidomainuser)
    (PROP_USER id_bndomaincredential id_bmdomainuser)
    (PROP_USER id_brdomaincredential id_bqdomainuser)
    (PROP_USER id_bvdomaincredential id_budomainuser)
    (PROP_USER id_bzdomaincredential id_bydomainuser)
    (PROP_USER id_cddomaincredential id_ccdomainuser)
    (PROP_USER id_chdomaincredential id_cgdomainuser)
    (PROP_USER id_cldomaincredential id_ckdomainuser)
    (PROP_USER id_cpdomaincredential id_codomainuser)
    (PROP_USER id_ctdomaincredential id_csdomainuser)
    (PROP_USER id_cxdomaincredential id_cwdomainuser)
    (PROP_USER id_ddomaincredential id_cdomainuser)
    (PROP_USER id_dbdomaincredential id_dadomainuser)
    (PROP_USER id_dfdomaincredential id_dedomainuser)
    (PROP_USER id_djdomaincredential id_didomainuser)
    (PROP_USER id_dndomaincredential id_dmdomainuser)
    (PROP_USER id_drdomaincredential id_dqdomainuser)
    (PROP_USER id_hdomaincredential id_gdomainuser)
    (PROP_USER id_ldomaincredential id_kdomainuser)
    (PROP_USER id_pdomaincredential id_odomainuser)
    (PROP_USER id_tdomaincredential id_sdomainuser)
    (PROP_USER id_xdomaincredential id_wdomainuser)
    (PROP_USERNAME id_badomainuser str__michael)
    (PROP_USERNAME id_bedomainuser str__barbara)
    (PROP_USERNAME id_bidomainuser str__william)
    (PROP_USERNAME id_bmdomainuser str__elizabeth)
    (PROP_USERNAME id_bqdomainuser str__david)
    (PROP_USERNAME id_budomainuser str__jennifer)
    (PROP_USERNAME id_bydomainuser str__richard)
    (PROP_USERNAME id_cdomainuser str__james)
    (PROP_USERNAME id_ccdomainuser str__maria)
    (PROP_USERNAME id_cgdomainuser str__charles)
    (PROP_USERNAME id_ckdomainuser str__susan)
    (PROP_USERNAME id_codomainuser str__joseph)
    (PROP_USERNAME id_csdomainuser str__margaret)
    (PROP_USERNAME id_cwdomainuser str__thomas)
    (PROP_USERNAME id_dadomainuser str__dorothy)
    (PROP_USERNAME id_dedomainuser str__christopher)
    (PROP_USERNAME id_didomainuser str__lisa)
    (PROP_USERNAME id_dmdomainuser str__daniel)
    (PROP_USERNAME id_dqdomainuser str__nancy)
    (PROP_USERNAME id_gdomainuser str__mary)
    (PROP_USERNAME id_kdomainuser str__john)
    (PROP_USERNAME id_odomainuser str__patricia)
    (PROP_USERNAME id_sdomainuser str__robert)
    (PROP_USERNAME id_wdomainuser str__linda)
    (PROP_WINDOWS_DOMAIN id_adomain str__alpha)
    (procnone)
    (= (total-cost) 0)
)
(:goal
(and
    (procnone)
    (prop_host id_israt id_eihost)
    (prop_host id_iorat id_gthost)
    (prop_host id_inrat id_ebhost)
    (prop_host id_ixrat id_duhost)
    (prop_host id_iprat id_gmhost)
    (prop_host id_iurat id_fdhost)
    (prop_host id_itrat id_ephost)
    (prop_host id_ivrat id_gfhost)
    (prop_host id_irrat id_fyhost)
    (prop_host id_imrat id_frhost)
    (prop_host id_iqrat id_ewhost)
)
)
(:metric minimize (total-cost))
)