(define (domain grounded-STRIPS-ROVER)
(:requirements
:strips
)
(:predicates
(AT-ROVER2-WAYPOINT5)
(AT-ROVER1-WAYPOINT5)
(AT-ROVER3-WAYPOINT4)
(AT-ROVER2-WAYPOINT4)
(AT-ROVER0-WAYPOINT4)
(AT-ROVER3-WAYPOINT2)
(AT-ROVER1-WAYPOINT3)
(AT-ROVER0-WAYPOINT3)
(AT-ROVER2-WAYPOINT1)
(AT-ROVER2-WAYPOINT0)
(AT-ROVER1-WAYPOINT0)
(AT-ROVER0-WAYPOINT0)
(AT-ROVER3-WAYPOINT0)
(AT-ROVER2-WAYPOINT3)
(AT-ROVER3-WAYPOINT1)
(AT-ROVER1-WAYPOINT1)
(AT-ROVER0-WAYPOINT1)
(FULL-ROVER3STORE)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT1)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT3)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT4)
(FULL-ROVER0STORE)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT1)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT3)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT4)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT2)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT4)
(FULL-ROVER2STORE)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT3)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT4)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT5)
(FULL-ROVER1STORE)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT2)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT3)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT5)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT2)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT3)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT4)
(CALIBRATED-CAMERA3-ROVER2)
(CALIBRATED-CAMERA2-ROVER1)
(CALIBRATED-CAMERA1-ROVER3)
(CALIBRATED-CAMERA0-ROVER3)
(HAVE_IMAGE-ROVER2-OBJECTIVE2-LOW_RES)
(HAVE_IMAGE-ROVER2-OBJECTIVE2-COLOUR)
(HAVE_IMAGE-ROVER1-OBJECTIVE2-LOW_RES)
(HAVE_IMAGE-ROVER1-OBJECTIVE2-HIGH_RES)
(HAVE_IMAGE-ROVER1-OBJECTIVE2-COLOUR)
(HAVE_IMAGE-ROVER3-OBJECTIVE2-HIGH_RES)
(HAVE_IMAGE-ROVER3-OBJECTIVE2-COLOUR)
(HAVE_IMAGE-ROVER3-OBJECTIVE2-LOW_RES)
(HAVE_IMAGE-ROVER2-OBJECTIVE1-LOW_RES)
(HAVE_IMAGE-ROVER2-OBJECTIVE1-COLOUR)
(HAVE_IMAGE-ROVER1-OBJECTIVE1-LOW_RES)
(HAVE_IMAGE-ROVER1-OBJECTIVE1-HIGH_RES)
(HAVE_IMAGE-ROVER1-OBJECTIVE1-COLOUR)
(HAVE_IMAGE-ROVER3-OBJECTIVE1-HIGH_RES)
(HAVE_IMAGE-ROVER3-OBJECTIVE1-COLOUR)
(HAVE_IMAGE-ROVER3-OBJECTIVE1-LOW_RES)
(HAVE_IMAGE-ROVER2-OBJECTIVE0-LOW_RES)
(HAVE_IMAGE-ROVER2-OBJECTIVE0-COLOUR)
(HAVE_IMAGE-ROVER1-OBJECTIVE0-LOW_RES)
(HAVE_IMAGE-ROVER1-OBJECTIVE0-HIGH_RES)
(HAVE_IMAGE-ROVER1-OBJECTIVE0-COLOUR)
(HAVE_IMAGE-ROVER3-OBJECTIVE0-HIGH_RES)
(HAVE_IMAGE-ROVER3-OBJECTIVE0-COLOUR)
(HAVE_IMAGE-ROVER3-OBJECTIVE0-LOW_RES)
(COMMUNICATED_SOIL_DATA-WAYPOINT1)
(COMMUNICATED_SOIL_DATA-WAYPOINT3)
(COMMUNICATED_SOIL_DATA-WAYPOINT4)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-COLOUR)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-LOW_RES)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-COLOUR)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-LOW_RES)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-COLOUR)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-LOW_RES)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-HIGH_RES)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-HIGH_RES)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-HIGH_RES)
(AT-ROVER3-WAYPOINT5)
(AT-ROVER0-WAYPOINT5)
(AT-ROVER1-WAYPOINT4)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT5)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT4)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT5)
(AVAILABLE-ROVER1)
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(AVAILABLE-ROVER0)
(EMPTY-ROVER0STORE)
(AT_ROCK_SAMPLE-WAYPOINT5)
(EMPTY-ROVER1STORE)
(AT_ROCK_SAMPLE-WAYPOINT4)
(EMPTY-ROVER3STORE)
(AVAILABLE-ROVER2)
(AT_ROCK_SAMPLE-WAYPOINT3)
(AT_ROCK_SAMPLE-WAYPOINT2)
(EMPTY-ROVER2STORE)
(AT_SOIL_SAMPLE-WAYPOINT4)
(AT_SOIL_SAMPLE-WAYPOINT3)
(AT_SOIL_SAMPLE-WAYPOINT1)
(AT-ROVER3-WAYPOINT3)
(AT-ROVER0-WAYPOINT2)
(AT-ROVER1-WAYPOINT2)
(AT-ROVER2-WAYPOINT2)
)
(:action NAVIGATE-ROVER1-WAYPOINT4-WAYPOINT3
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT4)
(AVAILABLE-ROVER1)
)
:effect
(and
(AT-ROVER1-WAYPOINT3)
(not (AT-ROVER1-WAYPOINT4))
)
)
(:action NAVIGATE-ROVER0-WAYPOINT5-WAYPOINT3
:parameters ()
:precondition
(and
(AT-ROVER0-WAYPOINT5)
(AVAILABLE-ROVER0)
)
:effect
(and
(AT-ROVER0-WAYPOINT3)
(not (AT-ROVER0-WAYPOINT5))
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE2-LOW_RES-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE2-LOW_RES)
(AT-ROVER1-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-LOW_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE2-HIGH_RES-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE2-HIGH_RES)
(AT-ROVER1-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-HIGH_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE2-COLOUR-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE2-COLOUR)
(AT-ROVER1-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-COLOUR)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE1-LOW_RES-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE1-LOW_RES)
(AT-ROVER1-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-LOW_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE1-HIGH_RES-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE1-HIGH_RES)
(AT-ROVER1-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-HIGH_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE1-COLOUR-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE1-COLOUR)
(AT-ROVER1-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-COLOUR)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE0-LOW_RES-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE0-LOW_RES)
(AT-ROVER1-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-LOW_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE0-HIGH_RES-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE0-HIGH_RES)
(AT-ROVER1-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-HIGH_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE0-COLOUR-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE0-COLOUR)
(AT-ROVER1-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-COLOUR)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT5-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT5)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT4-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT4)
(AT-ROVER1-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT5-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT5)
(AT-ROVER0-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT5-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT5)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT4-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT4)
(AT-ROVER1-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT5-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT5)
(AT-ROVER0-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT5-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT5)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT4-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT4)
(AT-ROVER1-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT5-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT5)
(AT-ROVER0-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT5-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT5)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT5-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT5)
(AT-ROVER1-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT4-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT4)
(AT-ROVER1-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT3-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT3)
(AT-ROVER1-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT2-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT2)
(AT-ROVER1-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT5-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT5)
(AT-ROVER0-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER0)
)
)
(:action SAMPLE_ROCK-ROVER0-ROVER0STORE-WAYPOINT5
:parameters ()
:precondition
(and
(EMPTY-ROVER0STORE)
(AT_ROCK_SAMPLE-WAYPOINT5)
(AT-ROVER0-WAYPOINT5)
)
:effect
(and
(FULL-ROVER0STORE)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT5)
(not (EMPTY-ROVER0STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT5))
)
)
(:action SAMPLE_ROCK-ROVER1-ROVER1STORE-WAYPOINT4
:parameters ()
:precondition
(and
(EMPTY-ROVER1STORE)
(AT_ROCK_SAMPLE-WAYPOINT4)
(AT-ROVER1-WAYPOINT4)
)
:effect
(and
(FULL-ROVER1STORE)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT4)
(not (EMPTY-ROVER1STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT4))
)
)
(:action SAMPLE_ROCK-ROVER3-ROVER3STORE-WAYPOINT5
:parameters ()
:precondition
(and
(EMPTY-ROVER3STORE)
(AT_ROCK_SAMPLE-WAYPOINT5)
(AT-ROVER3-WAYPOINT5)
)
:effect
(and
(FULL-ROVER3STORE)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT5)
(not (EMPTY-ROVER3STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT5))
)
)
(:action NAVIGATE-ROVER0-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(AT-ROVER0-WAYPOINT1)
(AVAILABLE-ROVER0)
)
:effect
(and
(AT-ROVER0-WAYPOINT0)
(not (AT-ROVER0-WAYPOINT1))
)
)
(:action NAVIGATE-ROVER1-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT1)
(AVAILABLE-ROVER1)
)
:effect
(and
(AT-ROVER1-WAYPOINT0)
(not (AT-ROVER1-WAYPOINT1))
)
)
(:action NAVIGATE-ROVER3-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT1)
(AVAILABLE-ROVER3)
)
:effect
(and
(AT-ROVER3-WAYPOINT0)
(not (AT-ROVER3-WAYPOINT1))
)
)
(:action NAVIGATE-ROVER2-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT3)
(AVAILABLE-ROVER2)
)
:effect
(and
(AT-ROVER2-WAYPOINT0)
(not (AT-ROVER2-WAYPOINT3))
)
)
(:action NAVIGATE-ROVER0-WAYPOINT0-WAYPOINT2
:parameters ()
:precondition
(and
(AT-ROVER0-WAYPOINT0)
(AVAILABLE-ROVER0)
)
:effect
(and
(AT-ROVER0-WAYPOINT2)
(not (AT-ROVER0-WAYPOINT0))
)
)
(:action NAVIGATE-ROVER1-WAYPOINT0-WAYPOINT2
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT0)
(AVAILABLE-ROVER1)
)
:effect
(and
(AT-ROVER1-WAYPOINT2)
(not (AT-ROVER1-WAYPOINT0))
)
)
(:action NAVIGATE-ROVER2-WAYPOINT0-WAYPOINT2
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT0)
(AVAILABLE-ROVER2)
)
:effect
(and
(AT-ROVER2-WAYPOINT2)
(not (AT-ROVER2-WAYPOINT0))
)
)
(:action NAVIGATE-ROVER2-WAYPOINT1-WAYPOINT2
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT1)
(AVAILABLE-ROVER2)
)
:effect
(and
(AT-ROVER2-WAYPOINT2)
(not (AT-ROVER2-WAYPOINT1))
)
)
(:action NAVIGATE-ROVER0-WAYPOINT3-WAYPOINT2
:parameters ()
:precondition
(and
(AT-ROVER0-WAYPOINT3)
(AVAILABLE-ROVER0)
)
:effect
(and
(AT-ROVER0-WAYPOINT2)
(not (AT-ROVER0-WAYPOINT3))
)
)
(:action NAVIGATE-ROVER1-WAYPOINT3-WAYPOINT2
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT3)
(AVAILABLE-ROVER1)
)
:effect
(and
(AT-ROVER1-WAYPOINT2)
(not (AT-ROVER1-WAYPOINT3))
)
)
(:action NAVIGATE-ROVER0-WAYPOINT4-WAYPOINT2
:parameters ()
:precondition
(and
(AT-ROVER0-WAYPOINT4)
(AVAILABLE-ROVER0)
)
:effect
(and
(AT-ROVER0-WAYPOINT2)
(not (AT-ROVER0-WAYPOINT4))
)
)
(:action NAVIGATE-ROVER2-WAYPOINT4-WAYPOINT2
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT4)
(AVAILABLE-ROVER2)
)
:effect
(and
(AT-ROVER2-WAYPOINT2)
(not (AT-ROVER2-WAYPOINT4))
)
)
(:action NAVIGATE-ROVER1-WAYPOINT3-WAYPOINT4
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT3)
(AVAILABLE-ROVER1)
)
:effect
(and
(AT-ROVER1-WAYPOINT4)
(not (AT-ROVER1-WAYPOINT3))
)
)
(:action NAVIGATE-ROVER3-WAYPOINT4-WAYPOINT3
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT4)
(AVAILABLE-ROVER3)
)
:effect
(and
(AT-ROVER3-WAYPOINT3)
(not (AT-ROVER3-WAYPOINT4))
)
)
(:action NAVIGATE-ROVER0-WAYPOINT3-WAYPOINT5
:parameters ()
:precondition
(and
(AT-ROVER0-WAYPOINT3)
(AVAILABLE-ROVER0)
)
:effect
(and
(AT-ROVER0-WAYPOINT5)
(not (AT-ROVER0-WAYPOINT3))
)
)
(:action NAVIGATE-ROVER3-WAYPOINT5-WAYPOINT2
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT5)
(AVAILABLE-ROVER3)
)
:effect
(and
(AT-ROVER3-WAYPOINT2)
(not (AT-ROVER3-WAYPOINT5))
)
)
(:action NAVIGATE-ROVER3-WAYPOINT2-WAYPOINT5
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT2)
(AVAILABLE-ROVER3)
)
:effect
(and
(AT-ROVER3-WAYPOINT5)
(not (AT-ROVER3-WAYPOINT2))
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE2-LOW_RES-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE2-LOW_RES)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-LOW_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE2-HIGH_RES-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE2-HIGH_RES)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-HIGH_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE2-COLOUR-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE2-COLOUR)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-COLOUR)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE1-LOW_RES-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE1-LOW_RES)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-LOW_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE1-HIGH_RES-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE1-HIGH_RES)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-HIGH_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE1-COLOUR-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE1-COLOUR)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-COLOUR)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE0-LOW_RES-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE0-LOW_RES)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-LOW_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE0-HIGH_RES-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE0-HIGH_RES)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-HIGH_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE0-COLOUR-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE0-COLOUR)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-COLOUR)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE2-LOW_RES-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE2-LOW_RES)
(AT-ROVER2-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-LOW_RES)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE2-COLOUR-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE2-COLOUR)
(AT-ROVER2-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-COLOUR)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE1-LOW_RES-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE1-LOW_RES)
(AT-ROVER2-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-LOW_RES)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE1-COLOUR-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE1-COLOUR)
(AT-ROVER2-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-COLOUR)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE0-LOW_RES-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE0-LOW_RES)
(AT-ROVER2-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-LOW_RES)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE0-COLOUR-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE0-COLOUR)
(AT-ROVER2-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-COLOUR)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE2-LOW_RES-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE2-LOW_RES)
(AT-ROVER1-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-LOW_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE2-HIGH_RES-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE2-HIGH_RES)
(AT-ROVER1-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-HIGH_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE2-COLOUR-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE2-COLOUR)
(AT-ROVER1-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-COLOUR)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE1-LOW_RES-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE1-LOW_RES)
(AT-ROVER1-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-LOW_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE1-HIGH_RES-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE1-HIGH_RES)
(AT-ROVER1-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-HIGH_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE1-COLOUR-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE1-COLOUR)
(AT-ROVER1-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-COLOUR)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE0-LOW_RES-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE0-LOW_RES)
(AT-ROVER1-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-LOW_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE0-HIGH_RES-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE0-HIGH_RES)
(AT-ROVER1-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-HIGH_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE0-COLOUR-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE0-COLOUR)
(AT-ROVER1-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-COLOUR)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE2-LOW_RES-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE2-LOW_RES)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-LOW_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE2-HIGH_RES-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE2-HIGH_RES)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-HIGH_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE2-COLOUR-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE2-COLOUR)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-COLOUR)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE1-LOW_RES-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE1-LOW_RES)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-LOW_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE1-HIGH_RES-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE1-HIGH_RES)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-HIGH_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE1-COLOUR-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE1-COLOUR)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-COLOUR)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE0-LOW_RES-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE0-LOW_RES)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-LOW_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE0-HIGH_RES-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE0-HIGH_RES)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-HIGH_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE0-COLOUR-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE0-COLOUR)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-COLOUR)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE2-LOW_RES-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE2-LOW_RES)
(AT-ROVER2-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-LOW_RES)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE2-COLOUR-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE2-COLOUR)
(AT-ROVER2-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-COLOUR)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE1-LOW_RES-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE1-LOW_RES)
(AT-ROVER2-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-LOW_RES)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE1-COLOUR-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE1-COLOUR)
(AT-ROVER2-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-COLOUR)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE0-LOW_RES-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE0-LOW_RES)
(AT-ROVER2-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-LOW_RES)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE0-COLOUR-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE0-COLOUR)
(AT-ROVER2-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-COLOUR)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE2-LOW_RES-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE2-LOW_RES)
(AT-ROVER1-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-LOW_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE2-HIGH_RES-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE2-HIGH_RES)
(AT-ROVER1-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-HIGH_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE2-COLOUR-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE2-COLOUR)
(AT-ROVER1-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-COLOUR)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE1-LOW_RES-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE1-LOW_RES)
(AT-ROVER1-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-LOW_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE1-HIGH_RES-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE1-HIGH_RES)
(AT-ROVER1-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-HIGH_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE1-COLOUR-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE1-COLOUR)
(AT-ROVER1-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-COLOUR)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE0-LOW_RES-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE0-LOW_RES)
(AT-ROVER1-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-LOW_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE0-HIGH_RES-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE0-HIGH_RES)
(AT-ROVER1-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-HIGH_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE0-COLOUR-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE0-COLOUR)
(AT-ROVER1-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-COLOUR)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE2-LOW_RES-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE2-LOW_RES)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-LOW_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE2-HIGH_RES-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE2-HIGH_RES)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-HIGH_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE2-COLOUR-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE2-COLOUR)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-COLOUR)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE1-LOW_RES-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE1-LOW_RES)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-LOW_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE1-HIGH_RES-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE1-HIGH_RES)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-HIGH_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE1-COLOUR-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE1-COLOUR)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-COLOUR)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE0-LOW_RES-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE0-LOW_RES)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-LOW_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE0-HIGH_RES-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE0-HIGH_RES)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-HIGH_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE0-COLOUR-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE0-COLOUR)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-COLOUR)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE2-LOW_RES-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE2-LOW_RES)
(AT-ROVER2-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-LOW_RES)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE2-COLOUR-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE2-COLOUR)
(AT-ROVER2-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-COLOUR)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE1-LOW_RES-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE1-LOW_RES)
(AT-ROVER2-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-LOW_RES)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE1-COLOUR-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE1-COLOUR)
(AT-ROVER2-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-COLOUR)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE0-LOW_RES-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE0-LOW_RES)
(AT-ROVER2-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-LOW_RES)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE0-COLOUR-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE0-COLOUR)
(AT-ROVER2-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-COLOUR)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE2-LOW_RES-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE2-LOW_RES)
(AT-ROVER1-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-LOW_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE2-HIGH_RES-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE2-HIGH_RES)
(AT-ROVER1-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-HIGH_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE2-COLOUR-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE2-COLOUR)
(AT-ROVER1-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-COLOUR)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE1-LOW_RES-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE1-LOW_RES)
(AT-ROVER1-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-LOW_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE1-HIGH_RES-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE1-HIGH_RES)
(AT-ROVER1-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-HIGH_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE1-COLOUR-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE1-COLOUR)
(AT-ROVER1-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-COLOUR)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE0-LOW_RES-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE0-LOW_RES)
(AT-ROVER1-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-LOW_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE0-HIGH_RES-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE0-HIGH_RES)
(AT-ROVER1-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-HIGH_RES)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER1-GENERAL-OBJECTIVE0-COLOUR-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_IMAGE-ROVER1-OBJECTIVE0-COLOUR)
(AT-ROVER1-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-COLOUR)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE2-LOW_RES-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE2-LOW_RES)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-LOW_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE2-HIGH_RES-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE2-HIGH_RES)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-HIGH_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE2-COLOUR-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE2-COLOUR)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-COLOUR)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE1-LOW_RES-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE1-LOW_RES)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-LOW_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE1-HIGH_RES-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE1-HIGH_RES)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-HIGH_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE1-COLOUR-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE1-COLOUR)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-COLOUR)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE0-LOW_RES-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE0-LOW_RES)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-LOW_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE0-HIGH_RES-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE0-HIGH_RES)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-HIGH_RES)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER3-GENERAL-OBJECTIVE0-COLOUR-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_IMAGE-ROVER3-OBJECTIVE0-COLOUR)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-COLOUR)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE2-LOW_RES-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE2-LOW_RES)
(AT-ROVER2-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-LOW_RES)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE2-COLOUR-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE2-COLOUR)
(AT-ROVER2-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE2-COLOUR)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE1-LOW_RES-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE1-LOW_RES)
(AT-ROVER2-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-LOW_RES)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE1-COLOUR-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE1-COLOUR)
(AT-ROVER2-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE1-COLOUR)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE0-LOW_RES-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE0-LOW_RES)
(AT-ROVER2-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-LOW_RES)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_IMAGE_DATA-ROVER2-GENERAL-OBJECTIVE0-COLOUR-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_IMAGE-ROVER2-OBJECTIVE0-COLOUR)
(AT-ROVER2-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_IMAGE_DATA-OBJECTIVE0-COLOUR)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT4-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT4)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT3-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT3)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT2-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT2)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT5-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT5)
(AT-ROVER2-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT4-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT4)
(AT-ROVER2-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT3-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT3)
(AT-ROVER2-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT2-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT2)
(AT-ROVER2-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT5-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT5)
(AT-ROVER1-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT3-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT3)
(AT-ROVER1-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT2-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT2)
(AT-ROVER1-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT4-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT4)
(AT-ROVER0-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT3-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT3)
(AT-ROVER0-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT2-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT2)
(AT-ROVER0-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT4-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT4)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT3-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT3)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT2-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT2)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT5-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT5)
(AT-ROVER2-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT4-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT4)
(AT-ROVER2-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT3-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT3)
(AT-ROVER2-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT2-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT2)
(AT-ROVER2-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT5-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT5)
(AT-ROVER1-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT3-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT3)
(AT-ROVER1-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT2-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT2)
(AT-ROVER1-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT4-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT4)
(AT-ROVER0-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT3-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT3)
(AT-ROVER0-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT2-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT2)
(AT-ROVER0-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT4-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT4)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT3-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT3)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT2-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT2)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT5-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT5)
(AT-ROVER2-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT4-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT4)
(AT-ROVER2-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT3-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT3)
(AT-ROVER2-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT2-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT2)
(AT-ROVER2-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT5-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT5)
(AT-ROVER1-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT3-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT3)
(AT-ROVER1-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER1-GENERAL-WAYPOINT2-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER1)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT2)
(AT-ROVER1-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER1)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT4-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT4)
(AT-ROVER0-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT3-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT3)
(AT-ROVER0-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT2-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT2)
(AT-ROVER0-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT4-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT4)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT3-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT3)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER3-GENERAL-WAYPOINT2-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT2)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT5-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT5)
(AT-ROVER2-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT5)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT4-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT4)
(AT-ROVER2-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT3-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT3)
(AT-ROVER2-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER2-GENERAL-WAYPOINT2-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER2)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT2)
(AT-ROVER2-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER2)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT4-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT4)
(AT-ROVER0-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT4)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT3-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT3)
(AT-ROVER0-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT3)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_ROCK_DATA-ROVER0-GENERAL-WAYPOINT2-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT2)
(AT-ROVER0-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_ROCK_DATA-WAYPOINT2)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER3-GENERAL-WAYPOINT4-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT4)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT4)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER3-GENERAL-WAYPOINT3-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT3)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT3)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER3-GENERAL-WAYPOINT1-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT1)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT1)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER0-GENERAL-WAYPOINT4-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT4)
(AT-ROVER0-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT4)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER0-GENERAL-WAYPOINT3-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT3)
(AT-ROVER0-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT3)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER0-GENERAL-WAYPOINT1-WAYPOINT1-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT1)
(AT-ROVER0-WAYPOINT1)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT1)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER3-GENERAL-WAYPOINT4-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT4)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT4)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER3-GENERAL-WAYPOINT3-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT3)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT3)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER3-GENERAL-WAYPOINT1-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT1)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT1)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER0-GENERAL-WAYPOINT4-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT4)
(AT-ROVER0-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT4)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER0-GENERAL-WAYPOINT3-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT3)
(AT-ROVER0-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT3)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER0-GENERAL-WAYPOINT1-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT1)
(AT-ROVER0-WAYPOINT3)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT1)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER3-GENERAL-WAYPOINT4-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT4)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT4)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER3-GENERAL-WAYPOINT3-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT3)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT3)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER3-GENERAL-WAYPOINT1-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT1)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT1)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER0-GENERAL-WAYPOINT4-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT4)
(AT-ROVER0-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT4)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER0-GENERAL-WAYPOINT3-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT3)
(AT-ROVER0-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT3)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER0-GENERAL-WAYPOINT1-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT1)
(AT-ROVER0-WAYPOINT2)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT1)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER3-GENERAL-WAYPOINT4-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT4)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT4)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER3-GENERAL-WAYPOINT3-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT3)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT3)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER3-GENERAL-WAYPOINT1-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER3)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT1)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT1)
(AVAILABLE-ROVER3)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER0-GENERAL-WAYPOINT4-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT4)
(AT-ROVER0-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT4)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER0-GENERAL-WAYPOINT3-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT3)
(AT-ROVER0-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT3)
(AVAILABLE-ROVER0)
)
)
(:action COMMUNICATE_SOIL_DATA-ROVER0-GENERAL-WAYPOINT1-WAYPOINT4-WAYPOINT0
:parameters ()
:precondition
(and
(CHANNEL_FREE-GENERAL)
(AVAILABLE-ROVER0)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT1)
(AT-ROVER0-WAYPOINT4)
)
:effect
(and
(CHANNEL_FREE-GENERAL)
(COMMUNICATED_SOIL_DATA-WAYPOINT1)
(AVAILABLE-ROVER0)
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT0-OBJECTIVE0-CAMERA0-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE0-COLOUR)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT0-OBJECTIVE0-CAMERA0-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE0-HIGH_RES)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT0-OBJECTIVE0-CAMERA0-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE0-LOW_RES)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT0-OBJECTIVE0-CAMERA1-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(CALIBRATED-CAMERA1-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE0-COLOUR)
(not (CALIBRATED-CAMERA1-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT0-OBJECTIVE0-CAMERA1-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(CALIBRATED-CAMERA1-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE0-HIGH_RES)
(not (CALIBRATED-CAMERA1-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT0-OBJECTIVE0-CAMERA2-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT0)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE0-COLOUR)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT0-OBJECTIVE0-CAMERA2-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT0)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE0-HIGH_RES)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT0-OBJECTIVE0-CAMERA2-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT0)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE0-LOW_RES)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER2-WAYPOINT0-OBJECTIVE0-CAMERA3-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT0)
(CALIBRATED-CAMERA3-ROVER2)
)
:effect
(and
(HAVE_IMAGE-ROVER2-OBJECTIVE0-COLOUR)
(not (CALIBRATED-CAMERA3-ROVER2))
)
)
(:action TAKE_IMAGE-ROVER2-WAYPOINT0-OBJECTIVE0-CAMERA3-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT0)
(CALIBRATED-CAMERA3-ROVER2)
)
:effect
(and
(HAVE_IMAGE-ROVER2-OBJECTIVE0-LOW_RES)
(not (CALIBRATED-CAMERA3-ROVER2))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT1-OBJECTIVE0-CAMERA0-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT1)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE0-COLOUR)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT1-OBJECTIVE0-CAMERA0-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT1)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE0-HIGH_RES)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT1-OBJECTIVE0-CAMERA0-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT1)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE0-LOW_RES)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT1-OBJECTIVE0-CAMERA1-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT1)
(CALIBRATED-CAMERA1-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE0-COLOUR)
(not (CALIBRATED-CAMERA1-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT1-OBJECTIVE0-CAMERA1-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT1)
(CALIBRATED-CAMERA1-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE0-HIGH_RES)
(not (CALIBRATED-CAMERA1-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT1-OBJECTIVE0-CAMERA2-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT1)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE0-COLOUR)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT1-OBJECTIVE0-CAMERA2-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT1)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE0-HIGH_RES)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT1-OBJECTIVE0-CAMERA2-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT1)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE0-LOW_RES)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER2-WAYPOINT1-OBJECTIVE0-CAMERA3-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT1)
(CALIBRATED-CAMERA3-ROVER2)
)
:effect
(and
(HAVE_IMAGE-ROVER2-OBJECTIVE0-COLOUR)
(not (CALIBRATED-CAMERA3-ROVER2))
)
)
(:action TAKE_IMAGE-ROVER2-WAYPOINT1-OBJECTIVE0-CAMERA3-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT1)
(CALIBRATED-CAMERA3-ROVER2)
)
:effect
(and
(HAVE_IMAGE-ROVER2-OBJECTIVE0-LOW_RES)
(not (CALIBRATED-CAMERA3-ROVER2))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT2-OBJECTIVE0-CAMERA0-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT2)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE0-COLOUR)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT2-OBJECTIVE0-CAMERA0-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT2)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE0-HIGH_RES)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT2-OBJECTIVE0-CAMERA0-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT2)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE0-LOW_RES)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT2-OBJECTIVE0-CAMERA1-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT2)
(CALIBRATED-CAMERA1-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE0-COLOUR)
(not (CALIBRATED-CAMERA1-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT2-OBJECTIVE0-CAMERA1-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT2)
(CALIBRATED-CAMERA1-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE0-HIGH_RES)
(not (CALIBRATED-CAMERA1-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT2-OBJECTIVE0-CAMERA2-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT2)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE0-COLOUR)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT2-OBJECTIVE0-CAMERA2-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT2)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE0-HIGH_RES)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT2-OBJECTIVE0-CAMERA2-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT2)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE0-LOW_RES)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER2-WAYPOINT2-OBJECTIVE0-CAMERA3-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT2)
(CALIBRATED-CAMERA3-ROVER2)
)
:effect
(and
(HAVE_IMAGE-ROVER2-OBJECTIVE0-COLOUR)
(not (CALIBRATED-CAMERA3-ROVER2))
)
)
(:action TAKE_IMAGE-ROVER2-WAYPOINT2-OBJECTIVE0-CAMERA3-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT2)
(CALIBRATED-CAMERA3-ROVER2)
)
:effect
(and
(HAVE_IMAGE-ROVER2-OBJECTIVE0-LOW_RES)
(not (CALIBRATED-CAMERA3-ROVER2))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT0-OBJECTIVE1-CAMERA0-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE1-COLOUR)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT0-OBJECTIVE1-CAMERA0-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE1-HIGH_RES)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT0-OBJECTIVE1-CAMERA0-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE1-LOW_RES)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT0-OBJECTIVE1-CAMERA1-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(CALIBRATED-CAMERA1-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE1-COLOUR)
(not (CALIBRATED-CAMERA1-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT0-OBJECTIVE1-CAMERA1-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(CALIBRATED-CAMERA1-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE1-HIGH_RES)
(not (CALIBRATED-CAMERA1-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT0-OBJECTIVE1-CAMERA2-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT0)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE1-COLOUR)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT0-OBJECTIVE1-CAMERA2-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT0)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE1-HIGH_RES)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT0-OBJECTIVE1-CAMERA2-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT0)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE1-LOW_RES)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER2-WAYPOINT0-OBJECTIVE1-CAMERA3-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT0)
(CALIBRATED-CAMERA3-ROVER2)
)
:effect
(and
(HAVE_IMAGE-ROVER2-OBJECTIVE1-COLOUR)
(not (CALIBRATED-CAMERA3-ROVER2))
)
)
(:action TAKE_IMAGE-ROVER2-WAYPOINT0-OBJECTIVE1-CAMERA3-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT0)
(CALIBRATED-CAMERA3-ROVER2)
)
:effect
(and
(HAVE_IMAGE-ROVER2-OBJECTIVE1-LOW_RES)
(not (CALIBRATED-CAMERA3-ROVER2))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT0-OBJECTIVE2-CAMERA0-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE2-COLOUR)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT0-OBJECTIVE2-CAMERA0-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE2-HIGH_RES)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT0-OBJECTIVE2-CAMERA0-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE2-LOW_RES)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT0-OBJECTIVE2-CAMERA1-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(CALIBRATED-CAMERA1-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE2-COLOUR)
(not (CALIBRATED-CAMERA1-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT0-OBJECTIVE2-CAMERA1-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(CALIBRATED-CAMERA1-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE2-HIGH_RES)
(not (CALIBRATED-CAMERA1-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT0-OBJECTIVE2-CAMERA2-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT0)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE2-COLOUR)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT0-OBJECTIVE2-CAMERA2-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT0)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE2-HIGH_RES)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT0-OBJECTIVE2-CAMERA2-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT0)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE2-LOW_RES)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER2-WAYPOINT0-OBJECTIVE2-CAMERA3-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT0)
(CALIBRATED-CAMERA3-ROVER2)
)
:effect
(and
(HAVE_IMAGE-ROVER2-OBJECTIVE2-COLOUR)
(not (CALIBRATED-CAMERA3-ROVER2))
)
)
(:action TAKE_IMAGE-ROVER2-WAYPOINT0-OBJECTIVE2-CAMERA3-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT0)
(CALIBRATED-CAMERA3-ROVER2)
)
:effect
(and
(HAVE_IMAGE-ROVER2-OBJECTIVE2-LOW_RES)
(not (CALIBRATED-CAMERA3-ROVER2))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT1-OBJECTIVE2-CAMERA0-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT1)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE2-COLOUR)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT1-OBJECTIVE2-CAMERA0-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT1)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE2-HIGH_RES)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT1-OBJECTIVE2-CAMERA0-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT1)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE2-LOW_RES)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT1-OBJECTIVE2-CAMERA1-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT1)
(CALIBRATED-CAMERA1-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE2-COLOUR)
(not (CALIBRATED-CAMERA1-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT1-OBJECTIVE2-CAMERA1-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT1)
(CALIBRATED-CAMERA1-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE2-HIGH_RES)
(not (CALIBRATED-CAMERA1-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT1-OBJECTIVE2-CAMERA2-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT1)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE2-COLOUR)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT1-OBJECTIVE2-CAMERA2-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT1)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE2-HIGH_RES)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT1-OBJECTIVE2-CAMERA2-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT1)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE2-LOW_RES)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER2-WAYPOINT1-OBJECTIVE2-CAMERA3-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT1)
(CALIBRATED-CAMERA3-ROVER2)
)
:effect
(and
(HAVE_IMAGE-ROVER2-OBJECTIVE2-COLOUR)
(not (CALIBRATED-CAMERA3-ROVER2))
)
)
(:action TAKE_IMAGE-ROVER2-WAYPOINT1-OBJECTIVE2-CAMERA3-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT1)
(CALIBRATED-CAMERA3-ROVER2)
)
:effect
(and
(HAVE_IMAGE-ROVER2-OBJECTIVE2-LOW_RES)
(not (CALIBRATED-CAMERA3-ROVER2))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT2-OBJECTIVE2-CAMERA0-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT2)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE2-COLOUR)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT2-OBJECTIVE2-CAMERA0-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT2)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE2-HIGH_RES)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT2-OBJECTIVE2-CAMERA0-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT2)
(CALIBRATED-CAMERA0-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE2-LOW_RES)
(not (CALIBRATED-CAMERA0-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT2-OBJECTIVE2-CAMERA1-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT2)
(CALIBRATED-CAMERA1-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE2-COLOUR)
(not (CALIBRATED-CAMERA1-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER3-WAYPOINT2-OBJECTIVE2-CAMERA1-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT2)
(CALIBRATED-CAMERA1-ROVER3)
)
:effect
(and
(HAVE_IMAGE-ROVER3-OBJECTIVE2-HIGH_RES)
(not (CALIBRATED-CAMERA1-ROVER3))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT2-OBJECTIVE2-CAMERA2-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT2)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE2-COLOUR)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT2-OBJECTIVE2-CAMERA2-HIGH_RES
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT2)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE2-HIGH_RES)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER1-WAYPOINT2-OBJECTIVE2-CAMERA2-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT2)
(CALIBRATED-CAMERA2-ROVER1)
)
:effect
(and
(HAVE_IMAGE-ROVER1-OBJECTIVE2-LOW_RES)
(not (CALIBRATED-CAMERA2-ROVER1))
)
)
(:action TAKE_IMAGE-ROVER2-WAYPOINT2-OBJECTIVE2-CAMERA3-COLOUR
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT2)
(CALIBRATED-CAMERA3-ROVER2)
)
:effect
(and
(HAVE_IMAGE-ROVER2-OBJECTIVE2-COLOUR)
(not (CALIBRATED-CAMERA3-ROVER2))
)
)
(:action TAKE_IMAGE-ROVER2-WAYPOINT2-OBJECTIVE2-CAMERA3-LOW_RES
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT2)
(CALIBRATED-CAMERA3-ROVER2)
)
:effect
(and
(HAVE_IMAGE-ROVER2-OBJECTIVE2-LOW_RES)
(not (CALIBRATED-CAMERA3-ROVER2))
)
)
(:action CALIBRATE-ROVER3-CAMERA0-OBJECTIVE1-WAYPOINT0
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
)
:effect
(and
(CALIBRATED-CAMERA0-ROVER3)
)
)
(:action CALIBRATE-ROVER3-CAMERA1-OBJECTIVE0-WAYPOINT0
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
)
:effect
(and
(CALIBRATED-CAMERA1-ROVER3)
)
)
(:action CALIBRATE-ROVER3-CAMERA1-OBJECTIVE0-WAYPOINT1
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(CALIBRATED-CAMERA1-ROVER3)
)
)
(:action CALIBRATE-ROVER3-CAMERA1-OBJECTIVE0-WAYPOINT2
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(CALIBRATED-CAMERA1-ROVER3)
)
)
(:action CALIBRATE-ROVER1-CAMERA2-OBJECTIVE0-WAYPOINT0
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT0)
)
:effect
(and
(CALIBRATED-CAMERA2-ROVER1)
)
)
(:action CALIBRATE-ROVER1-CAMERA2-OBJECTIVE0-WAYPOINT1
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT1)
)
:effect
(and
(CALIBRATED-CAMERA2-ROVER1)
)
)
(:action CALIBRATE-ROVER1-CAMERA2-OBJECTIVE0-WAYPOINT2
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT2)
)
:effect
(and
(CALIBRATED-CAMERA2-ROVER1)
)
)
(:action CALIBRATE-ROVER2-CAMERA3-OBJECTIVE1-WAYPOINT0
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT0)
)
:effect
(and
(CALIBRATED-CAMERA3-ROVER2)
)
)
(:action DROP-ROVER0-ROVER0STORE
:parameters ()
:precondition
(and
(FULL-ROVER0STORE)
)
:effect
(and
(EMPTY-ROVER0STORE)
(not (FULL-ROVER0STORE))
)
)
(:action DROP-ROVER1-ROVER1STORE
:parameters ()
:precondition
(and
(FULL-ROVER1STORE)
)
:effect
(and
(EMPTY-ROVER1STORE)
(not (FULL-ROVER1STORE))
)
)
(:action DROP-ROVER2-ROVER2STORE
:parameters ()
:precondition
(and
(FULL-ROVER2STORE)
)
:effect
(and
(EMPTY-ROVER2STORE)
(not (FULL-ROVER2STORE))
)
)
(:action DROP-ROVER3-ROVER3STORE
:parameters ()
:precondition
(and
(FULL-ROVER3STORE)
)
:effect
(and
(EMPTY-ROVER3STORE)
(not (FULL-ROVER3STORE))
)
)
(:action SAMPLE_ROCK-ROVER0-ROVER0STORE-WAYPOINT4
:parameters ()
:precondition
(and
(EMPTY-ROVER0STORE)
(AT_ROCK_SAMPLE-WAYPOINT4)
(AT-ROVER0-WAYPOINT4)
)
:effect
(and
(FULL-ROVER0STORE)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT4)
(not (EMPTY-ROVER0STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT4))
)
)
(:action SAMPLE_ROCK-ROVER0-ROVER0STORE-WAYPOINT3
:parameters ()
:precondition
(and
(EMPTY-ROVER0STORE)
(AT_ROCK_SAMPLE-WAYPOINT3)
(AT-ROVER0-WAYPOINT3)
)
:effect
(and
(FULL-ROVER0STORE)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT3)
(not (EMPTY-ROVER0STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT3))
)
)
(:action SAMPLE_ROCK-ROVER0-ROVER0STORE-WAYPOINT2
:parameters ()
:precondition
(and
(EMPTY-ROVER0STORE)
(AT_ROCK_SAMPLE-WAYPOINT2)
(AT-ROVER0-WAYPOINT2)
)
:effect
(and
(FULL-ROVER0STORE)
(HAVE_ROCK_ANALYSIS-ROVER0-WAYPOINT2)
(not (EMPTY-ROVER0STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT2))
)
)
(:action SAMPLE_ROCK-ROVER1-ROVER1STORE-WAYPOINT5
:parameters ()
:precondition
(and
(EMPTY-ROVER1STORE)
(AT_ROCK_SAMPLE-WAYPOINT5)
(AT-ROVER1-WAYPOINT5)
)
:effect
(and
(FULL-ROVER1STORE)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT5)
(not (EMPTY-ROVER1STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT5))
)
)
(:action SAMPLE_ROCK-ROVER1-ROVER1STORE-WAYPOINT3
:parameters ()
:precondition
(and
(EMPTY-ROVER1STORE)
(AT_ROCK_SAMPLE-WAYPOINT3)
(AT-ROVER1-WAYPOINT3)
)
:effect
(and
(FULL-ROVER1STORE)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT3)
(not (EMPTY-ROVER1STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT3))
)
)
(:action SAMPLE_ROCK-ROVER1-ROVER1STORE-WAYPOINT2
:parameters ()
:precondition
(and
(EMPTY-ROVER1STORE)
(AT_ROCK_SAMPLE-WAYPOINT2)
(AT-ROVER1-WAYPOINT2)
)
:effect
(and
(FULL-ROVER1STORE)
(HAVE_ROCK_ANALYSIS-ROVER1-WAYPOINT2)
(not (EMPTY-ROVER1STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT2))
)
)
(:action SAMPLE_ROCK-ROVER2-ROVER2STORE-WAYPOINT5
:parameters ()
:precondition
(and
(EMPTY-ROVER2STORE)
(AT_ROCK_SAMPLE-WAYPOINT5)
(AT-ROVER2-WAYPOINT5)
)
:effect
(and
(FULL-ROVER2STORE)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT5)
(not (EMPTY-ROVER2STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT5))
)
)
(:action SAMPLE_ROCK-ROVER2-ROVER2STORE-WAYPOINT4
:parameters ()
:precondition
(and
(EMPTY-ROVER2STORE)
(AT_ROCK_SAMPLE-WAYPOINT4)
(AT-ROVER2-WAYPOINT4)
)
:effect
(and
(FULL-ROVER2STORE)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT4)
(not (EMPTY-ROVER2STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT4))
)
)
(:action SAMPLE_ROCK-ROVER2-ROVER2STORE-WAYPOINT3
:parameters ()
:precondition
(and
(EMPTY-ROVER2STORE)
(AT_ROCK_SAMPLE-WAYPOINT3)
(AT-ROVER2-WAYPOINT3)
)
:effect
(and
(FULL-ROVER2STORE)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT3)
(not (EMPTY-ROVER2STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT3))
)
)
(:action SAMPLE_ROCK-ROVER2-ROVER2STORE-WAYPOINT2
:parameters ()
:precondition
(and
(EMPTY-ROVER2STORE)
(AT_ROCK_SAMPLE-WAYPOINT2)
(AT-ROVER2-WAYPOINT2)
)
:effect
(and
(FULL-ROVER2STORE)
(HAVE_ROCK_ANALYSIS-ROVER2-WAYPOINT2)
(not (EMPTY-ROVER2STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT2))
)
)
(:action SAMPLE_ROCK-ROVER3-ROVER3STORE-WAYPOINT4
:parameters ()
:precondition
(and
(EMPTY-ROVER3STORE)
(AT_ROCK_SAMPLE-WAYPOINT4)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(FULL-ROVER3STORE)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT4)
(not (EMPTY-ROVER3STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT4))
)
)
(:action SAMPLE_ROCK-ROVER3-ROVER3STORE-WAYPOINT3
:parameters ()
:precondition
(and
(EMPTY-ROVER3STORE)
(AT_ROCK_SAMPLE-WAYPOINT3)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(FULL-ROVER3STORE)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT3)
(not (EMPTY-ROVER3STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT3))
)
)
(:action SAMPLE_ROCK-ROVER3-ROVER3STORE-WAYPOINT2
:parameters ()
:precondition
(and
(EMPTY-ROVER3STORE)
(AT_ROCK_SAMPLE-WAYPOINT2)
(AT-ROVER3-WAYPOINT2)
)
:effect
(and
(FULL-ROVER3STORE)
(HAVE_ROCK_ANALYSIS-ROVER3-WAYPOINT2)
(not (EMPTY-ROVER3STORE))
(not (AT_ROCK_SAMPLE-WAYPOINT2))
)
)
(:action SAMPLE_SOIL-ROVER0-ROVER0STORE-WAYPOINT4
:parameters ()
:precondition
(and
(EMPTY-ROVER0STORE)
(AT_SOIL_SAMPLE-WAYPOINT4)
(AT-ROVER0-WAYPOINT4)
)
:effect
(and
(FULL-ROVER0STORE)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT4)
(not (EMPTY-ROVER0STORE))
(not (AT_SOIL_SAMPLE-WAYPOINT4))
)
)
(:action SAMPLE_SOIL-ROVER0-ROVER0STORE-WAYPOINT3
:parameters ()
:precondition
(and
(EMPTY-ROVER0STORE)
(AT_SOIL_SAMPLE-WAYPOINT3)
(AT-ROVER0-WAYPOINT3)
)
:effect
(and
(FULL-ROVER0STORE)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT3)
(not (EMPTY-ROVER0STORE))
(not (AT_SOIL_SAMPLE-WAYPOINT3))
)
)
(:action SAMPLE_SOIL-ROVER0-ROVER0STORE-WAYPOINT1
:parameters ()
:precondition
(and
(EMPTY-ROVER0STORE)
(AT_SOIL_SAMPLE-WAYPOINT1)
(AT-ROVER0-WAYPOINT1)
)
:effect
(and
(FULL-ROVER0STORE)
(HAVE_SOIL_ANALYSIS-ROVER0-WAYPOINT1)
(not (EMPTY-ROVER0STORE))
(not (AT_SOIL_SAMPLE-WAYPOINT1))
)
)
(:action SAMPLE_SOIL-ROVER3-ROVER3STORE-WAYPOINT4
:parameters ()
:precondition
(and
(EMPTY-ROVER3STORE)
(AT_SOIL_SAMPLE-WAYPOINT4)
(AT-ROVER3-WAYPOINT4)
)
:effect
(and
(FULL-ROVER3STORE)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT4)
(not (EMPTY-ROVER3STORE))
(not (AT_SOIL_SAMPLE-WAYPOINT4))
)
)
(:action SAMPLE_SOIL-ROVER3-ROVER3STORE-WAYPOINT3
:parameters ()
:precondition
(and
(EMPTY-ROVER3STORE)
(AT_SOIL_SAMPLE-WAYPOINT3)
(AT-ROVER3-WAYPOINT3)
)
:effect
(and
(FULL-ROVER3STORE)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT3)
(not (EMPTY-ROVER3STORE))
(not (AT_SOIL_SAMPLE-WAYPOINT3))
)
)
(:action SAMPLE_SOIL-ROVER3-ROVER3STORE-WAYPOINT1
:parameters ()
:precondition
(and
(EMPTY-ROVER3STORE)
(AT_SOIL_SAMPLE-WAYPOINT1)
(AT-ROVER3-WAYPOINT1)
)
:effect
(and
(FULL-ROVER3STORE)
(HAVE_SOIL_ANALYSIS-ROVER3-WAYPOINT1)
(not (EMPTY-ROVER3STORE))
(not (AT_SOIL_SAMPLE-WAYPOINT1))
)
)
(:action NAVIGATE-ROVER0-WAYPOINT0-WAYPOINT1
:parameters ()
:precondition
(and
(AT-ROVER0-WAYPOINT0)
(AVAILABLE-ROVER0)
)
:effect
(and
(AT-ROVER0-WAYPOINT1)
(not (AT-ROVER0-WAYPOINT0))
)
)
(:action NAVIGATE-ROVER1-WAYPOINT0-WAYPOINT1
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT0)
(AVAILABLE-ROVER1)
)
:effect
(and
(AT-ROVER1-WAYPOINT1)
(not (AT-ROVER1-WAYPOINT0))
)
)
(:action NAVIGATE-ROVER3-WAYPOINT0-WAYPOINT1
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(AVAILABLE-ROVER3)
)
:effect
(and
(AT-ROVER3-WAYPOINT1)
(not (AT-ROVER3-WAYPOINT0))
)
)
(:action NAVIGATE-ROVER2-WAYPOINT0-WAYPOINT3
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT0)
(AVAILABLE-ROVER2)
)
:effect
(and
(AT-ROVER2-WAYPOINT3)
(not (AT-ROVER2-WAYPOINT0))
)
)
(:action NAVIGATE-ROVER3-WAYPOINT0-WAYPOINT3
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT0)
(AVAILABLE-ROVER3)
)
:effect
(and
(AT-ROVER3-WAYPOINT3)
(not (AT-ROVER3-WAYPOINT0))
)
)
(:action NAVIGATE-ROVER3-WAYPOINT3-WAYPOINT0
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT3)
(AVAILABLE-ROVER3)
)
:effect
(and
(AT-ROVER3-WAYPOINT0)
(not (AT-ROVER3-WAYPOINT3))
)
)
(:action NAVIGATE-ROVER0-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(AT-ROVER0-WAYPOINT2)
(AVAILABLE-ROVER0)
)
:effect
(and
(AT-ROVER0-WAYPOINT0)
(not (AT-ROVER0-WAYPOINT2))
)
)
(:action NAVIGATE-ROVER1-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT2)
(AVAILABLE-ROVER1)
)
:effect
(and
(AT-ROVER1-WAYPOINT0)
(not (AT-ROVER1-WAYPOINT2))
)
)
(:action NAVIGATE-ROVER2-WAYPOINT2-WAYPOINT0
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT2)
(AVAILABLE-ROVER2)
)
:effect
(and
(AT-ROVER2-WAYPOINT0)
(not (AT-ROVER2-WAYPOINT2))
)
)
(:action NAVIGATE-ROVER2-WAYPOINT2-WAYPOINT1
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT2)
(AVAILABLE-ROVER2)
)
:effect
(and
(AT-ROVER2-WAYPOINT1)
(not (AT-ROVER2-WAYPOINT2))
)
)
(:action NAVIGATE-ROVER0-WAYPOINT2-WAYPOINT3
:parameters ()
:precondition
(and
(AT-ROVER0-WAYPOINT2)
(AVAILABLE-ROVER0)
)
:effect
(and
(AT-ROVER0-WAYPOINT3)
(not (AT-ROVER0-WAYPOINT2))
)
)
(:action NAVIGATE-ROVER1-WAYPOINT2-WAYPOINT3
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT2)
(AVAILABLE-ROVER1)
)
:effect
(and
(AT-ROVER1-WAYPOINT3)
(not (AT-ROVER1-WAYPOINT2))
)
)
(:action NAVIGATE-ROVER3-WAYPOINT2-WAYPOINT3
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT2)
(AVAILABLE-ROVER3)
)
:effect
(and
(AT-ROVER3-WAYPOINT3)
(not (AT-ROVER3-WAYPOINT2))
)
)
(:action NAVIGATE-ROVER3-WAYPOINT3-WAYPOINT2
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT3)
(AVAILABLE-ROVER3)
)
:effect
(and
(AT-ROVER3-WAYPOINT2)
(not (AT-ROVER3-WAYPOINT3))
)
)
(:action NAVIGATE-ROVER0-WAYPOINT2-WAYPOINT4
:parameters ()
:precondition
(and
(AT-ROVER0-WAYPOINT2)
(AVAILABLE-ROVER0)
)
:effect
(and
(AT-ROVER0-WAYPOINT4)
(not (AT-ROVER0-WAYPOINT2))
)
)
(:action NAVIGATE-ROVER2-WAYPOINT2-WAYPOINT4
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT2)
(AVAILABLE-ROVER2)
)
:effect
(and
(AT-ROVER2-WAYPOINT4)
(not (AT-ROVER2-WAYPOINT2))
)
)
(:action NAVIGATE-ROVER3-WAYPOINT3-WAYPOINT4
:parameters ()
:precondition
(and
(AT-ROVER3-WAYPOINT3)
(AVAILABLE-ROVER3)
)
:effect
(and
(AT-ROVER3-WAYPOINT4)
(not (AT-ROVER3-WAYPOINT3))
)
)
(:action NAVIGATE-ROVER1-WAYPOINT5-WAYPOINT2
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT5)
(AVAILABLE-ROVER1)
)
:effect
(and
(AT-ROVER1-WAYPOINT2)
(not (AT-ROVER1-WAYPOINT5))
)
)
(:action NAVIGATE-ROVER2-WAYPOINT5-WAYPOINT2
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT5)
(AVAILABLE-ROVER2)
)
:effect
(and
(AT-ROVER2-WAYPOINT2)
(not (AT-ROVER2-WAYPOINT5))
)
)
(:action NAVIGATE-ROVER1-WAYPOINT2-WAYPOINT5
:parameters ()
:precondition
(and
(AT-ROVER1-WAYPOINT2)
(AVAILABLE-ROVER1)
)
:effect
(and
(AT-ROVER1-WAYPOINT5)
(not (AT-ROVER1-WAYPOINT2))
)
)
(:action NAVIGATE-ROVER2-WAYPOINT2-WAYPOINT5
:parameters ()
:precondition
(and
(AT-ROVER2-WAYPOINT2)
(AVAILABLE-ROVER2)
)
:effect
(and
(AT-ROVER2-WAYPOINT5)
(not (AT-ROVER2-WAYPOINT2))
)
)
)
