
(define (problem roverprob17923-5)
        (:domain rover)
        (:objects general - lander colour - mode high_res - mode low_res - mode
         rover0 - rover rover1 - rover rover0store - store rover1store - store
         waypoint0 - waypoint waypoint1 - waypoint waypoint2 - waypoint
         waypoint3 - waypoint waypoint4 - waypoint waypoint5 - waypoint
         waypoint6 - waypoint waypoint7 - waypoint waypoint8 - waypoint
         waypoint9 - waypoint camera0 - camera camera1 - camera objective0 -
         objective objective1 - objective objective2 - objective objective3 -
         objective objective4 - objective objective5 - objective objective6 -
         objective objective7 - objective objective8 - objective objective9 -
         objective)
        (:init (visible waypoint0 waypoint4) (visible waypoint4 waypoint0)
         (visible waypoint0 waypoint5) (visible waypoint5 waypoint0)
         (visible waypoint0 waypoint9) (visible waypoint9 waypoint0)
         (visible waypoint1 waypoint7) (visible waypoint7 waypoint1)
         (visible waypoint2 waypoint3) (visible waypoint3 waypoint2)
         (visible waypoint2 waypoint7) (visible waypoint7 waypoint2)
         (visible waypoint3 waypoint0) (visible waypoint0 waypoint3)
         (visible waypoint3 waypoint1) (visible waypoint1 waypoint3)
         (visible waypoint4 waypoint3) (visible waypoint3 waypoint4)
         (visible waypoint4 waypoint5) (visible waypoint5 waypoint4)
         (visible waypoint4 waypoint6) (visible waypoint6 waypoint4)
         (visible waypoint4 waypoint7) (visible waypoint7 waypoint4)
         (visible waypoint4 waypoint8) (visible waypoint8 waypoint4)
         (visible waypoint5 waypoint2) (visible waypoint2 waypoint5)
         (visible waypoint5 waypoint8) (visible waypoint8 waypoint5)
         (visible waypoint6 waypoint2) (visible waypoint2 waypoint6)
         (visible waypoint6 waypoint5) (visible waypoint5 waypoint6)
         (visible waypoint6 waypoint7) (visible waypoint7 waypoint6)
         (visible waypoint7 waypoint3) (visible waypoint3 waypoint7)
         (visible waypoint8 waypoint0) (visible waypoint0 waypoint8)
         (visible waypoint8 waypoint1) (visible waypoint1 waypoint8)
         (visible waypoint8 waypoint2) (visible waypoint2 waypoint8)
         (visible waypoint8 waypoint6) (visible waypoint6 waypoint8)
         (visible waypoint8 waypoint9) (visible waypoint9 waypoint8)
         (visible waypoint9 waypoint1) (visible waypoint1 waypoint9)
         (visible waypoint9 waypoint2) (visible waypoint2 waypoint9)
         (visible waypoint9 waypoint3) (visible waypoint3 waypoint9)
         (visible waypoint9 waypoint6) (visible waypoint6 waypoint9)
         (at_soil_sample waypoint0) (at_rock_sample waypoint0)
         (at_rock_sample waypoint2) (at_rock_sample waypoint4)
         (at_soil_sample waypoint5) (at_soil_sample waypoint6)
         (at_rock_sample waypoint7) (at_rock_sample waypoint8)
         (at_soil_sample waypoint9) (at_rock_sample waypoint9)
         (at_lander general waypoint0) (channel_free general)
         (at rover0 waypoint9) (available rover0) (store_of rover0store rover0)
         (empty rover0store) (equipped_for_soil_analysis rover0)
         (equipped_for_rock_analysis rover0) (equipped_for_imaging rover0)
         (can_traverse rover0 waypoint9 waypoint0)
         (can_traverse rover0 waypoint0 waypoint9)
         (can_traverse rover0 waypoint9 waypoint1)
         (can_traverse rover0 waypoint1 waypoint9)
         (can_traverse rover0 waypoint9 waypoint3)
         (can_traverse rover0 waypoint3 waypoint9)
         (can_traverse rover0 waypoint9 waypoint6)
         (can_traverse rover0 waypoint6 waypoint9)
         (can_traverse rover0 waypoint9 waypoint8)
         (can_traverse rover0 waypoint8 waypoint9)
         (can_traverse rover0 waypoint1 waypoint7)
         (can_traverse rover0 waypoint7 waypoint1) (at rover1 waypoint6)
         (available rover1) (store_of rover1store rover1) (empty rover1store)
         (equipped_for_imaging rover1)
         (can_traverse rover1 waypoint6 waypoint2)
         (can_traverse rover1 waypoint2 waypoint6)
         (can_traverse rover1 waypoint6 waypoint5)
         (can_traverse rover1 waypoint5 waypoint6)
         (can_traverse rover1 waypoint6 waypoint7)
         (can_traverse rover1 waypoint7 waypoint6)
         (can_traverse rover1 waypoint6 waypoint9)
         (can_traverse rover1 waypoint9 waypoint6)
         (can_traverse rover1 waypoint2 waypoint3)
         (can_traverse rover1 waypoint3 waypoint2)
         (can_traverse rover1 waypoint2 waypoint8)
         (can_traverse rover1 waypoint8 waypoint2)
         (can_traverse rover1 waypoint5 waypoint0)
         (can_traverse rover1 waypoint0 waypoint5) (on_board camera0 rover0)
         (calibration_target camera0 objective8) (supports camera0 high_res)
         (on_board camera1 rover1) (calibration_target camera1 objective9)
         (supports camera1 colour) (supports camera1 high_res)
         (supports camera1 low_res) (visible_from objective0 waypoint0)
         (visible_from objective0 waypoint1)
         (visible_from objective0 waypoint2)
         (visible_from objective0 waypoint3)
         (visible_from objective0 waypoint4)
         (visible_from objective0 waypoint5)
         (visible_from objective0 waypoint6)
         (visible_from objective1 waypoint0)
         (visible_from objective1 waypoint1)
         (visible_from objective2 waypoint0)
         (visible_from objective2 waypoint1)
         (visible_from objective2 waypoint2)
         (visible_from objective2 waypoint3)
         (visible_from objective2 waypoint4)
         (visible_from objective2 waypoint5)
         (visible_from objective2 waypoint6)
         (visible_from objective2 waypoint7)
         (visible_from objective3 waypoint0)
         (visible_from objective3 waypoint1)
         (visible_from objective3 waypoint2)
         (visible_from objective4 waypoint0)
         (visible_from objective4 waypoint1)
         (visible_from objective4 waypoint2)
         (visible_from objective4 waypoint3)
         (visible_from objective4 waypoint4)
         (visible_from objective4 waypoint5)
         (visible_from objective4 waypoint6)
         (visible_from objective4 waypoint7)
         (visible_from objective4 waypoint8)
         (visible_from objective4 waypoint9)
         (visible_from objective5 waypoint0)
         (visible_from objective5 waypoint1)
         (visible_from objective6 waypoint0)
         (visible_from objective7 waypoint0)
         (visible_from objective7 waypoint1)
         (visible_from objective7 waypoint2)
         (visible_from objective7 waypoint3)
         (visible_from objective7 waypoint4)
         (visible_from objective8 waypoint0)
         (visible_from objective8 waypoint1)
         (visible_from objective8 waypoint2)
         (visible_from objective9 waypoint0)
         (visible_from objective9 waypoint1)
         (visible_from objective9 waypoint2)
         (visible_from objective9 waypoint3)
         (visible_from objective9 waypoint4)
         (visible_from objective9 waypoint5)
         (visible_from objective9 waypoint6)
         (= (traverse_cost rover0 waypoint9 waypoint0) 48.6)
         (= (traverse_cost rover0 waypoint0 waypoint9) 52.5)
         (= (traverse_cost rover0 waypoint9 waypoint1) 50.9)
         (= (traverse_cost rover0 waypoint1 waypoint9) 78.6)
         (= (traverse_cost rover0 waypoint9 waypoint3) 110.5)
         (= (traverse_cost rover0 waypoint3 waypoint9) 124.8)
         (= (traverse_cost rover0 waypoint9 waypoint6) 113.4)
         (= (traverse_cost rover0 waypoint6 waypoint9) 63.6)
         (= (traverse_cost rover0 waypoint9 waypoint8) 34.7)
         (= (traverse_cost rover0 waypoint8 waypoint9) 42.1)
         (= (traverse_cost rover0 waypoint1 waypoint7) 66.5)
         (= (traverse_cost rover0 waypoint7 waypoint1) 55.3)
         (= (traverse_cost rover1 waypoint6 waypoint2) 89.1)
         (= (traverse_cost rover1 waypoint2 waypoint6) 77.2)
         (= (traverse_cost rover1 waypoint6 waypoint5) 39.6)
         (= (traverse_cost rover1 waypoint5 waypoint6) 39.5)
         (= (traverse_cost rover1 waypoint6 waypoint7) 34.1)
         (= (traverse_cost rover1 waypoint7 waypoint6) 31.1)
         (= (traverse_cost rover1 waypoint6 waypoint9) 60.4)
         (= (traverse_cost rover1 waypoint9 waypoint6) 121.1)
         (= (traverse_cost rover1 waypoint2 waypoint3) 115.9)
         (= (traverse_cost rover1 waypoint3 waypoint2) 73.7)
         (= (traverse_cost rover1 waypoint2 waypoint8) 41.5)
         (= (traverse_cost rover1 waypoint8 waypoint2) 35.3)
         (= (traverse_cost rover1 waypoint5 waypoint0) 32.6)
         (= (traverse_cost rover1 waypoint0 waypoint5) 33.7)
         (= (sum-traverse-cost) 0))
        (:goal
         (and (preference g0 (communicated_soil_data waypoint9))
              (preference g1 (communicated_soil_data waypoint6))
              (preference g2 (communicated_soil_data waypoint0))
              (preference g3 (communicated_rock_data waypoint8))
              (preference g4 (communicated_image_data objective7 colour))))
        (:metric minimize
         (+ (* (is-violated g4) 172.6)
            (* (is-violated g3) 58.9)
            (* (is-violated g2) 113.2)
            (* (is-violated g1) 354)
            (* (is-violated g0) 6.9)
            (sum-traverse-cost))))
