
(define (problem roverprob31337-2)
        (:domain rover)
        (:objects general - lander colour - mode high_res - mode low_res - mode
         rover0 - rover rover1 - rover rover0store - store rover1store - store
         waypoint0 - waypoint waypoint1 - waypoint waypoint2 - waypoint
         waypoint3 - waypoint waypoint4 - waypoint waypoint5 - waypoint
         waypoint6 - waypoint waypoint7 - waypoint waypoint8 - waypoint
         waypoint9 - waypoint camera0 - camera objective0 - objective
         objective1 - objective objective2 - objective objective3 - objective
         objective4 - objective objective5 - objective objective6 - objective
         objective7 - objective objective8 - objective objective9 - objective)
        (:init (visible waypoint0 waypoint5) (visible waypoint5 waypoint0)
         (visible waypoint0 waypoint6) (visible waypoint6 waypoint0)
         (visible waypoint1 waypoint0) (visible waypoint0 waypoint1)
         (visible waypoint1 waypoint5) (visible waypoint5 waypoint1)
         (visible waypoint1 waypoint9) (visible waypoint9 waypoint1)
         (visible waypoint2 waypoint1) (visible waypoint1 waypoint2)
         (visible waypoint2 waypoint7) (visible waypoint7 waypoint2)
         (visible waypoint2 waypoint8) (visible waypoint8 waypoint2)
         (visible waypoint2 waypoint9) (visible waypoint9 waypoint2)
         (visible waypoint3 waypoint1) (visible waypoint1 waypoint3)
         (visible waypoint3 waypoint7) (visible waypoint7 waypoint3)
         (visible waypoint3 waypoint8) (visible waypoint8 waypoint3)
         (visible waypoint4 waypoint0) (visible waypoint0 waypoint4)
         (visible waypoint4 waypoint1) (visible waypoint1 waypoint4)
         (visible waypoint4 waypoint2) (visible waypoint2 waypoint4)
         (visible waypoint4 waypoint3) (visible waypoint3 waypoint4)
         (visible waypoint4 waypoint5) (visible waypoint5 waypoint4)
         (visible waypoint4 waypoint9) (visible waypoint9 waypoint4)
         (visible waypoint5 waypoint3) (visible waypoint3 waypoint5)
         (visible waypoint5 waypoint8) (visible waypoint8 waypoint5)
         (visible waypoint6 waypoint1) (visible waypoint1 waypoint6)
         (visible waypoint6 waypoint2) (visible waypoint2 waypoint6)
         (visible waypoint6 waypoint4) (visible waypoint4 waypoint6)
         (visible waypoint6 waypoint5) (visible waypoint5 waypoint6)
         (visible waypoint6 waypoint7) (visible waypoint7 waypoint6)
         (visible waypoint6 waypoint8) (visible waypoint8 waypoint6)
         (visible waypoint7 waypoint5) (visible waypoint5 waypoint7)
         (visible waypoint8 waypoint0) (visible waypoint0 waypoint8)
         (visible waypoint8 waypoint1) (visible waypoint1 waypoint8)
         (visible waypoint9 waypoint0) (visible waypoint0 waypoint9)
         (visible waypoint9 waypoint3) (visible waypoint3 waypoint9)
         (visible waypoint9 waypoint5) (visible waypoint5 waypoint9)
         (at_soil_sample waypoint0) (at_soil_sample waypoint1)
         (at_rock_sample waypoint2) (at_soil_sample waypoint3)
         (at_soil_sample waypoint4) (at_soil_sample waypoint6)
         (at_rock_sample waypoint7) (at_soil_sample waypoint9)
         (at_rock_sample waypoint9) (at_lander general waypoint7)
         (channel_free general) (at rover0 waypoint6) (available rover0)
         (store_of rover0store rover0) (empty rover0store)
         (equipped_for_soil_analysis rover0)
         (equipped_for_rock_analysis rover0) (equipped_for_imaging rover0)
         (can_traverse rover0 waypoint6 waypoint0)
         (can_traverse rover0 waypoint0 waypoint6)
         (can_traverse rover0 waypoint6 waypoint1)
         (can_traverse rover0 waypoint1 waypoint6)
         (can_traverse rover0 waypoint6 waypoint2)
         (can_traverse rover0 waypoint2 waypoint6)
         (can_traverse rover0 waypoint6 waypoint5)
         (can_traverse rover0 waypoint5 waypoint6)
         (can_traverse rover0 waypoint6 waypoint7)
         (can_traverse rover0 waypoint7 waypoint6)
         (can_traverse rover0 waypoint6 waypoint8)
         (can_traverse rover0 waypoint8 waypoint6)
         (can_traverse rover0 waypoint0 waypoint4)
         (can_traverse rover0 waypoint4 waypoint0)
         (can_traverse rover0 waypoint0 waypoint9)
         (can_traverse rover0 waypoint9 waypoint0)
         (can_traverse rover0 waypoint1 waypoint3)
         (can_traverse rover0 waypoint3 waypoint1) (at rover1 waypoint3)
         (available rover1) (store_of rover1store rover1) (empty rover1store)
         (equipped_for_soil_analysis rover1)
         (can_traverse rover1 waypoint3 waypoint1)
         (can_traverse rover1 waypoint1 waypoint3)
         (can_traverse rover1 waypoint3 waypoint4)
         (can_traverse rover1 waypoint4 waypoint3)
         (can_traverse rover1 waypoint3 waypoint5)
         (can_traverse rover1 waypoint5 waypoint3)
         (can_traverse rover1 waypoint3 waypoint8)
         (can_traverse rover1 waypoint8 waypoint3)
         (can_traverse rover1 waypoint1 waypoint2)
         (can_traverse rover1 waypoint2 waypoint1)
         (can_traverse rover1 waypoint1 waypoint6)
         (can_traverse rover1 waypoint6 waypoint1)
         (can_traverse rover1 waypoint1 waypoint9)
         (can_traverse rover1 waypoint9 waypoint1)
         (can_traverse rover1 waypoint5 waypoint0)
         (can_traverse rover1 waypoint0 waypoint5)
         (can_traverse rover1 waypoint2 waypoint7)
         (can_traverse rover1 waypoint7 waypoint2) (on_board camera0 rover0)
         (calibration_target camera0 objective6) (supports camera0 colour)
         (visible_from objective0 waypoint0)
         (visible_from objective0 waypoint1)
         (visible_from objective1 waypoint0)
         (visible_from objective1 waypoint1)
         (visible_from objective1 waypoint2)
         (visible_from objective1 waypoint3)
         (visible_from objective2 waypoint0)
         (visible_from objective3 waypoint0)
         (visible_from objective3 waypoint1)
         (visible_from objective3 waypoint2)
         (visible_from objective3 waypoint3)
         (visible_from objective3 waypoint4)
         (visible_from objective3 waypoint5)
         (visible_from objective3 waypoint6)
         (visible_from objective4 waypoint0)
         (visible_from objective4 waypoint1)
         (visible_from objective4 waypoint2)
         (visible_from objective4 waypoint3)
         (visible_from objective4 waypoint4)
         (visible_from objective4 waypoint5)
         (visible_from objective4 waypoint6)
         (visible_from objective5 waypoint0)
         (visible_from objective5 waypoint1)
         (visible_from objective5 waypoint2)
         (visible_from objective5 waypoint3)
         (visible_from objective5 waypoint4)
         (visible_from objective5 waypoint5)
         (visible_from objective5 waypoint6)
         (visible_from objective5 waypoint7)
         (visible_from objective6 waypoint0)
         (visible_from objective6 waypoint1)
         (visible_from objective6 waypoint2)
         (visible_from objective6 waypoint3)
         (visible_from objective6 waypoint4)
         (visible_from objective6 waypoint5)
         (visible_from objective6 waypoint6)
         (visible_from objective6 waypoint7)
         (visible_from objective6 waypoint8)
         (visible_from objective7 waypoint0)
         (visible_from objective7 waypoint1)
         (visible_from objective7 waypoint2)
         (visible_from objective7 waypoint3)
         (visible_from objective7 waypoint4)
         (visible_from objective7 waypoint5)
         (visible_from objective7 waypoint6)
         (visible_from objective7 waypoint7)
         (visible_from objective7 waypoint8)
         (visible_from objective7 waypoint9)
         (visible_from objective8 waypoint0)
         (visible_from objective9 waypoint0)
         (visible_from objective9 waypoint1)
         (visible_from objective9 waypoint2)
         (visible_from objective9 waypoint3)
         (visible_from objective9 waypoint4)
         (visible_from objective9 waypoint5)
         (visible_from objective9 waypoint6)
         (= (traverse_cost rover0 waypoint6 waypoint0) 72.1)
         (= (traverse_cost rover0 waypoint0 waypoint6) 47.9)
         (= (traverse_cost rover0 waypoint6 waypoint1) 58.1)
         (= (traverse_cost rover0 waypoint1 waypoint6) 68.5)
         (= (traverse_cost rover0 waypoint6 waypoint2) 42.1)
         (= (traverse_cost rover0 waypoint2 waypoint6) 39.7)
         (= (traverse_cost rover0 waypoint6 waypoint5) 32.6)
         (= (traverse_cost rover0 waypoint5 waypoint6) 35.4)
         (= (traverse_cost rover0 waypoint6 waypoint7) 58.7)
         (= (traverse_cost rover0 waypoint7 waypoint6) 63.9)
         (= (traverse_cost rover0 waypoint6 waypoint8) 54.4)
         (= (traverse_cost rover0 waypoint8 waypoint6) 65.2)
         (= (traverse_cost rover0 waypoint0 waypoint4) 47.3)
         (= (traverse_cost rover0 waypoint4 waypoint0) 82.4)
         (= (traverse_cost rover0 waypoint0 waypoint9) 60.6)
         (= (traverse_cost rover0 waypoint9 waypoint0) 59.7)
         (= (traverse_cost rover0 waypoint1 waypoint3) 32.5)
         (= (traverse_cost rover0 waypoint3 waypoint1) 40)
         (= (traverse_cost rover1 waypoint3 waypoint1) 79.5)
         (= (traverse_cost rover1 waypoint1 waypoint3) 50.2)
         (= (traverse_cost rover1 waypoint3 waypoint4) 46.3)
         (= (traverse_cost rover1 waypoint4 waypoint3) 48)
         (= (traverse_cost rover1 waypoint3 waypoint5) 52.3)
         (= (traverse_cost rover1 waypoint5 waypoint3) 67.9)
         (= (traverse_cost rover1 waypoint3 waypoint8) 52.6)
         (= (traverse_cost rover1 waypoint8 waypoint3) 28.7)
         (= (traverse_cost rover1 waypoint1 waypoint2) 37.3)
         (= (traverse_cost rover1 waypoint2 waypoint1) 36.5)
         (= (traverse_cost rover1 waypoint1 waypoint6) 75)
         (= (traverse_cost rover1 waypoint6 waypoint1) 41.3)
         (= (traverse_cost rover1 waypoint1 waypoint9) 58.5)
         (= (traverse_cost rover1 waypoint9 waypoint1) 49.3)
         (= (traverse_cost rover1 waypoint5 waypoint0) 27.5)
         (= (traverse_cost rover1 waypoint0 waypoint5) 22.6)
         (= (traverse_cost rover1 waypoint2 waypoint7) 29)
         (= (traverse_cost rover1 waypoint7 waypoint2) 28.7)
         (= (sum-traverse-cost) 0))
        (:goal
         (and (preference g0 (communicated_soil_data waypoint9))
              (preference g1 (communicated_soil_data waypoint4))
              (preference g2 (communicated_rock_data waypoint9))
              (preference g3 (communicated_rock_data waypoint7))
              (preference g4 (communicated_rock_data waypoint2))
              (preference g5 (communicated_image_data objective7 colour))
              (preference g6 (communicated_image_data objective4 colour))
              (preference g7 (communicated_image_data objective2 colour))))
        (:metric minimize
         (+ (* (is-violated g7) 94.2)
            (* (is-violated g6) 37)
            (* (is-violated g5) 35.3)
            (* (is-violated g4) 61.4)
            (* (is-violated g3) 91.9)
            (* (is-violated g2) 159.3)
            (* (is-violated g1) 172.5)
            (* (is-violated g0) 144)
            (sum-traverse-cost))))
