(define (domain grounded-STRIPS-PROTOCOL)
(:requirements
:strips
)
(:predicates
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-WFORK)
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-WFORK)
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-WFORK)
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-WFORK)
(ENABLED-PHILOSOPHER-3-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-3-)
(QUEUE-TAIL-MSG-FORKS-3--FORK)
(ENABLED-PHILOSOPHER-2-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-2-)
(QUEUE-TAIL-MSG-FORKS-2--FORK)
(ENABLED-PHILOSOPHER-1-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-1-)
(QUEUE-TAIL-MSG-FORKS-1--FORK)
(ENABLED-PHILOSOPHER-0-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-0-)
(QUEUE-TAIL-MSG-FORKS-0--FORK)
(QUEUE-MSG-FORKS-3--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-3--FORK)
(QUEUE-SIZE-FORKS-3--ONE)
(QUEUE-MSG-FORKS-2--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-2--FORK)
(QUEUE-SIZE-FORKS-2--ONE)
(QUEUE-MSG-FORKS-1--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-1--FORK)
(QUEUE-SIZE-FORKS-1--ONE)
(QUEUE-MSG-FORKS-0--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-0--FORK)
(QUEUE-SIZE-FORKS-0--ONE)
(AT-PROCESS-PHILOSOPHER-0-STATE-6)
(AT-PROCESS-PHILOSOPHER-1-STATE-6)
(AT-PROCESS-PHILOSOPHER-2-STATE-6)
(AT-PROCESS-PHILOSOPHER-3-STATE-6)
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-RFORK)
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-RFORK)
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-RFORK)
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-RFORK)
(ADVANCE-HEAD-FORKS-3-)
(ENABLED-PHILOSOPHER-3-FORKS--PID-RFORK)
(ADVANCE-HEAD-FORKS-2-)
(ENABLED-PHILOSOPHER-2-FORKS--PID-RFORK)
(ADVANCE-HEAD-FORKS-1-)
(ENABLED-PHILOSOPHER-1-FORKS--PID-RFORK)
(ADVANCE-HEAD-FORKS-0-)
(ENABLED-PHILOSOPHER-0-FORKS--PID-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-0-STATE-3)
(AT-PROCESS-PHILOSOPHER-1-STATE-3)
(AT-PROCESS-PHILOSOPHER-2-STATE-3)
(AT-PROCESS-PHILOSOPHER-3-STATE-3)
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK)
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK)
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK)
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK)
(BLOCKED-PHILOSOPHER-0)
(BLOCKED-PHILOSOPHER-1)
(BLOCKED-PHILOSOPHER-2)
(BLOCKED-PHILOSOPHER-3)
(ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK)
(ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK)
(ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK)
(ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK)
(AT-PROCESS-PHILOSOPHER-0-STATE-4)
(AT-PROCESS-PHILOSOPHER-1-STATE-4)
(AT-PROCESS-PHILOSOPHER-2-STATE-4)
(AT-PROCESS-PHILOSOPHER-3-STATE-4)
(AT-PROCESS-PHILOSOPHER-0-STATE-5)
(AT-PROCESS-PHILOSOPHER-1-STATE-5)
(AT-PROCESS-PHILOSOPHER-2-STATE-5)
(AT-PROCESS-PHILOSOPHER-3-STATE-5)
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK)
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK)
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK)
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK)
(ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK)
(ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK)
(ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK)
(ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-0-)
(PENDING-PHILOSOPHER-0)
(PENDING-PHILOSOPHER-1)
(PENDING-PHILOSOPHER-2)
(PENDING-PHILOSOPHER-3)
(QUEUE-HEAD-FORKS-0--QS-0)
(QUEUE-HEAD-FORKS-1--QS-0)
(QUEUE-HEAD-FORKS-2--QS-0)
(QUEUE-HEAD-FORKS-3--QS-0)
(AT-PROCESS-PHILOSOPHER-3-STATE-1)
(AT-PROCESS-PHILOSOPHER-2-STATE-1)
(AT-PROCESS-PHILOSOPHER-1-STATE-1)
(AT-PROCESS-PHILOSOPHER-0-STATE-1)
(QUEUE-TAIL-FORKS-0--QS-0)
(QUEUE-SIZE-FORKS-0--ZERO)
(QUEUE-HEAD-MSG-FORKS-0--EMPTY)
(QUEUE-TAIL-FORKS-1--QS-0)
(QUEUE-SIZE-FORKS-1--ZERO)
(QUEUE-HEAD-MSG-FORKS-1--EMPTY)
(QUEUE-TAIL-FORKS-2--QS-0)
(QUEUE-SIZE-FORKS-2--ZERO)
(QUEUE-HEAD-MSG-FORKS-2--EMPTY)
(QUEUE-TAIL-FORKS-3--QS-0)
(QUEUE-SIZE-FORKS-3--ZERO)
(QUEUE-HEAD-MSG-FORKS-3--EMPTY)
)
(:action BLOCK-PHILOSOPHER-3-STATE-5-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-5)
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-3)
)
)
(:action BLOCK-PHILOSOPHER-2-STATE-5-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-5)
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-2)
)
)
(:action BLOCK-PHILOSOPHER-1-STATE-5-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-5)
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-1)
)
)
(:action BLOCK-PHILOSOPHER-0-STATE-5-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-5)
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-0)
)
)
(:action PERFORM-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS-__-PIDP1__4_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-5)
(ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-6)
(PENDING-PHILOSOPHER-3)
(not (AT-PROCESS-PHILOSOPHER-3-STATE-5))
(not (ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS-__-PIDP1__4_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-5)
(ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-6)
(PENDING-PHILOSOPHER-2)
(not (AT-PROCESS-PHILOSOPHER-2-STATE-5))
(not (ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS-__-PIDP1__4_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-5)
(ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-6)
(PENDING-PHILOSOPHER-1)
(not (AT-PROCESS-PHILOSOPHER-1-STATE-5))
(not (ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS-__-PIDP1__4_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-5)
(ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-6)
(PENDING-PHILOSOPHER-0)
(not (AT-PROCESS-PHILOSOPHER-0-STATE-5))
(not (ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK-FORKS-1--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK)
(ADVANCE-TAIL-FORKS-1-)
(QUEUE-TAIL-MSG-FORKS-1--FORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (SETTLED-FORKS-1-))
(not (ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK-FORKS-2--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK)
(ADVANCE-TAIL-FORKS-2-)
(QUEUE-TAIL-MSG-FORKS-2--FORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (SETTLED-FORKS-2-))
(not (ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK-FORKS-3--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK)
(ADVANCE-TAIL-FORKS-3-)
(QUEUE-TAIL-MSG-FORKS-3--FORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (SETTLED-FORKS-3-))
(not (ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK-FORKS-0--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK)
(ADVANCE-TAIL-FORKS-0-)
(QUEUE-TAIL-MSG-FORKS-0--FORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (SETTLED-FORKS-0-))
(not (ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
)
)
(:action BLOCK-WRITE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK-FORKS-0--QUEUE-1-FORK-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-0--ONE)
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK)
(not (ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (SETTLED-FORKS-0-))
)
)
(:action BLOCK-WRITE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK-FORKS-1--QUEUE-1-FORK-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-1--ONE)
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK)
(not (ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (SETTLED-FORKS-1-))
)
)
(:action BLOCK-WRITE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK-FORKS-2--QUEUE-1-FORK-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-2--ONE)
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK)
(not (ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (SETTLED-FORKS-2-))
)
)
(:action BLOCK-WRITE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK-FORKS-3--QUEUE-1-FORK-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-3--ONE)
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK)
(not (ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (SETTLED-FORKS-3-))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS-__-PIDP1__4_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-0)
(AT-PROCESS-PHILOSOPHER-0-STATE-5)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK)
(not (PENDING-PHILOSOPHER-0))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS-__-PIDP1__4_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-1)
(AT-PROCESS-PHILOSOPHER-1-STATE-5)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK)
(not (PENDING-PHILOSOPHER-1))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS-__-PIDP1__4_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-2)
(AT-PROCESS-PHILOSOPHER-2-STATE-5)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK)
(not (PENDING-PHILOSOPHER-2))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS-__-PIDP1__4_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-3)
(AT-PROCESS-PHILOSOPHER-3-STATE-5)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK)
(not (PENDING-PHILOSOPHER-3))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-4)
(ENABLED-PHILOSOPHER-3-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-5)
(PENDING-PHILOSOPHER-3)
(not (AT-PROCESS-PHILOSOPHER-3-STATE-4))
(not (ENABLED-PHILOSOPHER-3-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-4)
(ENABLED-PHILOSOPHER-2-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-5)
(PENDING-PHILOSOPHER-2)
(not (AT-PROCESS-PHILOSOPHER-2-STATE-4))
(not (ENABLED-PHILOSOPHER-2-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-4)
(ENABLED-PHILOSOPHER-1-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-5)
(PENDING-PHILOSOPHER-1)
(not (AT-PROCESS-PHILOSOPHER-1-STATE-4))
(not (ENABLED-PHILOSOPHER-1-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-4)
(ENABLED-PHILOSOPHER-0-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-5)
(PENDING-PHILOSOPHER-0)
(not (AT-PROCESS-PHILOSOPHER-0-STATE-4))
(not (ENABLED-PHILOSOPHER-0-FORKS--PID-WFORK))
)
)
(:action BLOCK-PHILOSOPHER-3-STATE-4-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-4)
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-3)
)
)
(:action BLOCK-PHILOSOPHER-3-STATE-3-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-3)
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-3)
)
)
(:action BLOCK-PHILOSOPHER-2-STATE-4-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-4)
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-2)
)
)
(:action BLOCK-PHILOSOPHER-2-STATE-3-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-3)
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-2)
)
)
(:action BLOCK-PHILOSOPHER-1-STATE-4-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-4)
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-1)
)
)
(:action BLOCK-PHILOSOPHER-1-STATE-3-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-3)
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-1)
)
)
(:action BLOCK-PHILOSOPHER-0-STATE-4-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-4)
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-0)
)
)
(:action BLOCK-PHILOSOPHER-0-STATE-3-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-3)
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-0)
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-0)
(AT-PROCESS-PHILOSOPHER-0-STATE-4)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-0))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-1)
(AT-PROCESS-PHILOSOPHER-1-STATE-4)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-1))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-2)
(AT-PROCESS-PHILOSOPHER-2-STATE-4)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-2))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-3)
(AT-PROCESS-PHILOSOPHER-3-STATE-4)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-3))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS-__-PIDP1__4_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-3)
(ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-4)
(PENDING-PHILOSOPHER-3)
(not (AT-PROCESS-PHILOSOPHER-3-STATE-3))
(not (ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS-__-PIDP1__4_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-3)
(ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-4)
(PENDING-PHILOSOPHER-2)
(not (AT-PROCESS-PHILOSOPHER-2-STATE-3))
(not (ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS-__-PIDP1__4_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-3)
(ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-4)
(PENDING-PHILOSOPHER-1)
(not (AT-PROCESS-PHILOSOPHER-1-STATE-3))
(not (ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS-__-PIDP1__4_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-3)
(ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-4)
(PENDING-PHILOSOPHER-0)
(not (AT-PROCESS-PHILOSOPHER-0-STATE-3))
(not (ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
)
)
(:action BLOCK-READ-WRONG-MESSAGE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK-FORKS-1--FORK-EMPTY-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-1--EMPTY)
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK)
(not (ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (SETTLED-FORKS-1-))
)
)
(:action BLOCK-READ-WRONG-MESSAGE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK-FORKS-2--FORK-EMPTY-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-2--EMPTY)
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK)
(not (ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (SETTLED-FORKS-2-))
)
)
(:action BLOCK-READ-WRONG-MESSAGE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK-FORKS-3--FORK-EMPTY-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-3--EMPTY)
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK)
(not (ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (SETTLED-FORKS-3-))
)
)
(:action BLOCK-READ-WRONG-MESSAGE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK-FORKS-0--FORK-EMPTY-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-0--EMPTY)
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK)
(not (ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (SETTLED-FORKS-0-))
)
)
(:action BLOCK-READ-QUEUE-EMPTY-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK-FORKS-1--FORK-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-1--ZERO)
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK)
(not (ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (SETTLED-FORKS-1-))
)
)
(:action BLOCK-READ-QUEUE-EMPTY-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK-FORKS-2--FORK-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-2--ZERO)
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK)
(not (ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (SETTLED-FORKS-2-))
)
)
(:action BLOCK-READ-QUEUE-EMPTY-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK-FORKS-3--FORK-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-3--ZERO)
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK)
(not (ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (SETTLED-FORKS-3-))
)
)
(:action BLOCK-READ-QUEUE-EMPTY-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK-FORKS-0--FORK-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-0--ZERO)
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK)
(not (ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (SETTLED-FORKS-0-))
)
)
(:action QUEUE-READ-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK-FORKS-1--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-1--FORK)
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-1-)
(ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (SETTLED-FORKS-1-))
)
)
(:action QUEUE-READ-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK-FORKS-2--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-2--FORK)
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-2-)
(ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (SETTLED-FORKS-2-))
)
)
(:action QUEUE-READ-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK-FORKS-3--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-3--FORK)
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-3-)
(ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (SETTLED-FORKS-3-))
)
)
(:action QUEUE-READ-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK-FORKS-0--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-0--FORK)
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-0-)
(ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (SETTLED-FORKS-0-))
)
)
(:action BLOCK-PHILOSOPHER-3-STATE-6-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-6)
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-3)
)
)
(:action BLOCK-PHILOSOPHER-3-STATE-1-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-1)
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-3)
)
)
(:action BLOCK-PHILOSOPHER-2-STATE-6-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-6)
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-2)
)
)
(:action BLOCK-PHILOSOPHER-2-STATE-1-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-1)
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-2)
)
)
(:action BLOCK-PHILOSOPHER-1-STATE-6-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-6)
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-1)
)
)
(:action BLOCK-PHILOSOPHER-1-STATE-1-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-1)
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-1)
)
)
(:action BLOCK-PHILOSOPHER-0-STATE-6-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-6)
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-0)
)
)
(:action BLOCK-PHILOSOPHER-0-STATE-1-PHILOSOPHER-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-1)
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK)
)
:effect
(and
(BLOCKED-PHILOSOPHER-0)
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS-__-PIDP1__4_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-0)
(AT-PROCESS-PHILOSOPHER-0-STATE-3)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK)
(not (PENDING-PHILOSOPHER-0))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS-__-PIDP1__4_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-1)
(AT-PROCESS-PHILOSOPHER-1-STATE-3)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK)
(not (PENDING-PHILOSOPHER-1))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS-__-PIDP1__4_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-2)
(AT-PROCESS-PHILOSOPHER-2-STATE-3)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK)
(not (PENDING-PHILOSOPHER-2))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS-__-PIDP1__4_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-3)
(AT-PROCESS-PHILOSOPHER-3-STATE-3)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK)
(not (PENDING-PHILOSOPHER-3))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-6)
(ENABLED-PHILOSOPHER-3-FORKS--PID-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-3)
(PENDING-PHILOSOPHER-3)
(not (AT-PROCESS-PHILOSOPHER-3-STATE-6))
(not (ENABLED-PHILOSOPHER-3-FORKS--PID-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-6)
(ENABLED-PHILOSOPHER-2-FORKS--PID-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-3)
(PENDING-PHILOSOPHER-2)
(not (AT-PROCESS-PHILOSOPHER-2-STATE-6))
(not (ENABLED-PHILOSOPHER-2-FORKS--PID-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-6)
(ENABLED-PHILOSOPHER-1-FORKS--PID-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-3)
(PENDING-PHILOSOPHER-1)
(not (AT-PROCESS-PHILOSOPHER-1-STATE-6))
(not (ENABLED-PHILOSOPHER-1-FORKS--PID-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-6)
(ENABLED-PHILOSOPHER-0-FORKS--PID-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-3)
(PENDING-PHILOSOPHER-0)
(not (AT-PROCESS-PHILOSOPHER-0-STATE-6))
(not (ENABLED-PHILOSOPHER-0-FORKS--PID-RFORK))
)
)
(:action ADVANCE-QUEUE-HEAD-FORKS-0--QUEUE-1-QS-0-QS-0-FORK-ONE-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-0--ONE)
(QUEUE-MSG-FORKS-0--QS-0-FORK)
(ADVANCE-HEAD-FORKS-0-)
(QUEUE-HEAD-FORKS-0--QS-0)
)
:effect
(and
(SETTLED-FORKS-0-)
(QUEUE-HEAD-FORKS-0--QS-0)
(QUEUE-HEAD-MSG-FORKS-0--FORK)
(QUEUE-SIZE-FORKS-0--ZERO)
(not (ADVANCE-HEAD-FORKS-0-))
(not (QUEUE-SIZE-FORKS-0--ONE))
)
)
(:action ADVANCE-QUEUE-HEAD-FORKS-1--QUEUE-1-QS-0-QS-0-FORK-ONE-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-1--ONE)
(QUEUE-MSG-FORKS-1--QS-0-FORK)
(ADVANCE-HEAD-FORKS-1-)
(QUEUE-HEAD-FORKS-1--QS-0)
)
:effect
(and
(SETTLED-FORKS-1-)
(QUEUE-HEAD-FORKS-1--QS-0)
(QUEUE-HEAD-MSG-FORKS-1--FORK)
(QUEUE-SIZE-FORKS-1--ZERO)
(not (ADVANCE-HEAD-FORKS-1-))
(not (QUEUE-SIZE-FORKS-1--ONE))
)
)
(:action ADVANCE-QUEUE-HEAD-FORKS-2--QUEUE-1-QS-0-QS-0-FORK-ONE-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-2--ONE)
(QUEUE-MSG-FORKS-2--QS-0-FORK)
(ADVANCE-HEAD-FORKS-2-)
(QUEUE-HEAD-FORKS-2--QS-0)
)
:effect
(and
(SETTLED-FORKS-2-)
(QUEUE-HEAD-FORKS-2--QS-0)
(QUEUE-HEAD-MSG-FORKS-2--FORK)
(QUEUE-SIZE-FORKS-2--ZERO)
(not (ADVANCE-HEAD-FORKS-2-))
(not (QUEUE-SIZE-FORKS-2--ONE))
)
)
(:action ADVANCE-QUEUE-HEAD-FORKS-3--QUEUE-1-QS-0-QS-0-FORK-ONE-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-3--ONE)
(QUEUE-MSG-FORKS-3--QS-0-FORK)
(ADVANCE-HEAD-FORKS-3-)
(QUEUE-HEAD-FORKS-3--QS-0)
)
:effect
(and
(SETTLED-FORKS-3-)
(QUEUE-HEAD-FORKS-3--QS-0)
(QUEUE-HEAD-MSG-FORKS-3--FORK)
(QUEUE-SIZE-FORKS-3--ZERO)
(not (ADVANCE-HEAD-FORKS-3-))
(not (QUEUE-SIZE-FORKS-3--ONE))
)
)
(:action BLOCK-READ-WRONG-MESSAGE-PHILOSOPHER-0-FORKS--PID-RFORK-FORKS-0--FORK-EMPTY-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-0--EMPTY)
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK)
(not (ENABLED-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (ACTIVATE-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (SETTLED-FORKS-0-))
)
)
(:action BLOCK-READ-WRONG-MESSAGE-PHILOSOPHER-1-FORKS--PID-RFORK-FORKS-1--FORK-EMPTY-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-1--EMPTY)
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK)
(not (ENABLED-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (ACTIVATE-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (SETTLED-FORKS-1-))
)
)
(:action BLOCK-READ-WRONG-MESSAGE-PHILOSOPHER-2-FORKS--PID-RFORK-FORKS-2--FORK-EMPTY-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-2--EMPTY)
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK)
(not (ENABLED-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (ACTIVATE-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (SETTLED-FORKS-2-))
)
)
(:action BLOCK-READ-WRONG-MESSAGE-PHILOSOPHER-3-FORKS--PID-RFORK-FORKS-3--FORK-EMPTY-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-3--EMPTY)
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK)
(not (ENABLED-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (ACTIVATE-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (SETTLED-FORKS-3-))
)
)
(:action BLOCK-WRITE-PHILOSOPHER-0-FORKS--PID-WFORK-FORKS-0--QUEUE-1-FORK-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-0--ONE)
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-WFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK)
(not (ENABLED-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (ACTIVATE-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (SETTLED-FORKS-0-))
)
)
(:action BLOCK-WRITE-PHILOSOPHER-1-FORKS--PID-WFORK-FORKS-1--QUEUE-1-FORK-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-1--ONE)
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-WFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK)
(not (ENABLED-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (ACTIVATE-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (SETTLED-FORKS-1-))
)
)
(:action BLOCK-WRITE-PHILOSOPHER-2-FORKS--PID-WFORK-FORKS-2--QUEUE-1-FORK-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-2--ONE)
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-WFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK)
(not (ENABLED-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (ACTIVATE-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (SETTLED-FORKS-2-))
)
)
(:action BLOCK-WRITE-PHILOSOPHER-3-FORKS--PID-WFORK-FORKS-3--QUEUE-1-FORK-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-3--ONE)
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-WFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK)
(not (ENABLED-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (ACTIVATE-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (SETTLED-FORKS-3-))
)
)
(:action BLOCK-READ-QUEUE-EMPTY-PHILOSOPHER-0-FORKS--PID-RFORK-FORKS-0--FORK-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-0--ZERO)
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK)
(not (ENABLED-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (ACTIVATE-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (SETTLED-FORKS-0-))
)
)
(:action BLOCK-READ-QUEUE-EMPTY-PHILOSOPHER-1-FORKS--PID-RFORK-FORKS-1--FORK-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-1--ZERO)
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK)
(not (ENABLED-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (ACTIVATE-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (SETTLED-FORKS-1-))
)
)
(:action BLOCK-READ-QUEUE-EMPTY-PHILOSOPHER-2-FORKS--PID-RFORK-FORKS-2--FORK-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-2--ZERO)
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK)
(not (ENABLED-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (ACTIVATE-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (SETTLED-FORKS-2-))
)
)
(:action BLOCK-READ-QUEUE-EMPTY-PHILOSOPHER-3-FORKS--PID-RFORK-FORKS-3--FORK-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-3--ZERO)
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-RFORK)
)
:effect
(and
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK)
(not (ENABLED-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (ACTIVATE-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (SETTLED-FORKS-3-))
)
)
(:action QUEUE-READ-PHILOSOPHER-0-FORKS--PID-RFORK-FORKS-0--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-0--FORK)
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-0-)
(ENABLED-PHILOSOPHER-0-FORKS--PID-RFORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (ACTIVATE-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (SETTLED-FORKS-0-))
)
)
(:action QUEUE-READ-PHILOSOPHER-1-FORKS--PID-RFORK-FORKS-1--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-1--FORK)
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-1-)
(ENABLED-PHILOSOPHER-1-FORKS--PID-RFORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (ACTIVATE-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (SETTLED-FORKS-1-))
)
)
(:action QUEUE-READ-PHILOSOPHER-2-FORKS--PID-RFORK-FORKS-2--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-2--FORK)
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-2-)
(ENABLED-PHILOSOPHER-2-FORKS--PID-RFORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (ACTIVATE-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (SETTLED-FORKS-2-))
)
)
(:action QUEUE-READ-PHILOSOPHER-3-FORKS--PID-RFORK-FORKS-3--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-3--FORK)
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-3-)
(ENABLED-PHILOSOPHER-3-FORKS--PID-RFORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (ACTIVATE-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (SETTLED-FORKS-3-))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-0)
(AT-PROCESS-PHILOSOPHER-0-STATE-6)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-RFORK)
(not (PENDING-PHILOSOPHER-0))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-1)
(AT-PROCESS-PHILOSOPHER-1-STATE-6)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-RFORK)
(not (PENDING-PHILOSOPHER-1))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-2)
(AT-PROCESS-PHILOSOPHER-2-STATE-6)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-RFORK)
(not (PENDING-PHILOSOPHER-2))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-3)
(AT-PROCESS-PHILOSOPHER-3-STATE-6)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-RFORK)
(not (PENDING-PHILOSOPHER-3))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-1)
(ENABLED-PHILOSOPHER-3-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-6)
(PENDING-PHILOSOPHER-3)
(not (AT-PROCESS-PHILOSOPHER-3-STATE-1))
(not (ENABLED-PHILOSOPHER-3-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-1)
(ENABLED-PHILOSOPHER-2-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-6)
(PENDING-PHILOSOPHER-2)
(not (AT-PROCESS-PHILOSOPHER-2-STATE-1))
(not (ENABLED-PHILOSOPHER-2-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-1)
(ENABLED-PHILOSOPHER-1-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-6)
(PENDING-PHILOSOPHER-1)
(not (AT-PROCESS-PHILOSOPHER-1-STATE-1))
(not (ENABLED-PHILOSOPHER-1-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-1)
(ENABLED-PHILOSOPHER-0-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-6)
(PENDING-PHILOSOPHER-0)
(not (AT-PROCESS-PHILOSOPHER-0-STATE-1))
(not (ENABLED-PHILOSOPHER-0-FORKS--PID-WFORK))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-0--QUEUE-1-QS-0-QS-0-FORK-FORK-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-0--ZERO)
(QUEUE-HEAD-MSG-FORKS-0--FORK)
(QUEUE-TAIL-MSG-FORKS-0--FORK)
(ADVANCE-TAIL-FORKS-0-)
(QUEUE-TAIL-FORKS-0--QS-0)
)
:effect
(and
(SETTLED-FORKS-0-)
(QUEUE-TAIL-FORKS-0--QS-0)
(QUEUE-MSG-FORKS-0--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-0--FORK)
(QUEUE-SIZE-FORKS-0--ONE)
(not (ADVANCE-TAIL-FORKS-0-))
(not (QUEUE-SIZE-FORKS-0--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-0--QUEUE-1-QS-0-QS-0-FORK-EMPTY-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-0--ZERO)
(QUEUE-HEAD-MSG-FORKS-0--EMPTY)
(QUEUE-TAIL-MSG-FORKS-0--FORK)
(ADVANCE-TAIL-FORKS-0-)
(QUEUE-TAIL-FORKS-0--QS-0)
)
:effect
(and
(SETTLED-FORKS-0-)
(QUEUE-TAIL-FORKS-0--QS-0)
(QUEUE-MSG-FORKS-0--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-0--FORK)
(QUEUE-SIZE-FORKS-0--ONE)
(not (ADVANCE-TAIL-FORKS-0-))
(not (QUEUE-HEAD-MSG-FORKS-0--EMPTY))
(not (QUEUE-SIZE-FORKS-0--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-1--QUEUE-1-QS-0-QS-0-FORK-FORK-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-1--ZERO)
(QUEUE-HEAD-MSG-FORKS-1--FORK)
(QUEUE-TAIL-MSG-FORKS-1--FORK)
(ADVANCE-TAIL-FORKS-1-)
(QUEUE-TAIL-FORKS-1--QS-0)
)
:effect
(and
(SETTLED-FORKS-1-)
(QUEUE-TAIL-FORKS-1--QS-0)
(QUEUE-MSG-FORKS-1--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-1--FORK)
(QUEUE-SIZE-FORKS-1--ONE)
(not (ADVANCE-TAIL-FORKS-1-))
(not (QUEUE-SIZE-FORKS-1--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-1--QUEUE-1-QS-0-QS-0-FORK-EMPTY-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-1--ZERO)
(QUEUE-HEAD-MSG-FORKS-1--EMPTY)
(QUEUE-TAIL-MSG-FORKS-1--FORK)
(ADVANCE-TAIL-FORKS-1-)
(QUEUE-TAIL-FORKS-1--QS-0)
)
:effect
(and
(SETTLED-FORKS-1-)
(QUEUE-TAIL-FORKS-1--QS-0)
(QUEUE-MSG-FORKS-1--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-1--FORK)
(QUEUE-SIZE-FORKS-1--ONE)
(not (ADVANCE-TAIL-FORKS-1-))
(not (QUEUE-HEAD-MSG-FORKS-1--EMPTY))
(not (QUEUE-SIZE-FORKS-1--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-2--QUEUE-1-QS-0-QS-0-FORK-FORK-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-2--ZERO)
(QUEUE-HEAD-MSG-FORKS-2--FORK)
(QUEUE-TAIL-MSG-FORKS-2--FORK)
(ADVANCE-TAIL-FORKS-2-)
(QUEUE-TAIL-FORKS-2--QS-0)
)
:effect
(and
(SETTLED-FORKS-2-)
(QUEUE-TAIL-FORKS-2--QS-0)
(QUEUE-MSG-FORKS-2--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-2--FORK)
(QUEUE-SIZE-FORKS-2--ONE)
(not (ADVANCE-TAIL-FORKS-2-))
(not (QUEUE-SIZE-FORKS-2--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-2--QUEUE-1-QS-0-QS-0-FORK-EMPTY-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-2--ZERO)
(QUEUE-HEAD-MSG-FORKS-2--EMPTY)
(QUEUE-TAIL-MSG-FORKS-2--FORK)
(ADVANCE-TAIL-FORKS-2-)
(QUEUE-TAIL-FORKS-2--QS-0)
)
:effect
(and
(SETTLED-FORKS-2-)
(QUEUE-TAIL-FORKS-2--QS-0)
(QUEUE-MSG-FORKS-2--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-2--FORK)
(QUEUE-SIZE-FORKS-2--ONE)
(not (ADVANCE-TAIL-FORKS-2-))
(not (QUEUE-HEAD-MSG-FORKS-2--EMPTY))
(not (QUEUE-SIZE-FORKS-2--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-3--QUEUE-1-QS-0-QS-0-FORK-FORK-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-3--ZERO)
(QUEUE-HEAD-MSG-FORKS-3--FORK)
(QUEUE-TAIL-MSG-FORKS-3--FORK)
(ADVANCE-TAIL-FORKS-3-)
(QUEUE-TAIL-FORKS-3--QS-0)
)
:effect
(and
(SETTLED-FORKS-3-)
(QUEUE-TAIL-FORKS-3--QS-0)
(QUEUE-MSG-FORKS-3--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-3--FORK)
(QUEUE-SIZE-FORKS-3--ONE)
(not (ADVANCE-TAIL-FORKS-3-))
(not (QUEUE-SIZE-FORKS-3--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-3--QUEUE-1-QS-0-QS-0-FORK-EMPTY-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-3--ZERO)
(QUEUE-HEAD-MSG-FORKS-3--EMPTY)
(QUEUE-TAIL-MSG-FORKS-3--FORK)
(ADVANCE-TAIL-FORKS-3-)
(QUEUE-TAIL-FORKS-3--QS-0)
)
:effect
(and
(SETTLED-FORKS-3-)
(QUEUE-TAIL-FORKS-3--QS-0)
(QUEUE-MSG-FORKS-3--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-3--FORK)
(QUEUE-SIZE-FORKS-3--ONE)
(not (ADVANCE-TAIL-FORKS-3-))
(not (QUEUE-HEAD-MSG-FORKS-3--EMPTY))
(not (QUEUE-SIZE-FORKS-3--ZERO))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-0-FORKS--PID-WFORK-FORKS-0--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-0-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-0-)
(QUEUE-TAIL-MSG-FORKS-0--FORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (SETTLED-FORKS-0-))
(not (ACTIVATE-PHILOSOPHER-0-FORKS--PID-WFORK))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-1-FORKS--PID-WFORK-FORKS-1--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-1-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-1-)
(QUEUE-TAIL-MSG-FORKS-1--FORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (SETTLED-FORKS-1-))
(not (ACTIVATE-PHILOSOPHER-1-FORKS--PID-WFORK))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-2-FORKS--PID-WFORK-FORKS-2--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-2-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-2-)
(QUEUE-TAIL-MSG-FORKS-2--FORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (SETTLED-FORKS-2-))
(not (ACTIVATE-PHILOSOPHER-2-FORKS--PID-WFORK))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-3-FORKS--PID-WFORK-FORKS-3--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-3-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-3-)
(QUEUE-TAIL-MSG-FORKS-3--FORK)
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-RFORK))
(not (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__4_-WFORK))
(not (BLOCKED-PHILOSOPHER-0))
(not (BLOCKED-PHILOSOPHER-1))
(not (BLOCKED-PHILOSOPHER-2))
(not (BLOCKED-PHILOSOPHER-3))
(not (SETTLED-FORKS-3-))
(not (ACTIVATE-PHILOSOPHER-3-FORKS--PID-WFORK))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-0)
(AT-PROCESS-PHILOSOPHER-0-STATE-1)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-0))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-1)
(AT-PROCESS-PHILOSOPHER-1-STATE-1)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-1))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-2)
(AT-PROCESS-PHILOSOPHER-2-STATE-1)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-2))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-3)
(AT-PROCESS-PHILOSOPHER-3-STATE-1)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-3))
)
)
)
