;Copyright 2018 The MITRE Corporation. All rights reserved. Approved for public release. Distribution unlimited 17-2122.
; For more information on CALDERA, the automated adversary emulation system, visit https://github.com/mitre/caldera or email attack@mitre.org
; This has 5 hosts, 2 user, 1 admin per host, 1 active account per host
(define (problem p5_hosts_trial_6)
(:domain caldera)
(:objects
    str__b str__bk str__e str__james str__x str__j str__o str__p str__bl str__br str__bq str__f str__q str__i str__bd str__bj str__v str__w str__bc str__bs str__mary str__bu str__alpha str__be - string
    num__27 num__19 num__13 num__40 num__20 num__41 num__34 num__12 num__33 num__26 - num
    id_gdomainuser id_cdomainuser - observeddomainuser
    id_cjrat id_cfrat id_btrat id_chrat id_cirat id_cgrat - observedrat
    id_bfhost id_yhost id_rhost id_khost id_bmhost - observedhost
    id_bzshare id_byshare id_bxshare id_bvshare id_bwshare - observedshare
    id_adomain - observeddomain
    id_ddomaincredential id_hdomaincredential - observeddomaincredential
    id_bntimedelta id_bgtimedelta id_stimedelta id_ztimedelta id_ltimedelta - observedtimedelta
    id_cdfile id_cafile id_cefile id_cbfile id_ccfile - observedfile
    id_clschtask id_cmschtask id_ckschtask id_coschtask id_cnschtask - observedschtask
)
(:init
    (knows id_btrat)
    (knows id_rhost)
    (knows_property id_btrat pexecutable)
    (knows_property id_btrat phost)
    (knows_property id_rhost pfqdn)
    (MEM_CACHED_DOMAIN_CREDS id_bfhost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_bmhost id_hdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_khost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_rhost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_yhost id_hdomaincredential)
    (MEM_DOMAIN_USER_ADMINS id_bfhost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_bmhost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_khost id_gdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_rhost id_gdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_yhost id_gdomainuser)
    (mem_hosts id_adomain id_bfhost)
    (mem_hosts id_adomain id_bmhost)
    (mem_hosts id_adomain id_khost)
    (mem_hosts id_adomain id_rhost)
    (mem_hosts id_adomain id_yhost)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (PROP_DC id_bfhost no)
    (PROP_DC id_bmhost no)
    (PROP_DC id_khost no)
    (PROP_DC id_rhost no)
    (PROP_DC id_yhost no)
    (PROP_DNS_DOMAIN id_adomain str__b)
    (PROP_DNS_DOMAIN_NAME id_bfhost str__bk)
    (PROP_DNS_DOMAIN_NAME id_bmhost str__br)
    (PROP_DNS_DOMAIN_NAME id_khost str__p)
    (PROP_DNS_DOMAIN_NAME id_rhost str__w)
    (PROP_DNS_DOMAIN_NAME id_yhost str__bd)
    (PROP_DOMAIN id_bfhost id_adomain)
    (PROP_DOMAIN id_bmhost id_adomain)
    (PROP_DOMAIN id_cdomainuser id_adomain)
    (PROP_DOMAIN id_ddomaincredential id_adomain)
    (PROP_DOMAIN id_gdomainuser id_adomain)
    (PROP_DOMAIN id_hdomaincredential id_adomain)
    (PROP_DOMAIN id_khost id_adomain)
    (PROP_DOMAIN id_rhost id_adomain)
    (PROP_DOMAIN id_yhost id_adomain)
    (prop_elevated id_btrat yes)
    (prop_executable id_btrat str__bu)
    (PROP_FQDN id_bfhost str__bl)
    (PROP_FQDN id_bmhost str__bs)
    (PROP_FQDN id_khost str__q)
    (PROP_FQDN id_rhost str__x)
    (PROP_FQDN id_yhost str__be)
    (prop_host id_bgtimedelta id_bfhost)
    (prop_host id_bntimedelta id_bmhost)
    (prop_host id_btrat id_rhost)
    (prop_host id_ltimedelta id_khost)
    (prop_host id_stimedelta id_rhost)
    (prop_host id_ztimedelta id_yhost)
    (PROP_HOSTNAME id_bfhost str__bj)
    (PROP_HOSTNAME id_bmhost str__bq)
    (PROP_HOSTNAME id_khost str__o)
    (PROP_HOSTNAME id_rhost str__v)
    (PROP_HOSTNAME id_yhost str__bc)
    (PROP_IS_GROUP id_cdomainuser no)
    (PROP_IS_GROUP id_gdomainuser no)
    (PROP_MICROSECONDS id_bgtimedelta num__33)
    (PROP_MICROSECONDS id_bntimedelta num__40)
    (PROP_MICROSECONDS id_ltimedelta num__12)
    (PROP_MICROSECONDS id_stimedelta num__19)
    (PROP_MICROSECONDS id_ztimedelta num__26)
    (PROP_PASSWORD id_ddomaincredential str__e)
    (PROP_PASSWORD id_hdomaincredential str__i)
    (PROP_SECONDS id_bgtimedelta num__34)
    (PROP_SECONDS id_bntimedelta num__41)
    (PROP_SECONDS id_ltimedelta num__13)
    (PROP_SECONDS id_stimedelta num__20)
    (PROP_SECONDS id_ztimedelta num__27)
    (PROP_SID id_cdomainuser str__f)
    (PROP_SID id_gdomainuser str__j)
    (PROP_TIMEDELTA id_bfhost id_bgtimedelta)
    (PROP_TIMEDELTA id_bmhost id_bntimedelta)
    (PROP_TIMEDELTA id_khost id_ltimedelta)
    (PROP_TIMEDELTA id_rhost id_stimedelta)
    (PROP_TIMEDELTA id_yhost id_ztimedelta)
    (PROP_USER id_ddomaincredential id_cdomainuser)
    (PROP_USER id_hdomaincredential id_gdomainuser)
    (PROP_USERNAME id_cdomainuser str__james)
    (PROP_USERNAME id_gdomainuser str__mary)
    (PROP_WINDOWS_DOMAIN id_adomain str__alpha)
)
(:goal
(and
    (prop_host id_cgrat id_bmhost)
    (prop_host id_cjrat id_khost)
    (prop_host id_chrat id_bfhost)
    (prop_host id_cfrat id_yhost)
)
)
)