;Copyright 2018 The MITRE Corporation. All rights reserved. Approved for public release. Distribution unlimited 17-2122.
; For more information on CALDERA, the automated adversary emulation system, visit https://github.com/mitre/caldera or email attack@mitre.org
; This has 7 hosts, 14 user, 2 admin per host, 2 active account per host
(define (problem p7_hosts_trial_11)
(:domain caldera)
(:objects
    id_kdomainuser id_bedomainuser id_sdomainuser id_badomainuser id_bydomainuser id_gdomainuser id_cdomainuser id_bmdomainuser id_bqdomainuser id_wdomainuser id_odomainuser id_bidomainuser id_budomainuser id_ccdomainuser - observeddomainuser
    id_esfile id_enfile id_eofile id_eqfile id_epfile id_emfile id_erfile - observedfile
    id_dbhost id_dihost id_dphost id_cghost id_cnhost id_cuhost id_dwhost - observedhost
    id_etshare id_eyshare id_evshare id_ezshare id_exshare id_ewshare id_eushare - observedshare
    id_ekrat id_eirat id_elrat id_edrat id_egrat id_ehrat id_ejrat id_efrat - observedrat
    id_cotimedelta id_djtimedelta id_dqtimedelta id_dctimedelta id_chtimedelta id_dxtimedelta id_cvtimedelta - observedtimedelta
    id_adomain - observeddomain
    str__bp str__ce str__df str__bs str__cm str__bt str__james str__z str__bh str__william str__cz str__m str__dv str__bk str__cf str__maria str__bw str__dg str__cs str__ee str__bc str__bo str__dh str__david str__eb str__ca str__dt str__patricia str__alpha str__dm str__linda str__michael str__do str__u str__cr str__du str__r str__jennifer str__elizabeth str__cb str__dn str__i str__cl str__y str__j str__mary str__bd str__b str__v str__f str__n str__john str__bl str__cy str__ea str__barbara str__e str__ck str__robert str__ct str__da str__bx str__bg str__ec str__q str__richard - string
    id_bvdomaincredential id_tdomaincredential id_bzdomaincredential id_ldomaincredential id_ddomaincredential id_xdomaincredential id_brdomaincredential id_bjdomaincredential id_pdomaincredential id_bndomaincredential id_cddomaincredential id_bbdomaincredential id_hdomaincredential id_bfdomaincredential - observeddomaincredential
    id_fdschtask id_ffschtask id_feschtask id_fbschtask id_faschtask id_fcschtask id_fgschtask - observedschtask
    num__102 num__74 num__89 num__95 num__67 num__75 num__88 num__103 num__82 num__81 num__61 num__96 num__68 num__60 - num
)
(:init
    (knows id_dphost)
    (knows id_edrat)
    (knows_property id_dphost pfqdn)
    (knows_property id_edrat pexecutable)
    (knows_property id_edrat phost)
    (MEM_CACHED_DOMAIN_CREDS id_cghost id_pdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_cghost id_tdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_cnhost id_bzdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_cnhost id_cddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_cuhost id_brdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_cuhost id_xdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dbhost id_bfdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dbhost id_pdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dihost id_bfdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dihost id_cddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dphost id_bbdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dphost id_bndomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dwhost id_bbdomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_dwhost id_ldomaincredential)
    (MEM_DOMAIN_USER_ADMINS id_cghost id_bidomainuser)
    (MEM_DOMAIN_USER_ADMINS id_cghost id_bmdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_cnhost id_odomainuser)
    (MEM_DOMAIN_USER_ADMINS id_cnhost id_wdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_cuhost id_bmdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_cuhost id_bydomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dbhost id_bidomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dbhost id_ccdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dihost id_bqdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dihost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dphost id_bqdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dphost id_sdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dwhost id_bedomainuser)
    (MEM_DOMAIN_USER_ADMINS id_dwhost id_cdomainuser)
    (mem_hosts id_adomain id_cghost)
    (mem_hosts id_adomain id_cnhost)
    (mem_hosts id_adomain id_cuhost)
    (mem_hosts id_adomain id_dbhost)
    (mem_hosts id_adomain id_dihost)
    (mem_hosts id_adomain id_dphost)
    (mem_hosts id_adomain id_dwhost)
    (prop_cred id_badomainuser id_bbdomaincredential)
    (prop_cred id_bedomainuser id_bfdomaincredential)
    (prop_cred id_bidomainuser id_bjdomaincredential)
    (prop_cred id_bmdomainuser id_bndomaincredential)
    (prop_cred id_bqdomainuser id_brdomaincredential)
    (prop_cred id_budomainuser id_bvdomaincredential)
    (prop_cred id_bydomainuser id_bzdomaincredential)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (prop_cred id_ccdomainuser id_cddomaincredential)
    (prop_cred id_gdomainuser id_hdomaincredential)
    (prop_cred id_kdomainuser id_ldomaincredential)
    (prop_cred id_odomainuser id_pdomaincredential)
    (prop_cred id_sdomainuser id_tdomaincredential)
    (prop_cred id_wdomainuser id_xdomaincredential)
    (PROP_DC id_cghost no)
    (PROP_DC id_cnhost no)
    (PROP_DC id_cuhost no)
    (PROP_DC id_dbhost no)
    (PROP_DC id_dihost no)
    (PROP_DC id_dphost no)
    (PROP_DC id_dwhost no)
    (PROP_DNS_DOMAIN id_adomain str__b)
    (PROP_DNS_DOMAIN_NAME id_cghost str__cl)
    (PROP_DNS_DOMAIN_NAME id_cnhost str__cs)
    (PROP_DNS_DOMAIN_NAME id_cuhost str__cz)
    (PROP_DNS_DOMAIN_NAME id_dbhost str__dg)
    (PROP_DNS_DOMAIN_NAME id_dihost str__dn)
    (PROP_DNS_DOMAIN_NAME id_dphost str__du)
    (PROP_DNS_DOMAIN_NAME id_dwhost str__eb)
    (PROP_DOMAIN id_badomainuser id_adomain)
    (PROP_DOMAIN id_bbdomaincredential id_adomain)
    (PROP_DOMAIN id_bedomainuser id_adomain)
    (PROP_DOMAIN id_bfdomaincredential id_adomain)
    (PROP_DOMAIN id_bidomainuser id_adomain)
    (PROP_DOMAIN id_bjdomaincredential id_adomain)
    (PROP_DOMAIN id_bmdomainuser id_adomain)
    (PROP_DOMAIN id_bndomaincredential id_adomain)
    (PROP_DOMAIN id_bqdomainuser id_adomain)
    (PROP_DOMAIN id_brdomaincredential id_adomain)
    (PROP_DOMAIN id_budomainuser id_adomain)
    (PROP_DOMAIN id_bvdomaincredential id_adomain)
    (PROP_DOMAIN id_bydomainuser id_adomain)
    (PROP_DOMAIN id_bzdomaincredential id_adomain)
    (PROP_DOMAIN id_cdomainuser id_adomain)
    (PROP_DOMAIN id_ccdomainuser id_adomain)
    (PROP_DOMAIN id_cddomaincredential id_adomain)
    (PROP_DOMAIN id_cghost id_adomain)
    (PROP_DOMAIN id_cnhost id_adomain)
    (PROP_DOMAIN id_cuhost id_adomain)
    (PROP_DOMAIN id_ddomaincredential id_adomain)
    (PROP_DOMAIN id_dbhost id_adomain)
    (PROP_DOMAIN id_dihost id_adomain)
    (PROP_DOMAIN id_dphost id_adomain)
    (PROP_DOMAIN id_dwhost id_adomain)
    (PROP_DOMAIN id_gdomainuser id_adomain)
    (PROP_DOMAIN id_hdomaincredential id_adomain)
    (PROP_DOMAIN id_kdomainuser id_adomain)
    (PROP_DOMAIN id_ldomaincredential id_adomain)
    (PROP_DOMAIN id_odomainuser id_adomain)
    (PROP_DOMAIN id_pdomaincredential id_adomain)
    (PROP_DOMAIN id_sdomainuser id_adomain)
    (PROP_DOMAIN id_tdomaincredential id_adomain)
    (PROP_DOMAIN id_wdomainuser id_adomain)
    (PROP_DOMAIN id_xdomaincredential id_adomain)
    (prop_elevated id_edrat yes)
    (prop_executable id_edrat str__ee)
    (PROP_FQDN id_cghost str__ck)
    (PROP_FQDN id_cnhost str__cr)
    (PROP_FQDN id_cuhost str__cy)
    (PROP_FQDN id_dbhost str__df)
    (PROP_FQDN id_dihost str__dm)
    (PROP_FQDN id_dphost str__dt)
    (PROP_FQDN id_dwhost str__ea)
    (prop_host id_chtimedelta id_cghost)
    (prop_host id_cotimedelta id_cnhost)
    (prop_host id_cvtimedelta id_cuhost)
    (prop_host id_dctimedelta id_dbhost)
    (prop_host id_djtimedelta id_dihost)
    (prop_host id_dqtimedelta id_dphost)
    (prop_host id_dxtimedelta id_dwhost)
    (prop_host id_edrat id_dphost)
    (PROP_HOSTNAME id_cghost str__cm)
    (PROP_HOSTNAME id_cnhost str__ct)
    (PROP_HOSTNAME id_cuhost str__da)
    (PROP_HOSTNAME id_dbhost str__dh)
    (PROP_HOSTNAME id_dihost str__do)
    (PROP_HOSTNAME id_dphost str__dv)
    (PROP_HOSTNAME id_dwhost str__ec)
    (PROP_IS_GROUP id_badomainuser no)
    (PROP_IS_GROUP id_bedomainuser no)
    (PROP_IS_GROUP id_bidomainuser no)
    (PROP_IS_GROUP id_bmdomainuser no)
    (PROP_IS_GROUP id_bqdomainuser no)
    (PROP_IS_GROUP id_budomainuser no)
    (PROP_IS_GROUP id_bydomainuser no)
    (PROP_IS_GROUP id_cdomainuser no)
    (PROP_IS_GROUP id_ccdomainuser no)
    (PROP_IS_GROUP id_gdomainuser no)
    (PROP_IS_GROUP id_kdomainuser no)
    (PROP_IS_GROUP id_odomainuser no)
    (PROP_IS_GROUP id_sdomainuser no)
    (PROP_IS_GROUP id_wdomainuser no)
    (PROP_MICROSECONDS id_chtimedelta num__61)
    (PROP_MICROSECONDS id_cotimedelta num__68)
    (PROP_MICROSECONDS id_cvtimedelta num__75)
    (PROP_MICROSECONDS id_dctimedelta num__82)
    (PROP_MICROSECONDS id_djtimedelta num__89)
    (PROP_MICROSECONDS id_dqtimedelta num__96)
    (PROP_MICROSECONDS id_dxtimedelta num__103)
    (PROP_PASSWORD id_bbdomaincredential str__bc)
    (PROP_PASSWORD id_bfdomaincredential str__bg)
    (PROP_PASSWORD id_bjdomaincredential str__bk)
    (PROP_PASSWORD id_bndomaincredential str__bo)
    (PROP_PASSWORD id_brdomaincredential str__bs)
    (PROP_PASSWORD id_bvdomaincredential str__bw)
    (PROP_PASSWORD id_bzdomaincredential str__ca)
    (PROP_PASSWORD id_cddomaincredential str__ce)
    (PROP_PASSWORD id_ddomaincredential str__e)
    (PROP_PASSWORD id_hdomaincredential str__i)
    (PROP_PASSWORD id_ldomaincredential str__m)
    (PROP_PASSWORD id_pdomaincredential str__q)
    (PROP_PASSWORD id_tdomaincredential str__u)
    (PROP_PASSWORD id_xdomaincredential str__y)
    (PROP_SECONDS id_chtimedelta num__60)
    (PROP_SECONDS id_cotimedelta num__67)
    (PROP_SECONDS id_cvtimedelta num__74)
    (PROP_SECONDS id_dctimedelta num__81)
    (PROP_SECONDS id_djtimedelta num__88)
    (PROP_SECONDS id_dqtimedelta num__95)
    (PROP_SECONDS id_dxtimedelta num__102)
    (PROP_SID id_badomainuser str__bd)
    (PROP_SID id_bedomainuser str__bh)
    (PROP_SID id_bidomainuser str__bl)
    (PROP_SID id_bmdomainuser str__bp)
    (PROP_SID id_bqdomainuser str__bt)
    (PROP_SID id_budomainuser str__bx)
    (PROP_SID id_bydomainuser str__cb)
    (PROP_SID id_cdomainuser str__f)
    (PROP_SID id_ccdomainuser str__cf)
    (PROP_SID id_gdomainuser str__j)
    (PROP_SID id_kdomainuser str__n)
    (PROP_SID id_odomainuser str__r)
    (PROP_SID id_sdomainuser str__v)
    (PROP_SID id_wdomainuser str__z)
    (PROP_TIMEDELTA id_cghost id_chtimedelta)
    (PROP_TIMEDELTA id_cnhost id_cotimedelta)
    (PROP_TIMEDELTA id_cuhost id_cvtimedelta)
    (PROP_TIMEDELTA id_dbhost id_dctimedelta)
    (PROP_TIMEDELTA id_dihost id_djtimedelta)
    (PROP_TIMEDELTA id_dphost id_dqtimedelta)
    (PROP_TIMEDELTA id_dwhost id_dxtimedelta)
    (PROP_USER id_bbdomaincredential id_badomainuser)
    (PROP_USER id_bfdomaincredential id_bedomainuser)
    (PROP_USER id_bjdomaincredential id_bidomainuser)
    (PROP_USER id_bndomaincredential id_bmdomainuser)
    (PROP_USER id_brdomaincredential id_bqdomainuser)
    (PROP_USER id_bvdomaincredential id_budomainuser)
    (PROP_USER id_bzdomaincredential id_bydomainuser)
    (PROP_USER id_cddomaincredential id_ccdomainuser)
    (PROP_USER id_ddomaincredential id_cdomainuser)
    (PROP_USER id_hdomaincredential id_gdomainuser)
    (PROP_USER id_ldomaincredential id_kdomainuser)
    (PROP_USER id_pdomaincredential id_odomainuser)
    (PROP_USER id_tdomaincredential id_sdomainuser)
    (PROP_USER id_xdomaincredential id_wdomainuser)
    (PROP_USERNAME id_badomainuser str__michael)
    (PROP_USERNAME id_bedomainuser str__barbara)
    (PROP_USERNAME id_bidomainuser str__william)
    (PROP_USERNAME id_bmdomainuser str__elizabeth)
    (PROP_USERNAME id_bqdomainuser str__david)
    (PROP_USERNAME id_budomainuser str__jennifer)
    (PROP_USERNAME id_bydomainuser str__richard)
    (PROP_USERNAME id_cdomainuser str__james)
    (PROP_USERNAME id_ccdomainuser str__maria)
    (PROP_USERNAME id_gdomainuser str__mary)
    (PROP_USERNAME id_kdomainuser str__john)
    (PROP_USERNAME id_odomainuser str__patricia)
    (PROP_USERNAME id_sdomainuser str__robert)
    (PROP_USERNAME id_wdomainuser str__linda)
    (PROP_WINDOWS_DOMAIN id_adomain str__alpha)
)
(:goal
(and
    (prop_host id_efrat id_dwhost)
    (prop_host id_ekrat id_dbhost)
    (prop_host id_eirat id_dihost)
    (prop_host id_elrat id_cghost)
    (prop_host id_egrat id_cnhost)
    (prop_host id_ehrat id_cuhost)
)
)
)