(define (domain grounded-STRIPS-PROTOCOL)
(:requirements
:strips
:derived-predicates
)
(:predicates
(foo)
(ACTIVATE-PHILOSOPHER-6-FORKS--PID-WFORK)
(ACTIVATE-PHILOSOPHER-5-FORKS--PID-WFORK)
(ACTIVATE-PHILOSOPHER-4-FORKS--PID-WFORK)
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-WFORK)
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-WFORK)
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-WFORK)
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-WFORK)
(ENABLED-PHILOSOPHER-6-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-6-)
(QUEUE-TAIL-MSG-FORKS-6--FORK)
(ENABLED-PHILOSOPHER-5-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-5-)
(QUEUE-TAIL-MSG-FORKS-5--FORK)
(ENABLED-PHILOSOPHER-4-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-4-)
(QUEUE-TAIL-MSG-FORKS-4--FORK)
(ENABLED-PHILOSOPHER-3-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-3-)
(QUEUE-TAIL-MSG-FORKS-3--FORK)
(ENABLED-PHILOSOPHER-2-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-2-)
(QUEUE-TAIL-MSG-FORKS-2--FORK)
(ENABLED-PHILOSOPHER-1-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-1-)
(QUEUE-TAIL-MSG-FORKS-1--FORK)
(ENABLED-PHILOSOPHER-0-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-0-)
(QUEUE-TAIL-MSG-FORKS-0--FORK)
(QUEUE-MSG-FORKS-6--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-6--FORK)
(QUEUE-SIZE-FORKS-6--ONE)
(QUEUE-MSG-FORKS-5--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-5--FORK)
(QUEUE-SIZE-FORKS-5--ONE)
(QUEUE-MSG-FORKS-4--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-4--FORK)
(QUEUE-SIZE-FORKS-4--ONE)
(QUEUE-MSG-FORKS-3--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-3--FORK)
(QUEUE-SIZE-FORKS-3--ONE)
(QUEUE-MSG-FORKS-2--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-2--FORK)
(QUEUE-SIZE-FORKS-2--ONE)
(QUEUE-MSG-FORKS-1--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-1--FORK)
(QUEUE-SIZE-FORKS-1--ONE)
(QUEUE-MSG-FORKS-0--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-0--FORK)
(QUEUE-SIZE-FORKS-0--ONE)
(AT-PROCESS-PHILOSOPHER-0-STATE-6)
(AT-PROCESS-PHILOSOPHER-1-STATE-6)
(AT-PROCESS-PHILOSOPHER-2-STATE-6)
(AT-PROCESS-PHILOSOPHER-3-STATE-6)
(AT-PROCESS-PHILOSOPHER-4-STATE-6)
(AT-PROCESS-PHILOSOPHER-5-STATE-6)
(AT-PROCESS-PHILOSOPHER-6-STATE-6)
(ACTIVATE-PHILOSOPHER-6-FORKS--PID-RFORK)
(ACTIVATE-PHILOSOPHER-5-FORKS--PID-RFORK)
(ACTIVATE-PHILOSOPHER-4-FORKS--PID-RFORK)
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-RFORK)
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-RFORK)
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-RFORK)
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-RFORK)
(ADVANCE-HEAD-FORKS-6-)
(ENABLED-PHILOSOPHER-6-FORKS--PID-RFORK)
(ADVANCE-HEAD-FORKS-5-)
(ENABLED-PHILOSOPHER-5-FORKS--PID-RFORK)
(ADVANCE-HEAD-FORKS-4-)
(ENABLED-PHILOSOPHER-4-FORKS--PID-RFORK)
(ADVANCE-HEAD-FORKS-3-)
(ENABLED-PHILOSOPHER-3-FORKS--PID-RFORK)
(ADVANCE-HEAD-FORKS-2-)
(ENABLED-PHILOSOPHER-2-FORKS--PID-RFORK)
(ADVANCE-HEAD-FORKS-1-)
(ENABLED-PHILOSOPHER-1-FORKS--PID-RFORK)
(ADVANCE-HEAD-FORKS-0-)
(ENABLED-PHILOSOPHER-0-FORKS--PID-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-6-FORKS--PID-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-5-FORKS--PID-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-4-FORKS--PID-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-6-FORKS--PID-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-5-FORKS--PID-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-4-FORKS--PID-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-0-STATE-3)
(AT-PROCESS-PHILOSOPHER-1-STATE-3)
(AT-PROCESS-PHILOSOPHER-2-STATE-3)
(AT-PROCESS-PHILOSOPHER-3-STATE-3)
(AT-PROCESS-PHILOSOPHER-4-STATE-3)
(AT-PROCESS-PHILOSOPHER-5-STATE-3)
(AT-PROCESS-PHILOSOPHER-6-STATE-3)
(ACTIVATE-PHILOSOPHER-6-FORKS-__-PIDP1__7_-RFORK)
(ACTIVATE-PHILOSOPHER-5-FORKS-__-PIDP1__7_-RFORK)
(ACTIVATE-PHILOSOPHER-4-FORKS-__-PIDP1__7_-RFORK)
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__7_-RFORK)
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__7_-RFORK)
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__7_-RFORK)
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__7_-RFORK)
(ENABLED-PHILOSOPHER-6-FORKS-__-PIDP1__7_-RFORK)
(ENABLED-PHILOSOPHER-5-FORKS-__-PIDP1__7_-RFORK)
(ENABLED-PHILOSOPHER-4-FORKS-__-PIDP1__7_-RFORK)
(ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__7_-RFORK)
(ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__7_-RFORK)
(ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__7_-RFORK)
(ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__7_-RFORK)
(BLOCKED-PHILOSOPHER-6)
(BLOCKED-PHILOSOPHER-5)
(BLOCKED-PHILOSOPHER-4)
(BLOCKED-PHILOSOPHER-3)
(BLOCKED-PHILOSOPHER-2)
(BLOCKED-PHILOSOPHER-1)
(BLOCKED-PHILOSOPHER-0)
(BLOCKED-TRANS-PHILOSOPHER-5-FORKS-__-PIDP1__7_-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-4-FORKS-__-PIDP1__7_-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__7_-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__7_-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__7_-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__7_-RFORK)
(BLOCKED-TRANS-PHILOSOPHER-6-FORKS-__-PIDP1__7_-RFORK)
(AT-PROCESS-PHILOSOPHER-0-STATE-4)
(AT-PROCESS-PHILOSOPHER-1-STATE-4)
(AT-PROCESS-PHILOSOPHER-2-STATE-4)
(AT-PROCESS-PHILOSOPHER-3-STATE-4)
(AT-PROCESS-PHILOSOPHER-4-STATE-4)
(AT-PROCESS-PHILOSOPHER-5-STATE-4)
(AT-PROCESS-PHILOSOPHER-6-STATE-4)
(AT-PROCESS-PHILOSOPHER-0-STATE-5)
(AT-PROCESS-PHILOSOPHER-1-STATE-5)
(AT-PROCESS-PHILOSOPHER-2-STATE-5)
(AT-PROCESS-PHILOSOPHER-3-STATE-5)
(AT-PROCESS-PHILOSOPHER-4-STATE-5)
(AT-PROCESS-PHILOSOPHER-5-STATE-5)
(AT-PROCESS-PHILOSOPHER-6-STATE-5)
(ACTIVATE-PHILOSOPHER-6-FORKS-__-PIDP1__7_-WFORK)
(ACTIVATE-PHILOSOPHER-5-FORKS-__-PIDP1__7_-WFORK)
(ACTIVATE-PHILOSOPHER-4-FORKS-__-PIDP1__7_-WFORK)
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__7_-WFORK)
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__7_-WFORK)
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__7_-WFORK)
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__7_-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-5-FORKS-__-PIDP1__7_-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-4-FORKS-__-PIDP1__7_-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__7_-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__7_-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__7_-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__7_-WFORK)
(BLOCKED-TRANS-PHILOSOPHER-6-FORKS-__-PIDP1__7_-WFORK)
(ENABLED-PHILOSOPHER-6-FORKS-__-PIDP1__7_-WFORK)
(ENABLED-PHILOSOPHER-5-FORKS-__-PIDP1__7_-WFORK)
(ENABLED-PHILOSOPHER-4-FORKS-__-PIDP1__7_-WFORK)
(ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__7_-WFORK)
(ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__7_-WFORK)
(ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__7_-WFORK)
(ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__7_-WFORK)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
(SETTLED-FORKS-0-)
(PENDING-PHILOSOPHER-0)
(PENDING-PHILOSOPHER-1)
(PENDING-PHILOSOPHER-2)
(PENDING-PHILOSOPHER-3)
(PENDING-PHILOSOPHER-4)
(PENDING-PHILOSOPHER-5)
(PENDING-PHILOSOPHER-6)
(QUEUE-HEAD-FORKS-0--QS-0)
(QUEUE-HEAD-FORKS-1--QS-0)
(QUEUE-HEAD-FORKS-2--QS-0)
(QUEUE-HEAD-FORKS-3--QS-0)
(QUEUE-HEAD-FORKS-4--QS-0)
(QUEUE-HEAD-FORKS-5--QS-0)
(QUEUE-HEAD-FORKS-6--QS-0)
(AT-PROCESS-PHILOSOPHER-6-STATE-1)
(AT-PROCESS-PHILOSOPHER-5-STATE-1)
(AT-PROCESS-PHILOSOPHER-4-STATE-1)
(AT-PROCESS-PHILOSOPHER-3-STATE-1)
(AT-PROCESS-PHILOSOPHER-2-STATE-1)
(AT-PROCESS-PHILOSOPHER-1-STATE-1)
(AT-PROCESS-PHILOSOPHER-0-STATE-1)
(QUEUE-TAIL-FORKS-0--QS-0)
(QUEUE-SIZE-FORKS-0--ZERO)
(QUEUE-HEAD-MSG-FORKS-0--EMPTY)
(QUEUE-TAIL-FORKS-1--QS-0)
(QUEUE-SIZE-FORKS-1--ZERO)
(QUEUE-HEAD-MSG-FORKS-1--EMPTY)
(QUEUE-TAIL-FORKS-2--QS-0)
(QUEUE-SIZE-FORKS-2--ZERO)
(QUEUE-HEAD-MSG-FORKS-2--EMPTY)
(QUEUE-TAIL-FORKS-3--QS-0)
(QUEUE-SIZE-FORKS-3--ZERO)
(QUEUE-HEAD-MSG-FORKS-3--EMPTY)
(QUEUE-TAIL-FORKS-4--QS-0)
(QUEUE-SIZE-FORKS-4--ZERO)
(QUEUE-HEAD-MSG-FORKS-4--EMPTY)
(QUEUE-TAIL-FORKS-5--QS-0)
(QUEUE-SIZE-FORKS-5--ZERO)
(QUEUE-HEAD-MSG-FORKS-5--EMPTY)
(QUEUE-TAIL-FORKS-6--QS-0)
(QUEUE-SIZE-FORKS-6--ZERO)
(QUEUE-HEAD-MSG-FORKS-6--EMPTY)
)
(:action PERFORM-TRANS-PHILOSOPHER-6-PHILOSOPHER-FORKS-__-PIDP1__7_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-6-STATE-5)
(ENABLED-PHILOSOPHER-6-FORKS-__-PIDP1__7_-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-6-STATE-6)
(PENDING-PHILOSOPHER-6)
(not (AT-PROCESS-PHILOSOPHER-6-STATE-5))
(not (ENABLED-PHILOSOPHER-6-FORKS-__-PIDP1__7_-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-5-PHILOSOPHER-FORKS-__-PIDP1__7_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-5-STATE-5)
(ENABLED-PHILOSOPHER-5-FORKS-__-PIDP1__7_-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-5-STATE-6)
(PENDING-PHILOSOPHER-5)
(not (AT-PROCESS-PHILOSOPHER-5-STATE-5))
(not (ENABLED-PHILOSOPHER-5-FORKS-__-PIDP1__7_-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-4-PHILOSOPHER-FORKS-__-PIDP1__7_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-4-STATE-5)
(ENABLED-PHILOSOPHER-4-FORKS-__-PIDP1__7_-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-4-STATE-6)
(PENDING-PHILOSOPHER-4)
(not (AT-PROCESS-PHILOSOPHER-4-STATE-5))
(not (ENABLED-PHILOSOPHER-4-FORKS-__-PIDP1__7_-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS-__-PIDP1__7_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-5)
(ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__7_-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-6)
(PENDING-PHILOSOPHER-3)
(not (AT-PROCESS-PHILOSOPHER-3-STATE-5))
(not (ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__7_-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS-__-PIDP1__7_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-5)
(ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__7_-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-6)
(PENDING-PHILOSOPHER-2)
(not (AT-PROCESS-PHILOSOPHER-2-STATE-5))
(not (ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__7_-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS-__-PIDP1__7_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-5)
(ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__7_-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-6)
(PENDING-PHILOSOPHER-1)
(not (AT-PROCESS-PHILOSOPHER-1-STATE-5))
(not (ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__7_-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS-__-PIDP1__7_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-5)
(ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__7_-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-6)
(PENDING-PHILOSOPHER-0)
(not (AT-PROCESS-PHILOSOPHER-0-STATE-5))
(not (ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__7_-WFORK))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-0-FORKS-__-PIDP1__7_-WFORK-FORKS-1--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__7_-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__7_-WFORK)
(ADVANCE-TAIL-FORKS-1-)
(QUEUE-TAIL-MSG-FORKS-1--FORK)
(not (ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__7_-WFORK))
(not (SETTLED-FORKS-1-))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-1-FORKS-__-PIDP1__7_-WFORK-FORKS-2--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__7_-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__7_-WFORK)
(ADVANCE-TAIL-FORKS-2-)
(QUEUE-TAIL-MSG-FORKS-2--FORK)
(not (ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__7_-WFORK))
(not (SETTLED-FORKS-2-))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-2-FORKS-__-PIDP1__7_-WFORK-FORKS-3--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__7_-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__7_-WFORK)
(ADVANCE-TAIL-FORKS-3-)
(QUEUE-TAIL-MSG-FORKS-3--FORK)
(not (ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__7_-WFORK))
(not (SETTLED-FORKS-3-))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-3-FORKS-__-PIDP1__7_-WFORK-FORKS-4--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-4-)
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__7_-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__7_-WFORK)
(ADVANCE-TAIL-FORKS-4-)
(QUEUE-TAIL-MSG-FORKS-4--FORK)
(not (ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__7_-WFORK))
(not (SETTLED-FORKS-4-))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-4-FORKS-__-PIDP1__7_-WFORK-FORKS-5--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-5-)
(ACTIVATE-PHILOSOPHER-4-FORKS-__-PIDP1__7_-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-4-FORKS-__-PIDP1__7_-WFORK)
(ADVANCE-TAIL-FORKS-5-)
(QUEUE-TAIL-MSG-FORKS-5--FORK)
(not (ACTIVATE-PHILOSOPHER-4-FORKS-__-PIDP1__7_-WFORK))
(not (SETTLED-FORKS-5-))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-5-FORKS-__-PIDP1__7_-WFORK-FORKS-6--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-6-)
(ACTIVATE-PHILOSOPHER-5-FORKS-__-PIDP1__7_-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-5-FORKS-__-PIDP1__7_-WFORK)
(ADVANCE-TAIL-FORKS-6-)
(QUEUE-TAIL-MSG-FORKS-6--FORK)
(not (ACTIVATE-PHILOSOPHER-5-FORKS-__-PIDP1__7_-WFORK))
(not (SETTLED-FORKS-6-))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-6-FORKS-__-PIDP1__7_-WFORK-FORKS-0--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-6-FORKS-__-PIDP1__7_-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-6-FORKS-__-PIDP1__7_-WFORK)
(ADVANCE-TAIL-FORKS-0-)
(QUEUE-TAIL-MSG-FORKS-0--FORK)
(not (ACTIVATE-PHILOSOPHER-6-FORKS-__-PIDP1__7_-WFORK))
(not (SETTLED-FORKS-0-))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS-__-PIDP1__7_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-0)
(AT-PROCESS-PHILOSOPHER-0-STATE-5)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__7_-WFORK)
(not (PENDING-PHILOSOPHER-0))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS-__-PIDP1__7_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-1)
(AT-PROCESS-PHILOSOPHER-1-STATE-5)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__7_-WFORK)
(not (PENDING-PHILOSOPHER-1))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS-__-PIDP1__7_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-2)
(AT-PROCESS-PHILOSOPHER-2-STATE-5)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__7_-WFORK)
(not (PENDING-PHILOSOPHER-2))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS-__-PIDP1__7_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-3)
(AT-PROCESS-PHILOSOPHER-3-STATE-5)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__7_-WFORK)
(not (PENDING-PHILOSOPHER-3))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-4-PHILOSOPHER-FORKS-__-PIDP1__7_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-4)
(AT-PROCESS-PHILOSOPHER-4-STATE-5)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-4-FORKS-__-PIDP1__7_-WFORK)
(not (PENDING-PHILOSOPHER-4))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-5-PHILOSOPHER-FORKS-__-PIDP1__7_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-5)
(AT-PROCESS-PHILOSOPHER-5-STATE-5)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-5-FORKS-__-PIDP1__7_-WFORK)
(not (PENDING-PHILOSOPHER-5))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-6-PHILOSOPHER-FORKS-__-PIDP1__7_-WFORK-STATE-5-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-6)
(AT-PROCESS-PHILOSOPHER-6-STATE-5)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-6-FORKS-__-PIDP1__7_-WFORK)
(not (PENDING-PHILOSOPHER-6))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-6-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-6-STATE-4)
(ENABLED-PHILOSOPHER-6-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-6-STATE-5)
(PENDING-PHILOSOPHER-6)
(not (AT-PROCESS-PHILOSOPHER-6-STATE-4))
(not (ENABLED-PHILOSOPHER-6-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-5-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-5-STATE-4)
(ENABLED-PHILOSOPHER-5-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-5-STATE-5)
(PENDING-PHILOSOPHER-5)
(not (AT-PROCESS-PHILOSOPHER-5-STATE-4))
(not (ENABLED-PHILOSOPHER-5-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-4-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-4-STATE-4)
(ENABLED-PHILOSOPHER-4-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-4-STATE-5)
(PENDING-PHILOSOPHER-4)
(not (AT-PROCESS-PHILOSOPHER-4-STATE-4))
(not (ENABLED-PHILOSOPHER-4-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-4)
(ENABLED-PHILOSOPHER-3-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-5)
(PENDING-PHILOSOPHER-3)
(not (AT-PROCESS-PHILOSOPHER-3-STATE-4))
(not (ENABLED-PHILOSOPHER-3-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-4)
(ENABLED-PHILOSOPHER-2-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-5)
(PENDING-PHILOSOPHER-2)
(not (AT-PROCESS-PHILOSOPHER-2-STATE-4))
(not (ENABLED-PHILOSOPHER-2-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-4)
(ENABLED-PHILOSOPHER-1-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-5)
(PENDING-PHILOSOPHER-1)
(not (AT-PROCESS-PHILOSOPHER-1-STATE-4))
(not (ENABLED-PHILOSOPHER-1-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-4)
(ENABLED-PHILOSOPHER-0-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-5)
(PENDING-PHILOSOPHER-0)
(not (AT-PROCESS-PHILOSOPHER-0-STATE-4))
(not (ENABLED-PHILOSOPHER-0-FORKS--PID-WFORK))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-0)
(AT-PROCESS-PHILOSOPHER-0-STATE-4)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-0))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-1)
(AT-PROCESS-PHILOSOPHER-1-STATE-4)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-1))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-2)
(AT-PROCESS-PHILOSOPHER-2-STATE-4)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-2))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-3)
(AT-PROCESS-PHILOSOPHER-3-STATE-4)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-3))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-4-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-4)
(AT-PROCESS-PHILOSOPHER-4-STATE-4)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-4-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-4))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-5-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-5)
(AT-PROCESS-PHILOSOPHER-5-STATE-4)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-5-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-5))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-6-PHILOSOPHER-FORKS--PID-WFORK-STATE-4-STATE-5-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-6)
(AT-PROCESS-PHILOSOPHER-6-STATE-4)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-6-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-6))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-6-PHILOSOPHER-FORKS-__-PIDP1__7_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-6-STATE-3)
(ENABLED-PHILOSOPHER-6-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-6-STATE-4)
(PENDING-PHILOSOPHER-6)
(not (AT-PROCESS-PHILOSOPHER-6-STATE-3))
(not (ENABLED-PHILOSOPHER-6-FORKS-__-PIDP1__7_-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-5-PHILOSOPHER-FORKS-__-PIDP1__7_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-5-STATE-3)
(ENABLED-PHILOSOPHER-5-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-5-STATE-4)
(PENDING-PHILOSOPHER-5)
(not (AT-PROCESS-PHILOSOPHER-5-STATE-3))
(not (ENABLED-PHILOSOPHER-5-FORKS-__-PIDP1__7_-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-4-PHILOSOPHER-FORKS-__-PIDP1__7_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-4-STATE-3)
(ENABLED-PHILOSOPHER-4-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-4-STATE-4)
(PENDING-PHILOSOPHER-4)
(not (AT-PROCESS-PHILOSOPHER-4-STATE-3))
(not (ENABLED-PHILOSOPHER-4-FORKS-__-PIDP1__7_-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS-__-PIDP1__7_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-3)
(ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-4)
(PENDING-PHILOSOPHER-3)
(not (AT-PROCESS-PHILOSOPHER-3-STATE-3))
(not (ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__7_-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS-__-PIDP1__7_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-3)
(ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-4)
(PENDING-PHILOSOPHER-2)
(not (AT-PROCESS-PHILOSOPHER-2-STATE-3))
(not (ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__7_-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS-__-PIDP1__7_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-3)
(ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-4)
(PENDING-PHILOSOPHER-1)
(not (AT-PROCESS-PHILOSOPHER-1-STATE-3))
(not (ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__7_-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS-__-PIDP1__7_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-3)
(ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-4)
(PENDING-PHILOSOPHER-0)
(not (AT-PROCESS-PHILOSOPHER-0-STATE-3))
(not (ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__7_-RFORK))
)
)
(:action QUEUE-READ-PHILOSOPHER-0-FORKS-__-PIDP1__7_-RFORK-FORKS-1--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-1--FORK)
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__7_-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-1-)
(ENABLED-PHILOSOPHER-0-FORKS-__-PIDP1__7_-RFORK)
(not (ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__7_-RFORK))
(not (SETTLED-FORKS-1-))
)
)
(:action QUEUE-READ-PHILOSOPHER-1-FORKS-__-PIDP1__7_-RFORK-FORKS-2--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-2--FORK)
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__7_-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-2-)
(ENABLED-PHILOSOPHER-1-FORKS-__-PIDP1__7_-RFORK)
(not (ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__7_-RFORK))
(not (SETTLED-FORKS-2-))
)
)
(:action QUEUE-READ-PHILOSOPHER-2-FORKS-__-PIDP1__7_-RFORK-FORKS-3--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-3--FORK)
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__7_-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-3-)
(ENABLED-PHILOSOPHER-2-FORKS-__-PIDP1__7_-RFORK)
(not (ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__7_-RFORK))
(not (SETTLED-FORKS-3-))
)
)
(:action QUEUE-READ-PHILOSOPHER-3-FORKS-__-PIDP1__7_-RFORK-FORKS-4--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-4--FORK)
(SETTLED-FORKS-4-)
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__7_-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-4-)
(ENABLED-PHILOSOPHER-3-FORKS-__-PIDP1__7_-RFORK)
(not (ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__7_-RFORK))
(not (SETTLED-FORKS-4-))
)
)
(:action QUEUE-READ-PHILOSOPHER-4-FORKS-__-PIDP1__7_-RFORK-FORKS-5--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-5--FORK)
(SETTLED-FORKS-5-)
(ACTIVATE-PHILOSOPHER-4-FORKS-__-PIDP1__7_-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-5-)
(ENABLED-PHILOSOPHER-4-FORKS-__-PIDP1__7_-RFORK)
(not (ACTIVATE-PHILOSOPHER-4-FORKS-__-PIDP1__7_-RFORK))
(not (SETTLED-FORKS-5-))
)
)
(:action QUEUE-READ-PHILOSOPHER-5-FORKS-__-PIDP1__7_-RFORK-FORKS-6--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-6--FORK)
(SETTLED-FORKS-6-)
(ACTIVATE-PHILOSOPHER-5-FORKS-__-PIDP1__7_-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-6-)
(ENABLED-PHILOSOPHER-5-FORKS-__-PIDP1__7_-RFORK)
(not (ACTIVATE-PHILOSOPHER-5-FORKS-__-PIDP1__7_-RFORK))
(not (SETTLED-FORKS-6-))
)
)
(:action QUEUE-READ-PHILOSOPHER-6-FORKS-__-PIDP1__7_-RFORK-FORKS-0--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-0--FORK)
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-6-FORKS-__-PIDP1__7_-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-0-)
(ENABLED-PHILOSOPHER-6-FORKS-__-PIDP1__7_-RFORK)
(not (ACTIVATE-PHILOSOPHER-6-FORKS-__-PIDP1__7_-RFORK))
(not (SETTLED-FORKS-0-))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS-__-PIDP1__7_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-0)
(AT-PROCESS-PHILOSOPHER-0-STATE-3)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__7_-RFORK)
(not (PENDING-PHILOSOPHER-0))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS-__-PIDP1__7_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-1)
(AT-PROCESS-PHILOSOPHER-1-STATE-3)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__7_-RFORK)
(not (PENDING-PHILOSOPHER-1))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS-__-PIDP1__7_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-2)
(AT-PROCESS-PHILOSOPHER-2-STATE-3)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__7_-RFORK)
(not (PENDING-PHILOSOPHER-2))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS-__-PIDP1__7_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-3)
(AT-PROCESS-PHILOSOPHER-3-STATE-3)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__7_-RFORK)
(not (PENDING-PHILOSOPHER-3))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-4-PHILOSOPHER-FORKS-__-PIDP1__7_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-4)
(AT-PROCESS-PHILOSOPHER-4-STATE-3)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-4-FORKS-__-PIDP1__7_-RFORK)
(not (PENDING-PHILOSOPHER-4))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-5-PHILOSOPHER-FORKS-__-PIDP1__7_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-5)
(AT-PROCESS-PHILOSOPHER-5-STATE-3)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-5-FORKS-__-PIDP1__7_-RFORK)
(not (PENDING-PHILOSOPHER-5))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-6-PHILOSOPHER-FORKS-__-PIDP1__7_-RFORK-STATE-3-STATE-4-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-6)
(AT-PROCESS-PHILOSOPHER-6-STATE-3)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-6-FORKS-__-PIDP1__7_-RFORK)
(not (PENDING-PHILOSOPHER-6))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-6-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-6-STATE-6)
(ENABLED-PHILOSOPHER-6-FORKS--PID-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-6-STATE-3)
(PENDING-PHILOSOPHER-6)
(not (AT-PROCESS-PHILOSOPHER-6-STATE-6))
(not (ENABLED-PHILOSOPHER-6-FORKS--PID-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-5-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-5-STATE-6)
(ENABLED-PHILOSOPHER-5-FORKS--PID-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-5-STATE-3)
(PENDING-PHILOSOPHER-5)
(not (AT-PROCESS-PHILOSOPHER-5-STATE-6))
(not (ENABLED-PHILOSOPHER-5-FORKS--PID-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-4-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-4-STATE-6)
(ENABLED-PHILOSOPHER-4-FORKS--PID-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-4-STATE-3)
(PENDING-PHILOSOPHER-4)
(not (AT-PROCESS-PHILOSOPHER-4-STATE-6))
(not (ENABLED-PHILOSOPHER-4-FORKS--PID-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-6)
(ENABLED-PHILOSOPHER-3-FORKS--PID-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-3)
(PENDING-PHILOSOPHER-3)
(not (AT-PROCESS-PHILOSOPHER-3-STATE-6))
(not (ENABLED-PHILOSOPHER-3-FORKS--PID-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-6)
(ENABLED-PHILOSOPHER-2-FORKS--PID-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-3)
(PENDING-PHILOSOPHER-2)
(not (AT-PROCESS-PHILOSOPHER-2-STATE-6))
(not (ENABLED-PHILOSOPHER-2-FORKS--PID-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-6)
(ENABLED-PHILOSOPHER-1-FORKS--PID-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-3)
(PENDING-PHILOSOPHER-1)
(not (AT-PROCESS-PHILOSOPHER-1-STATE-6))
(not (ENABLED-PHILOSOPHER-1-FORKS--PID-RFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-6)
(ENABLED-PHILOSOPHER-0-FORKS--PID-RFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-3)
(PENDING-PHILOSOPHER-0)
(not (AT-PROCESS-PHILOSOPHER-0-STATE-6))
(not (ENABLED-PHILOSOPHER-0-FORKS--PID-RFORK))
)
)
(:action ADVANCE-QUEUE-HEAD-FORKS-0--QUEUE-1-QS-0-QS-0-FORK-ONE-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-0--ONE)
(QUEUE-MSG-FORKS-0--QS-0-FORK)
(ADVANCE-HEAD-FORKS-0-)
(QUEUE-HEAD-FORKS-0--QS-0)
)
:effect
(and
(SETTLED-FORKS-0-)
(QUEUE-HEAD-FORKS-0--QS-0)
(QUEUE-HEAD-MSG-FORKS-0--FORK)
(QUEUE-SIZE-FORKS-0--ZERO)
(not (ADVANCE-HEAD-FORKS-0-))
(not (QUEUE-SIZE-FORKS-0--ONE))
)
)
(:action ADVANCE-QUEUE-HEAD-FORKS-1--QUEUE-1-QS-0-QS-0-FORK-ONE-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-1--ONE)
(QUEUE-MSG-FORKS-1--QS-0-FORK)
(ADVANCE-HEAD-FORKS-1-)
(QUEUE-HEAD-FORKS-1--QS-0)
)
:effect
(and
(SETTLED-FORKS-1-)
(QUEUE-HEAD-FORKS-1--QS-0)
(QUEUE-HEAD-MSG-FORKS-1--FORK)
(QUEUE-SIZE-FORKS-1--ZERO)
(not (ADVANCE-HEAD-FORKS-1-))
(not (QUEUE-SIZE-FORKS-1--ONE))
)
)
(:action ADVANCE-QUEUE-HEAD-FORKS-2--QUEUE-1-QS-0-QS-0-FORK-ONE-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-2--ONE)
(QUEUE-MSG-FORKS-2--QS-0-FORK)
(ADVANCE-HEAD-FORKS-2-)
(QUEUE-HEAD-FORKS-2--QS-0)
)
:effect
(and
(SETTLED-FORKS-2-)
(QUEUE-HEAD-FORKS-2--QS-0)
(QUEUE-HEAD-MSG-FORKS-2--FORK)
(QUEUE-SIZE-FORKS-2--ZERO)
(not (ADVANCE-HEAD-FORKS-2-))
(not (QUEUE-SIZE-FORKS-2--ONE))
)
)
(:action ADVANCE-QUEUE-HEAD-FORKS-3--QUEUE-1-QS-0-QS-0-FORK-ONE-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-3--ONE)
(QUEUE-MSG-FORKS-3--QS-0-FORK)
(ADVANCE-HEAD-FORKS-3-)
(QUEUE-HEAD-FORKS-3--QS-0)
)
:effect
(and
(SETTLED-FORKS-3-)
(QUEUE-HEAD-FORKS-3--QS-0)
(QUEUE-HEAD-MSG-FORKS-3--FORK)
(QUEUE-SIZE-FORKS-3--ZERO)
(not (ADVANCE-HEAD-FORKS-3-))
(not (QUEUE-SIZE-FORKS-3--ONE))
)
)
(:action ADVANCE-QUEUE-HEAD-FORKS-4--QUEUE-1-QS-0-QS-0-FORK-ONE-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-4--ONE)
(QUEUE-MSG-FORKS-4--QS-0-FORK)
(ADVANCE-HEAD-FORKS-4-)
(QUEUE-HEAD-FORKS-4--QS-0)
)
:effect
(and
(SETTLED-FORKS-4-)
(QUEUE-HEAD-FORKS-4--QS-0)
(QUEUE-HEAD-MSG-FORKS-4--FORK)
(QUEUE-SIZE-FORKS-4--ZERO)
(not (ADVANCE-HEAD-FORKS-4-))
(not (QUEUE-SIZE-FORKS-4--ONE))
)
)
(:action ADVANCE-QUEUE-HEAD-FORKS-5--QUEUE-1-QS-0-QS-0-FORK-ONE-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-5--ONE)
(QUEUE-MSG-FORKS-5--QS-0-FORK)
(ADVANCE-HEAD-FORKS-5-)
(QUEUE-HEAD-FORKS-5--QS-0)
)
:effect
(and
(SETTLED-FORKS-5-)
(QUEUE-HEAD-FORKS-5--QS-0)
(QUEUE-HEAD-MSG-FORKS-5--FORK)
(QUEUE-SIZE-FORKS-5--ZERO)
(not (ADVANCE-HEAD-FORKS-5-))
(not (QUEUE-SIZE-FORKS-5--ONE))
)
)
(:action ADVANCE-QUEUE-HEAD-FORKS-6--QUEUE-1-QS-0-QS-0-FORK-ONE-ZERO-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-6--ONE)
(QUEUE-MSG-FORKS-6--QS-0-FORK)
(ADVANCE-HEAD-FORKS-6-)
(QUEUE-HEAD-FORKS-6--QS-0)
)
:effect
(and
(SETTLED-FORKS-6-)
(QUEUE-HEAD-FORKS-6--QS-0)
(QUEUE-HEAD-MSG-FORKS-6--FORK)
(QUEUE-SIZE-FORKS-6--ZERO)
(not (ADVANCE-HEAD-FORKS-6-))
(not (QUEUE-SIZE-FORKS-6--ONE))
)
)
(:action QUEUE-READ-PHILOSOPHER-0-FORKS--PID-RFORK-FORKS-0--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-0--FORK)
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-0-)
(ENABLED-PHILOSOPHER-0-FORKS--PID-RFORK)
(not (ACTIVATE-PHILOSOPHER-0-FORKS--PID-RFORK))
(not (SETTLED-FORKS-0-))
)
)
(:action QUEUE-READ-PHILOSOPHER-1-FORKS--PID-RFORK-FORKS-1--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-1--FORK)
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-1-)
(ENABLED-PHILOSOPHER-1-FORKS--PID-RFORK)
(not (ACTIVATE-PHILOSOPHER-1-FORKS--PID-RFORK))
(not (SETTLED-FORKS-1-))
)
)
(:action QUEUE-READ-PHILOSOPHER-2-FORKS--PID-RFORK-FORKS-2--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-2--FORK)
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-2-)
(ENABLED-PHILOSOPHER-2-FORKS--PID-RFORK)
(not (ACTIVATE-PHILOSOPHER-2-FORKS--PID-RFORK))
(not (SETTLED-FORKS-2-))
)
)
(:action QUEUE-READ-PHILOSOPHER-3-FORKS--PID-RFORK-FORKS-3--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-3--FORK)
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-3-)
(ENABLED-PHILOSOPHER-3-FORKS--PID-RFORK)
(not (ACTIVATE-PHILOSOPHER-3-FORKS--PID-RFORK))
(not (SETTLED-FORKS-3-))
)
)
(:action QUEUE-READ-PHILOSOPHER-4-FORKS--PID-RFORK-FORKS-4--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-4--FORK)
(SETTLED-FORKS-4-)
(ACTIVATE-PHILOSOPHER-4-FORKS--PID-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-4-)
(ENABLED-PHILOSOPHER-4-FORKS--PID-RFORK)
(not (ACTIVATE-PHILOSOPHER-4-FORKS--PID-RFORK))
(not (SETTLED-FORKS-4-))
)
)
(:action QUEUE-READ-PHILOSOPHER-5-FORKS--PID-RFORK-FORKS-5--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-5--FORK)
(SETTLED-FORKS-5-)
(ACTIVATE-PHILOSOPHER-5-FORKS--PID-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-5-)
(ENABLED-PHILOSOPHER-5-FORKS--PID-RFORK)
(not (ACTIVATE-PHILOSOPHER-5-FORKS--PID-RFORK))
(not (SETTLED-FORKS-5-))
)
)
(:action QUEUE-READ-PHILOSOPHER-6-FORKS--PID-RFORK-FORKS-6--FORK-0
:parameters ()
:precondition
(and
(QUEUE-HEAD-MSG-FORKS-6--FORK)
(SETTLED-FORKS-6-)
(ACTIVATE-PHILOSOPHER-6-FORKS--PID-RFORK)
)
:effect
(and
(ADVANCE-HEAD-FORKS-6-)
(ENABLED-PHILOSOPHER-6-FORKS--PID-RFORK)
(not (ACTIVATE-PHILOSOPHER-6-FORKS--PID-RFORK))
(not (SETTLED-FORKS-6-))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-0)
(AT-PROCESS-PHILOSOPHER-0-STATE-6)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-RFORK)
(not (PENDING-PHILOSOPHER-0))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-1)
(AT-PROCESS-PHILOSOPHER-1-STATE-6)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-RFORK)
(not (PENDING-PHILOSOPHER-1))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-2)
(AT-PROCESS-PHILOSOPHER-2-STATE-6)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-RFORK)
(not (PENDING-PHILOSOPHER-2))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-3)
(AT-PROCESS-PHILOSOPHER-3-STATE-6)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-RFORK)
(not (PENDING-PHILOSOPHER-3))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-4-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-4)
(AT-PROCESS-PHILOSOPHER-4-STATE-6)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-4-FORKS--PID-RFORK)
(not (PENDING-PHILOSOPHER-4))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-5-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-5)
(AT-PROCESS-PHILOSOPHER-5-STATE-6)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-5-FORKS--PID-RFORK)
(not (PENDING-PHILOSOPHER-5))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-6-PHILOSOPHER-FORKS--PID-RFORK-STATE-6-STATE-3-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-6)
(AT-PROCESS-PHILOSOPHER-6-STATE-6)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-6-FORKS--PID-RFORK)
(not (PENDING-PHILOSOPHER-6))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-6-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-6-STATE-1)
(ENABLED-PHILOSOPHER-6-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-6-STATE-6)
(PENDING-PHILOSOPHER-6)
(not (AT-PROCESS-PHILOSOPHER-6-STATE-1))
(not (ENABLED-PHILOSOPHER-6-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-5-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-5-STATE-1)
(ENABLED-PHILOSOPHER-5-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-5-STATE-6)
(PENDING-PHILOSOPHER-5)
(not (AT-PROCESS-PHILOSOPHER-5-STATE-1))
(not (ENABLED-PHILOSOPHER-5-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-4-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-4-STATE-1)
(ENABLED-PHILOSOPHER-4-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-4-STATE-6)
(PENDING-PHILOSOPHER-4)
(not (AT-PROCESS-PHILOSOPHER-4-STATE-1))
(not (ENABLED-PHILOSOPHER-4-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-1)
(ENABLED-PHILOSOPHER-3-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-3-STATE-6)
(PENDING-PHILOSOPHER-3)
(not (AT-PROCESS-PHILOSOPHER-3-STATE-1))
(not (ENABLED-PHILOSOPHER-3-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-1)
(ENABLED-PHILOSOPHER-2-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-2-STATE-6)
(PENDING-PHILOSOPHER-2)
(not (AT-PROCESS-PHILOSOPHER-2-STATE-1))
(not (ENABLED-PHILOSOPHER-2-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-1)
(ENABLED-PHILOSOPHER-1-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-1-STATE-6)
(PENDING-PHILOSOPHER-1)
(not (AT-PROCESS-PHILOSOPHER-1-STATE-1))
(not (ENABLED-PHILOSOPHER-1-FORKS--PID-WFORK))
)
)
(:action PERFORM-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-1)
(ENABLED-PHILOSOPHER-0-FORKS--PID-WFORK)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(AT-PROCESS-PHILOSOPHER-0-STATE-6)
(PENDING-PHILOSOPHER-0)
(not (AT-PROCESS-PHILOSOPHER-0-STATE-1))
(not (ENABLED-PHILOSOPHER-0-FORKS--PID-WFORK))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-0--QUEUE-1-QS-0-QS-0-FORK-FORK-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-0--ZERO)
(QUEUE-HEAD-MSG-FORKS-0--FORK)
(QUEUE-TAIL-MSG-FORKS-0--FORK)
(ADVANCE-TAIL-FORKS-0-)
(QUEUE-TAIL-FORKS-0--QS-0)
)
:effect
(and
(SETTLED-FORKS-0-)
(QUEUE-TAIL-FORKS-0--QS-0)
(QUEUE-MSG-FORKS-0--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-0--FORK)
(QUEUE-SIZE-FORKS-0--ONE)
(not (ADVANCE-TAIL-FORKS-0-))
(not (QUEUE-SIZE-FORKS-0--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-0--QUEUE-1-QS-0-QS-0-FORK-EMPTY-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-0--ZERO)
(QUEUE-HEAD-MSG-FORKS-0--EMPTY)
(QUEUE-TAIL-MSG-FORKS-0--FORK)
(ADVANCE-TAIL-FORKS-0-)
(QUEUE-TAIL-FORKS-0--QS-0)
)
:effect
(and
(SETTLED-FORKS-0-)
(QUEUE-TAIL-FORKS-0--QS-0)
(QUEUE-MSG-FORKS-0--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-0--FORK)
(QUEUE-SIZE-FORKS-0--ONE)
(not (ADVANCE-TAIL-FORKS-0-))
(not (QUEUE-HEAD-MSG-FORKS-0--EMPTY))
(not (QUEUE-SIZE-FORKS-0--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-1--QUEUE-1-QS-0-QS-0-FORK-FORK-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-1--ZERO)
(QUEUE-HEAD-MSG-FORKS-1--FORK)
(QUEUE-TAIL-MSG-FORKS-1--FORK)
(ADVANCE-TAIL-FORKS-1-)
(QUEUE-TAIL-FORKS-1--QS-0)
)
:effect
(and
(SETTLED-FORKS-1-)
(QUEUE-TAIL-FORKS-1--QS-0)
(QUEUE-MSG-FORKS-1--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-1--FORK)
(QUEUE-SIZE-FORKS-1--ONE)
(not (ADVANCE-TAIL-FORKS-1-))
(not (QUEUE-SIZE-FORKS-1--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-1--QUEUE-1-QS-0-QS-0-FORK-EMPTY-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-1--ZERO)
(QUEUE-HEAD-MSG-FORKS-1--EMPTY)
(QUEUE-TAIL-MSG-FORKS-1--FORK)
(ADVANCE-TAIL-FORKS-1-)
(QUEUE-TAIL-FORKS-1--QS-0)
)
:effect
(and
(SETTLED-FORKS-1-)
(QUEUE-TAIL-FORKS-1--QS-0)
(QUEUE-MSG-FORKS-1--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-1--FORK)
(QUEUE-SIZE-FORKS-1--ONE)
(not (ADVANCE-TAIL-FORKS-1-))
(not (QUEUE-HEAD-MSG-FORKS-1--EMPTY))
(not (QUEUE-SIZE-FORKS-1--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-2--QUEUE-1-QS-0-QS-0-FORK-FORK-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-2--ZERO)
(QUEUE-HEAD-MSG-FORKS-2--FORK)
(QUEUE-TAIL-MSG-FORKS-2--FORK)
(ADVANCE-TAIL-FORKS-2-)
(QUEUE-TAIL-FORKS-2--QS-0)
)
:effect
(and
(SETTLED-FORKS-2-)
(QUEUE-TAIL-FORKS-2--QS-0)
(QUEUE-MSG-FORKS-2--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-2--FORK)
(QUEUE-SIZE-FORKS-2--ONE)
(not (ADVANCE-TAIL-FORKS-2-))
(not (QUEUE-SIZE-FORKS-2--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-2--QUEUE-1-QS-0-QS-0-FORK-EMPTY-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-2--ZERO)
(QUEUE-HEAD-MSG-FORKS-2--EMPTY)
(QUEUE-TAIL-MSG-FORKS-2--FORK)
(ADVANCE-TAIL-FORKS-2-)
(QUEUE-TAIL-FORKS-2--QS-0)
)
:effect
(and
(SETTLED-FORKS-2-)
(QUEUE-TAIL-FORKS-2--QS-0)
(QUEUE-MSG-FORKS-2--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-2--FORK)
(QUEUE-SIZE-FORKS-2--ONE)
(not (ADVANCE-TAIL-FORKS-2-))
(not (QUEUE-HEAD-MSG-FORKS-2--EMPTY))
(not (QUEUE-SIZE-FORKS-2--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-3--QUEUE-1-QS-0-QS-0-FORK-FORK-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-3--ZERO)
(QUEUE-HEAD-MSG-FORKS-3--FORK)
(QUEUE-TAIL-MSG-FORKS-3--FORK)
(ADVANCE-TAIL-FORKS-3-)
(QUEUE-TAIL-FORKS-3--QS-0)
)
:effect
(and
(SETTLED-FORKS-3-)
(QUEUE-TAIL-FORKS-3--QS-0)
(QUEUE-MSG-FORKS-3--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-3--FORK)
(QUEUE-SIZE-FORKS-3--ONE)
(not (ADVANCE-TAIL-FORKS-3-))
(not (QUEUE-SIZE-FORKS-3--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-3--QUEUE-1-QS-0-QS-0-FORK-EMPTY-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-3--ZERO)
(QUEUE-HEAD-MSG-FORKS-3--EMPTY)
(QUEUE-TAIL-MSG-FORKS-3--FORK)
(ADVANCE-TAIL-FORKS-3-)
(QUEUE-TAIL-FORKS-3--QS-0)
)
:effect
(and
(SETTLED-FORKS-3-)
(QUEUE-TAIL-FORKS-3--QS-0)
(QUEUE-MSG-FORKS-3--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-3--FORK)
(QUEUE-SIZE-FORKS-3--ONE)
(not (ADVANCE-TAIL-FORKS-3-))
(not (QUEUE-HEAD-MSG-FORKS-3--EMPTY))
(not (QUEUE-SIZE-FORKS-3--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-4--QUEUE-1-QS-0-QS-0-FORK-FORK-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-4--ZERO)
(QUEUE-HEAD-MSG-FORKS-4--FORK)
(QUEUE-TAIL-MSG-FORKS-4--FORK)
(ADVANCE-TAIL-FORKS-4-)
(QUEUE-TAIL-FORKS-4--QS-0)
)
:effect
(and
(SETTLED-FORKS-4-)
(QUEUE-TAIL-FORKS-4--QS-0)
(QUEUE-MSG-FORKS-4--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-4--FORK)
(QUEUE-SIZE-FORKS-4--ONE)
(not (ADVANCE-TAIL-FORKS-4-))
(not (QUEUE-SIZE-FORKS-4--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-4--QUEUE-1-QS-0-QS-0-FORK-EMPTY-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-4--ZERO)
(QUEUE-HEAD-MSG-FORKS-4--EMPTY)
(QUEUE-TAIL-MSG-FORKS-4--FORK)
(ADVANCE-TAIL-FORKS-4-)
(QUEUE-TAIL-FORKS-4--QS-0)
)
:effect
(and
(SETTLED-FORKS-4-)
(QUEUE-TAIL-FORKS-4--QS-0)
(QUEUE-MSG-FORKS-4--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-4--FORK)
(QUEUE-SIZE-FORKS-4--ONE)
(not (ADVANCE-TAIL-FORKS-4-))
(not (QUEUE-HEAD-MSG-FORKS-4--EMPTY))
(not (QUEUE-SIZE-FORKS-4--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-5--QUEUE-1-QS-0-QS-0-FORK-FORK-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-5--ZERO)
(QUEUE-HEAD-MSG-FORKS-5--FORK)
(QUEUE-TAIL-MSG-FORKS-5--FORK)
(ADVANCE-TAIL-FORKS-5-)
(QUEUE-TAIL-FORKS-5--QS-0)
)
:effect
(and
(SETTLED-FORKS-5-)
(QUEUE-TAIL-FORKS-5--QS-0)
(QUEUE-MSG-FORKS-5--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-5--FORK)
(QUEUE-SIZE-FORKS-5--ONE)
(not (ADVANCE-TAIL-FORKS-5-))
(not (QUEUE-SIZE-FORKS-5--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-5--QUEUE-1-QS-0-QS-0-FORK-EMPTY-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-5--ZERO)
(QUEUE-HEAD-MSG-FORKS-5--EMPTY)
(QUEUE-TAIL-MSG-FORKS-5--FORK)
(ADVANCE-TAIL-FORKS-5-)
(QUEUE-TAIL-FORKS-5--QS-0)
)
:effect
(and
(SETTLED-FORKS-5-)
(QUEUE-TAIL-FORKS-5--QS-0)
(QUEUE-MSG-FORKS-5--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-5--FORK)
(QUEUE-SIZE-FORKS-5--ONE)
(not (ADVANCE-TAIL-FORKS-5-))
(not (QUEUE-HEAD-MSG-FORKS-5--EMPTY))
(not (QUEUE-SIZE-FORKS-5--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-6--QUEUE-1-QS-0-QS-0-FORK-FORK-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-6--ZERO)
(QUEUE-HEAD-MSG-FORKS-6--FORK)
(QUEUE-TAIL-MSG-FORKS-6--FORK)
(ADVANCE-TAIL-FORKS-6-)
(QUEUE-TAIL-FORKS-6--QS-0)
)
:effect
(and
(SETTLED-FORKS-6-)
(QUEUE-TAIL-FORKS-6--QS-0)
(QUEUE-MSG-FORKS-6--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-6--FORK)
(QUEUE-SIZE-FORKS-6--ONE)
(not (ADVANCE-TAIL-FORKS-6-))
(not (QUEUE-SIZE-FORKS-6--ZERO))
)
)
(:action ADVANCE-EMPTY-QUEUE-TAIL-FORKS-6--QUEUE-1-QS-0-QS-0-FORK-EMPTY-ZERO-ONE-0
:parameters ()
:precondition
(and
(QUEUE-SIZE-FORKS-6--ZERO)
(QUEUE-HEAD-MSG-FORKS-6--EMPTY)
(QUEUE-TAIL-MSG-FORKS-6--FORK)
(ADVANCE-TAIL-FORKS-6-)
(QUEUE-TAIL-FORKS-6--QS-0)
)
:effect
(and
(SETTLED-FORKS-6-)
(QUEUE-TAIL-FORKS-6--QS-0)
(QUEUE-MSG-FORKS-6--QS-0-FORK)
(QUEUE-HEAD-MSG-FORKS-6--FORK)
(QUEUE-SIZE-FORKS-6--ONE)
(not (ADVANCE-TAIL-FORKS-6-))
(not (QUEUE-HEAD-MSG-FORKS-6--EMPTY))
(not (QUEUE-SIZE-FORKS-6--ZERO))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-0-FORKS--PID-WFORK-FORKS-0--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-0-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-0-)
(QUEUE-TAIL-MSG-FORKS-0--FORK)
(not (ACTIVATE-PHILOSOPHER-0-FORKS--PID-WFORK))
(not (SETTLED-FORKS-0-))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-1-FORKS--PID-WFORK-FORKS-1--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-1-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-1-)
(QUEUE-TAIL-MSG-FORKS-1--FORK)
(not (ACTIVATE-PHILOSOPHER-1-FORKS--PID-WFORK))
(not (SETTLED-FORKS-1-))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-2-FORKS--PID-WFORK-FORKS-2--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-2-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-2-)
(QUEUE-TAIL-MSG-FORKS-2--FORK)
(not (ACTIVATE-PHILOSOPHER-2-FORKS--PID-WFORK))
(not (SETTLED-FORKS-2-))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-3-FORKS--PID-WFORK-FORKS-3--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-3-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-3-)
(QUEUE-TAIL-MSG-FORKS-3--FORK)
(not (ACTIVATE-PHILOSOPHER-3-FORKS--PID-WFORK))
(not (SETTLED-FORKS-3-))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-4-FORKS--PID-WFORK-FORKS-4--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-4-)
(ACTIVATE-PHILOSOPHER-4-FORKS--PID-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-4-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-4-)
(QUEUE-TAIL-MSG-FORKS-4--FORK)
(not (ACTIVATE-PHILOSOPHER-4-FORKS--PID-WFORK))
(not (SETTLED-FORKS-4-))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-5-FORKS--PID-WFORK-FORKS-5--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-5-)
(ACTIVATE-PHILOSOPHER-5-FORKS--PID-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-5-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-5-)
(QUEUE-TAIL-MSG-FORKS-5--FORK)
(not (ACTIVATE-PHILOSOPHER-5-FORKS--PID-WFORK))
(not (SETTLED-FORKS-5-))
)
)
(:action QUEUE-WRITE-PHILOSOPHER-6-FORKS--PID-WFORK-FORKS-6--FORK-0
:parameters ()
:precondition
(and
(SETTLED-FORKS-6-)
(ACTIVATE-PHILOSOPHER-6-FORKS--PID-WFORK)
)
:effect
(and
(ENABLED-PHILOSOPHER-6-FORKS--PID-WFORK)
(ADVANCE-TAIL-FORKS-6-)
(QUEUE-TAIL-MSG-FORKS-6--FORK)
(not (ACTIVATE-PHILOSOPHER-6-FORKS--PID-WFORK))
(not (SETTLED-FORKS-6-))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-0-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-0)
(AT-PROCESS-PHILOSOPHER-0-STATE-1)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-0))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-1-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-1)
(AT-PROCESS-PHILOSOPHER-1-STATE-1)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-1))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-2-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-2)
(AT-PROCESS-PHILOSOPHER-2-STATE-1)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-2))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-3-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-3)
(AT-PROCESS-PHILOSOPHER-3-STATE-1)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-3))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-4-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-4)
(AT-PROCESS-PHILOSOPHER-4-STATE-1)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-4-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-4))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-5-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-5)
(AT-PROCESS-PHILOSOPHER-5-STATE-1)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-5-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-5))
)
)
(:action ACTIVATE-TRANS-PHILOSOPHER-6-PHILOSOPHER-FORKS--PID-WFORK-STATE-1-STATE-6-0
:parameters ()
:precondition
(and
(PENDING-PHILOSOPHER-6)
(AT-PROCESS-PHILOSOPHER-6-STATE-1)
(SETTLED-FORKS-0-)
(SETTLED-FORKS-1-)
(SETTLED-FORKS-2-)
(SETTLED-FORKS-3-)
(SETTLED-FORKS-4-)
(SETTLED-FORKS-5-)
(SETTLED-FORKS-6-)
)
:effect
(and
(ACTIVATE-PHILOSOPHER-6-FORKS--PID-WFORK)
(not (PENDING-PHILOSOPHER-6))
)
)
(:derived (BLOCKED-PHILOSOPHER-0)
(and
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__7_-WFORK)
(AT-PROCESS-PHILOSOPHER-0-STATE-5)
)
)
(:derived (BLOCKED-PHILOSOPHER-1)
(and
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__7_-WFORK)
(AT-PROCESS-PHILOSOPHER-1-STATE-5)
)
)
(:derived (BLOCKED-PHILOSOPHER-2)
(and
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__7_-WFORK)
(AT-PROCESS-PHILOSOPHER-2-STATE-5)
)
)
(:derived (BLOCKED-PHILOSOPHER-3)
(and
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__7_-WFORK)
(AT-PROCESS-PHILOSOPHER-3-STATE-5)
)
)
(:derived (BLOCKED-PHILOSOPHER-4)
(and
(BLOCKED-TRANS-PHILOSOPHER-4-FORKS-__-PIDP1__7_-WFORK)
(AT-PROCESS-PHILOSOPHER-4-STATE-5)
)
)
(:derived (BLOCKED-PHILOSOPHER-5)
(and
(BLOCKED-TRANS-PHILOSOPHER-5-FORKS-__-PIDP1__7_-WFORK)
(AT-PROCESS-PHILOSOPHER-5-STATE-5)
)
)
(:derived (BLOCKED-PHILOSOPHER-6)
(and
(BLOCKED-TRANS-PHILOSOPHER-6-FORKS-__-PIDP1__7_-WFORK)
(AT-PROCESS-PHILOSOPHER-6-STATE-5)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-6-FORKS-__-PIDP1__7_-WFORK)
(and
(QUEUE-SIZE-FORKS-0--ONE)
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-6-FORKS-__-PIDP1__7_-WFORK)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__7_-WFORK)
(and
(QUEUE-SIZE-FORKS-1--ONE)
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__7_-WFORK)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__7_-WFORK)
(and
(QUEUE-SIZE-FORKS-2--ONE)
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__7_-WFORK)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__7_-WFORK)
(and
(QUEUE-SIZE-FORKS-3--ONE)
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__7_-WFORK)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__7_-WFORK)
(and
(QUEUE-SIZE-FORKS-4--ONE)
(SETTLED-FORKS-4-)
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__7_-WFORK)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-4-FORKS-__-PIDP1__7_-WFORK)
(and
(QUEUE-SIZE-FORKS-5--ONE)
(SETTLED-FORKS-5-)
(ACTIVATE-PHILOSOPHER-4-FORKS-__-PIDP1__7_-WFORK)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-5-FORKS-__-PIDP1__7_-WFORK)
(and
(QUEUE-SIZE-FORKS-6--ONE)
(SETTLED-FORKS-6-)
(ACTIVATE-PHILOSOPHER-5-FORKS-__-PIDP1__7_-WFORK)
)
)
(:derived (BLOCKED-PHILOSOPHER-0)
(and
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__7_-RFORK)
(AT-PROCESS-PHILOSOPHER-0-STATE-3)
)
)
(:derived (BLOCKED-PHILOSOPHER-1)
(and
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__7_-RFORK)
(AT-PROCESS-PHILOSOPHER-1-STATE-3)
)
)
(:derived (BLOCKED-PHILOSOPHER-2)
(and
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__7_-RFORK)
(AT-PROCESS-PHILOSOPHER-2-STATE-3)
)
)
(:derived (BLOCKED-PHILOSOPHER-3)
(and
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__7_-RFORK)
(AT-PROCESS-PHILOSOPHER-3-STATE-3)
)
)
(:derived (BLOCKED-PHILOSOPHER-4)
(and
(BLOCKED-TRANS-PHILOSOPHER-4-FORKS-__-PIDP1__7_-RFORK)
(AT-PROCESS-PHILOSOPHER-4-STATE-3)
)
)
(:derived (BLOCKED-PHILOSOPHER-5)
(and
(BLOCKED-TRANS-PHILOSOPHER-5-FORKS-__-PIDP1__7_-RFORK)
(AT-PROCESS-PHILOSOPHER-5-STATE-3)
)
)
(:derived (BLOCKED-PHILOSOPHER-6)
(and
(BLOCKED-TRANS-PHILOSOPHER-6-FORKS-__-PIDP1__7_-RFORK)
(AT-PROCESS-PHILOSOPHER-6-STATE-3)
)
)
(:derived (BLOCKED-PHILOSOPHER-0)
(and
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-0-STATE-4)
)
)
(:derived (BLOCKED-PHILOSOPHER-1)
(and
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-1-STATE-4)
)
)
(:derived (BLOCKED-PHILOSOPHER-2)
(and
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-2-STATE-4)
)
)
(:derived (BLOCKED-PHILOSOPHER-3)
(and
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-3-STATE-4)
)
)
(:derived (BLOCKED-PHILOSOPHER-4)
(and
(BLOCKED-TRANS-PHILOSOPHER-4-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-4-STATE-4)
)
)
(:derived (BLOCKED-PHILOSOPHER-5)
(and
(BLOCKED-TRANS-PHILOSOPHER-5-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-5-STATE-4)
)
)
(:derived (BLOCKED-PHILOSOPHER-6)
(and
(BLOCKED-TRANS-PHILOSOPHER-6-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-6-STATE-4)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-6-FORKS-__-PIDP1__7_-RFORK)
(and
(ACTIVATE-PHILOSOPHER-6-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-0-)
(QUEUE-HEAD-MSG-FORKS-0--EMPTY)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__7_-RFORK)
(and
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-1-)
(QUEUE-HEAD-MSG-FORKS-1--EMPTY)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__7_-RFORK)
(and
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-2-)
(QUEUE-HEAD-MSG-FORKS-2--EMPTY)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__7_-RFORK)
(and
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-3-)
(QUEUE-HEAD-MSG-FORKS-3--EMPTY)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__7_-RFORK)
(and
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-4-)
(QUEUE-HEAD-MSG-FORKS-4--EMPTY)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-4-FORKS-__-PIDP1__7_-RFORK)
(and
(ACTIVATE-PHILOSOPHER-4-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-5-)
(QUEUE-HEAD-MSG-FORKS-5--EMPTY)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-5-FORKS-__-PIDP1__7_-RFORK)
(and
(ACTIVATE-PHILOSOPHER-5-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-6-)
(QUEUE-HEAD-MSG-FORKS-6--EMPTY)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-6-FORKS-__-PIDP1__7_-RFORK)
(and
(ACTIVATE-PHILOSOPHER-6-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-0-)
(QUEUE-SIZE-FORKS-0--ZERO)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-0-FORKS-__-PIDP1__7_-RFORK)
(and
(ACTIVATE-PHILOSOPHER-0-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-1-)
(QUEUE-SIZE-FORKS-1--ZERO)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-1-FORKS-__-PIDP1__7_-RFORK)
(and
(ACTIVATE-PHILOSOPHER-1-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-2-)
(QUEUE-SIZE-FORKS-2--ZERO)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-2-FORKS-__-PIDP1__7_-RFORK)
(and
(ACTIVATE-PHILOSOPHER-2-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-3-)
(QUEUE-SIZE-FORKS-3--ZERO)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-3-FORKS-__-PIDP1__7_-RFORK)
(and
(ACTIVATE-PHILOSOPHER-3-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-4-)
(QUEUE-SIZE-FORKS-4--ZERO)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-4-FORKS-__-PIDP1__7_-RFORK)
(and
(ACTIVATE-PHILOSOPHER-4-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-5-)
(QUEUE-SIZE-FORKS-5--ZERO)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-5-FORKS-__-PIDP1__7_-RFORK)
(and
(ACTIVATE-PHILOSOPHER-5-FORKS-__-PIDP1__7_-RFORK)
(SETTLED-FORKS-6-)
(QUEUE-SIZE-FORKS-6--ZERO)
)
)
(:derived (BLOCKED-PHILOSOPHER-0)
(and
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-0-STATE-1)
)
)
(:derived (BLOCKED-PHILOSOPHER-1)
(and
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-1-STATE-1)
)
)
(:derived (BLOCKED-PHILOSOPHER-2)
(and
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-2-STATE-1)
)
)
(:derived (BLOCKED-PHILOSOPHER-3)
(and
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-3-STATE-1)
)
)
(:derived (BLOCKED-PHILOSOPHER-4)
(and
(BLOCKED-TRANS-PHILOSOPHER-4-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-4-STATE-1)
)
)
(:derived (BLOCKED-PHILOSOPHER-5)
(and
(BLOCKED-TRANS-PHILOSOPHER-5-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-5-STATE-1)
)
)
(:derived (BLOCKED-PHILOSOPHER-6)
(and
(BLOCKED-TRANS-PHILOSOPHER-6-FORKS--PID-WFORK)
(AT-PROCESS-PHILOSOPHER-6-STATE-1)
)
)
(:derived (BLOCKED-PHILOSOPHER-0)
(and
(BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK)
(AT-PROCESS-PHILOSOPHER-0-STATE-6)
)
)
(:derived (BLOCKED-PHILOSOPHER-1)
(and
(BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK)
(AT-PROCESS-PHILOSOPHER-1-STATE-6)
)
)
(:derived (BLOCKED-PHILOSOPHER-2)
(and
(BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK)
(AT-PROCESS-PHILOSOPHER-2-STATE-6)
)
)
(:derived (BLOCKED-PHILOSOPHER-3)
(and
(BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK)
(AT-PROCESS-PHILOSOPHER-3-STATE-6)
)
)
(:derived (BLOCKED-PHILOSOPHER-4)
(and
(BLOCKED-TRANS-PHILOSOPHER-4-FORKS--PID-RFORK)
(AT-PROCESS-PHILOSOPHER-4-STATE-6)
)
)
(:derived (BLOCKED-PHILOSOPHER-5)
(and
(BLOCKED-TRANS-PHILOSOPHER-5-FORKS--PID-RFORK)
(AT-PROCESS-PHILOSOPHER-5-STATE-6)
)
)
(:derived (BLOCKED-PHILOSOPHER-6)
(and
(BLOCKED-TRANS-PHILOSOPHER-6-FORKS--PID-RFORK)
(AT-PROCESS-PHILOSOPHER-6-STATE-6)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK)
(and
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-RFORK)
(SETTLED-FORKS-0-)
(QUEUE-HEAD-MSG-FORKS-0--EMPTY)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK)
(and
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-RFORK)
(SETTLED-FORKS-1-)
(QUEUE-HEAD-MSG-FORKS-1--EMPTY)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK)
(and
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-RFORK)
(SETTLED-FORKS-2-)
(QUEUE-HEAD-MSG-FORKS-2--EMPTY)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK)
(and
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-RFORK)
(SETTLED-FORKS-3-)
(QUEUE-HEAD-MSG-FORKS-3--EMPTY)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-4-FORKS--PID-RFORK)
(and
(ACTIVATE-PHILOSOPHER-4-FORKS--PID-RFORK)
(SETTLED-FORKS-4-)
(QUEUE-HEAD-MSG-FORKS-4--EMPTY)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-5-FORKS--PID-RFORK)
(and
(ACTIVATE-PHILOSOPHER-5-FORKS--PID-RFORK)
(SETTLED-FORKS-5-)
(QUEUE-HEAD-MSG-FORKS-5--EMPTY)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-6-FORKS--PID-RFORK)
(and
(ACTIVATE-PHILOSOPHER-6-FORKS--PID-RFORK)
(SETTLED-FORKS-6-)
(QUEUE-HEAD-MSG-FORKS-6--EMPTY)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-WFORK)
(and
(QUEUE-SIZE-FORKS-0--ONE)
(SETTLED-FORKS-0-)
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-WFORK)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-WFORK)
(and
(QUEUE-SIZE-FORKS-1--ONE)
(SETTLED-FORKS-1-)
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-WFORK)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-WFORK)
(and
(QUEUE-SIZE-FORKS-2--ONE)
(SETTLED-FORKS-2-)
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-WFORK)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-WFORK)
(and
(QUEUE-SIZE-FORKS-3--ONE)
(SETTLED-FORKS-3-)
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-WFORK)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-4-FORKS--PID-WFORK)
(and
(QUEUE-SIZE-FORKS-4--ONE)
(SETTLED-FORKS-4-)
(ACTIVATE-PHILOSOPHER-4-FORKS--PID-WFORK)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-5-FORKS--PID-WFORK)
(and
(QUEUE-SIZE-FORKS-5--ONE)
(SETTLED-FORKS-5-)
(ACTIVATE-PHILOSOPHER-5-FORKS--PID-WFORK)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-6-FORKS--PID-WFORK)
(and
(QUEUE-SIZE-FORKS-6--ONE)
(SETTLED-FORKS-6-)
(ACTIVATE-PHILOSOPHER-6-FORKS--PID-WFORK)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-0-FORKS--PID-RFORK)
(and
(ACTIVATE-PHILOSOPHER-0-FORKS--PID-RFORK)
(SETTLED-FORKS-0-)
(QUEUE-SIZE-FORKS-0--ZERO)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-1-FORKS--PID-RFORK)
(and
(ACTIVATE-PHILOSOPHER-1-FORKS--PID-RFORK)
(SETTLED-FORKS-1-)
(QUEUE-SIZE-FORKS-1--ZERO)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-2-FORKS--PID-RFORK)
(and
(ACTIVATE-PHILOSOPHER-2-FORKS--PID-RFORK)
(SETTLED-FORKS-2-)
(QUEUE-SIZE-FORKS-2--ZERO)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-3-FORKS--PID-RFORK)
(and
(ACTIVATE-PHILOSOPHER-3-FORKS--PID-RFORK)
(SETTLED-FORKS-3-)
(QUEUE-SIZE-FORKS-3--ZERO)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-4-FORKS--PID-RFORK)
(and
(ACTIVATE-PHILOSOPHER-4-FORKS--PID-RFORK)
(SETTLED-FORKS-4-)
(QUEUE-SIZE-FORKS-4--ZERO)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-5-FORKS--PID-RFORK)
(and
(ACTIVATE-PHILOSOPHER-5-FORKS--PID-RFORK)
(SETTLED-FORKS-5-)
(QUEUE-SIZE-FORKS-5--ZERO)
)
)
(:derived (BLOCKED-TRANS-PHILOSOPHER-6-FORKS--PID-RFORK)
(and
(ACTIVATE-PHILOSOPHER-6-FORKS--PID-RFORK)
(SETTLED-FORKS-6-)
(QUEUE-SIZE-FORKS-6--ZERO)
)
)
)
