
(define (problem roverprob1425)
        (:domain rover)
        (:objects general - lander colour - mode high_res - mode low_res - mode
         rover0 - rover rover1 - rover rover2 - rover rover3 - rover
         rover0store - store rover1store - store rover2store - store
         rover3store - store waypoint0 - waypoint waypoint1 - waypoint
         waypoint2 - waypoint waypoint3 - waypoint waypoint4 - waypoint
         waypoint5 - waypoint waypoint6 - waypoint waypoint7 - waypoint
         waypoint8 - waypoint waypoint9 - waypoint camera0 - camera camera1 -
         camera camera2 - camera camera3 - camera camera4 - camera objective0 -
         objective objective1 - objective objective2 - objective objective3 -
         objective)
        (:init (visible waypoint0 waypoint3) (visible waypoint3 waypoint0)
         (visible waypoint0 waypoint9) (visible waypoint9 waypoint0)
         (visible waypoint1 waypoint8) (visible waypoint8 waypoint1)
         (visible waypoint2 waypoint1) (visible waypoint1 waypoint2)
         (visible waypoint2 waypoint3) (visible waypoint3 waypoint2)
         (visible waypoint2 waypoint6) (visible waypoint6 waypoint2)
         (visible waypoint2 waypoint9) (visible waypoint9 waypoint2)
         (visible waypoint3 waypoint5) (visible waypoint5 waypoint3)
         (visible waypoint3 waypoint6) (visible waypoint6 waypoint3)
         (visible waypoint3 waypoint7) (visible waypoint7 waypoint3)
         (visible waypoint4 waypoint0) (visible waypoint0 waypoint4)
         (visible waypoint4 waypoint1) (visible waypoint1 waypoint4)
         (visible waypoint4 waypoint2) (visible waypoint2 waypoint4)
         (visible waypoint4 waypoint8) (visible waypoint8 waypoint4)
         (visible waypoint4 waypoint9) (visible waypoint9 waypoint4)
         (visible waypoint5 waypoint1) (visible waypoint1 waypoint5)
         (visible waypoint5 waypoint2) (visible waypoint2 waypoint5)
         (visible waypoint5 waypoint4) (visible waypoint4 waypoint5)
         (visible waypoint5 waypoint6) (visible waypoint6 waypoint5)
         (visible waypoint6 waypoint0) (visible waypoint0 waypoint6)
         (visible waypoint6 waypoint1) (visible waypoint1 waypoint6)
         (visible waypoint6 waypoint4) (visible waypoint4 waypoint6)
         (visible waypoint7 waypoint1) (visible waypoint1 waypoint7)
         (visible waypoint7 waypoint5) (visible waypoint5 waypoint7)
         (visible waypoint7 waypoint8) (visible waypoint8 waypoint7)
         (visible waypoint8 waypoint6) (visible waypoint6 waypoint8)
         (visible waypoint8 waypoint9) (visible waypoint9 waypoint8)
         (visible waypoint9 waypoint3) (visible waypoint3 waypoint9)
         (visible waypoint9 waypoint6) (visible waypoint6 waypoint9)
         (at_rock_sample waypoint1) (at_soil_sample waypoint3)
         (at_rock_sample waypoint3) (at_soil_sample waypoint4)
         (at_rock_sample waypoint4) (at_rock_sample waypoint5)
         (at_soil_sample waypoint6) (at_rock_sample waypoint8)
         (at_soil_sample waypoint9) (at_lander general waypoint7)
         (channel_free general) (at rover0 waypoint1) (available rover0)
         (store_of rover0store rover0) (empty rover0store)
         (equipped_for_soil_analysis rover0) (equipped_for_imaging rover0)
         (can_traverse rover0 waypoint1 waypoint2)
         (can_traverse rover0 waypoint2 waypoint1)
         (can_traverse rover0 waypoint1 waypoint4)
         (can_traverse rover0 waypoint4 waypoint1)
         (can_traverse rover0 waypoint1 waypoint6)
         (can_traverse rover0 waypoint6 waypoint1)
         (can_traverse rover0 waypoint1 waypoint8)
         (can_traverse rover0 waypoint8 waypoint1)
         (can_traverse rover0 waypoint2 waypoint3)
         (can_traverse rover0 waypoint3 waypoint2)
         (can_traverse rover0 waypoint4 waypoint0)
         (can_traverse rover0 waypoint0 waypoint4)
         (can_traverse rover0 waypoint4 waypoint5)
         (can_traverse rover0 waypoint5 waypoint4)
         (can_traverse rover0 waypoint4 waypoint9)
         (can_traverse rover0 waypoint9 waypoint4)
         (can_traverse rover0 waypoint8 waypoint7)
         (can_traverse rover0 waypoint7 waypoint8) (at rover1 waypoint4)
         (available rover1) (store_of rover1store rover1) (empty rover1store)
         (equipped_for_soil_analysis rover1)
         (equipped_for_rock_analysis rover1) (equipped_for_imaging rover1)
         (can_traverse rover1 waypoint4 waypoint0)
         (can_traverse rover1 waypoint0 waypoint4)
         (can_traverse rover1 waypoint4 waypoint2)
         (can_traverse rover1 waypoint2 waypoint4)
         (can_traverse rover1 waypoint4 waypoint5)
         (can_traverse rover1 waypoint5 waypoint4)
         (can_traverse rover1 waypoint4 waypoint6)
         (can_traverse rover1 waypoint6 waypoint4)
         (can_traverse rover1 waypoint4 waypoint9)
         (can_traverse rover1 waypoint9 waypoint4)
         (can_traverse rover1 waypoint0 waypoint3)
         (can_traverse rover1 waypoint3 waypoint0)
         (can_traverse rover1 waypoint2 waypoint1)
         (can_traverse rover1 waypoint1 waypoint2)
         (can_traverse rover1 waypoint5 waypoint7)
         (can_traverse rover1 waypoint7 waypoint5)
         (can_traverse rover1 waypoint6 waypoint8)
         (can_traverse rover1 waypoint8 waypoint6) (at rover2 waypoint0)
         (available rover2) (store_of rover2store rover2) (empty rover2store)
         (equipped_for_imaging rover2)
         (can_traverse rover2 waypoint0 waypoint3)
         (can_traverse rover2 waypoint3 waypoint0)
         (can_traverse rover2 waypoint0 waypoint4)
         (can_traverse rover2 waypoint4 waypoint0)
         (can_traverse rover2 waypoint0 waypoint6)
         (can_traverse rover2 waypoint6 waypoint0)
         (can_traverse rover2 waypoint0 waypoint9)
         (can_traverse rover2 waypoint9 waypoint0)
         (can_traverse rover2 waypoint3 waypoint2)
         (can_traverse rover2 waypoint2 waypoint3)
         (can_traverse rover2 waypoint4 waypoint1)
         (can_traverse rover2 waypoint1 waypoint4)
         (can_traverse rover2 waypoint4 waypoint5)
         (can_traverse rover2 waypoint5 waypoint4)
         (can_traverse rover2 waypoint4 waypoint8)
         (can_traverse rover2 waypoint8 waypoint4) (at rover3 waypoint2)
         (available rover3) (store_of rover3store rover3) (empty rover3store)
         (equipped_for_imaging rover3)
         (can_traverse rover3 waypoint2 waypoint1)
         (can_traverse rover3 waypoint1 waypoint2)
         (can_traverse rover3 waypoint2 waypoint6)
         (can_traverse rover3 waypoint6 waypoint2)
         (can_traverse rover3 waypoint2 waypoint9)
         (can_traverse rover3 waypoint9 waypoint2)
         (can_traverse rover3 waypoint1 waypoint4)
         (can_traverse rover3 waypoint4 waypoint1)
         (can_traverse rover3 waypoint1 waypoint5)
         (can_traverse rover3 waypoint5 waypoint1)
         (can_traverse rover3 waypoint1 waypoint7)
         (can_traverse rover3 waypoint7 waypoint1)
         (can_traverse rover3 waypoint6 waypoint0)
         (can_traverse rover3 waypoint0 waypoint6)
         (can_traverse rover3 waypoint6 waypoint3)
         (can_traverse rover3 waypoint3 waypoint6)
         (can_traverse rover3 waypoint6 waypoint8)
         (can_traverse rover3 waypoint8 waypoint6) (on_board camera0 rover3)
         (calibration_target camera0 objective2) (supports camera0 colour)
         (supports camera0 low_res) (on_board camera1 rover2)
         (calibration_target camera1 objective3) (supports camera1 colour)
         (on_board camera2 rover1) (calibration_target camera2 objective3)
         (supports camera2 low_res) (on_board camera3 rover1)
         (calibration_target camera3 objective0) (supports camera3 colour)
         (supports camera3 low_res) (on_board camera4 rover0)
         (calibration_target camera4 objective3) (supports camera4 colour)
         (supports camera4 low_res) (visible_from objective0 waypoint0)
         (visible_from objective0 waypoint1)
         (visible_from objective0 waypoint2)
         (visible_from objective0 waypoint3)
         (visible_from objective0 waypoint4)
         (visible_from objective0 waypoint5)
         (visible_from objective0 waypoint6)
         (visible_from objective1 waypoint0)
         (visible_from objective1 waypoint1)
         (visible_from objective1 waypoint2)
         (visible_from objective1 waypoint3)
         (visible_from objective1 waypoint4)
         (visible_from objective1 waypoint5)
         (visible_from objective1 waypoint6)
         (visible_from objective2 waypoint0)
         (visible_from objective2 waypoint1)
         (visible_from objective2 waypoint2)
         (visible_from objective2 waypoint3)
         (visible_from objective2 waypoint4)
         (visible_from objective2 waypoint5)
         (visible_from objective2 waypoint6)
         (visible_from objective2 waypoint7)
         (visible_from objective2 waypoint8)
         (visible_from objective3 waypoint0)
         (visible_from objective3 waypoint1)
         (visible_from objective3 waypoint2)
         (visible_from objective3 waypoint3)
         (visible_from objective3 waypoint4)
         (visible_from objective3 waypoint5)
         (visible_from objective3 waypoint6))
        (:goal
         (and (communicated_soil_data waypoint3)
              (communicated_soil_data waypoint6)
              (communicated_rock_data waypoint5)
              (communicated_rock_data waypoint4)
              (communicated_rock_data waypoint8)
              (communicated_image_data objective0 colour)
              (communicated_image_data objective2 low_res)
              (communicated_image_data objective0 low_res)))
        (:constraints
         (and (preference a0 (always (at rover3 waypoint2)))
              (preference a1 (always (at rover2 waypoint0)))
              (preference e0 (sometime (at rover3 waypoint8)))
              (preference e1 (sometime (at rover3 waypoint1)))
              (preference e2 (sometime (at rover2 waypoint3)))
              (preference e3 (sometime (at rover1 waypoint0)))
              (preference e4 (sometime (at rover1 waypoint3)))
              (preference e5 (sometime (at rover0 waypoint6)))
              (preference e6 (sometime (full rover1store)))
              (preference e7 (sometime (have_soil_analysis rover1 waypoint6)))
              (preference e8 (sometime (have_soil_analysis rover0 waypoint6)))
              (preference e9 (sometime (calibrated camera1 rover2)))
              (preference e10 (sometime (calibrated camera3 rover1)))
              (preference e11 (sometime (calibrated camera2 rover1)))
              (preference e12
               (sometime (have_image rover3 objective2 low_res)))
              (preference e13
               (sometime (have_image rover3 objective0 low_res)))
              (preference e14 (sometime (have_image rover2 objective0 colour)))
              (preference e15
               (sometime (have_image rover1 objective2 low_res)))
              (preference e16
               (sometime (have_image rover1 objective0 low_res)))
              (preference e17 (sometime (have_image rover1 objective0 colour)))
              (preference e18
               (sometime (have_image rover0 objective2 low_res)))
              (preference e19
               (sometime (have_image rover0 objective0 low_res)))
              (preference e20 (sometime (have_image rover0 objective0 colour)))
              (preference o0 (at-most-once (at rover1 waypoint4)))
              (preference o1 (at-most-once (at rover1 waypoint8)))
              (preference o2 (at-most-once (at rover1 waypoint6)))
              (preference o3 (at-most-once (at rover1 waypoint5)))
              (preference o4 (at-most-once (at rover0 waypoint1)))
              (preference o5 (at-most-once (at rover0 waypoint2)))
              (preference o6 (at-most-once (empty rover0store)))
              (preference o7 (at-most-once (full rover0store)))
              (preference o8 (at-most-once (calibrated camera0 rover3)))
              (preference o9 (at-most-once (calibrated camera4 rover0)))
              (preference sb13
               (sometime-before (at rover1 waypoint8)
                (have_soil_analysis rover0 waypoint6)))
              (preference sb28
               (sometime-before (at rover1 waypoint8)
                (have_image rover0 objective0 low_res)))
              (preference sb29
               (sometime-before (at rover1 waypoint8)
                (have_image rover0 objective0 colour)))
              (preference sb43
               (sometime-before (at rover1 waypoint5)
                (calibrated camera1 rover2)))
              (preference sb50
               (sometime-before (at rover1 waypoint5)
                (have_image rover1 objective2 low_res)))
              (preference sb65
               (sometime-before (at rover0 waypoint3) (full rover0store)))
              (preference sb74
               (sometime-before (at rover0 waypoint3)
                (calibrated camera4 rover0)))
              (preference sb81
               (sometime-before (at rover0 waypoint3)
                (have_image rover0 objective0 low_res)))
              (preference sb91
               (sometime-before (have_soil_analysis rover0 waypoint3)
                (at rover0 waypoint6)))
              (preference sb97
               (sometime-before (have_soil_analysis rover0 waypoint3)
                (have_rock_analysis rover1 waypoint8)))
              (preference sb101
               (sometime-before (have_soil_analysis rover0 waypoint3)
                (calibrated camera1 rover2)))
              (preference sb105
               (sometime-before (have_soil_analysis rover0 waypoint3)
                (have_image rover3 objective2 low_res)))
              (preference sb119
               (sometime-before (have_rock_analysis rover1 waypoint8)
                (at rover1 waypoint3)))
              (preference sb123
               (sometime-before (have_rock_analysis rover1 waypoint8)
                (full rover1store)))
              (preference sb125
               (sometime-before (have_rock_analysis rover1 waypoint8)
                (full rover0store)))
              (preference sb130
               (sometime-before (have_rock_analysis rover1 waypoint8)
                (calibrated camera1 rover2)))
              (preference sb137
               (sometime-before (have_rock_analysis rover1 waypoint8)
                (have_image rover1 objective2 low_res)))
              (preference sb139
               (sometime-before (have_rock_analysis rover1 waypoint8)
                (have_image rover1 objective0 colour)))
              (preference sb153
               (sometime-before (have_rock_analysis rover1 waypoint5)
                (have_soil_analysis rover0 waypoint3)))
              (preference sb161
               (sometime-before (have_rock_analysis rover1 waypoint5)
                (have_image rover3 objective2 low_res)))
              (preference sb165
               (sometime-before (have_rock_analysis rover1 waypoint5)
                (have_image rover1 objective0 low_res)))
              (preference sb166
               (sometime-before (have_rock_analysis rover1 waypoint5)
                (have_image rover1 objective0 colour)))
              (preference sb170
               (sometime-before (have_rock_analysis rover1 waypoint4)
                (at rover1 waypoint5)))
              (preference sb171
               (sometime-before (have_rock_analysis rover1 waypoint4)
                (at rover0 waypoint3)))
              (preference sb173
               (sometime-before (have_rock_analysis rover1 waypoint4)
                (full rover1store)))
              (preference sb174
               (sometime-before (have_rock_analysis rover1 waypoint4)
                (full rover0store)))
              (preference sb183
               (sometime-before (have_rock_analysis rover1 waypoint4)
                (have_image rover1 objective0 low_res)))))
        (:metric minimize
         (+ (* (is-violated sb183) 36.9231)
            (* (is-violated sb174) 39.9095)
            (* (is-violated sb173) 26.0633)
            (* (is-violated sb171) 39.9095)
            (* (is-violated sb170) 36.9231)
            (* (is-violated sb166) 39.9095)
            (* (is-violated sb165) 26.0633)
            (* (is-violated sb161) 36.9231)
            (* (is-violated sb153) 36.9231)
            (* (is-violated sb139) 39.9095)
            (* (is-violated sb137) 26.0633)
            (* (is-violated sb130) 26.0633)
            (* (is-violated sb125) 26.0633)
            (* (is-violated sb123) 26.0633)
            (* (is-violated sb119) 26.0633)
            (* (is-violated sb105) 36.9231)
            (* (is-violated sb101) 26.0633)
            (* (is-violated sb97) 43.7104)
            (* (is-violated sb91) 26.0633)
            (* (is-violated sb81) 43.7104)
            (* (is-violated sb74) 27.4208)
            (* (is-violated sb65) 26.0633)
            (* (is-violated sb50) 26.0633)
            (* (is-violated sb43) 26.0633)
            (* (is-violated sb29) 26.0633)
            (* (is-violated sb28) 42.3529)
            (* (is-violated sb13) 26.0633)
            (* (is-violated o9) 27.4208)
            (* (is-violated o8) 26.0633)
            (* (is-violated o7) 36.9231)
            (* (is-violated o6) 36.9231)
            (* (is-violated o5) 39.9095)
            (* (is-violated o4) 39.9095)
            (* (is-violated o3) 26.0633)
            (* (is-violated o2) 36.9231)
            (* (is-violated o1) 26.0633)
            (* (is-violated o0) 27.4208)
            (* (is-violated e20) 26.0633)
            (* (is-violated e19) 42.3529)
            (* (is-violated e18) 39.9095)
            (* (is-violated e17) 39.9095)
            (* (is-violated e16) 26.0633)
            (* (is-violated e15) 26.0633)
            (* (is-violated e14) 26.0633)
            (* (is-violated e13) 26.0633)
            (* (is-violated e12) 36.9231)
            (* (is-violated e11) 26.0633)
            (* (is-violated e10) 26.0633)
            (* (is-violated e9) 26.0633)
            (* (is-violated e8) 26.0633)
            (* (is-violated e7) 36.9231)
            (* (is-violated e6) 26.0633)
            (* (is-violated e5) 26.0633)
            (* (is-violated e4) 26.0633)
            (* (is-violated e3) 26.0633)
            (* (is-violated e2) 27.4208)
            (* (is-violated e1) 26.0633)
            (* (is-violated e0) 27.4208)
            (* (is-violated a1) 26.0633)
            (* (is-violated a0) 36.9231)
	)))
