
(define (problem roverprob7126)
        (:domain rover)
        (:objects general - lander colour - mode high_res - mode low_res - mode
         rover0 - rover rover1 - rover rover2 - rover rover3 - rover
         rover0store - store rover1store - store rover2store - store
         rover3store - store waypoint0 - waypoint waypoint1 - waypoint
         waypoint2 - waypoint waypoint3 - waypoint waypoint4 - waypoint
         waypoint5 - waypoint waypoint6 - waypoint waypoint7 - waypoint camera0
         - camera camera1 - camera camera2 - camera camera3 - camera objective0
         - objective objective1 - objective objective2 - objective)
        (:init (visible waypoint0 waypoint4) (visible waypoint4 waypoint0)
         (visible waypoint0 waypoint7) (visible waypoint7 waypoint0)
         (visible waypoint1 waypoint0) (visible waypoint0 waypoint1)
         (visible waypoint1 waypoint5) (visible waypoint5 waypoint1)
         (visible waypoint1 waypoint7) (visible waypoint7 waypoint1)
         (visible waypoint2 waypoint1) (visible waypoint1 waypoint2)
         (visible waypoint3 waypoint0) (visible waypoint0 waypoint3)
         (visible waypoint3 waypoint1) (visible waypoint1 waypoint3)
         (visible waypoint3 waypoint2) (visible waypoint2 waypoint3)
         (visible waypoint3 waypoint6) (visible waypoint6 waypoint3)
         (visible waypoint4 waypoint1) (visible waypoint1 waypoint4)
         (visible waypoint4 waypoint5) (visible waypoint5 waypoint4)
         (visible waypoint5 waypoint2) (visible waypoint2 waypoint5)
         (visible waypoint5 waypoint3) (visible waypoint3 waypoint5)
         (visible waypoint5 waypoint6) (visible waypoint6 waypoint5)
         (visible waypoint6 waypoint0) (visible waypoint0 waypoint6)
         (visible waypoint6 waypoint2) (visible waypoint2 waypoint6)
         (visible waypoint6 waypoint4) (visible waypoint4 waypoint6)
         (visible waypoint7 waypoint2) (visible waypoint2 waypoint7)
         (visible waypoint7 waypoint3) (visible waypoint3 waypoint7)
         (visible waypoint7 waypoint5) (visible waypoint5 waypoint7)
         (at_soil_sample waypoint0) (at_rock_sample waypoint0)
         (at_soil_sample waypoint1) (at_rock_sample waypoint1)
         (at_rock_sample waypoint2) (at_soil_sample waypoint3)
         (at_rock_sample waypoint4) (at_soil_sample waypoint6)
         (at_rock_sample waypoint6) (at_rock_sample waypoint7)
         (at_lander general waypoint1) (channel_free general)
         (at rover0 waypoint1) (available rover0) (store_of rover0store rover0)
         (empty rover0store) (equipped_for_soil_analysis rover0)
         (equipped_for_imaging rover0)
         (can_traverse rover0 waypoint1 waypoint0)
         (can_traverse rover0 waypoint0 waypoint1)
         (can_traverse rover0 waypoint1 waypoint3)
         (can_traverse rover0 waypoint3 waypoint1)
         (can_traverse rover0 waypoint1 waypoint4)
         (can_traverse rover0 waypoint4 waypoint1)
         (can_traverse rover0 waypoint1 waypoint5)
         (can_traverse rover0 waypoint5 waypoint1)
         (can_traverse rover0 waypoint0 waypoint6)
         (can_traverse rover0 waypoint6 waypoint0)
         (can_traverse rover0 waypoint0 waypoint7)
         (can_traverse rover0 waypoint7 waypoint0)
         (can_traverse rover0 waypoint3 waypoint2)
         (can_traverse rover0 waypoint2 waypoint3) (at rover1 waypoint3)
         (available rover1) (store_of rover1store rover1) (empty rover1store)
         (equipped_for_soil_analysis rover1)
         (equipped_for_rock_analysis rover1) (equipped_for_imaging rover1)
         (can_traverse rover1 waypoint3 waypoint0)
         (can_traverse rover1 waypoint0 waypoint3)
         (can_traverse rover1 waypoint3 waypoint7)
         (can_traverse rover1 waypoint7 waypoint3)
         (can_traverse rover1 waypoint0 waypoint6)
         (can_traverse rover1 waypoint6 waypoint0)
         (can_traverse rover1 waypoint7 waypoint1)
         (can_traverse rover1 waypoint1 waypoint7)
         (can_traverse rover1 waypoint7 waypoint2)
         (can_traverse rover1 waypoint2 waypoint7)
         (can_traverse rover1 waypoint6 waypoint4)
         (can_traverse rover1 waypoint4 waypoint6)
         (can_traverse rover1 waypoint6 waypoint5)
         (can_traverse rover1 waypoint5 waypoint6) (at rover2 waypoint3)
         (available rover2) (store_of rover2store rover2) (empty rover2store)
         (equipped_for_soil_analysis rover2) (equipped_for_imaging rover2)
         (can_traverse rover2 waypoint3 waypoint0)
         (can_traverse rover2 waypoint0 waypoint3)
         (can_traverse rover2 waypoint3 waypoint1)
         (can_traverse rover2 waypoint1 waypoint3)
         (can_traverse rover2 waypoint3 waypoint2)
         (can_traverse rover2 waypoint2 waypoint3)
         (can_traverse rover2 waypoint3 waypoint5)
         (can_traverse rover2 waypoint5 waypoint3)
         (can_traverse rover2 waypoint3 waypoint6)
         (can_traverse rover2 waypoint6 waypoint3)
         (can_traverse rover2 waypoint3 waypoint7)
         (can_traverse rover2 waypoint7 waypoint3)
         (can_traverse rover2 waypoint0 waypoint4)
         (can_traverse rover2 waypoint4 waypoint0) (at rover3 waypoint7)
         (available rover3) (store_of rover3store rover3) (empty rover3store)
         (equipped_for_soil_analysis rover3) (equipped_for_imaging rover3)
         (can_traverse rover3 waypoint7 waypoint0)
         (can_traverse rover3 waypoint0 waypoint7)
         (can_traverse rover3 waypoint7 waypoint1)
         (can_traverse rover3 waypoint1 waypoint7)
         (can_traverse rover3 waypoint7 waypoint3)
         (can_traverse rover3 waypoint3 waypoint7)
         (can_traverse rover3 waypoint7 waypoint5)
         (can_traverse rover3 waypoint5 waypoint7)
         (can_traverse rover3 waypoint0 waypoint4)
         (can_traverse rover3 waypoint4 waypoint0)
         (can_traverse rover3 waypoint1 waypoint2)
         (can_traverse rover3 waypoint2 waypoint1)
         (can_traverse rover3 waypoint3 waypoint6)
         (can_traverse rover3 waypoint6 waypoint3) (on_board camera0 rover1)
         (calibration_target camera0 objective1) (supports camera0 high_res)
         (supports camera0 low_res) (on_board camera1 rover2)
         (calibration_target camera1 objective0) (supports camera1 colour)
         (supports camera1 high_res) (on_board camera2 rover3)
         (calibration_target camera2 objective0) (supports camera2 high_res)
         (on_board camera3 rover0) (calibration_target camera3 objective1)
         (supports camera3 colour) (visible_from objective0 waypoint0)
         (visible_from objective0 waypoint1)
         (visible_from objective0 waypoint2)
         (visible_from objective0 waypoint3)
         (visible_from objective0 waypoint4)
         (visible_from objective0 waypoint5)
         (visible_from objective1 waypoint0)
         (visible_from objective1 waypoint1)
         (visible_from objective1 waypoint2)
         (visible_from objective2 waypoint0)
         (visible_from objective2 waypoint1)
         (visible_from objective2 waypoint2)
         (visible_from objective2 waypoint3)
         (visible_from objective2 waypoint4)
         (visible_from objective2 waypoint5)
         (visible_from objective2 waypoint6))
        (:goal
         (and (communicated_soil_data waypoint6)
              (communicated_soil_data waypoint0)
              (communicated_soil_data waypoint1)
              (communicated_soil_data waypoint3)
              (communicated_rock_data waypoint6)
              (communicated_rock_data waypoint0)
              (communicated_rock_data waypoint4)
              (communicated_rock_data waypoint7)
              (communicated_image_data objective1 high_res)))
        (:constraints
         (and (preference a0 (always (at rover3 waypoint7)))
              (preference a1 (always (at rover2 waypoint3)))
              (preference a2 (always (empty rover3store)))
              (preference a3 (always (empty rover2store)))
              (preference e0 (sometime (at rover3 waypoint5)))
              (preference e1 (sometime (at rover3 waypoint0)))
              (preference e2 (sometime (at rover2 waypoint6)))
              (preference e3 (sometime (at rover2 waypoint2)))
              (preference e4 (sometime (at rover0 waypoint6)))
              (preference e5 (sometime (at rover0 waypoint4)))
              (preference e6 (sometime (at rover0 waypoint3)))
              (preference e7 (sometime (full rover3store)))
              (preference e8 (sometime (have_soil_analysis rover3 waypoint0)))
              (preference e9 (sometime (have_soil_analysis rover2 waypoint6)))
              (preference e10 (sometime (have_soil_analysis rover2 waypoint3)))
              (preference e11 (sometime (full rover1store)))
              (preference e12 (sometime (have_soil_analysis rover1 waypoint6)))
              (preference e13 (sometime (have_soil_analysis rover1 waypoint3)))
              (preference e14 (sometime (have_soil_analysis rover1 waypoint0)))
              (preference e15 (sometime (have_soil_analysis rover0 waypoint6)))
              (preference e16 (sometime (have_soil_analysis rover0 waypoint0)))
              (preference e17 (sometime (calibrated camera2 rover3)))
              (preference e18 (sometime (calibrated camera1 rover2)))
              (preference e19 (sometime (calibrated camera0 rover1)))
              (preference e20
               (sometime (have_image rover3 objective1 high_res)))
              (preference e21
               (sometime (have_image rover2 objective1 high_res)))
              (preference e22
               (sometime (have_image rover1 objective1 high_res)))
              (preference o0 (at-most-once (at rover1 waypoint3)))
              (preference o1 (at-most-once (at rover1 waypoint6)))
              (preference o2 (at-most-once (at rover1 waypoint0)))
              (preference o3 (at-most-once (at rover0 waypoint0)))
              (preference o4 (at-most-once (full rover2store)))
              (preference o5 (at-most-once (empty rover0store)))
              (preference o6 (at-most-once (full rover0store)))
              (preference sb11
               (sometime-before (at rover1 waypoint7) (full rover2store)))
              (preference sb12
               (sometime-before (at rover1 waypoint7)
                (have_soil_analysis rover2 waypoint6)))
              (preference sb14
               (sometime-before (at rover1 waypoint7) (full rover1store)))
              (preference sb24
               (sometime-before (at rover1 waypoint7)
                (calibrated camera0 rover1)))
              (preference sb32
               (sometime-before (at rover1 waypoint6) (at rover1 waypoint0)))
              (preference sb40
               (sometime-before (at rover1 waypoint6)
                (have_soil_analysis rover2 waypoint3)))
              (preference sb47
               (sometime-before (at rover1 waypoint6)
                (have_soil_analysis rover0 waypoint0)))
              (preference sb49
               (sometime-before (at rover1 waypoint6)
                (have_rock_analysis rover1 waypoint0)))
              (preference sb52
               (sometime-before (at rover1 waypoint6)
                (calibrated camera0 rover1)))
              (preference sb53
               (sometime-before (at rover1 waypoint6)
                (have_image rover3 objective1 high_res)))
              (preference sb54
               (sometime-before (at rover1 waypoint6)
                (have_image rover1 objective1 high_res)))
              (preference sb65
               (sometime-before (at rover1 waypoint4)
                (have_soil_analysis rover3 waypoint0)))
              (preference sb67
               (sometime-before (at rover1 waypoint4)
                (have_soil_analysis rover2 waypoint6)))
              (preference sb69
               (sometime-before (at rover1 waypoint4) (full rover1store)))
              (preference sb70
               (sometime-before (at rover1 waypoint4)
                (have_soil_analysis rover1 waypoint6)))
              (preference sb90
               (sometime-before (at rover1 waypoint0) (full rover3store)))
              (preference sb105
               (sometime-before (have_soil_analysis rover0 waypoint1)
                (at rover2 waypoint6)))
              (preference sb114
               (sometime-before (have_soil_analysis rover0 waypoint1)
                (have_soil_analysis rover2 waypoint3)))
              (preference sb115
               (sometime-before (have_soil_analysis rover0 waypoint1)
                (full rover1store)))
              (preference sb120
               (sometime-before (have_soil_analysis rover0 waypoint1)
                (have_rock_analysis rover1 waypoint4)))
              (preference sb126
               (sometime-before (have_soil_analysis rover0 waypoint1)
                (have_image rover1 objective1 high_res)))
              (preference sb127
               (sometime-before (have_rock_analysis rover1 waypoint7)
                (at rover3 waypoint5)))
              (preference sb129
               (sometime-before (have_rock_analysis rover1 waypoint7)
                (at rover2 waypoint6)))
              (preference sb146
               (sometime-before (have_rock_analysis rover1 waypoint7)
                (have_soil_analysis rover0 waypoint6)))
              (preference sb150
               (sometime-before (have_rock_analysis rover1 waypoint7)
                (calibrated camera1 rover2)))
              (preference sb156
               (sometime-before (have_rock_analysis rover1 waypoint6)
                (at rover3 waypoint0)))
              (preference sb165
               (sometime-before (have_rock_analysis rover1 waypoint6)
                (full rover2store)))
              (preference sb185
               (sometime-before (have_rock_analysis rover1 waypoint4)
                (at rover2 waypoint6)))
              (preference sb196
               (sometime-before (have_rock_analysis rover1 waypoint4)
                (have_soil_analysis rover2 waypoint3)))
              (preference sb201
               (sometime-before (have_rock_analysis rover1 waypoint4)
                (full rover0store)))
              (preference sb204
               (sometime-before (have_rock_analysis rover1 waypoint4)
                (have_soil_analysis rover0 waypoint0)))
              (preference sb212
               (sometime-before (have_rock_analysis rover1 waypoint4)
                (have_image rover1 objective1 high_res)))
              (preference sb213
               (sometime-before (have_rock_analysis rover1 waypoint0)
                (at rover3 waypoint5)))
              (preference sb223
               (sometime-before (have_rock_analysis rover1 waypoint0)
                (full rover2store)))
              (preference sb225
               (sometime-before (have_rock_analysis rover1 waypoint0)
                (full rover1store)))
              (preference sb226
               (sometime-before (have_rock_analysis rover1 waypoint0)
                (have_soil_analysis rover1 waypoint3)))
              (preference sb229
               (sometime-before (have_rock_analysis rover1 waypoint0)
                (have_soil_analysis rover0 waypoint6)))
              (preference sb235
               (sometime-before (have_rock_analysis rover1 waypoint0)
                (calibrated camera0 rover1)))
              (preference sb236
               (sometime-before (have_rock_analysis rover1 waypoint0)
                (have_image rover3 objective1 high_res)))))
        (:metric minimize
         (+ (* (is-violated sb236) 29.9354)
            (* (is-violated sb235) 48.5343)
            (* (is-violated sb229) 28.5988)
            (* (is-violated sb226) 38.1318)
            (* (is-violated sb225) 22.7964)
            (* (is-violated sb223) 23.8994)
            (* (is-violated sb213) 23.5318)
            (* (is-violated sb212) 44.8574)
            (* (is-violated sb204) 37.8714)
            (* (is-violated sb201) 48.9019)
            (* (is-violated sb196) 53.6818)
            (* (is-violated sb185) 33.0915)
            (* (is-violated sb165) 51.4757)
            (* (is-violated sb156) 36.4597)
            (* (is-violated sb150) 21.3257)
            (* (is-violated sb146) 41.3094)
            (* (is-violated sb129) 20.958)
            (* (is-violated sb127) 39.7099)
            (* (is-violated sb126) 70.0478)
            (* (is-violated sb120) 56.2851)
            (* (is-violated sb115) 31.3793)
            (* (is-violated sb114) 29.047)
            (* (is-violated sb105) 36.296)
            (* (is-violated sb90) 27.4072)
            (* (is-violated sb70) 52.195)
            (* (is-violated sb69) 40.8129)
            (* (is-violated sb67) 34.5623)
            (* (is-violated sb65) 55.6491)
            (* (is-violated sb54) 52.5788)
            (* (is-violated sb53) 41.0652)
            (* (is-violated sb52) 50.005)
            (* (is-violated sb49) 37.8714)
            (* (is-violated sb47) 37.5037)
            (* (is-violated sb40) 22.7964)
            (* (is-violated sb32) 43.019)
            (* (is-violated sb24) 25.0025)
            (* (is-violated sb14) 47.7989)
            (* (is-violated sb12) 39.7099)
            (* (is-violated sb11) 32.3562)
            (* (is-violated o6) 35.6922)
            (* (is-violated o5) 44.1355)
            (* (is-violated o4) 47.9733)
            (* (is-violated o3) 30.8854)
            (* (is-violated o2) 55.1526)
            (* (is-violated o1) 54.0495)
            (* (is-violated o0) 20.2226)
            (* (is-violated e22) 23.5318)
            (* (is-violated e21) 61.5454)
            (* (is-violated e20) 20.3407)
            (* (is-violated e19) 41.5483)
            (* (is-violated e18) 40.4452)
            (* (is-violated e17) 52.2111)
            (* (is-violated e16) 34.93)
            (* (is-violated e15) 50.8424)
            (* (is-violated e14) 49.7581)
            (* (is-violated e13) 30.1876)
            (* (is-violated e12) 36.8435)
            (* (is-violated e11) 37.1361)
            (* (is-violated e10) 44.1221)
            (* (is-violated e9) 27.5763)
            (* (is-violated e8) 48.3571)
            (* (is-violated e7) 54.4977)
            (* (is-violated e6) 44.7125)
            (* (is-violated e5) 65.7)
            (* (is-violated e4) 21.4491)
            (* (is-violated e3) 64.1756)
            (* (is-violated e2) 43.7544)
            (* (is-violated e1) 39.1463)
            (* (is-violated e0) 19.8549)
            (* (is-violated a3) 36.1457)
            (* (is-violated a2) 31.9885)
            (* (is-violated a1) 40.2976)
            (* (is-violated a0) 64.2507)
	)))
