
(define (problem roverprob4621)
        (:domain rover)
        (:objects general - lander colour - mode high_res - mode low_res - mode
         rover0 - rover rover1 - rover rover2 - rover rover3 - rover rover4 -
         rover rover5 - rover rover0store - store rover1store - store
         rover2store - store rover3store - store rover4store - store
         rover5store - store waypoint0 - waypoint waypoint1 - waypoint
         waypoint2 - waypoint waypoint3 - waypoint waypoint4 - waypoint
         waypoint5 - waypoint waypoint6 - waypoint waypoint7 - waypoint
         waypoint8 - waypoint waypoint9 - waypoint waypoint10 - waypoint
         waypoint11 - waypoint waypoint12 - waypoint waypoint13 - waypoint
         waypoint14 - waypoint waypoint15 - waypoint waypoint16 - waypoint
         waypoint17 - waypoint waypoint18 - waypoint waypoint19 - waypoint
         camera0 - camera camera1 - camera camera2 - camera camera3 - camera
         camera4 - camera camera5 - camera camera6 - camera objective0 -
         objective objective1 - objective objective2 - objective objective3 -
         objective objective4 - objective objective5 - objective objective6 -
         objective)
        (:init (visible waypoint0 waypoint1) (visible waypoint1 waypoint0)
         (visible waypoint0 waypoint2) (visible waypoint2 waypoint0)
         (visible waypoint0 waypoint12) (visible waypoint12 waypoint0)
         (visible waypoint0 waypoint13) (visible waypoint13 waypoint0)
         (visible waypoint1 waypoint2) (visible waypoint2 waypoint1)
         (visible waypoint1 waypoint6) (visible waypoint6 waypoint1)
         (visible waypoint1 waypoint11) (visible waypoint11 waypoint1)
         (visible waypoint1 waypoint15) (visible waypoint15 waypoint1)
         (visible waypoint2 waypoint6) (visible waypoint6 waypoint2)
         (visible waypoint2 waypoint9) (visible waypoint9 waypoint2)
         (visible waypoint2 waypoint14) (visible waypoint14 waypoint2)
         (visible waypoint2 waypoint16) (visible waypoint16 waypoint2)
         (visible waypoint2 waypoint18) (visible waypoint18 waypoint2)
         (visible waypoint3 waypoint7) (visible waypoint7 waypoint3)
         (visible waypoint3 waypoint11) (visible waypoint11 waypoint3)
         (visible waypoint3 waypoint13) (visible waypoint13 waypoint3)
         (visible waypoint3 waypoint15) (visible waypoint15 waypoint3)
         (visible waypoint4 waypoint5) (visible waypoint5 waypoint4)
         (visible waypoint4 waypoint9) (visible waypoint9 waypoint4)
         (visible waypoint4 waypoint12) (visible waypoint12 waypoint4)
         (visible waypoint4 waypoint18) (visible waypoint18 waypoint4)
         (visible waypoint5 waypoint6) (visible waypoint6 waypoint5)
         (visible waypoint5 waypoint10) (visible waypoint10 waypoint5)
         (visible waypoint5 waypoint12) (visible waypoint12 waypoint5)
         (visible waypoint5 waypoint14) (visible waypoint14 waypoint5)
         (visible waypoint6 waypoint3) (visible waypoint3 waypoint6)
         (visible waypoint6 waypoint12) (visible waypoint12 waypoint6)
         (visible waypoint6 waypoint13) (visible waypoint13 waypoint6)
         (visible waypoint6 waypoint14) (visible waypoint14 waypoint6)
         (visible waypoint6 waypoint19) (visible waypoint19 waypoint6)
         (visible waypoint7 waypoint1) (visible waypoint1 waypoint7)
         (visible waypoint7 waypoint2) (visible waypoint2 waypoint7)
         (visible waypoint7 waypoint5) (visible waypoint5 waypoint7)
         (visible waypoint7 waypoint9) (visible waypoint9 waypoint7)
         (visible waypoint8 waypoint14) (visible waypoint14 waypoint8)
         (visible waypoint9 waypoint0) (visible waypoint0 waypoint9)
         (visible waypoint9 waypoint3) (visible waypoint3 waypoint9)
         (visible waypoint9 waypoint5) (visible waypoint5 waypoint9)
         (visible waypoint9 waypoint6) (visible waypoint6 waypoint9)
         (visible waypoint9 waypoint8) (visible waypoint8 waypoint9)
         (visible waypoint9 waypoint12) (visible waypoint12 waypoint9)
         (visible waypoint10 waypoint3) (visible waypoint3 waypoint10)
         (visible waypoint10 waypoint7) (visible waypoint7 waypoint10)
         (visible waypoint10 waypoint8) (visible waypoint8 waypoint10)
         (visible waypoint10 waypoint9) (visible waypoint9 waypoint10)
         (visible waypoint10 waypoint16) (visible waypoint16 waypoint10)
         (visible waypoint11 waypoint4) (visible waypoint4 waypoint11)
         (visible waypoint11 waypoint5) (visible waypoint5 waypoint11)
         (visible waypoint11 waypoint7) (visible waypoint7 waypoint11)
         (visible waypoint11 waypoint12) (visible waypoint12 waypoint11)
         (visible waypoint11 waypoint16) (visible waypoint16 waypoint11)
         (visible waypoint12 waypoint1) (visible waypoint1 waypoint12)
         (visible waypoint12 waypoint8) (visible waypoint8 waypoint12)
         (visible waypoint12 waypoint14) (visible waypoint14 waypoint12)
         (visible waypoint12 waypoint19) (visible waypoint19 waypoint12)
         (visible waypoint13 waypoint4) (visible waypoint4 waypoint13)
         (visible waypoint13 waypoint19) (visible waypoint19 waypoint13)
         (visible waypoint14 waypoint9) (visible waypoint9 waypoint14)
         (visible waypoint14 waypoint15) (visible waypoint15 waypoint14)
         (visible waypoint15 waypoint6) (visible waypoint6 waypoint15)
         (visible waypoint16 waypoint0) (visible waypoint0 waypoint16)
         (visible waypoint16 waypoint12) (visible waypoint12 waypoint16)
         (visible waypoint16 waypoint13) (visible waypoint13 waypoint16)
         (visible waypoint17 waypoint0) (visible waypoint0 waypoint17)
         (visible waypoint17 waypoint11) (visible waypoint11 waypoint17)
         (visible waypoint18 waypoint0) (visible waypoint0 waypoint18)
         (visible waypoint18 waypoint9) (visible waypoint9 waypoint18)
         (visible waypoint18 waypoint11) (visible waypoint11 waypoint18)
         (visible waypoint19 waypoint9) (visible waypoint9 waypoint19)
         (visible waypoint19 waypoint14) (visible waypoint14 waypoint19)
         (visible waypoint19 waypoint15) (visible waypoint15 waypoint19)
         (visible waypoint19 waypoint16) (visible waypoint16 waypoint19)
         (visible waypoint19 waypoint17) (visible waypoint17 waypoint19)
         (at_soil_sample waypoint0) (at_rock_sample waypoint1)
         (at_rock_sample waypoint2) (at_soil_sample waypoint3)
         (at_rock_sample waypoint4) (at_rock_sample waypoint5)
         (at_rock_sample waypoint6) (at_rock_sample waypoint7)
         (at_soil_sample waypoint8) (at_soil_sample waypoint9)
         (at_rock_sample waypoint9) (at_soil_sample waypoint10)
         (at_soil_sample waypoint11) (at_soil_sample waypoint12)
         (at_rock_sample waypoint12) (at_soil_sample waypoint13)
         (at_rock_sample waypoint13) (at_soil_sample waypoint14)
         (at_soil_sample waypoint15) (at_soil_sample waypoint17)
         (at_rock_sample waypoint17) (at_soil_sample waypoint18)
         (at_rock_sample waypoint18) (at_soil_sample waypoint19)
         (at_lander general waypoint17) (channel_free general)
         (at rover0 waypoint2) (available rover0) (store_of rover0store rover0)
         (empty rover0store) (equipped_for_soil_analysis rover0)
         (equipped_for_rock_analysis rover0) (equipped_for_imaging rover0)
         (can_traverse rover0 waypoint2 waypoint0)
         (can_traverse rover0 waypoint0 waypoint2)
         (can_traverse rover0 waypoint2 waypoint6)
         (can_traverse rover0 waypoint6 waypoint2)
         (can_traverse rover0 waypoint2 waypoint7)
         (can_traverse rover0 waypoint7 waypoint2)
         (can_traverse rover0 waypoint2 waypoint9)
         (can_traverse rover0 waypoint9 waypoint2)
         (can_traverse rover0 waypoint2 waypoint14)
         (can_traverse rover0 waypoint14 waypoint2)
         (can_traverse rover0 waypoint2 waypoint18)
         (can_traverse rover0 waypoint18 waypoint2)
         (can_traverse rover0 waypoint0 waypoint12)
         (can_traverse rover0 waypoint12 waypoint0)
         (can_traverse rover0 waypoint0 waypoint13)
         (can_traverse rover0 waypoint13 waypoint0)
         (can_traverse rover0 waypoint6 waypoint1)
         (can_traverse rover0 waypoint1 waypoint6)
         (can_traverse rover0 waypoint6 waypoint15)
         (can_traverse rover0 waypoint15 waypoint6)
         (can_traverse rover0 waypoint6 waypoint19)
         (can_traverse rover0 waypoint19 waypoint6)
         (can_traverse rover0 waypoint7 waypoint3)
         (can_traverse rover0 waypoint3 waypoint7)
         (can_traverse rover0 waypoint7 waypoint11)
         (can_traverse rover0 waypoint11 waypoint7)
         (can_traverse rover0 waypoint9 waypoint4)
         (can_traverse rover0 waypoint4 waypoint9)
         (can_traverse rover0 waypoint9 waypoint5)
         (can_traverse rover0 waypoint5 waypoint9)
         (can_traverse rover0 waypoint9 waypoint8)
         (can_traverse rover0 waypoint8 waypoint9)
         (can_traverse rover0 waypoint13 waypoint16)
         (can_traverse rover0 waypoint16 waypoint13)
         (can_traverse rover0 waypoint5 waypoint10)
         (can_traverse rover0 waypoint10 waypoint5) (at rover1 waypoint9)
         (available rover1) (store_of rover1store rover1) (empty rover1store)
         (equipped_for_rock_analysis rover1) (equipped_for_imaging rover1)
         (can_traverse rover1 waypoint9 waypoint0)
         (can_traverse rover1 waypoint0 waypoint9)
         (can_traverse rover1 waypoint9 waypoint3)
         (can_traverse rover1 waypoint3 waypoint9)
         (can_traverse rover1 waypoint9 waypoint4)
         (can_traverse rover1 waypoint4 waypoint9)
         (can_traverse rover1 waypoint9 waypoint7)
         (can_traverse rover1 waypoint7 waypoint9)
         (can_traverse rover1 waypoint9 waypoint10)
         (can_traverse rover1 waypoint10 waypoint9)
         (can_traverse rover1 waypoint9 waypoint12)
         (can_traverse rover1 waypoint12 waypoint9)
         (can_traverse rover1 waypoint9 waypoint14)
         (can_traverse rover1 waypoint14 waypoint9)
         (can_traverse rover1 waypoint9 waypoint18)
         (can_traverse rover1 waypoint18 waypoint9)
         (can_traverse rover1 waypoint9 waypoint19)
         (can_traverse rover1 waypoint19 waypoint9)
         (can_traverse rover1 waypoint0 waypoint2)
         (can_traverse rover1 waypoint2 waypoint0)
         (can_traverse rover1 waypoint0 waypoint13)
         (can_traverse rover1 waypoint13 waypoint0)
         (can_traverse rover1 waypoint0 waypoint16)
         (can_traverse rover1 waypoint16 waypoint0)
         (can_traverse rover1 waypoint3 waypoint6)
         (can_traverse rover1 waypoint6 waypoint3)
         (can_traverse rover1 waypoint4 waypoint11)
         (can_traverse rover1 waypoint11 waypoint4)
         (can_traverse rover1 waypoint7 waypoint5)
         (can_traverse rover1 waypoint5 waypoint7)
         (can_traverse rover1 waypoint10 waypoint8)
         (can_traverse rover1 waypoint8 waypoint10)
         (can_traverse rover1 waypoint12 waypoint1)
         (can_traverse rover1 waypoint1 waypoint12)
         (can_traverse rover1 waypoint14 waypoint15)
         (can_traverse rover1 waypoint15 waypoint14)
         (can_traverse rover1 waypoint19 waypoint17)
         (can_traverse rover1 waypoint17 waypoint19) (at rover2 waypoint0)
         (available rover2) (store_of rover2store rover2) (empty rover2store)
         (equipped_for_soil_analysis rover2) (equipped_for_imaging rover2)
         (can_traverse rover2 waypoint0 waypoint1)
         (can_traverse rover2 waypoint1 waypoint0)
         (can_traverse rover2 waypoint0 waypoint9)
         (can_traverse rover2 waypoint9 waypoint0)
         (can_traverse rover2 waypoint0 waypoint13)
         (can_traverse rover2 waypoint13 waypoint0)
         (can_traverse rover2 waypoint0 waypoint16)
         (can_traverse rover2 waypoint16 waypoint0)
         (can_traverse rover2 waypoint0 waypoint17)
         (can_traverse rover2 waypoint17 waypoint0)
         (can_traverse rover2 waypoint0 waypoint18)
         (can_traverse rover2 waypoint18 waypoint0)
         (can_traverse rover2 waypoint1 waypoint2)
         (can_traverse rover2 waypoint2 waypoint1)
         (can_traverse rover2 waypoint1 waypoint6)
         (can_traverse rover2 waypoint6 waypoint1)
         (can_traverse rover2 waypoint1 waypoint11)
         (can_traverse rover2 waypoint11 waypoint1)
         (can_traverse rover2 waypoint1 waypoint12)
         (can_traverse rover2 waypoint12 waypoint1)
         (can_traverse rover2 waypoint1 waypoint15)
         (can_traverse rover2 waypoint15 waypoint1)
         (can_traverse rover2 waypoint9 waypoint3)
         (can_traverse rover2 waypoint3 waypoint9)
         (can_traverse rover2 waypoint9 waypoint4)
         (can_traverse rover2 waypoint4 waypoint9)
         (can_traverse rover2 waypoint9 waypoint5)
         (can_traverse rover2 waypoint5 waypoint9)
         (can_traverse rover2 waypoint9 waypoint7)
         (can_traverse rover2 waypoint7 waypoint9)
         (can_traverse rover2 waypoint9 waypoint10)
         (can_traverse rover2 waypoint10 waypoint9)
         (can_traverse rover2 waypoint9 waypoint14)
         (can_traverse rover2 waypoint14 waypoint9)
         (can_traverse rover2 waypoint9 waypoint19)
         (can_traverse rover2 waypoint19 waypoint9) (at rover3 waypoint18)
         (available rover3) (store_of rover3store rover3) (empty rover3store)
         (equipped_for_rock_analysis rover3) (equipped_for_imaging rover3)
         (can_traverse rover3 waypoint18 waypoint0)
         (can_traverse rover3 waypoint0 waypoint18)
         (can_traverse rover3 waypoint18 waypoint4)
         (can_traverse rover3 waypoint4 waypoint18)
         (can_traverse rover3 waypoint18 waypoint11)
         (can_traverse rover3 waypoint11 waypoint18)
         (can_traverse rover3 waypoint0 waypoint1)
         (can_traverse rover3 waypoint1 waypoint0)
         (can_traverse rover3 waypoint0 waypoint2)
         (can_traverse rover3 waypoint2 waypoint0)
         (can_traverse rover3 waypoint0 waypoint9)
         (can_traverse rover3 waypoint9 waypoint0)
         (can_traverse rover3 waypoint0 waypoint12)
         (can_traverse rover3 waypoint12 waypoint0)
         (can_traverse rover3 waypoint0 waypoint17)
         (can_traverse rover3 waypoint17 waypoint0)
         (can_traverse rover3 waypoint11 waypoint16)
         (can_traverse rover3 waypoint16 waypoint11)
         (can_traverse rover3 waypoint1 waypoint6)
         (can_traverse rover3 waypoint6 waypoint1)
         (can_traverse rover3 waypoint1 waypoint7)
         (can_traverse rover3 waypoint7 waypoint1)
         (can_traverse rover3 waypoint1 waypoint15)
         (can_traverse rover3 waypoint15 waypoint1)
         (can_traverse rover3 waypoint2 waypoint14)
         (can_traverse rover3 waypoint14 waypoint2)
         (can_traverse rover3 waypoint9 waypoint3)
         (can_traverse rover3 waypoint3 waypoint9)
         (can_traverse rover3 waypoint9 waypoint5)
         (can_traverse rover3 waypoint5 waypoint9)
         (can_traverse rover3 waypoint9 waypoint8)
         (can_traverse rover3 waypoint8 waypoint9)
         (can_traverse rover3 waypoint12 waypoint19)
         (can_traverse rover3 waypoint19 waypoint12)
         (can_traverse rover3 waypoint16 waypoint13)
         (can_traverse rover3 waypoint13 waypoint16)
         (can_traverse rover3 waypoint7 waypoint10)
         (can_traverse rover3 waypoint10 waypoint7) (at rover4 waypoint3)
         (available rover4) (store_of rover4store rover4) (empty rover4store)
         (equipped_for_soil_analysis rover4) (equipped_for_imaging rover4)
         (can_traverse rover4 waypoint3 waypoint6)
         (can_traverse rover4 waypoint6 waypoint3)
         (can_traverse rover4 waypoint3 waypoint7)
         (can_traverse rover4 waypoint7 waypoint3)
         (can_traverse rover4 waypoint3 waypoint9)
         (can_traverse rover4 waypoint9 waypoint3)
         (can_traverse rover4 waypoint3 waypoint10)
         (can_traverse rover4 waypoint10 waypoint3)
         (can_traverse rover4 waypoint3 waypoint11)
         (can_traverse rover4 waypoint11 waypoint3)
         (can_traverse rover4 waypoint3 waypoint13)
         (can_traverse rover4 waypoint13 waypoint3)
         (can_traverse rover4 waypoint3 waypoint15)
         (can_traverse rover4 waypoint15 waypoint3)
         (can_traverse rover4 waypoint6 waypoint5)
         (can_traverse rover4 waypoint5 waypoint6)
         (can_traverse rover4 waypoint6 waypoint12)
         (can_traverse rover4 waypoint12 waypoint6)
         (can_traverse rover4 waypoint6 waypoint14)
         (can_traverse rover4 waypoint14 waypoint6)
         (can_traverse rover4 waypoint9 waypoint0)
         (can_traverse rover4 waypoint0 waypoint9)
         (can_traverse rover4 waypoint9 waypoint4)
         (can_traverse rover4 waypoint4 waypoint9)
         (can_traverse rover4 waypoint9 waypoint8)
         (can_traverse rover4 waypoint8 waypoint9)
         (can_traverse rover4 waypoint9 waypoint19)
         (can_traverse rover4 waypoint19 waypoint9)
         (can_traverse rover4 waypoint10 waypoint16)
         (can_traverse rover4 waypoint16 waypoint10)
         (can_traverse rover4 waypoint11 waypoint17)
         (can_traverse rover4 waypoint17 waypoint11)
         (can_traverse rover4 waypoint11 waypoint18)
         (can_traverse rover4 waypoint18 waypoint11)
         (can_traverse rover4 waypoint15 waypoint1)
         (can_traverse rover4 waypoint1 waypoint15)
         (can_traverse rover4 waypoint14 waypoint2)
         (can_traverse rover4 waypoint2 waypoint14) (at rover5 waypoint0)
         (available rover5) (store_of rover5store rover5) (empty rover5store)
         (equipped_for_rock_analysis rover5) (equipped_for_imaging rover5)
         (can_traverse rover5 waypoint0 waypoint1)
         (can_traverse rover5 waypoint1 waypoint0)
         (can_traverse rover5 waypoint0 waypoint12)
         (can_traverse rover5 waypoint12 waypoint0)
         (can_traverse rover5 waypoint0 waypoint13)
         (can_traverse rover5 waypoint13 waypoint0)
         (can_traverse rover5 waypoint0 waypoint17)
         (can_traverse rover5 waypoint17 waypoint0)
         (can_traverse rover5 waypoint0 waypoint18)
         (can_traverse rover5 waypoint18 waypoint0)
         (can_traverse rover5 waypoint1 waypoint2)
         (can_traverse rover5 waypoint2 waypoint1)
         (can_traverse rover5 waypoint1 waypoint6)
         (can_traverse rover5 waypoint6 waypoint1)
         (can_traverse rover5 waypoint1 waypoint7)
         (can_traverse rover5 waypoint7 waypoint1)
         (can_traverse rover5 waypoint1 waypoint11)
         (can_traverse rover5 waypoint11 waypoint1)
         (can_traverse rover5 waypoint1 waypoint15)
         (can_traverse rover5 waypoint15 waypoint1)
         (can_traverse rover5 waypoint12 waypoint4)
         (can_traverse rover5 waypoint4 waypoint12)
         (can_traverse rover5 waypoint12 waypoint5)
         (can_traverse rover5 waypoint5 waypoint12)
         (can_traverse rover5 waypoint12 waypoint8)
         (can_traverse rover5 waypoint8 waypoint12)
         (can_traverse rover5 waypoint12 waypoint9)
         (can_traverse rover5 waypoint9 waypoint12)
         (can_traverse rover5 waypoint12 waypoint14)
         (can_traverse rover5 waypoint14 waypoint12)
         (can_traverse rover5 waypoint12 waypoint19)
         (can_traverse rover5 waypoint19 waypoint12)
         (can_traverse rover5 waypoint13 waypoint16)
         (can_traverse rover5 waypoint16 waypoint13)
         (can_traverse rover5 waypoint7 waypoint3)
         (can_traverse rover5 waypoint3 waypoint7)
         (can_traverse rover5 waypoint7 waypoint10)
         (can_traverse rover5 waypoint10 waypoint7) (on_board camera0 rover1)
         (calibration_target camera0 objective4) (supports camera0 high_res)
         (on_board camera1 rover2) (calibration_target camera1 objective6)
         (supports camera1 colour) (supports camera1 low_res)
         (on_board camera2 rover4) (calibration_target camera2 objective0)
         (supports camera2 colour) (supports camera2 high_res)
         (on_board camera3 rover3) (calibration_target camera3 objective6)
         (supports camera3 colour) (on_board camera4 rover3)
         (calibration_target camera4 objective4) (supports camera4 high_res)
         (supports camera4 low_res) (on_board camera5 rover0)
         (calibration_target camera5 objective2) (supports camera5 colour)
         (on_board camera6 rover5) (calibration_target camera6 objective6)
         (supports camera6 high_res) (supports camera6 low_res)
         (visible_from objective0 waypoint0)
         (visible_from objective0 waypoint1)
         (visible_from objective0 waypoint2)
         (visible_from objective0 waypoint3)
         (visible_from objective0 waypoint4)
         (visible_from objective0 waypoint5)
         (visible_from objective0 waypoint6)
         (visible_from objective0 waypoint7)
         (visible_from objective0 waypoint8)
         (visible_from objective0 waypoint9)
         (visible_from objective0 waypoint10)
         (visible_from objective1 waypoint0)
         (visible_from objective1 waypoint1)
         (visible_from objective1 waypoint2)
         (visible_from objective1 waypoint3)
         (visible_from objective1 waypoint4)
         (visible_from objective1 waypoint5)
         (visible_from objective1 waypoint6)
         (visible_from objective1 waypoint7)
         (visible_from objective1 waypoint8)
         (visible_from objective1 waypoint9)
         (visible_from objective1 waypoint10)
         (visible_from objective1 waypoint11)
         (visible_from objective1 waypoint12)
         (visible_from objective2 waypoint0)
         (visible_from objective2 waypoint1)
         (visible_from objective2 waypoint2)
         (visible_from objective2 waypoint3)
         (visible_from objective2 waypoint4)
         (visible_from objective2 waypoint5)
         (visible_from objective2 waypoint6)
         (visible_from objective2 waypoint7)
         (visible_from objective2 waypoint8)
         (visible_from objective2 waypoint9)
         (visible_from objective2 waypoint10)
         (visible_from objective2 waypoint11)
         (visible_from objective2 waypoint12)
         (visible_from objective2 waypoint13)
         (visible_from objective2 waypoint14)
         (visible_from objective3 waypoint0)
         (visible_from objective3 waypoint1)
         (visible_from objective3 waypoint2)
         (visible_from objective3 waypoint3)
         (visible_from objective3 waypoint4)
         (visible_from objective3 waypoint5)
         (visible_from objective3 waypoint6)
         (visible_from objective3 waypoint7)
         (visible_from objective3 waypoint8)
         (visible_from objective3 waypoint9)
         (visible_from objective3 waypoint10)
         (visible_from objective3 waypoint11)
         (visible_from objective3 waypoint12)
         (visible_from objective3 waypoint13)
         (visible_from objective3 waypoint14)
         (visible_from objective3 waypoint15)
         (visible_from objective3 waypoint16)
         (visible_from objective3 waypoint17)
         (visible_from objective3 waypoint18)
         (visible_from objective3 waypoint19)
         (visible_from objective4 waypoint0)
         (visible_from objective4 waypoint1)
         (visible_from objective4 waypoint2)
         (visible_from objective4 waypoint3)
         (visible_from objective4 waypoint4)
         (visible_from objective4 waypoint5)
         (visible_from objective4 waypoint6)
         (visible_from objective4 waypoint7)
         (visible_from objective4 waypoint8)
         (visible_from objective4 waypoint9)
         (visible_from objective4 waypoint10)
         (visible_from objective4 waypoint11)
         (visible_from objective4 waypoint12)
         (visible_from objective4 waypoint13)
         (visible_from objective4 waypoint14)
         (visible_from objective4 waypoint15)
         (visible_from objective5 waypoint0)
         (visible_from objective5 waypoint1)
         (visible_from objective5 waypoint2)
         (visible_from objective6 waypoint0)
         (visible_from objective6 waypoint1)
         (visible_from objective6 waypoint2)
         (visible_from objective6 waypoint3)
         (visible_from objective6 waypoint4)
         (visible_from objective6 waypoint5)
         (visible_from objective6 waypoint6)
         (visible_from objective6 waypoint7)
         (visible_from objective6 waypoint8)
         (visible_from objective6 waypoint9)
         (visible_from objective6 waypoint10))
        (:goal
         (and (communicated_soil_data waypoint14)
              (communicated_soil_data waypoint0)
              (communicated_rock_data waypoint4)
              (communicated_rock_data waypoint7)
              (communicated_rock_data waypoint2)
              (communicated_rock_data waypoint5)
              (communicated_rock_data waypoint6)
              (communicated_image_data objective5 colour)
              (communicated_image_data objective3 low_res)
              (communicated_image_data objective2 colour)
              (communicated_image_data objective4 high_res)))
        (:constraints
         (and (preference a0 (always (at rover4 waypoint3)))
              (preference a1 (always (at rover3 waypoint18)))
              (preference a2 (always (at rover2 waypoint0)))
              (preference a3 (always (empty rover4store)))
              (preference a4 (always (empty rover5store)))
              (preference a5 (always (empty rover3store)))
              (preference e0 (sometime (at rover5 waypoint19)))
              (preference e1 (sometime (at rover5 waypoint12)))
              (preference e2 (sometime (at rover5 waypoint5)))
              (preference e3 (sometime (at rover5 waypoint6)))
              (preference e4 (sometime (at rover4 waypoint11)))
              (preference e5 (sometime (at rover4 waypoint14)))
              (preference e6 (sometime (at rover3 waypoint4)))
              (preference e7 (sometime (at rover3 waypoint7)))
              (preference e8 (sometime (at rover3 waypoint5)))
              (preference e9 (sometime (at rover3 waypoint6)))
              (preference e10 (sometime (at rover2 waypoint19)))
              (preference e11 (sometime (at rover2 waypoint1)))
              (preference e12 (sometime (at rover2 waypoint14)))
              (preference e13 (sometime (at rover2 waypoint11)))
              (preference e14 (sometime (at rover1 waypoint19)))
              (preference e15 (sometime (at rover1 waypoint0)))
              (preference e16 (sometime (at rover1 waypoint11)))
              (preference e17 (sometime (at rover1 waypoint7)))
              (preference e18 (sometime (at rover1 waypoint5)))
              (preference e19 (sometime (at rover0 waypoint19)))
              (preference e20 (sometime (at rover0 waypoint6)))
              (preference e21 (sometime (at rover0 waypoint14)))
              (preference e22 (sometime (at rover0 waypoint11)))
              (preference e23 (sometime (full rover4store)))
              (preference e24
               (sometime (have_soil_analysis rover4 waypoint14)))
              (preference e25
               (sometime (have_soil_analysis rover2 waypoint14)))
              (preference e26
               (sometime (have_soil_analysis rover0 waypoint14)))
              (preference e27 (sometime (have_rock_analysis rover5 waypoint6)))
              (preference e28 (sometime (have_rock_analysis rover5 waypoint5)))
              (preference e29 (sometime (have_rock_analysis rover3 waypoint6)))
              (preference e30 (sometime (have_rock_analysis rover3 waypoint5)))
              (preference e31 (sometime (have_rock_analysis rover3 waypoint4)))
              (preference e32 (sometime (have_rock_analysis rover1 waypoint7)))
              (preference e33 (sometime (have_rock_analysis rover1 waypoint5)))
              (preference e34 (sometime (have_rock_analysis rover1 waypoint4)))
              (preference e35 (sometime (have_rock_analysis rover0 waypoint7)))
              (preference e36 (sometime (have_rock_analysis rover0 waypoint6)))
              (preference e37 (sometime (calibrated camera2 rover4)))
              (preference e38 (sometime (calibrated camera4 rover3)))
              (preference e39 (sometime (calibrated camera0 rover1)))
              (preference e40 (sometime (calibrated camera5 rover0)))
              (preference e41
               (sometime (have_image rover5 objective3 low_res)))
              (preference e42
               (sometime (have_image rover5 objective4 high_res)))
              (preference e43
               (sometime (have_image rover4 objective4 high_res)))
              (preference e44 (sometime (have_image rover4 objective2 colour)))
              (preference e45
               (sometime (have_image rover3 objective3 low_res)))
              (preference e46 (sometime (have_image rover3 objective2 colour)))
              (preference e47 (sometime (have_image rover3 objective5 colour)))
              (preference e48
               (sometime (have_image rover2 objective3 low_res)))
              (preference e49 (sometime (have_image rover2 objective2 colour)))
              (preference e50 (sometime (have_image rover2 objective5 colour)))
              (preference e51
               (sometime (have_image rover1 objective4 high_res)))
              (preference e52 (sometime (have_image rover0 objective2 colour)))
              (preference e53 (sometime (have_image rover0 objective5 colour)))
              (preference o0 (at-most-once (at rover5 waypoint0)))
              (preference o1 (at-most-once (at rover5 waypoint1)))
              (preference o2 (at-most-once (at rover5 waypoint11)))
              (preference o3 (at-most-once (at rover4 waypoint6)))
              (preference o4 (at-most-once (at rover3 waypoint11)))
              (preference o5 (at-most-once (at rover3 waypoint0)))
              (preference o6 (at-most-once (at rover3 waypoint1)))
              (preference o7 (at-most-once (at rover3 waypoint9)))
              (preference o8 (at-most-once (at rover2 waypoint9)))
              (preference o9 (at-most-once (at rover1 waypoint9)))
              (preference o10 (at-most-once (at rover1 waypoint4)))
              (preference o11 (at-most-once (at rover0 waypoint2)))
              (preference o12 (at-most-once (at rover0 waypoint0)))
              (preference o13 (at-most-once (at rover0 waypoint7)))
              (preference o14 (at-most-once (empty rover2store)))
              (preference o15 (at-most-once (full rover2store)))
              (preference o16 (at-most-once (empty rover0store)))
              (preference o17 (at-most-once (full rover0store)))
              (preference o18 (at-most-once (full rover5store)))
              (preference o19 (at-most-once (full rover3store)))
              (preference o20 (at-most-once (empty rover1store)))
              (preference o21 (at-most-once (full rover1store)))
              (preference o22 (at-most-once (calibrated camera6 rover5)))
              (preference o23 (at-most-once (calibrated camera3 rover3)))
              (preference o24 (at-most-once (calibrated camera1 rover2)))
              (preference sb0
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (at rover5 waypoint12)))
              (preference sb1
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (at rover5 waypoint1)))
              (preference sb2
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (at rover4 waypoint6)))
              (preference sb3
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (at rover3 waypoint11)))
              (preference sb4
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (at rover3 waypoint4)))
              (preference sb5
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (at rover3 waypoint0)))
              (preference sb6
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (at rover2 waypoint9)))
              (preference sb7
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (at rover1 waypoint19)))
              (preference sb8
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (at rover1 waypoint4)))
              (preference sb9
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (at rover1 waypoint7)))
              (preference sb10
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (at rover0 waypoint19)))
              (preference sb11
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (at rover0 waypoint6)))
              (preference sb12
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (at rover0 waypoint14)))
              (preference sb13
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (at rover0 waypoint0)))
              (preference sb14
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (full rover2store)))
              (preference sb15
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (full rover0store)))
              (preference sb16
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (have_soil_analysis rover0 waypoint14)))
              (preference sb17
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (full rover3store)))
              (preference sb18
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (have_rock_analysis rover3 waypoint4)))
              (preference sb19
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (full rover1store)))
              (preference sb20
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (have_rock_analysis rover1 waypoint7)))
              (preference sb21
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (have_rock_analysis rover1 waypoint4)))
              (preference sb22
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (have_rock_analysis rover0 waypoint6)))
              (preference sb23
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (have_rock_analysis rover0 waypoint2)))
              (preference sb24
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (calibrated camera6 rover5)))
              (preference sb25
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (calibrated camera2 rover4)))
              (preference sb26
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (calibrated camera1 rover2)))
              (preference sb27
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (calibrated camera0 rover1)))
              (preference sb28
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (calibrated camera5 rover0)))
              (preference sb29
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (have_image rover5 objective4 high_res)))
              (preference sb30
               (sometime-before (have_soil_analysis rover2 waypoint0)
                (have_image rover2 objective5 colour)))
              (preference sb31
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (at rover5 waypoint12)))
              (preference sb32
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (at rover4 waypoint6)))
              (preference sb33
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (at rover3 waypoint11)))
              (preference sb34
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (at rover3 waypoint4)))
              (preference sb35
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (at rover3 waypoint0)))
              (preference sb36
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (at rover1 waypoint11)))
              (preference sb37
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (at rover1 waypoint4)))
              (preference sb38
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (at rover1 waypoint7)))
              (preference sb39
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (at rover0 waypoint14)))
              (preference sb40
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (full rover2store)))
              (preference sb41
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (have_soil_analysis rover2 waypoint0)))
              (preference sb42
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (full rover0store)))
              (preference sb43
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (have_soil_analysis rover0 waypoint14)))
              (preference sb44
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (full rover3store)))
              (preference sb45
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (have_rock_analysis rover3 waypoint4)))
              (preference sb46
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (full rover1store)))
              (preference sb47
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (have_rock_analysis rover1 waypoint7)))
              (preference sb48
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (have_rock_analysis rover1 waypoint4)))
              (preference sb49
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (calibrated camera6 rover5)))
              (preference sb50
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (calibrated camera2 rover4)))
              (preference sb51
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (calibrated camera3 rover3)))
              (preference sb52
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (calibrated camera1 rover2)))
              (preference sb53
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (calibrated camera0 rover1)))
              (preference sb54
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (calibrated camera5 rover0)))
              (preference sb55
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (have_image rover5 objective3 low_res)))
              (preference sb56
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (have_image rover5 objective4 high_res)))
              (preference sb57
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (have_image rover3 objective2 colour)))
              (preference sb58
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (have_image rover3 objective5 colour)))
              (preference sb59
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (have_image rover2 objective3 low_res)))
              (preference sb60
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (have_image rover1 objective4 high_res)))
              (preference sb61
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (have_image rover0 objective2 colour)))
              (preference sb62
               (sometime-before (have_rock_analysis rover0 waypoint2)
                (have_image rover0 objective5 colour)))))
        (:metric minimize
         (+ (* (is-violated sb62) 99)
            (* (is-violated sb61) 99)
            (* (is-violated sb60) 99)
            (* (is-violated sb59) 99)
            (* (is-violated sb58) 99)
            (* (is-violated sb57) 99)
            (* (is-violated sb56) 99)
            (* (is-violated sb55) 99)
            (* (is-violated sb54) 98)
            (* (is-violated sb53) 95)
            (* (is-violated sb52) 95)
            (* (is-violated sb51) 99)
            (* (is-violated sb50) 95)
            (* (is-violated sb49) 95)
            (* (is-violated sb48) 99)
            (* (is-violated sb47) 92)
            (* (is-violated sb46) 92)
            (* (is-violated sb45) 92)
            (* (is-violated sb44) 92)
            (* (is-violated sb43) 92)
            (* (is-violated sb42) 92)
            (* (is-violated sb41) 95)
            (* (is-violated sb40) 95)
            (* (is-violated sb39) 92)
            (* (is-violated sb38) 92)
            (* (is-violated sb37) 99)
            (* (is-violated sb36) 99)
            (* (is-violated sb35) 95)
            (* (is-violated sb34) 92)
            (* (is-violated sb33) 98)
            (* (is-violated sb32) 102)
            (* (is-violated sb31) 105)
            (* (is-violated sb30) 92)
            (* (is-violated sb29) 99)
            (* (is-violated sb28) 98)
            (* (is-violated sb27) 95)
            (* (is-violated sb26) 92)
            (* (is-violated sb25) 95)
            (* (is-violated sb24) 92)
            (* (is-violated sb23) 92)
            (* (is-violated sb22) 92)
            (* (is-violated sb21) 99)
            (* (is-violated sb20) 92)
            (* (is-violated sb19) 92)
            (* (is-violated sb18) 92)
            (* (is-violated sb17) 92)
            (* (is-violated sb16) 92)
            (* (is-violated sb15) 92)
            (* (is-violated sb14) 92)
            (* (is-violated sb13) 104)
            (* (is-violated sb12) 92)
            (* (is-violated sb11) 92)
            (* (is-violated sb10) 92)
            (* (is-violated sb9) 92)
            (* (is-violated sb8) 99)
            (* (is-violated sb7) 92)
            (* (is-violated sb6) 104)
            (* (is-violated sb5) 95)
            (* (is-violated sb4) 92)
            (* (is-violated sb3) 92)
            (* (is-violated sb2) 102)
            (* (is-violated sb1) 104)
            (* (is-violated sb0) 105)
            (* (is-violated o24) 99)
            (* (is-violated o23) 104)
            (* (is-violated o22) 92)
            (* (is-violated o21) 92)
            (* (is-violated o20) 92)
            (* (is-violated o19) 92)
            (* (is-violated o18) 92)
            (* (is-violated o17) 98)
            (* (is-violated o16) 98)
            (* (is-violated o15) 92)
            (* (is-violated o14) 92)
            (* (is-violated o13) 99)
            (* (is-violated o12) 95)
            (* (is-violated o11) 98)
            (* (is-violated o10) 99)
            (* (is-violated o9) 98)
            (* (is-violated o8) 98)
            (* (is-violated o7) 95)
            (* (is-violated o6) 105)
            (* (is-violated o5) 99)
            (* (is-violated o4) 92)
            (* (is-violated o3) 95)
            (* (is-violated o2) 98)
            (* (is-violated o1) 102)
            (* (is-violated o0) 98)
            (* (is-violated e53) 95)
            (* (is-violated e52) 95)
            (* (is-violated e51) 95)
            (* (is-violated e50) 92)
            (* (is-violated e49) 92)
            (* (is-violated e48) 92)
            (* (is-violated e47) 95)
            (* (is-violated e46) 95)
            (* (is-violated e45) 95)
            (* (is-violated e44) 95)
            (* (is-violated e43) 95)
            (* (is-violated e42) 92)
            (* (is-violated e41) 95)
            (* (is-violated e40) 98)
            (* (is-violated e39) 95)
            (* (is-violated e38) 95)
            (* (is-violated e37) 95)
            (* (is-violated e36) 92)
            (* (is-violated e35) 95)
            (* (is-violated e34) 95)
            (* (is-violated e33) 98)
            (* (is-violated e32) 92)
            (* (is-violated e31) 92)
            (* (is-violated e30) 102)
            (* (is-violated e29) 104)
            (* (is-violated e28) 92)
            (* (is-violated e27) 95)
            (* (is-violated e26) 92)
            (* (is-violated e25) 95)
            (* (is-violated e24) 102)
            (* (is-violated e23) 102)
            (* (is-violated e22) 95)
            (* (is-violated e21) 92)
            (* (is-violated e20) 92)
            (* (is-violated e19) 92)
            (* (is-violated e18) 95)
            (* (is-violated e17) 92)
            (* (is-violated e16) 95)
            (* (is-violated e15) 95)
            (* (is-violated e14) 92)
            (* (is-violated e13) 102)
            (* (is-violated e12) 95)
            (* (is-violated e11) 99)
            (* (is-violated e10) 98)
            (* (is-violated e9) 104)
            (* (is-violated e8) 102)
            (* (is-violated e7) 95)
            (* (is-violated e6) 92)
            (* (is-violated e5) 95)
            (* (is-violated e4) 98)
            (* (is-violated e3) 95)
            (* (is-violated e2) 92)
            (* (is-violated e1) 92)
            (* (is-violated e0) 99)
            (* (is-violated a5) 95)
            (* (is-violated a4) 104)
            (* (is-violated a3) 92)
            (* (is-violated a2) 92)
            (* (is-violated a1) 99)
            (* (is-violated a0) 92)
	)))
