;Copyright 2018 The MITRE Corporation. All rights reserved. Approved for public release. Distribution unlimited 17-2122.
; For more information on CALDERA, the automated adversary emulation system, visit https://github.com/mitre/caldera or email attack@mitre.org
; This has 6 hosts, 1 user, 1 admin per host, 1 active account per host
(define (problem p6_hosts_trial_1)
(:domain caldera)
(:objects
    id_ddomaincredential - observeddomaincredential
    id_cdfile id_byfile id_bzfile id_cbfile id_ccfile id_cafile - observedfile
    id_bihost id_nhost id_ghost id_uhost id_bphost id_bbhost - observedhost
    id_cdomainuser - observeddomainuser
    num__36 num__37 num__15 num__16 num__29 num__30 num__23 num__44 num__43 num__22 num__9 num__8 - num
    id_chschtask id_ceschtask id_cfschtask id_cjschtask id_cischtask id_cgschtask - observedschtask
    id_adomain - observeddomain
    id_bqtimedelta id_otimedelta id_htimedelta id_bctimedelta id_bjtimedelta id_vtimedelta - observedtimedelta
    str__bf str__bg str__bh str__t str__bm str__bn str__bo str__z str__s str__l str__e str__b str__bt str__ba str__k str__m str__bv str__y str__bx str__bu str__alpha str__r str__f str__james - string
    id_cmshare id_ckshare id_cpshare id_cnshare id_coshare id_clshare - observedshare
    id_cvrat id_csrat id_crrat id_ctrat id_curat id_cqrat id_bwrat - observedrat
)
(:init
    (knows id_bwrat)
    (knows id_ghost)
    (knows_property id_bwrat pexecutable)
    (knows_property id_bwrat phost)
    (knows_property id_ghost pfqdn)
    (MEM_CACHED_DOMAIN_CREDS id_bbhost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_bihost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_bphost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_ghost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_nhost id_ddomaincredential)
    (MEM_CACHED_DOMAIN_CREDS id_uhost id_ddomaincredential)
    (MEM_DOMAIN_USER_ADMINS id_bbhost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_bihost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_bphost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_ghost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_nhost id_cdomainuser)
    (MEM_DOMAIN_USER_ADMINS id_uhost id_cdomainuser)
    (mem_hosts id_adomain id_bbhost)
    (mem_hosts id_adomain id_bihost)
    (mem_hosts id_adomain id_bphost)
    (mem_hosts id_adomain id_ghost)
    (mem_hosts id_adomain id_nhost)
    (mem_hosts id_adomain id_uhost)
    (prop_cred id_cdomainuser id_ddomaincredential)
    (PROP_DC id_bbhost no)
    (PROP_DC id_bihost no)
    (PROP_DC id_bphost yes)
    (PROP_DC id_ghost no)
    (PROP_DC id_nhost yes)
    (PROP_DC id_uhost no)
    (PROP_DNS_DOMAIN id_adomain str__b)
    (PROP_DNS_DOMAIN_NAME id_bbhost str__bh)
    (PROP_DNS_DOMAIN_NAME id_bihost str__bo)
    (PROP_DNS_DOMAIN_NAME id_bphost str__bv)
    (PROP_DNS_DOMAIN_NAME id_ghost str__m)
    (PROP_DNS_DOMAIN_NAME id_nhost str__t)
    (PROP_DNS_DOMAIN_NAME id_uhost str__ba)
    (PROP_DOMAIN id_bbhost id_adomain)
    (PROP_DOMAIN id_bihost id_adomain)
    (PROP_DOMAIN id_bphost id_adomain)
    (PROP_DOMAIN id_cdomainuser id_adomain)
    (PROP_DOMAIN id_ddomaincredential id_adomain)
    (PROP_DOMAIN id_ghost id_adomain)
    (PROP_DOMAIN id_nhost id_adomain)
    (PROP_DOMAIN id_uhost id_adomain)
    (prop_elevated id_bwrat yes)
    (prop_executable id_bwrat str__bx)
    (PROP_FQDN id_bbhost str__bf)
    (PROP_FQDN id_bihost str__bm)
    (PROP_FQDN id_bphost str__bt)
    (PROP_FQDN id_ghost str__k)
    (PROP_FQDN id_nhost str__r)
    (PROP_FQDN id_uhost str__y)
    (prop_host id_bctimedelta id_bbhost)
    (prop_host id_bjtimedelta id_bihost)
    (prop_host id_bqtimedelta id_bphost)
    (prop_host id_bwrat id_ghost)
    (prop_host id_htimedelta id_ghost)
    (prop_host id_otimedelta id_nhost)
    (prop_host id_vtimedelta id_uhost)
    (PROP_HOSTNAME id_bbhost str__bg)
    (PROP_HOSTNAME id_bihost str__bn)
    (PROP_HOSTNAME id_bphost str__bu)
    (PROP_HOSTNAME id_ghost str__l)
    (PROP_HOSTNAME id_nhost str__s)
    (PROP_HOSTNAME id_uhost str__z)
    (PROP_IS_GROUP id_cdomainuser no)
    (PROP_MICROSECONDS id_bctimedelta num__29)
    (PROP_MICROSECONDS id_bjtimedelta num__36)
    (PROP_MICROSECONDS id_bqtimedelta num__43)
    (PROP_MICROSECONDS id_htimedelta num__8)
    (PROP_MICROSECONDS id_otimedelta num__15)
    (PROP_MICROSECONDS id_vtimedelta num__22)
    (PROP_PASSWORD id_ddomaincredential str__e)
    (PROP_SECONDS id_bctimedelta num__30)
    (PROP_SECONDS id_bjtimedelta num__37)
    (PROP_SECONDS id_bqtimedelta num__44)
    (PROP_SECONDS id_htimedelta num__9)
    (PROP_SECONDS id_otimedelta num__16)
    (PROP_SECONDS id_vtimedelta num__23)
    (PROP_SID id_cdomainuser str__f)
    (PROP_TIMEDELTA id_bbhost id_bctimedelta)
    (PROP_TIMEDELTA id_bihost id_bjtimedelta)
    (PROP_TIMEDELTA id_bphost id_bqtimedelta)
    (PROP_TIMEDELTA id_ghost id_htimedelta)
    (PROP_TIMEDELTA id_nhost id_otimedelta)
    (PROP_TIMEDELTA id_uhost id_vtimedelta)
    (PROP_USER id_ddomaincredential id_cdomainuser)
    (PROP_USERNAME id_cdomainuser str__james)
    (PROP_WINDOWS_DOMAIN id_adomain str__alpha)
)
(:goal
(and
    (prop_host id_cqrat id_nhost)
    (prop_host id_cvrat id_bihost)
    (prop_host id_csrat id_bbhost)
    (prop_host id_crrat id_uhost)
    (prop_host id_ctrat id_bphost)
)
)
)