(define (problem grounded-STRIPS-TPP)
(:domain grounded-STRIPS-TPP-PROPOSITIONAL)
(:init
(AT-TRUCK1-DEPOT1)
(ON-SALE-GOODS1-MARKET1-LEVEL1)
(LOADED-GOODS1-TRUCK1-LEVEL0)
(STORED-GOODS1-LEVEL0)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL0)
)
(:goal
(and
(STORED-GOODS1-LEVEL1)
)
)
)
