(define (problem strips-mprime-x-19)
   (:domain mystery-prime-strips)
   (:objects bacon tofu lamb lobster beef cantelope onion
             wonderbread lemon haroset marzipan flounder okra snickers ham
             aesthetics stimulation entertainment achievement lubricity love
             expectation learning sciatica loneliness laceration grief
             abrasion anxiety dread boils jealousy prostatitis anger
             hangover depression angina bavaria manitoba pennsylvania
             oregon goias bosnia vulcan uranus saturn earth)
   (:init (food bacon)
          (food tofu)
          (food lamb)
          (food lobster)
          (food beef)
          (food cantelope)
          (food onion)
          (food wonderbread)
          (food lemon)
          (food haroset)
          (food marzipan)
          (food flounder)
          (food okra)
          (food snickers)
          (food ham)
          (pleasure aesthetics)
          (pleasure stimulation)
          (pleasure entertainment)
          (pleasure achievement)
          (pleasure lubricity)
          (pleasure love)
          (pleasure expectation)
          (pleasure learning)
          (pain sciatica)
          (pain loneliness)
          (pain laceration)
          (pain grief)
          (pain abrasion)
          (pain anxiety)
          (pain dread)
          (pain boils)
          (pain jealousy)
          (pain prostatitis)
          (pain anger)
          (pain hangover)
          (pain depression)
          (pain angina)
          (province bavaria)
          (province manitoba)
          (province pennsylvania)
          (province oregon)
          (province goias)
          (province bosnia)
          (planet vulcan)
          (planet uranus)
          (planet saturn)
          (planet earth)
          (locale cantelope bavaria)
          (harmony achievement saturn)
          (harmony love uranus)
          (locale onion bavaria)
          (eats lobster bacon)
          (craves jealousy haroset)
          (craves love haroset)
          (craves sciatica bacon)
          (craves abrasion beef)
          (eats lobster haroset)
          (eats lemon ham)
          (harmony stimulation earth)
          (eats wonderbread bacon)
          (harmony lubricity earth)
          (craves hangover okra)
          (craves stimulation lamb)
          (eats okra snickers)
          (locale marzipan oregon)
          (eats beef lemon)
          (eats haroset flounder)
          (eats lemon cantelope)
          (eats marzipan tofu)
          (harmony expectation saturn)
          (craves dread wonderbread)
          (attacks pennsylvania oregon)
          (eats wonderbread okra)
          (eats onion tofu)
          (eats marzipan cantelope)
          (locale lemon manitoba)
          (locale okra manitoba)
          (eats lemon beef)
          (craves angina ham)
          (eats bacon wonderbread)
          (eats okra wonderbread)
          (eats beef lamb)
          (craves laceration lamb)
          (eats lamb beef)
          (eats wonderbread marzipan)
          (eats snickers wonderbread)
          (locale lobster manitoba)
          (eats haroset lamb)
          (craves loneliness tofu)
          (locale bacon manitoba)
          (eats tofu marzipan)
          (eats marzipan wonderbread)
          (craves lubricity lemon)
          (eats cantelope lemon)
          (eats beef marzipan)
          (locale haroset manitoba)
          (attacks goias bosnia)
          (craves depression snickers)
          (eats bacon lobster)
          (attacks manitoba pennsylvania)
          (eats lamb haroset)
          (eats snickers okra)
          (eats flounder ham)
          (attacks bavaria manitoba)
          (locale beef oregon)
          (craves anger flounder)
          (locale lamb bosnia)
          (harmony entertainment uranus)
          (orbits uranus saturn)
          (harmony learning saturn)
          (orbits vulcan uranus)
          (craves anxiety onion)
          (eats cantelope marzipan)
          (craves learning snickers)
          (harmony aesthetics earth)
          (locale flounder oregon)
          (eats ham lemon)
          (craves grief lobster)
          (eats marzipan beef)
          (locale ham bosnia)
          (locale wonderbread bavaria)
          (locale tofu manitoba)
          (craves expectation okra)
          (craves achievement wonderbread)
          (eats haroset lobster)
          (locale snickers manitoba)
          (orbits saturn earth)
          (attacks oregon goias)
          (eats onion snickers)
          (eats flounder haroset)
          (craves boils lemon)
          (eats wonderbread snickers)
          (eats tofu onion)
          (eats snickers onion)
          (craves prostatitis marzipan)
          (craves aesthetics bacon)
          (eats ham flounder)
          (craves entertainment lobster))
   (:goal (and (craves abrasion lobster))))